### ISSUE TITLE
Internet provider does not work

### ISSUE THREAD

**Issue by jkob** [joke2k/faker#1001]
* Faker version: 2.0.2
* OS: Windows 10 Home

Internet providers methods returns errors

### Steps to reproduce
>>> from faker import Faker
>>> from faker.providers import internet
>>> fake = Faker()
>>> fake.add_provider(internet)
>>> fake.username()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'username'

### Expected behavior

Should return a username

### Actual behavior

Errors

**Comment by fcurella** [comment]
the method is `user_name()`, with an underscore. See https://faker.readthedocs.io/en/master/providers/faker.providers.internet.html
