### ISSUE TITLE
Faker error

### ISSUE THREAD

**Issue by Pranjal1212** [joke2k/faker#1002]
![Untitled](https://user-images.githubusercontent.com/55194688/65830817-a1f87380-e2d0-11e9-931f-1efbb3f06a50.png)
* Faker version:2.0.2

* OS:windows 10 home

Brief summary of the issue goes here.

### Expected behavior

Should populate the database

### Actual behavior

Throwing an error

**Comment by fcurella** [comment]
This problem has nothing to do with Faker. Looks like your User model doesn't define a `last_name` field, but I see there's one named `second_name`. Check your User model fields.
