### ISSUE TITLE
Proposal for enhancement of Swedish SSN values (Pers ID, Org ID & MOMS (VAT) ID)

### ISSUE THREAD

**Issue by michjnich** [joke2k/faker#1005]
* Faker version: 2.0.2
* OS: *

I'd like to expand and correct some of the behaviour for Swedish ssn and VAT numbers, and add an option to return an organisation ID. 

Some info on how these codes work in Sweden:

1. **Personal number (SSN)** - the code for this is largely correct, but I would like to add a "long=False" parameter to the call. Default behaviour would remain the same, when set to true it would return a 12-digit SSN, which includes the century digits for the year. Most systems actually use the long version of the SSN and it would be handy to get this returned directly.

2. **Organisation number** - the code for this is mostly the same as the pers ID (SSN), but the "month" part of the number is 20 or higher. When taking 12 digit versions these are usually prefixed with "16".

3. **VAT number** (VAT is also called MOMS in Sweden) -  This number is not just a random sequence of numbers in Sweden. The organisation number is part of this. So the pattern is usually SEnnnnnnnnnnss, where n= org ID and s=sequence number (usually 01, unless you are a sole trader with multiple businesses)

..See wikipedia under Sweden for more info: https://en.wikipedia.org/wiki/VAT_identification_number

### Expected behavior

**Pers ID:**
1.  Request a Personal number without setting any params
2.  The 10 digit personal number is returned as it is today. 
3.  Request a personal number setting "long=True"
4.  A 12 digit personal number is returned, which passes Swedish validation checks. 

**Org ID:**
1.  Request an org ID setting no params or setting "long=False"
2.  A valid 10 digit org ID is returned (same checkdigit validation as for pers ID), which passes Swedish validation checks.
3.  Request an org ID setting "long=True"
4.  A valid 12 digit org ID is returned, which passes Swedish validation checks. 

**VAT numbers:**
1.  Request a VAT number
2.  The VAT number returned 
3.  The VAT number passes the validation that the first 10 digits after the "SE" are a valid org ID.

Note: Implementation of Org ID could either be as a new function, or using the existing ssn function with a parameter to set "org_id=True". Whichever is preferable.

### Actual behavior

**Pers ID:** Cannot return a long pers ID with 12 digits
**Org ID:** Not an option today
**VAT number:** currently returns a random string of digits

**Comment by michjnich** [comment]
Just to be clear, I'm happy to take this enhancement myself if you want to assign it to me (I live in Sweden and would like to use this functionality).

**Comment by michjnich** [comment]
Excellent. I'm away for a few days now, so I'll get on this when I get back next week :)

**Comment by michjnich** [comment]
Actually, minor change to the proposal. From the new org_id method I think it wise to return 2 values - the org ID itself, and a corresponding VAT number, since these match up in reality. The vat routine can still return a random VAT number should that be required by itself. 

How do you feel about 2 return values when requesting an org_id? Or would it be better to have an extra method that aligned the 2 by calling something like `fake.org_and_vat()` do you think?

**Comment by fcurella** [comment]
@michjnich I'd rather have two separate methods. Seems more natural.

**Comment by michjnich** [comment]
I've submitted a pull request for this - in retrospect I guess it should have been assigned to me so the pull request came for this issue number, but it's #1022
