### ISSUE TITLE
Generate master card number invalid

### ISSUE THREAD

**Issue by nkthanh98** [joke2k/faker#1013]
* Faker version: 2.0.2
* OS: MacOS

I validate master card number with Faker prodvider but they don't match with regex ^(5[1-5][0-9]{14}|2(22[1-9][0-9]{12}|2[3-9][0-9]{13}|[3-6][0-9]{14}|7[0-1][0-9]{13}|720[0-9]{12}))$
If number begin with 2, it is one of 4 group and they generate 2610440153652. But length of string is 16, not 13

### Steps to reproduce

1. value = fake.credit_card_number(card_type='mastercard')
2. regex = r'^(5[1-5][0-9]{14}|2(22[1-9][0-9]{12}|2[3-9][0-9]{13}|[3-6][0-9]{14}|7[0-1][0-9]{13}|720[0-9]{12}))$' 
3. ret = re.fullmatch(regex, value)

### Expected behavior

ret is not None

### Actual behavior

ret is None

**Comment by fcurella** [comment]
Thank you for the report @nkthanh98 !

Would you be able to submit a PR?

**Comment by nkthanh98** [comment]
> Thank you for the report @nkthanh98 !
> 
> Would you be able to submit a PR?

Can you assign this issue for me?

**Comment by fcurella** [comment]
@nkthanh98 done!
