### ISSUE TITLE
suggestion: add provider for vietnamese locale

### ISSUE THREAD

**Issue by magiskboy** [joke2k/faker#1015]
I want to add new provider for vietnamese locale

**Comment by fcurella** [comment]
Thank you so much! Go for it!

**Comment by thang080920** [comment]
@fcurella Is this ready for the new version sir?

**Comment by fcurella** [comment]
Hi @thang080920 

The wroks is being done in https://github.com/joke2k/faker/pull/1020, but we're still waiting on the last finishing touches by the author.
