### ISSUE TITLE
[Change] Change method generate some text type

### ISSUE THREAD

**Issue by magiskboy** [joke2k/faker#1018]
* Faker version: 2.0.2
* OS: macos, linux, windows

As I know, some global standardized texts such as uuid, email, url, ipv4 and so on are all generated by hard code so maintenance is difficult.

Instead of hard code, we can generate text using regular expressions, python has many libraries that do this. Thus, the code will be clearer

### Steps to reproduce

1. fake = faker.Faker()
2. uuid = faker.uuid()

### Expected behavior

uuid = '2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d'

**Comment by fcurella** [comment]
Hi @nkthanh98 ,

I'm not sure what you're trying to say.

Could you follow and fill out the issue template instead of replacing? It gives the description more structure and helps me out understanding what the problem is and how to fix it.
