### ISSUE TITLE
suggestion: support for ja_JP at faker.providers.job

### ISSUE THREAD

**Issue by shmokmt** [joke2k/faker#1035]
I checked items of ja_JP but they are not that perfect.
For example, `faker.providers.job` doesn't correspond.
So I'd like to send a PR which I make compatible with ja_JP.
What do you think?

**Comment by fcurella** [comment]
Thank you @shmokmt ! Feel free to submit a PR :)

**Comment by shmokmt** [comment]
I've just created a PR now
#1038

**Comment by shmokmt** [comment]
@fcurella Cloud you review it?

**Comment by fcurella** [comment]
Closed in https://github.com/joke2k/faker/pull/1038
