### ISSUE TITLE
BBAN for en_GB too short

### ISSUE THREAD

**Issue by Necrathex** [joke2k/faker#1040]
* Faker version: v2.0.3
* OS: linux

Numeric part of the en_GB BBAN needs to be 14 digits long, it currently only returns 13, failing further validation.

### Steps to reproduce

Invoke `fake.iban()` or `fake.bban()` with the en_GB locale, an IBAN or BBAN with 1 digit missing is returned.

### Expected behavior

GB ibans should be 22 chars long: https://www.xe.com/ibancalculator/sample/?ibancountry=united kingdom

**Comment by fcurella** [comment]
Thank you for the report @Necrathex !

Feel free to submit a PR. Let me know if you have any question or need any help :)
