### ISSUE TITLE
locale 'ar_Ps' provides wrong country code

### ISSUE THREAD

**Issue by loeti82** [joke2k/faker#1051]
* Faker version: Faker==2.0.3
* OS: NAME="Ubuntu", VERSION="18.04.3 LTS (Bionic Beaver)"

The provider for locale ar_PS provides the telephone country code instead of the ISO country code.

### Steps to reproduce

```
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Faker
>>> from faker.providers import address
>>> fake = Faker()
>>> fake.add_provider(address)
>>> print(fake.country_code())
AT
>>> fake = Faker('ar_PS')
>>> print(fake.country_code())
00972
```

### Expected behavior

Country Code in Letters as defined here: https://www.iso.org/obp/ui/#iso:code:3166:PS

### Actual behavior

Telephone Country Code provided

**Comment by fcurella** [comment]
Thank you for the report @loeti82 !

Feel free to submit a PR, and I'll get it merged in.
