### ISSUE TITLE
FactoryBoy: TypeError with numeric types

### ISSUE THREAD

**Issue by zahessi** [joke2k/faker#1061]
* Faker version: latest FactoryBoy dependency (at the time of writing it is Faker==0.9.1)
* OS: Ubuntu 18.04

Brief summary of the issue goes here.

### Steps to reproduce

1. Create a factory with any numeric type. For e.g. we have attribute
```
amount = Faker("pydecimal", left_digits=9, right_digits=3, positive=True, min_value=Decimal(10),  max_value=Decimal(100))
```

### Expected behaviour

`amount` should be generated with respect to `min_value` and `max_value` attributes

### Actual behaviour

`TypeError` is raised.
```
def format(self, formatter, *args, **kwargs):
        """
        This is a secure way to make a fake from another Provider.
        """
        # TODO: data export?
>       return self.get_formatter(formatter)(*args, **kwargs)
E       TypeError: pydecimal() got an unexpected keyword argument 'min_value'
```

**Comment by malefice** [comment]
Upgrade your `Faker` version. A quick search for "pydecimal" in the [changelog](https://github.com/joke2k/faker/blob/master/CHANGELOG.rst) will show that you need at least the 1.0.5 version.

**Comment by zahessi** [comment]
My bad, thanks @malefice
