### ISSUE TITLE
FactoryBoy's fake.ipv4(network=True) generates /32 network

### ISSUE THREAD

**Issue by oza4h07** [joke2k/faker#1065]
* Factory Boy version: 2.12.0
* Faker version: 2.0.3
* OS: Debian Buster

Brief summary of the issue goes here.

### Steps to reproduce

>>> from faker import Faker
>>> fake = Faker()
>>> fake.ipv4(network=True, private=True)
...
'192.168.108.253/32'

### Expected behavior

I would expect each network mask to be at most valued to 30 to deserve its network title.

If network prefix length could be passed as an optional argument, that could be even better:
>>> fake.ipv4(network=True, private=True, prefix_length=26)

Online doc mentions an address_class argument but no example of acceptable address_class value (I tried with 'C' without success).

### Actual behavior

Sometimes, a '/32' network value is replied

**Comment by malefice** [comment]
> I would expect each network mask to be at most valued to 30 to deserve its network title.

I agree, but others might not. Notation-wise, it is still valid, and only the name `network` might be a bit of a misnomer.  

> If network prefix length could be passed as an optional argument, that could be even better:

Personally if it is okay to break backward compatibility, I would just get rid of the `network` argument, and use the aptly named `prefix_length` moving forward. A value of 0 to 32 will explicitly set the prefix length, a value of `True` will do what `network=True` already does, and a value of `None` or `False` will just output an IP without a subnet mask.
 
> Online doc mentions an address_class argument but no example of acceptable address_class value (I tried with 'C' without success).

Use lowercase.

Anyway, feel free to submit a PR.

**Comment by luckman212** [comment]
Is there a solution to generate, say a random, valid RFC1918 network in CIDR notation? e.g. 172.18.204.64/28

**Comment by nsalitakamai** [comment]
Lookign for the same, easy way to create and IP with a random (1-32) CIDR notation

**Comment by luckman212** [comment]
@nsalitakamai until faker can do this, you could try https://github.com/luckman212/random-subnet.py

**Comment by stefan6419846** [comment]
Instead of implementing/copying code into a (basically) CLI-only module, proposing a corresponding PR to *faker* seems like the more appropriate approach.
