### ISSUE TITLE
domain_name often generates colliding names.

### ISSUE THREAD

**Issue by stuaxo** [joke2k/faker#1067]
* Faker version:  2.0.0
* OS:  Arch

Brief summary of the issue goes here.

### Steps to reproduce

Run faker domain_name a few times
### Expected behavior

```
root@786539edc208:/app# faker domain_name
rivers.info

root@786539edc208:/app# faker domain_name
gould.net

root@786539edc208:/app# faker domain_name
hernandez.com

root@786539edc208:/app# faker domain_name
rivers.info
```

In reality I have a test suite that generates sites in many tests, and I get collisions, I added some code to try and avoid this, but it would be nice if the domain_name faker could have less of a chance of collision.

Suggestion:  generate domains made of two word or names.

In the above example, I would have ended up with `riversgould.net` and  `riversstephens.biz`

**Comment by lehtihet** [comment]
I'll start working on this issue.

**Comment by lehtihet** [comment]
It looks like this issue has already been resolved with the ```level``` parameter.

```
>>> domain_name()
nichols-phillips.com
>>> domain_name(2)
williamson-hopkins.jackson.com
```

**Comment by stuaxo** [comment]
While you can use the level parameter, this means each new domain will have an extra dot in it, which may not always be desirable.

I didn't write this before as I couldn't work out exactly what it was I didn't like about the solution, but I guess the fact you end up with domains with lots and lots of dots felt a littly "icky", but it also may not be what you want.

I think in general it would be good if fakers generators had a way of giving you unique names within a either a test run, or just within a single test or a with block.
