### ISSUE TITLE
Error when calling pyfloat provider

### ISSUE THREAD

**Issue by raikel** [joke2k/faker#1068]
* Faker version: 2.0.4
* OS: Ubuntu 19.04
* Python version: 3.7.3

There is a bug in `pyfloat` provider.

### Steps to reproduce

```python
from faker import Faker
fake = Faker()
# just any random float numbers in min_value < max_value
fake.pyfloat(min_value=-15.23, max_value=4512313)
```
### Expected behavior

Above call should not raise any error.

### Actual behavior

Running the code above will raise the following error:
```
....
File "/usr/lib/python3.7/random.py", line 186, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
```

**Comment by malefice** [comment]
@fcurella I think the `pyfloat` provider can benefit from some changes. IMO, it is not an unreasonable expectation that a method that generates floats must be capable of accepting floats for its `min_value` and `max_value` keyword arguments. 

While we can opt to rename those to imply "integers only," there are some other cases that can be confusing. For example:

```
from faker import Faker
fake = Faker()

# Should fail because left_digits=2 imply 10 <= number < 100
# which conflicts with min_value=1 and max_value=3
fake.pyfloat(left_digits=2, min_value=1, max_value=3)

# Works, but returns floats that do not respect left_digits=2
fake.pyfloat(left_digits=2, min_value=1, max_value=1000)

```

At least in my experience, I never needed to generate floats with a specific number of digits to the left of the decimal point (or decimal comma for Europeans), and typical use cases almost always involve generating values within a certain range with some number of decimal places (right digits) or a number of significant digits/figures.

Anyway, I volunteer to fix this issue, but I would like to hear your thoughts on how much fixing should be done on this provider method.

**Comment by fcurella** [comment]
Hi agree that this signature is confusing (and same for `pydecimal`).

Ideally, all it should need are a `min_value`, `max_value` and `right_digits` (which could be called `precision` at this point).

I'm generally ok with changing the signature of both methods, keeping in mind that it will break back compatibility and it should trigger a new major version bump.

**Comment by malefice** [comment]
> I'm generally ok with changing the signature of both methods, keeping in mind that it will break back compatibility and it should trigger a new major version bump.

It will be weird to release another major version so soon just for this, so this overhaul probably can be done much later, alongside other items that can benefit from breaking backwards compatibility. Maybe you can just tag this issue as something to do later, so it will be easy to search and to revisit.

**Comment by florinlabou** [comment]
Suggestion: It would help a lot to use for pydecimal, pyfloat argument type annotations. I try to dynamically call these methods and I cannot provide the proper argument's type. 

`def pydecimal(self, left_digits: int=None, right_digits: int=None, positive: bool=False,
                  min_value: int=None, max_value: int=None) -> decimal:`

I would use it like this:
`
>>>import inspect 
>>>sig = inspect.signature(pydecimal)
>>>sig.parameters['left_digits'].annotation
<class 'int'>
>>>sig.parameters['left_digits'].annotation('12')
12
`

**Comment by anentropic** [comment]
I'm a bit skeptical about the tests here:

```
class TestPyfloat(unittest.TestCase):
    def setUp(self):
        self.fake = Faker()
        Faker.seed(0)
```

I think this means that every time the tests are run the same random numbers will be generated in the same order.  It's good to have reproducible, deterministic tests... but this also means that it's quite possible some of the tests only pass "by luck" and could potentially produce wrong values in normal use, but will never do so in the tests.

Wouldn't it make sense to either not seed the generator (tests no longer deterministic: bad) or to run the tests many times with different known seed values?

**Comment by anentropic** [comment]
I also agree with comments above... `pyfloat` should not have `left_digits` and `right_digits` options, it complicates the implementation a lot and does not seem very useful for idiomatic float usage

if you want exactly 2 "right digits" you should be using Decimal type

but `min_value` and `max_value` should definitely accept floats

also, `positive` arg seems a bit redundant when you could just specify `min_value=0`

**Comment by fcurella** [comment]
> Wouldn't it make sense to either not seed the generator (tests no longer deterministic: bad) or to run the tests many times with different known seed values?

I'd rather have tests with different known seed values. One issue we had in the past is that the same seed gives different results on python 2 vs python 3. We recently have abandoned Python 2, so that's not an issue anymore.


I'm going to create a new milestone that I will use to tag all non-backward compatibility changes.

I'm all for simplifying methods (there are plenty like this in the codebase, for historical reasons) and welcome any PR on this. Just know it will take longer than usual to have them merged into master :)

**Comment by sciencectn** [comment]
Looks like we just went to 6.0.0, does this mean we can change the signature of this function and break compatibility? 

I think @fcurella's proposal to drop `left_digits` and change `right_digits` to `precision` makes the most sense. Then allow `min_value` and `max_value` to be floats. 

I can do the PR if you don't have anything in the works yet, let me know.

**Comment by libcthorne** [comment]
I've hit a similar issue when trying to declare two floats where one should always be greater than the other:
```
    minimum_quantity = factory.Faker(
        "pydecimal",
        left_digits=5,
        right_digits=2,
        positive=True,
    )
    maximum_quantity = factory.Faker(
        "pydecimal",
        left_digits=5,
        right_digits=2,
        positive=True,
        min_value=factory.SelfAttribute("..minimum_quantity"),
    )
```

**Comment by fcurella** [comment]
@sciencectn A Pul Request will be most welcome! thank you!
