### ISSUE TITLE
Any Upgrade documentation for 3.0

### ISSUE THREAD

**Issue by abumalick** [joke2k/faker#1080]
* Faker version: 3.0
* OS: macOS using docker

Brief summary of the issue goes here.

### Steps to reproduce

Upgrade a project that is using faker 2 to 3

### Expected behavior

Have some documentation to how to migrate our code

### Actual behavior

I don't find any documentation to fix my 371 failing tests

**Comment by malefice** [comment]
Are you sure?

![Screenshot from 2019-12-12 20-19-31](https://user-images.githubusercontent.com/7114869/70711551-c59e5800-1d1c-11ea-8bac-ddf41935356e.png)

![Screenshot from 2019-12-12 20-20-27](https://user-images.githubusercontent.com/7114869/70711596-de0e7280-1d1c-11ea-8a7a-407bf1459126.png)

**Comment by abumalick** [comment]
Oh, my bad, I thought there were other breaking changes. I saw this notice and made an error while migrating the code.

Sorry about this.

Thank you very much for your work 👍
