### ISSUE TITLE
Changelog links are backwards

### ISSUE THREAD

**Issue by Ianleeclark** [joke2k/faker#1090]
* Faker version: >=2.0
* OS:Ubuntu

In the changelog, you aren't able to see commits between tags due to the tags being in the opposite order in the URL. It should be https://github.com/joke2k/faker/compare/{FROM}...{TO}, but is instead https://github.com/joke2k/faker/compare/{TO}...{FROM}

For example: https://github.com/joke2k/faker/compare/v3.0.0...v2.0.5

### Steps to reproduce

1. Go to https://github.com/joke2k/faker/blob/master/CHANGELOG.rst
2. Click any version's link after the affected version, and you'll be greeted with an empty changelog (e.g., https://github.com/joke2k/faker/compare/v2.0.0...v1.0.8)

### Expected behavior

You should be able to see all commits between each tag.

### Actual behavior

You see nothing.

### Additional

If you manually swap the two tags in the URL or in the UI, you can see the commits.

I'd be happy to submit a fix for this if this is, as I expect, unintended behavior.

I don't expect this to be more than manually updating all affected changelog entries and (probably?) updating the bumpversion config.

**Comment by fcurella** [comment]
Thank you for reporting this @Ianleeclark !

Feel free to submit a PR if you have time! :)

**Comment by Ianleeclark** [comment]
I'd be happy to take a look at this, but New Years celebrations call! Will try and submit a PR before the end of the week
