### ISSUE TITLE
Implementation of person id number for cs_CZ - Czech (rodné číslo)

### ISSUE THREAD

**Issue by andrew-coxuatoinc** [joke2k/faker#1099]
Can you implement randomizer which will generate a proper person ID number (rodné číslo) for Czech local?

**Comment by laurentbristiel** [comment]
Can you give more details about what you are trying to achieve and what you tried?
Having some names in Czech locale seems available, like in:

```
from faker import Faker
fake = Faker('cs-CZ')
for _ in range(10):
    print(fake.name())
```

Are you looking for something different?

**Comment by Jengah** [comment]
@laurentbristiel, I believe @andrew-coxuatoinc is talking about the Birth Number system rodné číslo, as described here: https://en.wikipedia.org/wiki/National_identification_number#Czech_Republic_and_Slovakia

I've put up a PR that adds this functionality to the Czech locale of the SSN Provider.
