### ISSUE TITLE
How to use "fields=xxx" in faker.provider.profile

### ISSUE THREAD

**Issue by Dunaway-Group-LLC** [joke2k/faker#1100]
* Faker version:3.0.0
* OS: Linux / Ubuntu 18.04

I want to use  faker.provider.profile(fields=

I can't find info in docs about parms for fields

### Steps to reproduce
N/A

### Expected behavior
Complete docs

### Actual behavior

Incomplete docs.

**Comment by 153957** [comment]
Not the solution, but the answer to what you want to know can be found in the profile provider.
The options are the combination of the `simple_profile` and those in `profile`.

https://github.com/joke2k/faker/blob/master/faker/providers/profile/__init__.py#L24-L29
https://github.com/joke2k/faker/blob/master/faker/providers/profile/__init__.py#L41-L47

i.e.
```
"username"
"name"
"sex"
"address"
"mail"
"birthdate"

"job"
"company"
"ssn"
"residence"
"current_location"
"blood_group"
"website"
```
