### ISSUE TITLE
Faker returning invalid UK postcodes

### ISSUE THREAD

**Issue by zplush** [joke2k/faker#1113]
* Faker version: 4.1.0

Is there any plan on improving this?

**Comment by fcurella** [comment]
@zplush I would love to improve, but your description of the issue is quite vague.

It would be helpful if you'd provide a description of your issue by following our [PR Template](https://github.com/joke2k/faker/blob/master/PULL_REQUEST_TEMPLATE.md).

**Comment by crd** [comment]
I believe this complaint gets to the general strategy of Faker, which is to simulate real-_looking_ data as opposed to real data. 

@zplush, You're absolutely right: Faker generates simulated UK postcodes that satisfy regular expressions but are not actual postcodes that map to addresses in the UK. This is the same strategy used for:

* City names
* Credit card numbers
* Phone numbers
* Email addresses

If you find that generated postcodes fail validations like those listed [in the Wikipedia article on UK postcodes](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation) I'm sure someone would be happy to look at them. I don't think there's appetite to revisit Faker's fundamentals, though.

**Comment by FrancYescO** [comment]
also here, this strategy can be applied https://github.com/joke2k/faker/pull/1593
