### ISSUE TITLE
CHANGELOG.rst has wrong years

### ISSUE THREAD

**Issue by itsdkey** [joke2k/faker#1126]
* Faker version: newest
* OS: ubuntu

The years in CHANGELOG.rst do not coincide with release dates.

![image](https://user-images.githubusercontent.com/26058315/75781319-3faf0d80-5d5d-11ea-8c7f-7d68fcf222c2.png)

![image](https://user-images.githubusercontent.com/26058315/75781342-4b023900-5d5d-11ea-8956-f14e5027ae0c.png)

**Comment by bluefish6** [comment]
Hi, the same issue is for 4.0.2 and 4.0.3...
