### ISSUE TITLE
Error in Provider date_time for method fake.date() colliding with faker.date_time.date()

### ISSUE THREAD

**Issue by vfrank66** [joke2k/faker#1130]
* Faker version: 4.02
* OS: MAC, LINUX

Brief summary of the issue goes here.
The documenation for the date_time provider for the function 

`fake.date(pattern='%Y-%m-%d', end_datetime=None)` 

 Returning 

> Exception has occurred: TypeError
> function missing required argument 'year' (pos 1)
>   File "/Users/test/test-py/faker_test.py", line 15, in <module>
>     date = fake.date(pattern='%Y-%m-%d', end_datetime=None)

Which I think is clashing with the signature for:

```
class datetime(real_datetime):
    def strftime(self, fmt):
        return strftime(self, fmt)

    def combine(self, date, time):
        return datetime(date.year, date.month, date.day,
                        time.hour, time.minute, time.microsecond,
                        time.tzinfo)

    def date(self):        <===============================
        return date(self.year, self.month, self.day)

```

### Steps to reproduce

```
from faker import Faker
from faker.providers import ( date_time)

fake = Faker()
fake.add_provider(date_time)
date = fake.date(pattern='%Y-%m-%d', end_datetime=None)
```

### Expected behavior

Should produce a random string
# '2000-07-13'

### Actual behavior

> Exception has occurred: TypeError
> function missing required argument 'year' (pos 1)
>   File "/Users/test/test-py/faker_test.py", line 15, in <module>
>     date = fake.date(pattern='%Y-%m-%d', end_datetime=None)

**Comment by laurentbristiel** [comment]
+1 
I reproduce the problem with both 4.0.2 and 3.0.1 version of pytest
