### ISSUE TITLE
Missing implementation of no_NO license plates.

### ISSUE THREAD

**Issue by bjorskog** [joke2k/faker#1141]
* Faker version:
* OS:

no_NO license plates are not implemeted.

### Expected behavior

Should be of the form 

> AB 12345

### Actual behavior
#1140

**Comment by malefice** [comment]
@fcurella I think this can be closed. This was not auto-closed because the related PR's "Fixes" section was not properly written.

**Comment by fcurella** [comment]
Thank you for triaging @malefice !
