### ISSUE TITLE
suggestion: Add a Provider for medical information like drug names, dosages and strengths

### ISSUE THREAD

**Issue by luiscberrocal** [joke2k/faker#1142]
* Faker version: all
* OS: all

Create a new provider with medicines names, dosages and strengths. The source of the data is https://data.gov.sa/Data/en/dataset/essential-medicines-list

### Expected behavior

from faker import Faker
from faker.providers import medical

fake = Faker()
fake.add_provider(medical)

drug_name = fake.drug_name() #Acetaminophen for example
drug_dosage = fake.drug_dosage() # 2 mg for example

**Comment by malefice** [comment]
IMO only healthcare-focused applications will benefit from fake data of that level of "authenticity" if that is the proper term, so I think the use case is not generic enough for it to be included in the main library.

I can definitely see how this can be important for healthcare systems, since medical data have a much larger scope than just drug names and dosages. It is probably best to implement this as a separate package. Perhaps you would be interested?

**Comment by luiscberrocal** [comment]
Actually I was thinking of starting with drug names and dosages and afterwards add stuff like diagnostic codes and CPT (treatment) codes. The idea would be to all healthcare providers here.

I'm currently working on a pull request for the main package. Please let me know if you will consider accepting the pull request, or should I go with a separate package.

**Comment by fcurella** [comment]
@luiscberrocal I think we should go with a separate package. Not only this is a very specific case, but I think it could receive better attention by being maintained separately by a team entirely dedicated to it.

**Comment by luiscberrocal** [comment]
@fcurella thanks. Will do that. Do you have any external repos you can recommend to look at to get an idea of the best way to implement an external provider?

**Comment by fcurella** [comment]
@luiscberrocal You can look at any of the [community providers](https://faker.readthedocs.io/en/master/communityproviders.html).

Once you're done, feel free to submit a PR to include yours in the list :)

**Comment by martinburchell** [comment]
@luiscberrocal we might be interested in something like this for a couple of projects - generating fake medical records and UK NHS numbers. Have you got anywhere with development?

https://github.com/RudolfCardinal/pythonlib/blob/master/cardinal_pythonlib/nhs.py
https://github.com/RudolfCardinal/crate/blob/master/crate_anon/anonymise/make_demo_database.py

**Comment by martinburchell** [comment]
Cross-referencing #2307, which added faker-healthcare-provider to the list of community providers.
