### ISSUE TITLE
Suggestion: Include "Codename" generator

### ISSUE THREAD

**Issue by airstrike** [joke2k/faker#1161]
I'll steal the description from http://www.codenamegenerator.com/ since it's succinct and thorough:

> What is a codename? A codename, codeword or cryptonym is a name used to refer clandestinely to another name or word. Codename, codeword and cryptonym are usually interchangeable. Codenames are used to identify projects while maintaining secrecy against rival concerns. In more simple terms, a codename is a name that you agree upon and you use to hide what you are talking about. In industry, codenames are often used to designate products that are in their developement phase to protect them from competitors. In the military, codenames are frequently used to designate missions and operations.

This is not exactly the same as the single word generator that's already available (which can yield words like "such") but a narrower in scope as it often includes proper nouns, adjectives, mythological names, locations and more, and possibly a combination of these words.

Happy to kick start the effort by providing an initial list of codenames if this has any chance of being added.

**Comment by fcurella** [comment]
I think I would rather have two separate `adjective` and `noun` methods, and people can combine them to make their codenames. This would give users more flexibility while keeping the implementation simple:

```python
from faker import Faker

fake = Faker()

for _ in range(100):
    print(f"{fake.adjective()} {fake.noun()}")

# "slow llama"
# "fast rocket"
```

**Comment by airstrike** [comment]
That works. You'd be favoring simplicity in implementation for miss out on the proper nouns which are very commonly used for codenames IRL e.g. Barbarossa, Manhattan, Longhorn, Atlantis, etc. Though arguably the user could pull from the names and addresses generators to get (some) of those as well if desired.

**Comment by crd** [comment]
This feels like a good use case for a new [Community Provider](https://faker.readthedocs.io/en/master/communityproviders.html).

**Comment by dkotschessa** [comment]
@airstrike I a,m looking for contributions to make to this project.  I have recently created a community provider and was looking for another issue to work on.  Has this been initiated in any way?  It looks like a good one to work on.

**Comment by airstrike** [comment]
> @airstrike I a,m looking for contributions to make to this project. I have recently created a community provider and was looking for another issue to work on. Has this been initiated in any way? It looks like a good one to work on.

Great to hear! I have not started on this at all, so I'm sorry to report I don't have anything to provide off-the-shelf to help jump start this exercise, but if there's anything I can help with, please let me know

**Comment by dkotschessa** [comment]
@airstrike Meet me over in https://github.com/dkotschessa/faker_codename/issues

I used my last provider as a template repository, but haven't done anything yet.  There's plenty you can do depending on how involved you want to be.  For a start you could edit the README to demonstrate what this might look like in practice.   If you stop there, cool, I'll take off with it, though maybe some lists would be helpful as well.
