### ISSUE TITLE
Shall we pytestify our tests?

### ISSUE THREAD

**Issue by malefice** [joke2k/faker#1162]
Since `Faker` now has its own `pytest` plugin,  it is kind of weird if our test suite itself does not take advantage of pytest-style tests and our own plugin. The test suite currently seems like it has an identity crisis because of all the `unittest` and `pytest` stuff mixed together.  One of the things I eventually like to see is the complete switch to a pure pytest-style test suite.

I did not push for this back then because as good as `pytest` is, there were just not enough good reasons to fight the inertia. The test suite works fine after all, but now, at least we have additional reasons, and I have an idea to simplify our test suite handling provider methods and to make it easier for contributors to write those tests.

We can define a ``faker`` fixture under `tests/providers/conftest.py` that extends the plugin's default behavior. This fixture will only be available for tests under `tests/providers`, and the additional behavior will involve introducing the availability of a class-scoped `Faker` instance for what i call "locale test classes". The details are best discussed via sample code:

```python
class TestEnUs:
   # Notice we did not declare anything here

    def test_something_1(self, faker):
        # but faker will be a class-scoped instance with locale='en_US'
        pass

    def test_something_2(self, faker):
        # and is shared here
        pass

    def test_something_3(self, faker):
        # and here as well
        pass

    def test_something_4(self, faker):
        # and seeded for each test inside this class
        pass


class TestEnPh:

    def test_something_else(self, faker):
        # but a new class-scoped instance will be created here with locale='en_PH'
        pass

class TestFilPh(TestEnPh):
    # and there will be a test similar to the EnPh test here
    # but with a fixture returning a 'fil_PH' class-scoped instance 
    pass


class TestNotALocale:

    def test_yet_another_thing(self, faker):
        # and since this is not a locale class, it defaults to the plugin's default behavior
        pass


def test_outside_of_class(faker):
    # this is not inside a locale class, so it also defaults to the plugin's default behavior
    pass
``` 

I already have some dirty test code that works as described, but I would like to hear your thoughts on this issue first.

**Comment by fcurella** [comment]
Thank you @malefice !

The structure you outline makes a lot of sense to me :)

I would love to have the tests use `pytest`, but it seems a pretty tedious job to convert them all. 

I personally don't have the bandwidth to do it, but I would gladly review and merge a PR if someone else is willing to write it.

**Comment by malefice** [comment]
Even if #1248 gets merged, the pytestified test suite runs just as fast as, if not faster than, it used to [before](https://github.com/joke2k/faker/tree/262a5bba77b826adc695144d3bdf41d7e9b77b0f) this initiative at least on my computer, and that is despite the updated tests performing significantly more sample runs. At the very least, th

On top of adding pytest fixtures for easier writing of tests in this test suite, the list below shows the progress of this issue so far for the benefit of others who might be interested in tackling this.

Provider Tests:
- [X] base
- [X] address
- [X] automotive
- [X] bank
- [X] barcode
- [ ] color
- [ ] company
- [ ] credit card
- [X] currency
- [ ] datetime
- [ ] file
- [ ] geo
- [X] internet
- [X] isbn
- [X] job
- [X] lorem
- [ ] misc
- [ ] person
- [ ] phone number
- [ ] profile
- [ ] python
- [ ] ssn
- [X] user agent

Misc Tests:
- [X] Faker proxy class
- [X] Generator class
- [ ] Factory class (already partially cleaned up in the process)
- [X] Sphinx module
- [X] Pytest plugin
