### ISSUE TITLE
Why does faker.misc.uuid has `cast_to=str` by default? 

### ISSUE THREAD

**Issue by rodrigondec** [joke2k/faker#1163]
# I'm willing to open PR
should this issue be accepted

* Faker version: latest
* OS: N/A

`faker.misc.uuid` has a arg `cast_to` with `str` as default.  So the returned value is always string.
https://github.com/joke2k/faker/blob/9f48a5c6a251b2b8d9f84f65472f946b85b9a923/faker/providers/misc/__init__.py#L95

I want to have the `uuid.UUID` object returned. 

Calling with `cast_to=UUID` again raises a Error on UUID lib (of course it would). Since it's returned `UUID(UUID([...]))`from faker with this

![image](https://user-images.githubusercontent.com/3301060/80141445-f1113900-857f-11ea-85a2-2252c74acd00.png)

So I would have to cast it like this `UUID(str(UUID([...])))` to be funcional.

### Steps to reproduce

1. `faker.uuid(cast_to=str)`
1. `faker.uuid(cast_to=uuid.UUID)`

### Expected behavior
I should be able to call  `faker.uuid(cast_to=None)` and have the pure `UUID` object returned.

### Actual behavior
Faker forces object `UUID` to be cast.

**Comment by fcurella** [comment]
I agree, we should make it possible to retrieve a full-fledged uuid object.

I would like to keep the default `cast_to=str` in the method's signature for backward-compatibility.

We could just special-case `None`:

```python
uuid_instance = uuid.UUID(...)

if cast_to is not None:
    uuid_instance = cast_to(uuid_instance)
return uuid_instance
```

**Comment by rodrigondec** [comment]
After working on the PR found how it could be possible without the changes on the tests. Still better to make the None case. I'ts more explicit. Added docs too

![image](https://user-images.githubusercontent.com/3301060/80156838-41e25b00-859b-11ea-9877-080f858857aa.png)
