### ISSUE TITLE
Issue with latest faker version: AttributeError: 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by mouradmourafiq** [joke2k/faker#1177]
* Faker version: 4.1.0
* OS: ubuntu

Tests that used to pass are now failing, the error:

```
>   lambda: ihook(item=item, **kwds),
    when=when,
            )

/usr/local/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py:273:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.7/site-packages/faker/contrib/pytest/plugin.py:20: in _session_faker
    return Faker(locale=locale)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'faker.factory.Factory'>, locale = ['en_US'], providers = None, generator = None, includes = [], config = {}

    @classmethod
    def create(cls, locale=None, providers=None, generator=None, includes=None, **config):
        if includes is None:
            includes = []

        # fix locale to package name
>       locale = locale.replace('-', '_') if locale else DEFAULT_LOCALE
E       AttributeError: 'list' object has no attribute 'replace'

/usr/local/lib/python3.7/site-packages/faker/factory.py:22: AttributeError
``` 

### Steps to reproduce
I just pinned faker to: `faker==4.0.3` and all tests are passing.

### Expected behavior

It should work, similarly to the previous release.

**Comment by malefice** [comment]
A new `pytest` plugin has been introduced in `4.1.0`, and based on your error log, something in your test suite and/or `flaky` might be conflicting with our `_session_faker` fixture ([source](https://github.com/joke2k/faker/blob/f930d83a85e49321437799bf19f00251143dcf47/faker/contrib/pytest/plugin.py#L9)).

I have never used `flaky`, so I cannot comment much on that front, but does your test suite declare a `faker_session_locale` fixture of its own? In any case, I encourage you to read through the [pytest fixture docs](https://faker.readthedocs.io/en/master/pytest-fixtures.html) so you can help us help you troubleshoot.

**Comment by pezholio** [comment]
Can confirm, I get the same problem:

```
request = <SubRequest '_session_faker' for <Function test_page_can_be_created>>

    @pytest.fixture(scope='session', autouse=True)
    def _session_faker(request):
        """Fixture that stores the session level ``Faker`` instance.

        This fixture is internal and is only meant for use within the project.
        Third parties should instead use the ``faker`` fixture for their tests.
        """
        if 'faker_session_locale' in request.fixturenames:
            locale = request.getfixturevalue('faker_session_locale')
        else:
            locale = [DEFAULT_LOCALE]
>       return Faker(locale=locale)

/usr/lib/python3.6/site-packages/faker/contrib/pytest/plugin.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'faker.factory.Factory'>, locale = ['en_US'], providers = None, generator = None, includes = [], config = {}

    @classmethod
    def create(cls, locale=None, providers=None, generator=None, includes=None, **config):
        if includes is None:
            includes = []

        # fix locale to package name
>       locale = locale.replace('-', '_') if locale else DEFAULT_LOCALE
E       AttributeError: 'list' object has no attribute 'replace'

/usr/lib/python3.6/site-packages/faker/factory.py:22: AttributeError
```

I use Faker with FactoryBoy, so might be something to do with it?

**Comment by malefice** [comment]
@pezholio Please post your sample test, your `conftest.py` and fixtures, as well as the versions you used. The projects I handle have tests that both use `factory_boy` and the `faker` fixture without the issues you are encountering. I really cannot help any further without additional information.

I have tested both on Ubuntu 18.04 which ships with Python 3.6 and on Pop!_OS 20.04 which ships with Python 3.8. Here are some screenshots showing that there are no issues:

Vanilla behavior:
![image](https://user-images.githubusercontent.com/7114869/87696385-49dd2000-c7c3-11ea-961c-b7cc081bffec.png)

Defining a session-scoped `faker_session_locale` fixture:
![image](https://user-images.githubusercontent.com/7114869/87695940-bb689e80-c7c2-11ea-8434-33d0c12c1c2e.png)

Defining an autouse function-scoped `faker_locale` fixture 
![image](https://user-images.githubusercontent.com/7114869/87695604-42694700-c7c2-11ea-96c8-74ef26620d09.png)

**Comment by mouradmourafiq** [comment]
After we have dropped python 2 we upgraded all packages to the latest versions, we no longer see the error. I have to mention that we had to pin some deps before because we were supporting python2/3.

For others reading this, check if your project still depends on fake-factory instead of faker.

**Comment by malefice** [comment]
@mouradmourafiq Good to hear that you have solved the problem. The project has already dropped Python2 since January this year if I recall correctly (around Python2's EOL), so it was an oversight from my end to assume that you were already in Python 3 and that you have relatively modern packages installed. I will submit a PR to change the README so that users have fair warning. Thank you for your coming back to this issue to share your insights and experience.
