### ISSUE TITLE
Feature request: safe_domain_name()

### ISSUE THREAD

**Issue by ex-nerd** [joke2k/faker#1182]
There are methods for `safe_email()` but nothing that just returns the a  rfc6761 domain name for those cases where a user might want to provide a username generated off of other data (e.g. a faker-generated first/last name combo so it doesn't look weird that `George Smith` has an email address of `janedoe@example.com`).

I know I can get this with `fake.random_element(["example.com", "example.net", "example.org"])` but it would be nice to have this built in.

**Comment by crd** [comment]
Neat idea, @ex-nerd. Raised a quick PR to provide this.
