### ISSUE TITLE
profile/simple_profile should return a consistent set of names/usernames/emails

### ISSUE THREAD

**Issue by Trolldemorted** [joke2k/faker#1185]
* Faker version: `4.1.0`
* OS: `W10 Pro N`

The fields of `profile` and `simple_profile` don't fit together at all :(

### Steps to reproduce
- call `profile` or `simple_profile`

### Expected behavior

The username and email should be either completely fictional or depend on the name.

### Actual behavior
```
>>> from faker import Faker
>>> fake = Faker()
>>> fake.simple_profile()
{'username': 'michaeladams', 'name': 'Kevin Brown', 'sex': 'M', 'address': '505 Willis Fields\nSouth Christina, CT 48376', 'mail': 'rollinslisa@hotmail.com', 'birthdate': datetime.date(1968, 12, 29)}
```

Related:
#296 (sex)
#915 (phone numbers)

**Comment by pixie79** [comment]
Agreed this is silly behaviour, when validating data 99% of the time it is better if things agree rather than an email that is nothing like the person.
