### ISSUE TITLE
Lots of output at terminal

### ISSUE THREAD

**Issue by H4CKY54CK** [joke2k/faker#1187]
If I just enter `faker` at the terminal and hit enter, is it supposed to produce nearly 50mb of output? The text flew by so fast, I piped it into a text file, and it was something like 46mb of text. I'm fairly confident this isn't intended, but I obviously can't say for sure, since I'm not the one who wrote it. If this isn't intended, I can provide more details.

**Comment by malefice** [comment]
It is sort of intended but not exactly. I am a relatively new contributor, so this is just my take. I think the original intent was to produce some docs and sample code based on the available provider methods. This part of the codebase is somewhat ancient, back when there are probably very few provider methods, but as more provider methods were added, the amount of text just increased, more so with the addition of methods that can generate random binary files.

There has been a discussion in #1078 about overhauling the cli utility, but I have not had the time to focus on this one. Perhaps you would like to try?

**Comment by H4CKY54CK** [comment]
I'm sorta fairly knowledgeable with argparse, if you'd like me to see what I can do. But in the meantime, I think just displaying the normal argparse error would be the best solution for now, and then maybe relocating this text to a "example" subcommand, which could possibly write it to a file? At least until it gets explored more in depth. Or I can just report back with a more elaborate proposal?

**Comment by mportesdev** [comment]
I think a simple message like this would be sufficient:

```
$ faker
usage: faker [-h] [--version] [-v] [-o output] [-l LOCALE] [-r REPEAT] [-s SEP] [--seed SEED] [-i [INCLUDE ...]] [fake] [fake argument ...]
Try 'faker --help' for more information.
```

i.e. the same output you get when running e.g. `grep` without arguments.
