### ISSUE TITLE
name_male() can not work properly when your locale is 'zh_CN'

### ISSUE THREAD

**Issue by vintager** [joke2k/faker#1210]
* Faker version:4.1.1
* OS:windows 10

Brief summary of the issue goes here.

### Steps to reproduce
```
f = Faker(locale = 'zh_CN')
f.name_male()
```
you will get both male name and female name.

after i checked the code in `/faker/providers/person/zh_CN/__init__.py`, i found should add this in the top of this file:
```
    formats_female = ('{{last_name}}{{first_name_female}}')
    formats_male = ('{{last_name}}{{first_name_male}}')
```

`/faker/providers/person/zh_TW/__init__.py` also need be fix

**Comment by fcurella** [comment]
Thank you for the report, @vintager !

Would you mind submitting a PR with those changes?

**Comment by datadominik** [comment]
> Thank you for the report, @vintager !
> 
> Would you mind submitting a PR with those changes?

@fcurella , I created the following PR for the zh_CN provider: https://github.com/joke2k/faker/pull/1255
