### ISSUE TITLE
faker fixture cannot be used when specified through @pytes.mark.usefixtures("faker")

### ISSUE THREAD

**Issue by ljubanka** [joke2k/faker#1211]
* Faker version: 4.1.1
* OS: Ubuntu 18.04
* Python version: 3.7.6
* pytest version: 5.3.2

When usage of 'faker' fixture is specified through @pytest.mark.usefixtures("faker") placed before the test class definition:
```
@pytest.mark.usefixtures("faker")
class TestMyFakerExp():
    def test_faker(self):
        assert isinstance(faker.name(), str)

```
the next exception is thrown when the test is executed `pytest tests/my_tests/test_my_faker.py::TestMyFakerExp`:

```
    def test_faker(self):
>       assert isinstance(faker.name(), str)
E       AttributeError: module 'faker' has no attribute 'name'
```
At the same time when 'faker' fixture is passed directly to the test method, it works, assertion is PASSED:

```
class TestMyFakerExp():
    def test_faker(self, faker):
        assert isinstance(faker.name(), str)

```
In `conftest.py` having no additional definitions for faker fixtures.

**Comment by malefice** [comment]
The `pytest.mark.usefixtures` marker/decorator work on the assumption that you do not need access to the fixture object as stated in the [pytest docs](https://docs.pytest.org/en/stable/fixture.html#using-fixtures-from-classes-modules-or-projects), so I do not think it is an issue of this library. Your last code excerpt is the way to do it.

By the way, your code might be doing some variable shadowing. I would expect that your error to be `NameError: name 'faker' is not defined`, but your error says `AttributeError: module 'faker' has no attribute 'name'` instead, so you might already be using the variable `faker` in an outside scope.
