### ISSUE TITLE
How to add config for address with certain locale?

### ISSUE THREAD

**Issue by stopdesign** [joke2k/faker#1222]
* Faker version: 4.1.1

I'm using faker to generate addresses in several locales: fr_FR, ru_RU, en_GB...
Unfortunately there is no address provider for dk_DK and the default en_US is used.
So I have "danish" street names in the US format:
```
7059 Øjvind Manor
789 Østergaard Ports
523 Thygesen Pass
27582 Østergaard Village Suite 402
572 Jepsen Springs
```
Danish address format is different:
```
{{street_name}} {{building_number}}, apartment 
Oldjordsvej 2, 3. tv.
```
Can I adjust the address provider for dk_DK without making my own fork of the code?
Or can I at least change default locale to en_GB?

**Comment by stopdesign** [comment]
I think I figured it out:
```
class DanishStreetAddress(AddressProvider):

    building_number_formats = ('##', '#')

    street_address_formats = (
        '{{street_name}} {{building_number}}',
        '{{street_name}} {{building_number}}, {{building_number}}. th.',
        '{{street_name}} {{building_number}}, {{building_number}}. tv.',
        '{{street_name}} {{building_number}}, {{building_number}}. mf.',
        '{{street_name}} {{building_number}}, {{building_number}}. sal.',
    )

    def street_address(self):
        return super().street_address()

faker = Faker(['en_GB', 'dk_DK', 'fr_FR'])

# custom address provider for Danish locale
faker['dk_DK'].add_provider(DanishStreetAddress)
```

**Comment by malefice** [comment]
@stopdesign I am sorry for the late reply. Please consider submitting a PR for your localization so that in future versions, you and other folks that need Danish addresses will no longer need to go with `faker['dk_DK'].add_provider(DanishStreetAddress)`.

Create a module named `dk_DK` under `faker.providers.address`, and in that module's `__init__.py` file, use this template

```python 
from .. import Provider as BaseProvider

class Provider(BaseProvider):
    # Put your stuff here.
```
