### ISSUE TITLE
this tool is very good 

### ISSUE THREAD

**Issue by kingsalman99** [joke2k/faker#1224]
hello sir. 
this tool is very good. but I can't use it.

what is the command In cli. I am using termux

"i want to make bulk Fake addres with iban with country German" 

thank you

**Comment by fcurella** [comment]
Hi @kingsalman99 !

There's an example in the [README](https://github.com/joke2k/faker#command-line-usage).

Specifically for your use case, you can use something like:

```bash
faker -l de_DE -r 100 address
```

Where `100` is the number of addresses you want to generate.

**Comment by kingsalman99** [comment]
> Hi @kingsalman99 !
> 
> There's an example in the [README](https://github.com/joke2k/faker#command-line-usage).
> 
> Specifically for your use case, you can use something like:
> 
> ```shell
> faker -l de_DE -r 100 address
> ```
> 
> Where `100` is the number of addresses you want to generate.

Thanks Bro ,Good job may be useful
