### ISSUE TITLE
AttributeError: Invalid configuration for faker locale `en_IN`

### ISSUE THREAD

**Issue by Rajmehta123** [joke2k/faker#1225]
* Faker version: 4.0.0
* OS: Mac

Brief summary of the issue goes here.

Error when I am trying to load en_IN locale
`AttributeError: Invalid configuration for faker locale en_IN`

### Steps to reproduce

1. step 1 `pip install Faker`
1. step 2 `from faker import Faker`
1. step 3 `fake = Faker('en_IN')`

### Expected behavior

en_IN should be initialized

### Actual behavior

`AttributeError: Invalid configuration for faker locale en_IN`
![image](https://user-images.githubusercontent.com/22636443/88686953-a1ce2d80-d0c5-11ea-8ab3-49c79100bd9c.png)

**Comment by Rajmehta123** [comment]
Hey @fcurella 

Thanks for the quick reply.

But I see the locale in the ssn provider.

![image](https://user-images.githubusercontent.com/22636443/88694553-b105a900-d0ce-11ea-8097-4d2ab20ef2b6.png)

**Comment by fcurella** [comment]
@Rajmehta123 That providers was added _after_ version 4.0.0. Specifically, it was added in [4.0.3](https://github.com/joke2k/faker/blob/master/CHANGELOG.rst#403---13-april-2020). Try upgrading Faker to a newer version.

**Comment by Rajmehta123** [comment]
Yes. It worked. I was using pip install Faker which by default picked 4.0.0. I thought that is the latest release. Fixed it by upgrading. My bad.

Appreciate your help.
