### ISSUE TITLE
Faker.Commerce provider is missing

### ISSUE THREAD

**Issue by DoubleHub** [joke2k/faker#1231]
* Faker version: 4.1.1
* OS: Ubuntu 18.04 Bionic Beaver

While reading the documentation I've noticed that there is no Commerce provider (as seen [here](https://hexdocs.pm/faker/Faker.Commerce.html)). This provider would be pretty useful to implement as it allows the developer to generate fake product names, adjectives, etc...

### Steps to reproduce
There are no steps to reproduce as this is a missing provider.

### Expected behavior
The Commerce provider should be present.

### Actual behavior
There is no Commerce provider.

Maybe I didn't test it properly, and there's actually a Commerce provider hiding somewhere?

**Comment by fcurella** [comment]
Hi @DoubleHub ,

The documentation you're referring is a different package. It looks like there's a `Faker` package for Erlang, but this is the repo for the _Python_ Faker package.

**Comment by DoubleHub** [comment]
You are right, my bad. Closing this! Thanks for the help ^^
