### ISSUE TITLE
installed faker library still getting no module named faker

### ISSUE THREAD

**Issue by sushant23199** [joke2k/faker#1238]
* Faker version:
* OS:

Brief summary of the issue goes here.
ModuleNotFoundError: No module named 'faker'

### Steps to reproduce

1. step 1
1. step 2
1. step 3

### Expected behavior

X should be ...

### Actual behavior

X is ...

**Comment by fcurella** [comment]
Thank you for the report @sushant23199 

I really need more info to be able to help you. Specifically, I need Faker version and steps to reproduce at the very minimum.

**Comment by PlutarcoII** [comment]
Hello, I have the same issue:

Docker:
```
FROM python:3.7-slim-buster as img2
RUN apt-get update
RUN pip3 install Faker

RUN pip3 install fastapi
RUN pip3 install uvicorn

EXPOSE 8800
CMD ["uvicorn","api:appFastapi", "--reload", "--host", "0.0.0.0", "--port", "8800"]
...
```


LOGS: 
Collecting Faker
  Downloading Faker-4.1.2-py3-none-any.whl (1.0 MB)
Collecting python-dateutil>=2.4
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting text-unidecode==1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting six>=1.5
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, python-dateutil, text-unidecode, Faker
Successfully installed Faker-4.1.2 python-dateutil-2.8.1 six-1.15.0 text-unidecode-1.3

CODE:
```
import logging
import os
import json
import datetime
import time

from fastapi import FastAPI
from faker import Faker
```

Error:
img2_1  | Traceback (most recent call last):
img2_1  |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
img2_1  |     self.run()
img2_1  |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
img2_1  |     self._target(*self._args, **self._kwargs)
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
img2_1  |     target(sockets=sockets)
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 390, in run
img2_1  |     loop.run_until_complete(self.serve(sockets=sockets))
img2_1  |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 397, in serve
img2_1  |     config.load()
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 278, in load
img2_1  |     self.loaded_app = import_from_string(self.app)
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 23, in import_from_string
img2_1  |     raise exc from None
img2_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
img2_1  |     module = importlib.import_module(module_str)
img2_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
img2_1  |     return _bootstrap._gcd_import(name[level:], package, level)
img2_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
img2_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
img2_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
img2_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
img2_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
img2_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
img2_1  |   File "./api.py", line 14, in <module>
img2_1  |     import Faker
img2_1  | ModuleNotFoundError: No module named 'Faker'


Thanks

**Comment by fcurella** [comment]
@PlutarcoII you're import the wrong module name. The module name is `faker`, all lowercase. Tthe [Readme](https://github.com/joke2k/faker#basic-usage) shows how to correctly import it:

```python
from faker import Faker
fake = Faker()
```

**Comment by PlutarcoII** [comment]
@fcurella 

I got the same issue, but lowercase now.

img2_1  |   File "./api.py", line 14, in <module>
img2_1  |     from faker import Faker
img2_1  | ModuleNotFoundError: No module named 'faker'

**Comment by PlutarcoII** [comment]
@fcurella

It was my mistake. 

I was using docker command: 

` docker build -t ctrdash . `

instead of:

`docker-compose build`

Now, It's working as expected. 

Thanks a lot.
