### ISSUE TITLE
Typo for German job description

### ISSUE THREAD

**Issue by datadominik** [joke2k/faker#1251]
* Faker version: latest

I found a small typo in the job provider using German as a target language. There is no such word as "Forstwirst", it's "Forstwirt". (https://www.duden.de/suchen/dudenonline/Forstwirt , link to a German dictionary)

### Steps to reproduce

You can find the typo in line 27:
https://github.com/joke2k/faker/blob/master/faker/providers/job/de_DE/__init__.py

### Expected behavior

Should be: Forstwirt

### Actual behavior

Forstwir**s**t

**Comment by datadominik** [comment]
I created the following pull request for it: https://github.com/joke2k/faker/pull/1252

**Comment by fcurella** [comment]
fixed in https://github.com/joke2k/faker/pull/1252
