### ISSUE TITLE
Bad versioning in the repository

### ISSUE THREAD

**Issue by envil** [joke2k/faker#1264]
* Faker version: 4.1.2
* OS: macOS 10.15.6

The versioning of 4.1.2 is not good when it's a patch from 4.1.1 but new features were added (e.g. json generator)

### Steps to reproduce

1. machine 1 installs faker==4.1.1 before 4.1.2 was released.
2. machine 2 installs faker==4.1.2 after that, developers use new features.
3. code will break in machine 1 because 4.1.2 is considered compatible with 4.1.x and machine 2 had it installed.

Reference: https://semver.org/

### Expected behavior

4.1.2 should be 4.2.0

### Actual behavior

4.1.2 is 4.1.2

**Comment by fcurella** [comment]
I agree that `4.1.2` should've been `4.2.0`, but now we're on `4.1.3` and I don't think force-pushing is a good idea.

I can release `4.2.0` now, if that helps you.

I'd also like to set up some kind of process so we don't mess this up again, I'm open to any suggestion.

**Comment by envil** [comment]
Thank you for your quick response. If you really want to make it right then there's a solution:

1. Revoke the new features and release 4.1.4.
2. Cherry pick the changes of the new features and put them in 4.2.0

But that seems a bit too much and I think maybe it's ok to get away with it this time.
In the future I guess we can just stick to the SemVer then it will be fine. I don't know any process that can guarantee that you will tag the correct versions of the releases unfortunately. For me I just want to make sure future versions will be correct then I'm satisfied. I think we can close the issue now. Cheers :).
