### ISSUE TITLE
Danish address formatting in Faker

### ISSUE THREAD

**Issue by myicq** [joke2k/faker#1266]
* Faker version: 4.1.3
* OS: ubuntu 18

Faker does not produce a correctly formattet Danish address when locale da_DA is selected.

### Steps to reproduce

Get an address in Danish locale

`faker -l dk_DK address`

### Expected behavior

Output a Danish address format, like this:
`Æblerød Hovedgade 123`
`9999 Æblerød`

### Actual behavior

Output is an American format address with some Danish words/surnames inside.

`1815 Kristoffersen Field`
`West Kentmouth, NV 29761`

**Comment by fcurella** [comment]
We currently [don't have an address provider for `da_DK`](https://github.com/joke2k/faker/tree/master/faker/providers/address), so it falls back to `en_US` [as documented](https://github.com/joke2k/faker#localization).

Feel free to submit a PR for one and I'll be happy to include it :)

**Comment by johnbrandborg** [comment]
I would be happy to tackle this one.  My Wife is Danish, and I can speak some Danish myself.

**Comment by johnbrandborg** [comment]
I would be happy to try tackle this one.  Jeg taler også lidt dansk
