### ISSUE TITLE
substantive, adjetive, verbs, prepositions... provider or in lorem?

### ISSUE THREAD

**Issue by mondeja** [joke2k/faker#1269]
It would be awesome if we can retrieve a random word as currently does the `lorem` provider with `faker.providers.lorem::word`, but filtering by word type:

- [ ] substantives
- [ ] adjetive
- [ ] verb
- [ ] preposition

Is this within the reach of `lorem` provider? Only we need to separate `word_list` by word type, but I know that is a lot of work to do because currently there are 16 locales.

Any thoughs about this?

**Comment by fcurella** [comment]
I'm not convinced this is needed often enough that it's worth implementing and maintaining.

Besides, how do we know which words are nouns, verbs etc in the 'Latin' lorem ipsum, since it's not real Latin?

**Comment by malefice** [comment]
In addition to what @fcurella has stated, what you are proposing is somewhat Western-centric, and the "constructs" you have in mind do not apply very neatly in other languages. In Mandarin Chinese for example, you can use adjectives as verbs, you can stack verbs, and there are verbs that can be interpreted as prepositions, and the insanity does not end there.

I have had formal education in different (human) languages, and I dare say that it will be very difficult to design a uniform API for this, and I am not sure how worthwhile it will be. IMO, if you have a use case for this, it is best that you implement your own custom provider such that it works really well for your target locale.

**Comment by mondeja** [comment]
Thanks for your responses, I maybe will implement this in a third party provider. Greetings!
