### ISSUE TITLE
VAT for IT provider generates invalid values

### ISSUE THREAD

**Issue by LordGordonQ** [joke2k/faker#1272]
* Faker version: `4.1.3`
* OS: Linux Debian

`company_vat` for `it_IT` providers randomly returns invalid VAT values.

### Expected behavior

As example, `company_vat()` generated the invalid value `IT00472451194`. This value is not valid because the last part of the code, `IT#######119#` is not a valid number for the algorithm that validates the Italian VAT (the [stdnum library](https://github.com/arthurdejong/python-stdnum), for example, correctly recognize this as an invalid VAT). As described in the ["Partita IVA" (VAT) wikipedia page](https://www.wikiwand.com/it/Partita_IVA), the valid values must be in the range `001-100` plus the values `120,121,888,999`.

The current code is:

```python
def company_vat(self):
        """
        Returns Italian VAT identification number (Partita IVA).
        """
        code = "0" + self.bothify('######') + str(self.generator.random.randrange(1, 121)).zfill(3)
        luhn_checksum = str(calculate_luhn(code))
        return 'IT{}{}'.format(code, luhn_checksum)
```

this code has some issues:

- The `randrange` is generating invalid values.
- The method is not generating all the possible VAT due to the missing `888` and `999` values. Also, the first digit of the VAT is allowed to be values other than 0 (currently it is fixed to 0).

**Comment by fcurella** [comment]
Thank you for the report @LordGordonQ :)

Do you have time to work on a Pull Request to fix this?

**Comment by LordGordonQ** [comment]
> Thank you for the report @LordGordonQ :)
> 
> Do you have time to work on a Pull Request to fix this?

Yes, working on it right now. Also adding some tests that are missing.
