### ISSUE TITLE
Ranges too small in some state ZIP codes in the en_US locale

### ISSUE THREAD

**Issue by embooglement** [joke2k/faker#1277]
* Faker version: 4.1.2
* OS: MacOS X 10.15.6

It appears that in the `en_US` locale, two states are only associated with a single ZIP code. In particular, Texas will always return 73301, and Maryland will always return 20331. Additionally, Virginia only returns two ZIP codes, 20040 and 20041, and DC only returns 38 possible ZIP codes. While these are all technically valid ZIP codes for the corresponding state, they're not really representative of the variety of ZIP codes present in these states. For example, the use case that led me to noticing this requires simulating reasonable addresses in Texas specifically, and having all addresses be in a single ZIP code breaks the accuracy of the simulation.

### Steps to reproduce

1. Create a `Faker` instance with the `en_US` locale
1. Call `fake.postcode_in_state(state_abbr='TX')` or `fake.postcode_in_state(state_abbr='MD')`

### Expected behavior
`postcode_in_state` should always return a ZIP code for the given state, but it should be sampled from a large range of valid ZIP codes for the state. Ideally it would be from the full list of valid ZIP codes for the state, but I think it'd also be acceptable to pick a reasonably large subset (such as 75503 to 79999 for Texas)

### Actual behavior
`postcode_in_state` sometimes returns a specific ZIP code, or only samples from a small range of ZIP codes.

**Comment by malefice** [comment]
@embooglement this is very similar to #1060, and I am not sure why #892 implemented it this way for some states, but feel free to submit a PR. I also think that we should include source(s) for these zip codes, but I am not from the US so I do not know where to find something (semi-)official for this.
