### ISSUE TITLE
Turkish translation for job provider

### ISSUE THREAD

**Issue by molcay** [joke2k/faker#1280]
* Faker version:
* OS:

The job provider does not contain Turkish translation. It is using the base job provider.

### Steps to reproduce
```python
import faker
f = faker.Faker('tr_TR')
j = f.job()
```

### Expected behavior

`j` will needs to hold a job title in Turkish(e.g: Opera sanatçısı)

### Actual behavior

`j` will hold a job but it will in English(e.g: Investment banker, corporate)

**Comment by molcay** [comment]
I will implement the job provider for this (actually, I have). If it is OK with you, I will make a PR.

**Comment by fcurella** [comment]
Thank you so much @molcay ! Go for it!
