### ISSUE TITLE
[REQUEST] fake.programming_language

### ISSUE THREAD

**Issue by IgnisDa** [joke2k/faker#1305]
Pretty self explanatory. Faker should allow you to randomly generate valid programming language names. We can use this [Wikipedia list](https://en.m.wikipedia.org/wiki/List_of_programming_languages) to generate them.

This shouldn't be too hard to implement, so I can submit a PR for it soon once it is approved.

**Comment by fcurella** [comment]
I don't think this is a common enough case to be included by default. I'd rather see this packaged as a [community provider](https://github.com/joke2k/faker/blob/master/docs/communityproviders.rst).

**Comment by IgnisDa** [comment]
I just added a community provider a few days ago #1300 
Do you want me to create a new package for it or do I integrate it into the existing one?

I would personally prefer the first.

**Comment by fcurella** [comment]
I think a separate provider would be more appropriate

**Comment by IgnisDa** [comment]
Alright, you can expect a PR to your documentation soon!
