### ISSUE TITLE
en_US should implement postcode, not postalcode, see #789

### ISSUE THREAD

**Issue by munichpavel** [joke2k/faker#1307]
* Faker version: Faker==4.1.6
* OS:OS X 10.15.6

Brief summary of the issue goes here.

### Steps to reproduce

1. `faker = Faker('en_US')`
1. `faker.postalcode()`, outputs postal code
1. `faker = Faker('de_DE')`
1. `faker.postalcode()`, results in `AttributeError: 'Generator' object has no attribute 'postalcode'`

### Expected behavior

The method convention for postal code should be uniform across all locales, raised and (at least partially) fixed for `en_CA` in #790 

See [repo search for `postcode`](https://github.com/joke2k/faker/search?p=2&q=postcode) vs [repo search for `postalcode`](https://github.com/joke2k/faker/search?q=postalcode&type=code).

### Actual behavior

The `Faker` interface uses `postcode` for all locales but `en_US` and (still) `en_CA`.

*Note*: `postcode` is valid for all locales I have tested, so that this issue is just about consistency and saving developers myself who use autocomplete to find methods to avoid a few minutes of searching through the repo to see why `postalcode` doesn't work for non-US english locales.

**Comment by fcurella** [comment]
the `en_US` provider already implements [`postcode`](https://github.com/joke2k/faker/blob/master/faker/providers/address/en_US/__init__.py#L368-L369).

It was added in v4.14.0: (see: https://github.com/joke2k/faker/commit/8ad47c0467aa7240f46712b886a296b189157c5c) exactly for the reason you describe.

Try upgrading to at least `4.14.0`, that should fix your issue :)

**Comment by munichpavel** [comment]
Hi @fcurella ! 

Thanks for the feedback. As I mentioned, the issue is about consistency of the api, not missing features. The suggestion was to remove the (idiosyncratic) `postalcode` for locales `en_US` and `en_CA`, but if this would cause backwards compatibility issues or other head-aches, feel free to close.
