### ISSUE TITLE
Sometimes generated person names end with a space (in it_IT)

### ISSUE THREAD

**Issue by edomora97** [joke2k/faker#1311]
* Faker version: `Faker==4.14.0`
* OS: `Linux`

Sometimes the names it generates in Italian end with a space (e.g. `'Sig.ra Loretta Pagliaro '`), I suspect it's due to the fact that there are no suffixes defined.

Maybe the regression is introduced by https://github.com/joke2k/faker/pull/1030 (just a claim, it's the first time I use this library):

https://github.com/joke2k/faker/blob/299f6b6bbc18fc576642069ccfbf279160b7be54/faker/providers/person/it_IT/__init__.py#L13-L14

AFAIK Italian names do not have suffixes, and for sure no suffix is defined in that provider.

### Steps to reproduce

```python
>>> from faker import Faker
>>> fake = Faker("it_IT")
>>> for _ in range(1000):
...     name = fake.name()
...     if name.endswith(" "):
...         print(f"Invalid name: '{name}'")
...         break
... else:
...     print("Probably ok")
...
Invalid name: 'Sig. Goffredo Morellato '
```

### Expected behavior

All the generated names should not start or end with a space.

### Actual behavior

Sometimes the generated names end with a space.

**Comment by fcurella** [comment]
Thank you for the report, @edomora97 !

You are correct, the formats in `formats_male` and `formats_female` should not have any suffixes in them, since they are not defined anywhere in the Provider.

Would you mind submitting a Pull Request?

**Comment by edomora97** [comment]
Sure, tomorrow I'll submit one!
