### ISSUE TITLE
"latest" label on GitHub may need to update to the actual latest release (4.x.x)

### ISSUE THREAD

**Issue by bact** [joke2k/faker#1318]
Currently, the "latest" release tag/label points to v.0.5.6 at https://github.com/joke2k/faker/releases/tag/v0.5.6

### Expected behavior

The label should point to the latest release (4.x.x)

### Actual behavior

The label points to v.0.5.6 release from 7 March 2016.

**Comment by fcurella** [comment]
Thank you for bringing this up, @bact !

I've added a GitHub action, so now releases will be created every time we push a release tag to the repo.

**Comment by bact** [comment]
Thank you for prompt response!
