### ISSUE TITLE
image_url provider lorempixel is down 

### ISSUE THREAD

**Issue by Virako** [joke2k/faker#1319]
* Faker version: all
* OS: all

Provider image_url lorempixel is down

### Steps to reproduce

Enter in lorempixel.com

### Expected behavior

The provider should be online

### Actual behavior

lorempixel.com is down

### Proposal change

I propose changed by http://picsum.photos

**Comment by fcurella** [comment]
Hi, thank you for the report @Virako.

https://lorempixel.com is currently working for me. Can you confirm?

**Comment by Virako** [comment]
Hi, today is working but is very slow, 90 seconds in load one image (100x100) and other times timeout and error. Yesterday, I was looking for in similar projects and I found this discussion in other similar repositories:
* https://github.com/Marak/faker.js/issues/641
* https://github.com/fzaninotto/Faker/issues/1884

**Comment by EpocDotFr** [comment]
It's down for me as well.

**Comment by vicodeveloper** [comment]
https://lorempixel.com is down :(
