### ISSUE TITLE
Spelling errors in city names 

### ISSUE THREAD

**Issue by AnjaGer** [joke2k/faker#1322]
* Faker version: master
* OS:  ---

There are spelling error in the city name in de_DE
https://github.com/joke2k/faker/blob/master/faker/providers/address/de_DE/__init__.py

For example:
line 39 'Büsingenm Hochrhein', correct 'Büsingen am Hochrhein'
lin  77 'Neustadtm Rübenberge' correct 'Neustadt am Rübenberge'
line 87 'Rothenburg oberauber' correct 'Rothenburg ob der Tauber'
line 82 'Pfaffenhofenner Ilm' correct 'Pfaffenhofen an der Ilm'
line 75 'Mühldorf am Inn' correct 'Mühldorf am Inn'
line 80 'Osterodem Harz' correct 'Osterode am Harz'

**Comment by fcurella** [comment]
Thank you for the report, @AnjaGer !

Could you submit a Pull Request with those fixes?

**Comment by AnjaGer** [comment]
@fcurella 
I think I don't have the permissions to submit a pull request.
Should I send you the file via email?

**Comment by fcurella** [comment]
@AnjaGer You don't have permission to push, but you can fork, make your changes, and submit a Pull Request.

If you go to [the file](https://github.com/joke2k/faker/blob/master/faker/providers/address/de_DE/__init__.py) and click "Edit this file", GitHub will create a Fork and prepare the PR for you when you save your changes.

![Screen Shot 2020-11-19 at 4 36 26 PM](https://user-images.githubusercontent.com/89607/99732600-60eb9180-2a85-11eb-8dae-77a77ca7d5f0.png)

**Comment by AnjaGer** [comment]
@fcurella
Thanks for the description. I did everything as you described. Could you please take over?
