### ISSUE TITLE
Russian name transliteration chokes on "тов.", etc.

### ISSUE THREAD

**Issue by jeremywadsack** [joke2k/faker#1324]
* Faker version: 4.16
* OS: macOS Catalina 10.15.7

When generating person names, including Russian locale, `faker.providers.person.ru_RU.translit` crashes on names that include ".". These are included in the provided Russian names.

### Steps to reproduce

```
from collections import OrderedDict

from faker import Faker
from faker.providers.person.ru_RU import translit

LOCALES = OrderedDict(
    [
        ("ru_RU", 200),
    ]
)

i18n_fake = Faker(LOCALES)
for _ in range(5000):
    i18n_fake = fake.name()
    name = translit(name)
```
### Expected behavior

It should handle the "." character when transliterating them.

### Actual behavior

It crashes with this error:

```
  File ".../faker/providers/person/ru_RU/__init__.py", line 18, in translit
    text = text.replace(letter, translit_dict[letter])
KeyError: '.'
```

### Current workaround
```
        if re.match("\\p{Cyrillic}", name):
            name = name.replace(
                ".", ""
            )  # Work around bug in faker.providers.person.ru_RU#translit
            name = translit(name)
```

**Comment by fcurella** [comment]
Thank you for the report, @jeremywadsack ! Could you submit a Pull Request?
