### ISSUE TITLE
Performance Optimizations

### ISSUE THREAD

**Issue by prescod** [joke2k/faker#1327]
* Faker version: Master branch

* OS: Mac OS 

I am a Performance Engineer at Salesforce.org and I use Faker within my tool Snowfakery to generate hundreds of millions of rows of data. Some teams within my company have avoided Faker because they say it is too slow.

I'm a huge fan of Faker, but it is true that despite the complexity of Snowfakery overall (including writing to a SQL database), Faker is often the bottleneck. Luckily, it seems easy to fix.  I investigated and found some very quick wins in terms of performance.

If the person creating the Faker() object could have more influence on the random_element method, they could get a gigantic speedup. I understand that some people in some cases need the sophisticated distribution features of the underlying Faker library, but my users do not, so I wish I could turn them off.

### Steps to reproduce

```
from unittest.mock import patch
import random
from collections import OrderedDict

import faker
import timeit

def bench():
    f = faker.Faker()

    print(timeit.timeit(lambda:f.first_name(), number=100000))
        

def fast_random_element(self, choices):
    if isinstance(choices, OrderedDict):
        return random.choice(tuple(choices.keys()))
    else:
        return random.choice(choices)


def fast_random_element_2(self, choices):
    if isinstance(choices, OrderedDict):
        if not hasattr(choices, "_cached_choice_list"):
            setattr(choices, "_cached_choice_list", tuple(choices.keys()))
        choices = choices._cached_choice_list

    return random.choice(choices)

def all_bench():
    print("Warmup")
    bench()
    print("Normal")
    bench()
    with patch("faker.providers.BaseProvider.random_element", fast_random_element):
        from faker import providers
        print("Simple optimization - No caching")
        bench()

    with patch("faker.providers.BaseProvider.random_element", fast_random_element_2):
        print("With caching")
        bench()
    print("Baseline again")
    bench()

all_bench()
````

### Expected behaviour

Faker should be roughly as fast for simple element choices as Python itself.

### Actual behavior

These times are in seconds:

```
Faker
6.72312176
Simpler optimization
1.888246217999999
With caching
0.3221195019999996
```

I am willing to submit a PR for this but I might need some guidance about where you would want to store the "weighted or fast" flag. Perhaps pass it from the Faker() constructor to the Provider objects?

**Comment by fcurella** [comment]
Thank you! Nice work!

I agree with you, this is a feature flag worth having.

I agree this should be an initialization argument on the main constructor
class. We could have it as ‘distributions=True’, defaulting to the slower
behavior for backward compatibility.

**Comment by bact** [comment]
Very nice.

**Comment by prescod** [comment]
Have you guys seen this error?

```  
@pytest.fixture(autouse=True)
def faker(_class_locale_faker, faker):
E       recursive dependency involving fixture 'faker' detected
```

```
 $  pytest --version
pytest 6.1.2
```

I can test in tox but that's very slow.

**Comment by bact** [comment]
I'm thinking of a case that although there's no need to have a realistic distribution but at the same time would like to avoid rare entities to occur a lot in the data set. So proposed that we could have a one-time easy filter for this.

```python
def fast_random_element_3(self, choices):
    if isinstance(choices, OrderedDict):
        if not hasattr(choices, "_cached_choice_list"):
            sum_p = sum(choices.values())
            # keep only ones with higher than 0.5% (the number is arbitrary)
            filtered = [a for a, p in choices.items() if p/sum_p > 0.005]
            setattr(choices, "_cached_choice_list", tuple(filtered))
        choices = choices._cached_choice_list

    return random.choice(choices)
```

**Comment by bact** [comment]
> Have you guys seen this error?
> 
> ```
> @pytest.fixture(autouse=True)
> def faker(_class_locale_faker, faker):
> E       recursive dependency involving fixture 'faker' detected
> ```
> 
> ```
>  $  pytest --version
> pytest 6.1.2
> ```
> 
> I can test in tox but that's very slow.

How to get into this?
I normally go with tox.

**Comment by prescod** [comment]
I just ran "pytest" without tox.

**Comment by prescod** [comment]
@bact : I'm not opposed to your suggestion but I also haven't personally seen a use-case for it. Do you have a specific use-case in mind? In my datasets I don't care if "Waldo" appears as often as "John", personally.

**Comment by fcurella** [comment]
@prescod feel free to submit a PR whenever you have time :)

**Comment by prescod** [comment]
@fcurella Do you have an opinion on:

https://github.com/joke2k/faker/issues/1327#issuecomment-734748785

**Comment by fcurella** [comment]
> I'm thinking of a case that although there's no need to have a realistic distribution but at the same time would like to avoid rare entities to occur a lot in the data set

@prescod That sounds too magical. I'd rather keep it simple and shift the responsibility to the user.

**Comment by bact** [comment]
Agree to keep it simple.
