### ISSUE TITLE
Arabic names are sometimes empty

### ISSUE THREAD

**Issue by prescod** [joke2k/faker#1361]
* Faker version: 5.4.0
* OS: Mac, Linux, Windows

My pull request fails when ar_PS or one of the other Arabic generators generates the empty string. I don't know what about my branch triggers this bug but the bug seems to exist on master.

### Steps to reproduce

Run this program:

https://repl.it/talk/share/Faker-bug-relating-to-arabic/113973

```
from faker import Faker

f = Faker("ar_PS")
for i in range(0, 10000):
    name = f.first_name_female()
    print(name)
    assert name, f"'{name}', {len(name)}, {i}"
```

### Expected behavior

The program should print 10,000 names.

### Actual behavior

It always fails its assertion in the first 1000 names.

**Comment by prescod** [comment]
I can reproduce the issue in pytest on master with a carefully crafted test case. I'm not sure why it shows up more often on my optimization branch however.

https://github.com/joke2k/faker/pull/1362/commits/badd77b5156cfeff3649ea9e70176e2f415ce3c0

**Comment by fcurella** [comment]
Thank you so much for your work, @prescod! It's been very helpful.

There is an empty in string in the [`first_names_female` of the `ar_AA` Person provider](https://github.com/joke2k/faker/blob/master/faker/providers/person/ar_AA/__init__.py#L38). I swear I've look at that file at least a dozen times before, and couldn't find it.

I'm going to remove the empty string, and you can rebase your branch.
