### ISSUE TITLE
Random sentence of length 1 fails

### ISSUE THREAD

**Issue by DanielHarrisSeequent** [joke2k/faker#1367]
* Faker version: 5.5.0
* OS: Ubuntu 20.04.1

Creating a random sentence of length 1 fails because it attempts to titleize the first word of the sentence, but `random_choices`  is returning a tuple which is immutable. 

This also occurs sometimes with 2 or 3 length sentences, although I presume that under the hood they are randomly selecting sentences of length 1.

This works as expected in Faker version 5.4.1.

### Steps to reproduce

```
>>> import faker
>>> thing = faker.Faker()
>>> print(thing.sentence(1))
```

### Expected behavior

A random titleized word is printed with a fullstop

### Actual behavior

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "~/.../venv/lib/python3.6/site-packages/faker/providers/lorem/__init__.py", line 86, in sentence
    words[0] = words[0].title()
TypeError: 'tuple' object does not support item assignment
```

**Comment by fcurella** [comment]
Hi, Thank you for the report @DanielHarrisSeequent !

I've made a Pull Request with a fix. It should be released today, pending CI :)

**Comment by DanielHarrisSeequent** [comment]
Cheers

**Comment by lewis-grimmett** [comment]
@fcurella Hi I was just about to report this and a fix - FWIW I think the real issue is here: https://github.com/joke2k/faker/blob/acdfc155099722414be5e46103ad09c3bf19c58b/faker/utils/distribution.py#L64 where a tuple is returned erroneously
