### ISSUE TITLE
Synchronize states and countries?

### ISSUE THREAD

**Issue by prescod** [joke2k/faker#1386]
Brief summary of the issue goes here.

People often use my Snowfakery tool to write programs that randomly choose a locale and generate an address for the locale. There are two challenges that I'd like to ask for advice on.

1. The name for the field bigger than city but smaller than country varies from place. State, province, prefecture, ... A lot of databases have a single field for this concept: does Faker have a standard way to handle it? Is there any name to ask it to find the middle-region-thing no matter what it is called in that locale.

2. If you set the locale you must also hard-code the country to go with it for the purposes of addresses. Does Faker have within it any easy way to do that mapping or should I to bundle a locale-code -> country mapping?

**Comment by fcurella** [comment]
> The name for the field bigger than city but smaller than country varies from place. State, province, prefecture, ... A lot of databases have a single field for this concept: does Faker have a standard way to handle it? Is there any name to ask it to find the middle-region-thing no matter what it is called in that locale.

We have done that for `postcode`, (eg 3d5f440308499db2c198f5b69232656ad0e70a30, 75545664912ea4262cd2130249bdca868c2c28e9).

Some locales used to have `zipcode` and some had `postcode`. We made sure all had `postcode`, and aliased the "localized method" to it. We could the same for `administrative_area`.

> If you set the locale you must also hard-code the country to go with it for the purposes of addresses. Does Faker have within it any easy way to do that mapping or should I to bundle a locale-code -> country mapping?

There currently isn't anything like that, but it wouldn't be too hard to add ``current_country()`` method.

**Comment by prescod** [comment]
With respect to `current_country()` : Do I have to manually add it to every Provider or is there a way to infer from the locale what the country is (in the locale language!).

With respect to `administrative_area`? What do you think about having both that name and also `state` as a short alias for it?

Should administrative_area raise or return empty string when a country has none?

Possible precedent:

https://github.com/joke2k/faker/blob/66e29ce5838720906a74b6a86ab3b73234201def/faker/providers/address/en_NZ/__init__.py#L227

**Comment by prescod** [comment]
@fcurella what are your thoughts on this? ^

**Comment by fcurella** [comment]
I think we can find a way to infer `current_country` and just implement it in the Base Provider class.

If all we need is the current country _code_, then all we have to do is something like `current_locale.split('_')[1]`. If we want the name, we'll have to map that code to a localized name somewhere.

re `administrative_area`: I would expect the behavior to be exactly the same as with `postcode`. The logic will be in `administrative_area`, and localized methods (ie `state`) will be the short alias.

In the rare case where a Country does not have an administrative area (small countries like, say, Monaco), I think it should raise an exception.

**Comment by prescod** [comment]
> If we want the name, we'll have to map that code to a localized name somewhere.

It's that mapping of (current_locale, country_code) -> string that I'm looking for. We have *lists* of countries for each locale, but the lists are probably not in a reliable order and I don't think they are indexed by country code.

I guess I could implement it for English and then let every language implementer override it when they get a chance?
