### ISSUE TITLE
pyfloat provider with positive=True sometimes returns zero

### ISSUE THREAD

**Issue by sciencectn** [joke2k/faker#1387]
* Faker version: 5.8.0
* OS: macOS 11.1

Call pyfloat with positive=True, and it will sometimes return a zero. 

### Steps to reproduce

Here's an example:

```
import faker
f=faker.Faker()
are_zero = [f.pyfloat(positive=True, max_value=10)==0 for _ in range(100)]
print(any(are_zero))
```

### Expected behavior

It should always print `False` always. 

### Actual behavior

Sometimes it's `True` with f.pyfloat() returning zero.

**Comment by fcurella** [comment]
Thank you for the rpeort, @sciencectn !

Would you mind submit a Pull Request?

**Comment by sciencectn** [comment]
Sure, I'll give it a shot.

**Comment by sciencectn** [comment]
Let me know what you think: #1393
