### ISSUE TITLE
Generate specific Swedish MSISDNs

### ISSUE THREAD

**Issue by michjnich** [joke2k/faker#1400]
* Faker version: 6.3.0
* OS: Any

No ability to generate a Swedish mobile number. 

### Steps to reproduce
1. Run `Faker().msisdn()` when locale set to `sv_SE`

### Expected behavior
X should be a random msisdn in the Swedish format

### Actual behavior
X is random global MSISDN

Swedish MSISDNs start with `07` (or 00467, or +467), and are of the form +467ssnnnnnn, where 07ss is the number series, and nnnnnn is the number, with some notable exceptions - see [https://en.wikipedia.org/wiki/Telephone_numbers_in_Sweden](https://en.wikipedia.org/wiki/Telephone_numbers_in_Sweden) and check the `07` ranges for more specific info. 

The issue here of course is that perhaps there is a need to grab a global MSISDN when the Swedish locale is set, as well as existing use cases that rely on current behaviour, so both behaviours need to be supported.

I see 2 options: 

1. Add a new method for a locale - `local_msisdn`, `locale_msisdn`, `country_msisdn` maybe, or something else. 
2. Override `msisdn` to add a `local`, `locale` or `country` boolean parameter (that defaults to `False` to maintain current behaviour` which would then restrict the returned value to Swedish format (or whatever other local format anybody wants to implement. If a value is passed without a locale, or for a locale that doesn't support it, it would of course error. 

Open question as to what to put in the docs for this as well.

I'd probably lean towards the second option, but that's just me maybe?

**Comment by fcurella** [comment]
[`pt_BR`](https://github.com/joke2k/faker/blob/66e29ce5838720906a74b6a86ab3b73234201def/faker/providers/phone_number/pt_BR/__init__.py) simply overrides the `msisdn_formats` and always returns local MSISDNs. I think the `sv_SE` provider should do the same. 

The expectation is that if a localized provider is missing a method, it would fall back to what's in the `en_US` provider. If anything, the bug is that `phone_number.en_US` is NOT localized.

Instead of a `local` argument, I'd add a `global` argument, and default it to `False`.

I'm not sure if this would constitute a MAJOR or a MINOR change. We could bump the MAJOR version just to be on the safe side.

**Comment by michjnich** [comment]
That makes sense. I guess really there should be a "global" method that `en_US` inherits from and overrides in the same way. 

Adding the `global` and defaulting to `False` would change behavior for existing Swedish implementations. It woul dhave to default to `True` for it not to make a difference, but I think you're right in that `False` should be the default. 

I can sort this during the week probably, if you're OK with the solution?

**Comment by fcurella** [comment]
sorry for the late response.

Let's add `global`, defaulting it `False`, and we can schedule this to go out on our next MAJOR version.

**Comment by michjnich** [comment]
Hi, no problem. I'd actually totally forgotten about this too - a couple of days after writing that last message I got covid - not seriously, but the symptoms lingered for about 10 weeks after and I confess to not doing much at all during that time! 

I'll see if I can find some time to pick this up again - pretty sure I can make use of this functionality in the future at some point :)
