### ISSUE TITLE
Calling pyfloat with `right_digits` and `positive` set can yield much smaller number (sys.float_info.epsilon)

### ISSUE THREAD

**Issue by tomage** [joke2k/faker#1402]
* Faker version: 6.4.1 (latest as of submitting this issue)
* OS: OSX 10.14.6

Calling pyfloat with `left_digits=0`, `right_digits=N` and `positive=True` can yield a value with way more right digits than `N`.

### Steps to reproduce

This _can_ happen (if you're "lucky"):
```python
>>> import faker
>>> print(faker.Faker().pyfloat(left_digits=0, right_digits=2, positive=True))
2.220446049250313e-16
```

A more surefire way to reproduce this is to run in a for-loop, i.e.:
```python
>>> import faker
>>> my_faker = faker.Faker()
>>> for _ in range(1000):
...     f = my_faker.pyfloat(left_digits=0, right_digits=2, positive=True)
...     if f < 0.001:
...         print('This is odd!', f)
```

Out of the 1000 calls, about 10 should print out `This is odd! 2.220446049250313e-16`

This can also be reproduced with `left_digits=1`, with less frequency (and probably for any value of `left_digits` - just less likely), and also with various values of `right_digits`. `right_digits=1` makes this happen roughly every 10th call to the function.

### Expected behavior

If `left_digits=0` `right_digits=2` and `positive=True` - I would expect all values to be in the interval `[.01 -> .99]`.

Actually it might even be debatable if `left_digits=0` has really any meaning. Perhaps it means that the number is always `0.<right-side>`? Whereas `left_digits=1` means it can be `\d.<right-side>`.

### Actual behavior

Occasonally (every 10th/100th/etc.. call, depending on input parameters) a value of `2.220446049250313e-16` pops out.

### Analysis/suggestions

Reading thru the source code, I see the culprit. `Provider.pyfloat` _can_ end up with a `0` close to the end of that function. But if that is the case, and `positive == True`, it adds `sys.float_info.epsilon`. This does make sense on the outset - but not if the caller has also stated they want maximum of `N` `right_digits`.

I monkey patched the lib in my code for now to call `pyfloat` again and again, until I get a "valid" value.

Side-problem: Seems that one cannot get values such as `0.01` when calling pyfloat. This is because the right-side is constructed with `f'{sign}{left_number}.{self.random_number(right_digits)}`. Now, if `self.random_number(right_digits)` returns 10, or 1 - they both end up as `.1` in the final number. Less of an issue really, but it does narrow the interval to `[.1 -> 0.99]` (i.e. excludes anything less than `0.1`).

### Final thoughts

Thanks in advance! We use Faker quite a bit in our test suite, and appreciate greatly the effort you put into the library! I'd be more than happy to write my own patch and submit a PR if you'd like me too, or participate in reviewing a PR if any of you are going to fix it up.

**Comment by tomage** [comment]
Note: I'm def. not suggesting my approach to solving it is the way to go (the while-loop until you get a valid value) :)
But that seemed the neatest way in my code to fix this temporarily.
Not sure how best to fix this in the code - didn't wanna dive that deep unless you wanted me to suggest a PR/patch.

**Comment by fcurella** [comment]
Thank you so much for your very detailed analysis, @tomage ! Really great work!

I'll be happy to review your PRs if you have time to work on it. I'd just ask if we could have 2 PRs: one for the "side problem" you mentioned (the "concatenating 10" problem), and the one for `float_info.epsilon`

**Comment by tomage** [comment]
Well, I'll be happy to contribute @fcurella !
And yeah - would definitely write up in two separate PRs (I'm a stickler about keeping gits and PRs atomic!).

I'll follow the contribution guidelines and hopefully come up with a patch in a day or two.

**Comment by tomage** [comment]
Taking the liberty to close this issue (CC @fcurella  - not sure if the policy is to keep these open until whatever fix goes out into a release..? But feel free to re-open if that is the case).
