### ISSUE TITLE
Feature Request: Fake JWT Tokens

### ISSUE THREAD

**Issue by EricOuma** [joke2k/faker#1409]
From the reading I have done, I believe this feature does not exist.

Could we have a feature for generating fake access and refresh tokens:
```
tokens = fake.tokens()
tokens.access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpX.....
tokens.refresh_token = eyJzdWIiOiIxMjM0NTY3ODk.........
```

Sort of what happens here [https://django-rest-framework-simplejwt.readthedocs.io/en/latest/creating_tokens_manually.html](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/creating_tokens_manually.html)

**Comment by fcurella** [comment]
This sounds like a useful feature, but I'm not sure how we could implement it in a way that's easy to use _and_ still be useful.

* How would the payload to be encoded look like?
* How long should the token last?
* How much  customization should we allow? Are we going to end up with a method accepting [all these arguments](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html)?

**Comment by EricOuma** [comment]
I thought of this as I was writing tests for my DRF API and I needed to test that invalid tokens can't be used. I found a way around this. Thank you.
