### ISSUE TITLE
Idea: Generating Australian Business Number (ABN)

### ISSUE THREAD

**Issue by l33tr4n555** [joke2k/faker#1412]
### Faker ABN:

Here is the python code I used in my test to generate ABN 
Please add it to the faker if possible.
Thanks,

```
import sys
import random

weighting = [10, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

def validate(abn):
    """
    Validate that the provided number is indeed an ABN.
    """
    values = map(int, list(abn))
    values[0] -= 1
    total = sum([x * w for (x, w) in zip(values, weighting)])
    return total % 89 == 0

def abn():
    """
    Generate a random ABN
    """
    value = ''.join([str(int(random.random() * 10)) for i in range(9)])
    temp = list('00%s' % value)
    total = sum([w * x for (w,x) in zip(weighting, map(int, temp))])
    remainder = total % 89
    prefix = 10 + (89 - remainder)
    abn = '%s%s' % (prefix, value)
    assert validate(abn), '%s is not a valid ABN' % abn
    return abn

sys.stdout.write(abn())
```

**Comment by fcurella** [comment]
Hi @l33tr4n555 !

Feel free to submit a Pull Request, I'll be happy to review it :)

**Comment by l33tr4n555** [comment]
I tried to create a branch fix/master/1412-ABN from this repo, I can't push it back 

I tried to fork this repo and then create a branch branch fix/master/1412-ABN. I can't push it back. 

Any permission need to change here?

**Comment by fcurella** [comment]
@l33tr4n555 are you sure you're pushing the new branch to your fork? GitHub has a good [guide about making Pull Requests from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by l33tr4n555** [comment]
my bad authorization is out dated. I synced up again ... All good now
