### ISSUE TITLE
gmail.co.uk isn't a valid free email domain in the UK

### ISSUE THREAD

**Issue by efung** [joke2k/faker#1417]
* Faker version: 6.6.2
* OS: macOS 11.2.3

When generating a free email address, I got a result with the domain `gmail.co.uk`. From the source code, this list of free UK email domains was copied from the PHP version of Faker, which is now archived. 

According to [this Google support thread](https://support.google.com/mail/thread/4572636?hl=en) (albeit not necessarily from someone with the authority to speak on behalf of Google), there is no such domain.

### Steps to reproduce

1. Configure Faker with the `en_UK` locale.
1. Generate free emails by calling `fake.free_email()` repeatedly
1. Observe that some of them end in `gmail.co.uk`

### Expected behavior
Email addresses should not have `gmail.co.uk` as a domain.

### Actual behavior
As a replacement, maybe include Hotmail's successor, `outlook.com`?  It's not UK specific, but I don't know anything about the state of free UK email providers.

**Comment by bact** [comment]
@efung please see the proposal in #1432 - removing gmail.co.uk in en_GB
