### ISSUE TITLE
Provide API to return address parts that are all from the same locale

### ISSUE THREAD

**Issue by efung** [joke2k/faker#1419]
* Faker version: 6.6.2
* OS: macOS 11.2.3

When generating addresses, there may be times when you do not want to replace a full mailing address, with the street address, city, state/province/region, country, post code.  You might only want to replace a city and state, or a city and post code.

Currently, if Faker is configured with multiple locales, calling `fake.city()` and `fake.state()` might return a city and state that are in different countries.

One idea might be to have an API, e.g. `fake.address_parts()` which would return a dictionary of the elements that make up a complete address, **but are all from the same locale**. The keys would be `city`, `street`, `region`, `country`, etc.

**Comment by prescod** [comment]
Yes I've been thinking about how to add this feature to Snowfakery (which is built on Faker) as well.

https://github.com/SFDO-Tooling/Snowfakery/issues/233
