### ISSUE TITLE
Generate a fake email that is consistent with a fake name

### ISSUE THREAD

**Issue by lucazav** [joke2k/faker#1420]
Hi all,

is it possible to generate a fake email that is consistent with a fake name? For example, if a name is "John Smith", I expect to have an email like "johnsmith@example.com".
Simply put, is there a way to use the `safe_email()` (or the `email()`) function like this:

```
name = fake.name()
fake.safe_email(name)
```

Thank you.

**Comment by 2000prath** [comment]
This will help 
you can add as many email provider name in `mails` list
```
import random
def safe_email(name):
    #Use email provider list from this url
    #https://gist.githubusercontent.com/tbrianjones/5992856/raw/93213efb652749e226e69884d6c048e595c1280a/free_email_provider_domains.txt
    mails = ['edge.com','gmail.com','yahoo.com','example.com']
    words=name.split()
    if len(words)>2:
        result = words[0]+words[-1]+'@'+random.choice(mails)
    else:
        result = words[0]+'@'+random.choice(mails)
    return result

```

**Comment by OJFord** [comment]
You could construct the email yourself from a fake name + fake domain, i.e. something like:
```python
name = fake.name()
f"{name.replace(' ', '-')}@{fake.domain()}"
```
