### ISSUE TITLE
Add new optional argument to the hex color functions to skip adding the leading #

### ISSUE THREAD

**Issue by nickjj** [joke2k/faker#1424]
* Faker version: 7.0.1
* OS: Ubuntu

Currently we have these 3 functions to generate a random hex color:

```python
>>> Faker.seed(0)
>>> for _ in range(5):
...     fake.color(hue='red')
...
'#af2f33'
```

```python
>>> Faker.seed(0)
>>> for _ in range(5):
...     fake.hex_color()
...
'#d82c08'
```

```python
>>> Faker.seed(0)
>>> for _ in range(5):
...     fake.safe_hex_color()
...
'#cc5500'
```

It would be nice if we had an optional argument to skip outputting the leading `#` so it only returns the hex color itself. That could be done by adjusting the return value to have `[1:]` applied if it's set.

As for the argument name, that's up to you. Maybe it could be `skip_hash` which defaults to `False` to keep things backwards compatible, or `with_hash` which defaults to `True` if that's easier to reason about.

**Comment by 2000prath** [comment]
add one positional argument in function to `skip_hash ` 
```
def safe_hex_color(skip_hash):
    #generate color and store the hashcode in 'result' variable
    result = '#cc5500' 
    result = result[1:] if skip_hash else result
    return result
```

**Comment by fcurella** [comment]
Couldn't you apply the slicing to the returned value in your code?

```python
colors = [fake.hex_color()[:1] for _ in range(9999)]
```

Seems to be like adding arguments to the signature would more complex than just having users converting the results to their more specific use-case. What if you need uppercase and no hash (eg `CC5500`)? Should we also add an `uppercase=False` argument?

**Comment by nickjj** [comment]
> Couldn't you apply the slicing to the returned value in your code?

Sure, I've ended up creating my own local "faker" module which then calls yours which strips the prefix. I didn't want to inline parse the return value where I called it directly because it doesn't feel like the right abstraction.

> What if you need uppercase and no hash (eg CC5500)?

At some point you need to draw the line I suppose.

In my case with the `#` this is a difference of storing 6 characters or 7 characters in a database for around 175,000 rows so I thought it could be beneficial to store the value without the `#` directly and opened this issue because it seemed like something I'd want to do in multiple projects, preferably without having to make my own faker module in all of those projects.
