### ISSUE TITLE
What is the semantics of faker major versions?

### ISSUE THREAD

**Issue by pudo** [joke2k/faker#1425]
In general [semver](https://semver.org/) parlance, a major version upgrade indicates that a package has made significant, breaking changes to its API. This seems to occur with `faker` about every month or so in the last while, making it by far the fastest moving dependency among the 100 or so Python packages we depend on. Yet I've noticed that none of these major API versions really broke the API noticeably.

In the project we're using `faker` in, we're trying to pin the dependency so that a person who wants to build version X of the project in 18 months could still get compatible versions of dependencies. In that context, what is the recommended pinning policy for faker:

a) Pin to a specific version and never upgrade 
b) Upgrade to each major version and spend a few hours validating that it doesn't break
c) Just leave `faker` unpinned, because the API doesn't really break

Thanks for your advice.

**Comment by fcurella** [comment]
We upgrade the Major version every time a change could break compatibility
with _any_ of users. So the last breaking change may not have broken
anything for you, but broke for other people that use Faker in
different ways than yours (in this specific case, using the CLI).

I do agree the pace can be too much. Maybe we can have a policy where we
delay breaking changes so we don’t have more than one every 18 months.

**Comment by pudo** [comment]
Thanks very much for your response. If there could be some bundling of breaking changes that makes major version releases a bit less frequent, it would indeed make adopting the library a bit less involved :) Appreciate your thoughts.
