### ISSUE TITLE
Update readthedocs with latest providers

### ISSUE THREAD

**Issue by dkotschessa** [joke2k/faker#1430]
I am very grateful that my community provider has been added to the list of community providers in the documentation:
https://github.com/joke2k/faker/blob/master/docs/communityproviders.rst

However - and perhaps I am being too impatient - it has been 4 days - the documentation has not been refreshed here: 
https://faker.readthedocs.io/en/master/communityproviders.html

Please let me know if it will be updated so I can brag about it. :)  (I plan on creating more providers in the future)

**Comment by fcurella** [comment]
Hi @dkotschessa 

the docs are spposed to built automatically every time there's a commit to master, but the build is broken.

I'm in the process of fixing it. I'll keep you posted!

**Comment by fcurella** [comment]
The docs build is now fixed. Thanks for your patience!

**Comment by dkotschessa** [comment]
@fcurella great! thanks!
