### ISSUE TITLE
Faker produces double the amount of requested fake.data

### ISSUE THREAD

**Issue by cocoonkid** [joke2k/faker#1457]
* Faker version: faker (8.6.0)
* OS: Linux Arch  and MacOS Big Sour 11.14

Flask 2.x

fake = Faker()
fake.add_provider(internet)

### Steps to reproduce

```
# Create dummy user data
def generate_dummy_data(amount):
    for i in range(amount):
        sex_option = ["male", "female"]
        random_sex = choice(sex_option)
        random_age = randint(12, 99)
        random_weight = randint(15, 200)
        random_height = randint(50, 230)
        username, password, sex, weight, height, age = fake.user_name(), fake.password(), random_sex, 
        random_weight,random_height, random_age
        generated_user = User(username=username, password=password,
                              sex=sex, weight=weight, height=height, age=age)
        db.session.add(generated_user)
        db.session.commit()
```
```
if __name__ == '__main__':
    db.create_all()
    generate_dummy_data(3)
    app.run(debug=True, host='127.0.0.1')
```

### Expected behavior
```
 generate_dummy_data(3)  should generate 3 database entries 
```

### Actual behavior
```
 generate_dummy_data(3)   generates 6 database entries 
```

EDIT:            
The database fields have constraints and these are kept e.g. the database as cause can be excluded.
It's a one table sqlite for what it's worth.
![image](https://user-images.githubusercontent.com/43231640/121381234-d5b0eb00-c945-11eb-886a-3303cb9a8dbc.png)

Thank you in advance

**Comment by fcurella** [comment]
Hi @cocoonkid 

Could you try to move the `db.session.commit()` out of the loop (IE: could you de-dent it 1 level back?)

**Comment by cocoonkid** [comment]
I de-dented once to the end of the loop, and once to the end of the function but both cases still generate 6.
I was surprised though that it didn't throw an error.

**Comment by fcurella** [comment]
I don't see how `Faker` could be generating 6 entries, since you're SQLAlchemy to commit the entries to the database.

I would add a [`pdb.set_trace()`](https://docs.python.org/3/library/pdb.html) right above the `for` loop and see if `generate_dummy_data` gets called twice for some reason.

**Comment by cocoonkid** [comment]
I just went through it step by step with the vscode debugger.
It correctly sets amount to 3 and stops after i <= 2.

This is quite a curious issue.

**Comment by cocoonkid** [comment]
I am happy to report that I found the root cause of this issue. I haven't confirmed it yet but will do soon.
 
https://stackoverflow.com/questions/14874782/apscheduler-in-flask-executes-twice
```


In debug mode, Flask's reloader will load the flask app twice (How to stop Flask from initialising twice in Debug Mode?). I'm not sure why this is, but it causes apscheduler's jobs to be scheduled twice. A quick print "loaded scheduler" right before sched.start() confirms this.

There are a couple ways around this, as mentioned in the linked answer. The one I found that worked best is just to disable the reloader like so:

app.run(use_reloader=False)

It means I have to reload my app manually as I develop it, but it's a small price to pay to get apscheduler working.



```

I will report back as soon as I have confirmed. I recommend adding this information as a hint to the docs.
