### ISSUE TITLE
Bug in `mac_platform_token`

### ISSUE THREAD

**Issue by iamkeyur** [joke2k/faker#1466]
* Faker version: Latest
* OS: Any

`mac_platform_token` generates a MacOS platform token used in user agent strings. However, during https://github.com/joke2k/faker/commit/da1ae11a06a8f64bd4b0f7d1391d7661521e4caf#diff-7d7f34af58b0ae686b413e6ed3463229243aacfb0891fbc544cb951224c5af97L220, looks like it got missing underscore. Now, it generates `Macintosh; PPC Mac OS X 10 6_5` where as it should be `Macintosh; PPC Mac OS X 10_6_5`

### Expected behavior

Output of `mac_platform_token` should be `Macintosh; PPC Mac OS X 10_6_5`

### Actual behavior
`Macintosh; PPC Mac OS X 10 6_5`

**Comment by fcurella** [comment]
Thank you for the report @iamkeyur ! Do you have time to submit a Pull Request?

**Comment by iamkeyur** [comment]
Sure, I will do that.
