### ISSUE TITLE
Return value of `random_letters` is not always a list

### ISSUE THREAD

**Issue by svisser** [joke2k/faker#1484]
* Faker version: 8.10.1
* OS: Ubuntu 20.04

The return type of `random_letters` is not always a list as indicated in the docstring:

https://github.com/joke2k/faker/blob/2dac486e6d3b5f018feb524f6fa19917ec10299e/faker/providers/__init__.py#L194-L195

### Steps to reproduce

```pycon
>>> from faker import Faker
>>> f = Faker()
>>> f.random_letters(length=0)
[]
>>> f.random_letters(length=1)
('Y',)
>>> f.random_letters(length=2)
['o', 'K']
>>> f.random_letters(length=3)
['L', 'k', 'M']
```

### Expected behavior

`type(f.random_letters(length=n))` should be list when `n=1`

### Actual behavior

`type(f.random_letters(length=n))` has type tuple when `n=1`

**Comment by fcurella** [comment]
Thank you for the report @svisser ! Do you have time to submit a Pull Request?

**Comment by svisser** [comment]
Thanks for merging in the PR :ok_hand: I'm happy for this issue to be closed but I'll leave it open in case there is anything related to docs / changelog / release management that is left to do here.
