### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by madelonhulsebos** [joke2k/faker#1494]
* Faker version: latest
* OS:  any

I would like to be able to cite the Faker library in my research, as intended by its authors.

### Steps to reproduce

Steps to create a citation file: [citation file format site](https://citation-file-format.github.io/).

### Expected behavior

The Faker repository provides the information to cite it, e.g. in APA and BibTex format, as below.

![Screenshot 2021-08-12 at 09 36 04](https://user-images.githubusercontent.com/15101953/129156883-51a129c3-950a-47f0-bc42-3f601d589a22.png)

**Comment by fcurella** [comment]
Added in 39dcb4021bd2c2721a7fca107132e868d70f65c2. Thank you!
