### ISSUE TITLE
Titles of people names in British English should not have periods/fullstops

### ISSUE THREAD

**Issue by stephengruppetta** [joke2k/faker#1507]
* Faker version: 8.12.1
* OS: macOS 11.5.2

In the `en_UK` locale, names with titles such as Dr, Mr and Ms shouldn't have a period/fullstop as in the American version, as in British English these are considered contractions which therefore don't take a period/fullstop

### Steps to reproduce

1. `fake = faker.Faker(locale="en_UK")`
2. `fake.name()  # For those names with titles`

### Expected behavior

Titles should be shown as `"Dr Tony Dennis"`

### Actual behavior

Instead they're shown as `"Dr. Tony Dennis"`

**Comment by fcurella** [comment]
Thank. you for the report, @stephengruppetta !

Do you have time to submit a Pull Request?

**Comment by fcurella** [comment]
Fixed in https://github.com/joke2k/faker/pull/1508
