### ISSUE TITLE
how we can generate  name in  Pakistan counter in  name fields

### ISSUE THREAD

**Issue by Arslanthought** [joke2k/faker#1511]
* Faker version:
* OS:

Brief summary of the issue goes here.

### Steps to reproduce

1. step 1
1. step 2
1. step 3

### Expected behavior

X should be ...

### Actual behavior

X is ...

**Comment by fcurella** [comment]
Assuming you mean to people names, we'll need to create a [`person` provider](https://github.com/joke2k/faker/tree/master/faker/providers/person) for Pakistan.

According to [Wikipedia](https://en.wikipedia.org/wiki/Pakistan), Pakistan has [2 official languages](). We'll need a provider for each language we want to support
