### ISSUE TITLE
Inconsistent data between date

### ISSUE THREAD

**Issue by yuenking** [joke2k/faker#1512]
* Faker version: 8.0.0
* OS: macOS 10.15.7

Data generated changed from 2021-09-05 to 2021-09-06. Replicated with `freezegun`. 

### Steps to reproduce

```
import faker

from freezegun import freeze_time

import pytest


def fake_row(fake):
    row = {
        "fake_number": str(fake.random_number(digits=9, fix_len=True)),
        "sentence": fake.sentence(),
        "paragraph": fake.paragraph(),
        "words": "/".join(fake.word() for _ in range(10)),
        "word_choice": fake.word(("1", "2", "3")),
        "date_time_str": str(fake.date_time()),
        "bool": fake.boolean(),
        "bool2": fake.boolean(),
        "date": fake.date(),
        # "word_choice2": fake.word(("true", "false")),
        "date_time_iso": fake.date_time().isoformat(),
    }

    return row


def test_faker():

    num_rows = 30
    seed = 42

    with freeze_time("2021-09-06"):
        fake = faker.Faker("uk_UA")
        fake.seed_instance(seed)
        newer = [fake_row(fake) for _ in range(num_rows)]

    with freeze_time("2021-09-05"):
        fake = faker.Faker("uk_UA")
        fake.seed_instance(seed)
        older = [fake_row(fake) for _ in range(num_rows)]

    assert newer == older
```

### Expected behavior

This should pass, i.e. `newer == older`. 

### Actual behavior

The 2 lists are identical up for the first 20+ entries. And interestingly, if the line `"word_choice2": fake.word(("true", "false")),` is uncommented out, it passes.

**Comment by fcurella** [comment]
The date inconsistency bakes sense to me.

Both `fake.date()` and `fake.date_time()` return a random date/datetime between January 1, 1970 and now. In other words, they are time dependent. By changing when "now" is, it's picking between different boundaries. Basically,  `freeze_time("2021-09-06")` may pick September 6th, where `freeze_time("2021-09-05")` never will.

This should probably documented better in the docs, both in the 'seeding the faker' section, and the docs for `date()` and `datetime()`

re: the `word_choice2`, yeah that's really weird. I have no idea why that could happen. What Python version are you using?

**Comment by yuenking** [comment]
Thanks for your response.

Perhaps I should have elaborated more on the initial post. The differences is not only in the `date` field, but in all of them (e.g. `sentence`, `paragraph`, etc). It also works if I put the dates "2021-09-06" and dates after that OR "2021-09-05" and dates before that. The 5th and the 6th just happened to be the "boundary" that causes the error.

I'm using python 3.8.
