### ISSUE TITLE
Add DateTimeProvider for Bangladesh(bangla)

### ISSUE THREAD

**Issue by jabertuhin** [joke2k/faker#1517]
I want to add DateTimeProvider for Bengali week and month names.

**Comment by fcurella** [comment]
Thank you interest, @jabertuhin !

You can use any of the existing DateTimeProvider as a starting point. For example, you could copy the [Indian provider](https://github.com/joke2k/faker/blob/master/faker/providers/date_time/hi_IN/__init__.py) into `faker/providers/date_time/bn_BD/__init__.py` and modify it from there.
