### ISSUE TITLE
Default to Safe Email Addresses

### ISSUE THREAD

**Issue by errbufferoverfl** [joke2k/faker#1523]
By default `faker.email()` will generate email addresses that are potentially valid, especially considering `@gmail.com`, `@yahoo.com` and other free providers are included in the data. 

This can be problematic considering there are a few potential outcomes that can come of this that can affect the developers using `faker` or the people who have unwittingly had their emails generated as part of a test suite.

While there is the argument that developers should be configuring mailers in test environments to not send outbound, using the in-built `ascii_safe_email()` or provide the optional `domain` argument, I also think that `faker` would benefit from having the `email()` provider use the safe domains by default and require developers to enable unsafe email address generation.

### Expected behavior

Here was something I very quickly put together, to demonstrate what I'd like to see happen, with how it could be used by a developer:

```python
@lowercase
def email(self, unsafe=False, domain=None):
    if domain:
      email = f'{self.user_name()}@{domain}'
    if unsafe:
      pattern = self.random_element(self.email_formats)
      email = "".join(self.generator.parse(pattern).split(" "))
    else:
      domain = self.random_element(self.safe_domain_name)
      email = f'{self.user_name()}@{domain}'
    return email
```

Which when used by the developer would look something like:
```
fake = Faker()

# safe by default
print(fake.email())

# enable unsafe mode
print(fake.email(unsafe=True))

# use a domain
print(fake.email(domain="mycooldomain.com"))
```

```
>>> justinramos@domain.com
>>> justinramos@jackson-cuevas.net
>>> justinramos@mycooldomain.com
```

### Actual behavior

Currently, the default behaviour is for `faker` to generate email addresses that may be valid. 

I'd be more than happy to open a PR to make these changes if you'd like to pursue this approach!

Thanks!

**Comment by fcurella** [comment]
Thank you @errbufferoverfl !

I think that's a good idea. The only thing I'm not sure about is the argument name. I wonder is using `safe=True` as default would be more intuitive.

**Comment by errbufferoverfl** [comment]
@fcurella using `safe=True` is a lot more intuitive, I'll put together a PR this week and we can go from there.
