### ISSUE TITLE
Default to fake phone numbers (en_US)

### ISSUE THREAD

**Issue by dzcode** [joke2k/faker#1525]
Inspired by https://github.com/joke2k/faker/issues/1523, it would be helpful if phone numbers by default used [unallocated area codes](https://www.areacodehelp.com/where/unassigned-area-codes.shtml), since generating potentially real numbers is problematic for the same reasons outlined in  https://github.com/joke2k/faker/issues/1523.

### Expected behavior

Since this would be specific to the US, we could add an optional `safe=True` param to the `phone_number` method in the en_US provider and vary the `formats` based on that, or add a new method `safe_phone_number` that only uses the safe formats. To generate those formats, we could make essentially a cross-product of the `formats` list and the list of safe area codes upon initialization to be used in safe phone numbers

### Actual behavior

Right now, generated phone numbers are potentially callable and real, which can be problematic when in an environment with fake data but real functionality.

Happy to put up a PR if this would be a useful bit of functionality and there's an approach that makes sense

**Comment by fcurella** [comment]
Yeah it makes sense :) I would like to be consistent, and do it the same way as we do with emails.

**Comment by allisonletts** [comment]
I did something like this [here](https://github.com/allisonletts/faker_highered/blob/main/config.py) -- feel free to use for inspiration, or anything else that might be valuable. I'm positive that my code is not up to par for inclusion here, but I did do some research about the concept 😄 . Particularly, I separated out the area code, exchange, and last four, and used the North American Numbering Plan. You could change out the exchange to always be 555 and still generate a bunch of distinct numbers.
