### ISSUE TITLE
Python 3.7.9 ImportError/ModuelNotFoundError

### ISSUE THREAD

**Issue by SzySteve** [joke2k/faker#1556]
* Faker version:
9.5.0
 
* OS:
MacOS Big Sur 11.6
Python 3.7.9

https://github.com/joke2k/faker/blob/9a382ed237ef6ac40eb272703eb3b6ce0546ad0f/faker/typing.py#L5
This try/except block doesnt resolve for python 3.7.9 and breaks builds. `Literal` is not defined in the stdlib `typing` module, and Faker does not specify `typing_extensions` as a dependency

### Steps to reproduce

1. Fire up a fresh python 3.7.9 shell
2. `from typing import Literal`
observe this raises an ImportError
3. try to import from typing extensions, and observe that if you dont have it installed, it raised ModuleNotFound

### Expected behavior

Faker specifies typing_extensions as a dependency

### Actual behavior

Faker does not specify this dependency, and dies during build time

**Comment by fcurella** [comment]
fixed in https://github.com/joke2k/faker/pull/1557
