### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by Unungentium** [joke2k/faker#1563]
* Faker version:9.7.1
* OS:Ubuntu
Importing factory from shell causes the errors

### Steps to reproduce

1. ```$ python3.7```
2. ```import faker```

### Expected Behaviour

There should be no errors or messages

### Actual behaviour

There is an import error which doesn't allow for the importing of faker

**Comment by fcurella** [comment]
Thank you for the report @Unungentium !

I've jut tried importing on a brand new virtualenv on 3.7.11, and it's working for me:

```
Python 3.7.11 (default, Jul 15 2021, 11:58:46) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
>>> faker.VERSION
'9.7.1'
```

**Comment by Unungentium** [comment]
I am using python3.7.9. I believe that this might be causing the issue.

**Comment by fcurella** [comment]
I just tested on 3.7.9, and it's still working for me:
```
Python 3.7.9 (default, Nov  3 2021, 09:21:20) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
>>> faker.VERSION
'9.7.1'
>>> 
```

**Comment by nicarl** [comment]
I also tested and it works for me
```
pyenv install 3.7.9
pyenv virtualenv 3.7.9 test_faker_import
pyenv activate test_faker_import
pip3 install faker
python3
``` 
```
Python 3.7.9 (default, Nov  3 2021, 15:35:40) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faker
>>> print(faker.VERSION)
9.8.0
```

**Comment by fcurella** [comment]
Closing as invalid
