### ISSUE TITLE
fake.address does not work properly for 'de-CH'

### ISSUE THREAD

**Issue by fx99-D** [joke2k/faker#1570]
* Faker version: 9.8.3             build: pyhd8ed1ab_0    from: conda-forge
* OS: Windows 10 / anaconda

    fake = Faker('de_CH')
    fake.address()

does not work properly. 
Instead of producing a city/village, it produces a Canton
### Steps to reproduce

from faker import Faker
fake = Faker('de_CH')
print(fake.address())

### Expected behavior

Output should be: 
street housenumber
zip_code village

### Actual behavior

Output  is
street housenumber
zip_code canton

**Comment by mykhailoleskiv** [comment]
Provider for `de_CH` locale is not fully filled. There's no streets or cities, only cantons list.

**Comment by fx99-D** [comment]
Streets + housenumber work fine. Ca I helf to fill de_CH ?

**Comment by fcurella** [comment]
Feel free to submit a Pull Request with the data :)
