### ISSUE TITLE
faker.date_between doesn't support absolute date.

### ISSUE THREAD

**Issue by Ledorub** [joke2k/faker#1571]
* Faker version: 9.8.2
* OS: W10 19043.1348

`faker.date_between` fails on absolute date.

`_parse_date` assumes here that date is relative if it's of type `str`
https://github.com/joke2k/faker/blob/4eff2c913973ac9d5c29fc9ef1ef687b6cbd816a/faker/providers/date_time/__init__.py#L1991-L1995
### Steps to reproduce

```python
from faker import Faker
faker = Faker()
faker.date_between('2021-12-27', '2022-04-15')
```

### Expected behavior

`datetime.date` object with date between 2021-12-27 and 2022-04-15.

### Actual behavior

```python
faker.providers.date_time.ParseError: Can 't parse date string `2021-12-27`
```

**Comment by micahstrube** [comment]
Why not use:
`faker.date_between(datetime.date(2021, 12, 27), datetime.date(2022, 4, 15))`

It appears that the only `str` that is supported here is 'today', 'now', or something like '-30d', '+30d', etc., which I think makes sense. If you have an absolute date in mind, it seems you should just use `datetime.date()`.

**Comment by Ledorub** [comment]
Yeah, it will work, but it doesn't look clean, at least to me.
It seems that `timedelta_pattern` expect `+` or `-` sign before actual value:
https://github.com/joke2k/faker/blob/4eff2c913973ac9d5c29fc9ef1ef687b6cbd816a/faker/providers/date_time/__init__.py#L61-L71
Maybe check whether value starts with `+` or `-`, if so parse it as relative, otherwise as absolute.
