### ISSUE TITLE
Breaking change in 9.9.0?

### ISSUE THREAD

**Issue by riconnon** [joke2k/faker#1574]
* Faker version: 9.9.0
* OS: Linux

The following call worked in 9.8.3:
```
    data = factory.LazyFunction(lambda: json.dumps(Faker().pydict(                                                                                              
        10,                                                                                                                                                     
        True,                                                                                                                                                   
        'str', 'str', 'str', 'str', 'float', 'int', 'int',                                                                                                      
    )))
```
and gives the following error in 9.9.0:
```
TypeError: pydict() takes from 1 to 5 positional arguments but 10 were given
```

### Steps to reproduce

1. Use the above code

### Expected behavior

Should produce a dict with 10 elements.

### Actual behavior

The above exception.

**Comment by fcurella** [comment]
Yes, that should've been a MAJOR increment on the version. The automated versioning got it wrong because the PR was mislabeled. I can revert the change, release `9.9.1`, the reapply the change to `10.0.0.`

**Comment by fcurella** [comment]
@riconnon I've reverted the change on `v9.9.1`
