### ISSUE TITLE
ro_RO

### ISSUE THREAD

**Issue by alexei** [joke2k/faker#1578]
* Faker version: 9.9.0
* OS: macOS

The ro_RO address provider offers the `state` and `state_abbr` which return counties and county codes respectively. The method names are misleading in that [Romania is organised into counties](https://en.wikipedia.org/wiki/Counties_of_Romania), not states.

I can make the required changes: add the new methods, deprecate the old ones etc. However, this might break other people's code, so please let me know if you're ok with such changes.

### Expected behavior

As a developer, I would expect the ro_RO provider to offer a pair of `county` and `county_code` methods.

### Actual behavior

Counties are available via the `state` and `state_abbr` methods.

**Comment by fcurella** [comment]
Thank you for the report @alexei !

The way we handle this is that we create an `administrative_unit()` method, and then alias the correct name to that method.

For example, Canada has ["provinces"](https://github.com/joke2k/faker/blob/master/faker/providers/address/en_CA/__init__.py#L357-L361). You would do the same, but with `county = administrative_unit`
