### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chaimt** [joke2k/faker#1579]
* Faker version:
* OS:
MAC
Brief summary of the issue goes here.

Your license is MIT, but you use a libarary (text-unidecode) that is GPL licenese????

**Comment by fcurella** [comment]
See also #727

`text-unidecode` is [licensed](https://github.com/kmike/text-unidecode#text-unidecode), under Artistic License, GPL, _or_ GPLv3.

Is any of these licenses acceptable for you? 
If not, what would you suggest?

**Comment by fcurella** [comment]
Closed by https://github.com/joke2k/faker/pull/1601
