### ISSUE TITLE
Q: is it possible to replace use `random2` by something else?🤔

### ISSUE THREAD

**Issue by kloczek** [joke2k/faker#1581]
Looks like `faker` in test suite is using `random2` which is no longer maintained since 2012.
```console
[tkloczko@ss-desktop faker-11.0.0]$ grep -r random2
CHANGELOG.md:* Loosen version restrictions on ``freezegun`` and ``random2``.
tests/providers/test_ssn.py:import random2
tests/providers/test_ssn.py:        self.fake.random = random2.Random()
tests/providers/test_ssn.py:        self.fake.random = random2.Random()
tests/providers/test_ssn.py:        self.fake.random = random2.Random()
tests/providers/test_ssn.py:        self.fake.random = random2.Random()
tox.ini:    random2>=1.0.1
```
Just humble question: is it possible to replace that module by something a bit modern? :)
I'm asking because I'm packaging python modules as rpm and Solaris IPS packages and on packaging I'm trying obligatory to execute included test suite. Looks like `random2` is used only by `faker` :P

**Comment by fcurella** [comment]
We'll have to update a bunch of tests, and release a new MAJOR version, since it's going to be a breaking change for lots of people. Do you have time to contribute a Pull Request?

**Comment by kloczek** [comment]
My python developer skills are probably a bit to weak. My strongest skills are around packaging stuff. So from that point of view you may count definitely on me if you would like to test something on scale large possible cases to test some PRs before actual merge (I have such automation which is able to test temporary created new version of the module with other packages build processes which uses that package).

FYI: temporary I've added tests/providers/test_ssn.py to pytest --ignore list so no rush :)

I've created that ticket because trying to effective as possible I'm trying to be kind of lazy in positive way. In such cases if I see something odd as usually it is better to flag and ask someone :P

**Comment by kloczek** [comment]
Duplicate of #1454
