### ISSUE TITLE
invalid phone numbers for it_IT

### ISSUE THREAD

**Issue by FrancYescO** [joke2k/faker#1586]
The phone numbers for italy are too much random:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#Historical_number_formats

For landline, starting with one of these prefix and with a total of 10 digits
https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Italy

For mobile, starting with one of these prefix and with a total of 10 digits (some of 9 exists..)
https://it.wikipedia.org/wiki/Prefissi_telefonici_dei_cellulari_italiani

i think can be also simplified in 3XXXXXXXXX, simulating in this way only mobile numbers

PS: a validation lib https://github.com/daviddrysdale/python-phonenumbers

**Comment by fcurella** [comment]
Thank you for the report @FrancYescO ! Do you have time to work on a Pull Request? I'll be happy to review it.

**Comment by nicarl** [comment]
You can have a look at the provider for France, where I added something similar:
https://github.com/joke2k/faker/blob/master/faker/providers/phone_number/fr_FR/__init__.py
