### ISSUE TITLE
E.164 phone format 

### ISSUE THREAD

**Issue by FrancYescO** [joke2k/faker#1588]
I don't know if it can be easily implemented with all phone numbers generated, but generating a phone number in a global valid format can be useful... something configurable like `.phone_number(e164=True)`

**Comment by sshishov** [comment]
It should be a `format` key there which will indicate in which format you want to have the phone_number, as there are multiple formats available

Currently this `phone_number` method is useless as it generates VERY different format every time not compatible with libraries
