### ISSUE TITLE
is faking time series data in the scope of this project ?

### ISSUE THREAD

**Issue by diadara** [joke2k/faker#159]
I wanted some fake time series data for a project and couldn't find anything suitable for my needs.
Is something like [this](http://www.xaprb.com/blog/2014/01/24/methods-generate-realistic-time-series-data/) in the scope of this project ?

**Comment by dodysw** [comment]
Interested on this also -- it's been 3 years...

**Comment by fcurella** [comment]
@dodysw It's been 3 years and we haven't received any PR for it yet. Could you prepare one?

**Comment by dodysw** [comment]
I could invest some hours for this. 

Is there a expectation for this PR? e.g. what's the input, what's the output?

Currently I have  a simple implementation that generates x number of random datetime(s) between two datetimes that follows a normal distribution. These list of datetimes then can be iterated as one of attribute or input to the the actual time series data generator.

The post above mentioned [this blog](https://www.xaprb.com/blog/2014/01/24/methods-generate-realistic-time-series-data/) which seems overall a great source of ideas, but I don't have the time to implement all of them in one PR.

**Comment by vema** [comment]
Don't know yet if I can help, but I'm sure interested.

One PR is certainly not enough. Referring to '[The Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar)', lesson 7: **Release early. Release often. And listen to your customers**
The other lessons are great for inspiration also ...

**Comment by fcurella** [comment]
What should the output be? just a list of `datetime`s?

**Comment by vema** [comment]
I would prefer an iterable list instead of a 'simple' list. The applications I have in mind often need to augment (or combine) the series with other data. That way, it's easy to add more data to the items in the series.

E.g. a dateseries that represents number of (simulated) visitors of a museum/airport/... at a given moment.

**Comment by fcurella** [comment]
I'm thinking of a method with this signature:
```
def time_serie(start, end, precision, distribution):
```

`distribution` will be the function generating the values. `precision` is basically 'how often you want a datapoint'.

For example:
```
>>> import random
>>> from datetime import datetime, timedelta

>>> distribution lambda = random.uniform(0, 5)
>>> time_serie(datetime.now(), datetime.now()+timedelta(days=7), precision=timedelta(days=1), distribution=distribution)
```

The output could be an iterable of tuples, something like:
```
(
    (datetime.datetime(2017, 8, 8, 17, 9, 0, 569562), 0.767017023571912),
    (datetime.datetime(2017, 8, 9, 17, 9, 0, 569562), 0.550568452469854),
    (datetime.datetime(2017, 8, 10, 17, 9, 0, 569562), 1.8060492750124613),
    (datetime.datetime(2017, 8, 11, 17, 9, 0, 569562), 1.0195647347289332),
    (datetime.datetime(2017, 8, 12, 17, 9, 0, 569562), 4.063748959116069),
    (datetime.datetime(2017, 8, 13, 17, 9, 0, 569562), 1.2355522029691586),
    (datetime.datetime(2017, 8, 14, 17, 9, 0, 569562), 3.9570822924224434),
)
```

**Comment by vema** [comment]
That seems very workable. My idea was to have a 'class' with an initializer where you could set (most) of the parameters and then have a method to generate the series. That was closer aligned to the idea description in the blog. But I don't object to your suggestion at all. First thing is to have something workable, then we can fine-tune.

**Comment by fcurella** [comment]
I've got a draft working, let me know if there's anything wrong that jumps to your eye

https://gist.github.com/fcurella/8316c3a27c322eb0e02c3d4714de15c6

**Comment by vema** [comment]
Looks all fine to me. Good job.
