### ISSUE TITLE
faker打包成exe执行报错

### ISSUE THREAD

**Issue by cz973409335** [joke2k/faker#1590]
* Faker version: 8.9.1
* OS:

![image](https://user-images.githubusercontent.com/26372901/148150821-1fcebda0-623b-428d-86e6-8496e8ac3b3a.png)

**Comment by fcurella** [comment]
Thanks for the report @cz973409335 ! Could you try with a more recent version of Faker? We're currently on v11.2.0.

**Comment by cz973409335** [comment]
最新版本存在同样的问题



---原始邮件---
发件人: "Flavio ***@***.***&gt;
发送时间: 2022年1月5日(周三) 晚上11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [joke2k/faker] faker打包成exe执行报错 (Issue #1590)




 
Thanks for the report @cz973409335 ! Could you try with a more recent version of Faker? We're currently on v11.2.0.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
