### ISSUE TITLE
Refactor the `date_time` provider

### ISSUE THREAD

**Issue by alexei** [joke2k/faker#1591]
As pointed out in https://github.com/joke2k/faker/pull/1577, I find the `date_time` provider confusing, both due to the methods' interfaces, and their implementations.

I think refactoring the provider would break other people's code, though I guess it's doable with the proper warnings etc. so here it goes:

## `unix_time`

The exceptional method that returns integers: I'd rename it to `unix_timestamp`.

## `date_time`, `date_time_between`, `date_time_between_dates`

`date_time`, `date_time_between`, `date_time_between_dates` achieve the same thing, except that:
- `date_time` doesn't have a `start_datetime`
- `date_time_between` params default to -30y..now
- `date_time_between_dates` params have some unobvious defaults

They could be combined into a single `date_time` and the implementation could be simplified:
```python
datetime.fromtimestamp(self.unix_timestamp(start, end), tzinfo)
```

I suppose this would also get rid of the `date_time_between` and `date_time_between_dates` weirdness.

## `date`

If `date_time` returns an object, one would expect `date` to return an object, not a string. I would rename `date` to `date_str` or something like that.

Additionally, I would add a `start_date` parameter.

## `date_object`, `date_between`, `date_between_dates`

Same situation as with the `datetime` methods above: the three methods achieve the same thing, except that:
- `date_object` doesn't have a `start_date` param
- `date_between` params default to -30y..today
- `date_between_dates` params have some unobvious defaults

They could be combined into a single `date` method with a simplified implementation:

```python
self.date_time(start, end).date()
```

## `date_time_ad`

Also implement `date_ad` as `self.date_time_ad(...).date()`.

## `iso8601`

Since the ISO format is not just about datetimes, I'd rename `iso8601` to `iso_date_time`, and implement additional `iso_date` and `iso_time` methods as `self.date(...).isoformat()` and `self.time(...).isoformat()` respectively.

## `time`

Like `date`, returns a string, though one would expect a `time` object. I would rename it to `time_str` or something like that, and add a `start_time` param.

## `time_object`

Same situation: I think `time_object` should be renamed `time`, and could benefit from a `start_time` param.

## `date_this_century`, `date_this_decade`, `date_this_year`, `date_this_month`

Update to use `self.date_time`.

## `date_this_century`, `date_this_decade`, `date_this_year`, `date_this_month`

Update to use their `date_time_*` equivalents.

## New method: `time_today`

```python
def time_today(self, before_now: bool = True, after_now: bool = False) -> time:
    ...
```

**Comment by fcurella** [comment]
Thank you for looking into this @alexei !

I like this API much better than the current one. But I'd like a clearly defined transition strategy. I'd also like to reduce the API surface a little bit. Here's what I'm thinking:

### on MINOR release:
* Add `unix_timestamp`
  * Add `PendingDeprecation` warning to `unix_time`, directing users to use `unix_timestamp`
* Add  a new `datetime` (no underscore)
  * Add `PendingDeprecation` warnings to `date_time`, `date_time_between`, `date_time_between_dates`, pointing users to `datetime`
* For consistency, rename `date_time_ad` to `datetime_ad`:
  * Add `datetime_ad` (no underscore)
  * Add `PendingDeprecation` warning to `date_time_ad` pointing to `datetime_ad`
* Add `date_str` and `time_str`
  * Add `PendingDeprecation` warning to `date`, pointing to `date_str`. Suggest users who want a `Date` object  to use `Faker.datetime().date()`
  * Add `PendingDeprecation` warning to `time`, pointing to `time_str`. Suggest users who want a `Time` object  to use `Faker.datetime().time()`
  * Add `PendingDeprecation` warning to `time_object`, pointing to users  to use `Faker.datetime().time()`
* For consistency with the above, let's *not* add `date_ad`. Users can call `Faker.datetime_ad().date()`
* Add `iso_datetime` (again, no underscore), `iso_date`, and `iso_time`
  * Add `PendingDeprecation` warning to `iso8601` pointing to `iso_datetime`
* Add `time_today`


### on MAJOR release (at least 6 months after the MINOR release):
* Deprecate all methods with a `PendingDeprecation` warning

Let me know what you think, I appreciate your feedback!

**Comment by alexei** [comment]
I'd like to clear up a couple more things before we prepare a plan and proceed with the implementation.


## AD vs Unix epoch

I checked the code again today and found I was wrong in my previous assessment about `date_time`, `date_time_between` and `date_time_between_dates`. Based on my visually inspecting the code, I thought they were the same, but that's not the case: it appears `date_time` returns a dt in the Unix epoch, while `date_time_between` and `date_time_between_dates` are in the AD epoch. They are more similar to `date_time_ad`, just with different defaults. If we were to unify these, there are a couple of ways to doing it:

<ol type="a">
    <li>One method: generic <code>datetime</code> method, returns a dt anywhere in the AD epoch</li>
    <li>Two methods: <code>datetime</code> returns a dt in the Unix epoch; <code>datetime_ad</code> returns a dt in the AD epoch</li>
    <li>Two methods alt: <code>datetime</code> returns a dt in the AD epoch; <code>unix_datetime</code> returns a dt in the Unix epoch</li>
</ol>

Personally, I'm in favor of c. because it works on the AD epoch and regards the Unix epoch as the special case, not the other way around. In the end, Unix time is 1970 AD. See also notes on "API surface" below.

What are your thoughts?


## Defaults

I don't know what is the reasoning behind the current default values. I'm obviously missing the context of when and where they were set, but it's also possible they're just arbitrary. While I don't care much about the values themselves, there is one thing that bothers me, which is all methods are set to return dates in the past. It seems the only thing that separates the general date[time] methods from the `[past|future]_*` ones is the defaults: the former go +/- 30 years, while the latter go +/- 30 days.

What do you think about dropping the "now" limit on the *base* date[time] methods and limiting just the *convenience* methods (and sticking to the 30 years limit everywhere)? I.e.:
   
```python
    def datetime(start=-30y, end=+30y):
        ...

    def past_datetime(start=-30y):
        return self.datetime(start, end=now)

    def future_datetime(end=+30y):
        return self.datetime(start=now, end)

    def unix_datetime(end=+30y):
        return self.datetime(start=dt(1970, 1, 1), end)

    etc.
```


## API surface

Generally speaking I think it's a good idea to reduce the surface area of the API. But - to what end? I think dropping e.g. the `date_*` methods and asking users to call `.date()` manually hurts their experience. I suspect most of the methods were added **because** people needed them.

If, on the other hand, we drop some of the redundant **base** methods and refactor whatever remains, all the while keeping the **convenience** methods, then the library will be easier to develop and use: the maintainers will have less code to care about, the users will have a broad and clear API, so everybody's happy. The gist of this discussion isn't the API surface as much as it's the details of it.

To illustrate what I mean, consider the current API (note <code>...</code> means it can be inferred):

<table>
    <tr>
        <th rowspan="2"></th>
        <th colspan="3">datetime</th>
        <th colspan="3">date</th>
        <th colspan="3">time</th>
    </tr>
    <tr>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
    </tr>
    <tr>
        <td>AD</td>
        <td>
            <code>date_time_ad</code>
            <br>
            <code>date_time_between</code>
            <br>
            <code>date_time_between_dates</code>
        </td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td>
            <code>date_time_between</code>
            <br>
            <code>date_time_between_dates</code>
        </td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
    <tr>
        <td>Unix</td>
        <td><code>date_time</code></td>
        <td><code>...</code></td>
        <td><code>iso8601</code></td>
        <td><code>date_object</code></td>
        <td><code>date</code></td>
        <td><code>...</code></td>
        <td><code>time_object</code></td>
        <td><code>time</code></td>
        <td><code>...</code></td>
    </tr>
    <tr>
        <td>Past</td>
        <td><code>past_datetime</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>past_date</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
    <tr>
        <td>Future</td>
        <td><code>future_datetime</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>future_date</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
</table>

An if you look at the calls between them, you'll find:

<ul>
    <li>
        <i><code>custom1</code></i>
        <ul>
            <li>
                <code>unix_time</code>
                <ul>
                    <li>
                        <code>date_time</code>
                        <ul>
                            <li><code>iso8601</code></li>
                            <li><code>date</code></li>
                            <li><code>date_object</code></li>
                            <li><code>time</code></li>
                            <li><code>time_object</code></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <i><code>custom2</code></i>
        <ul>
            <li>
                <code>date_time_ad</code>
                <ul>
                    <li><code>date_of_birth</code></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <i><code>custom3</code></i>
        <ul>
            <li>
                <code>date_time_between</code>
                <ul>
                    <li><code>future_datetime</code></li>
                    <li><code>past_datetime</code></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <i><code>custom4</code></i>
        <ul>
            <li>
                <code>date_time_between_dates</code>
                <ul>
                    <li><code>date_time_this_century</code></li>
                    <li><code>date_time_this_decade</code></li>
                    <li><code>date_time_this_year</code></li>
                    <li><code>date_time_this_month</code></li>
                    <li>
                        <code>date_between_dates</code>
                        <ul>
                            <li><code>date_between</code></li>
                            <li><code>future_date</code></li>
                            <li><code>past_date</code></li>
                            <li><code>date_this_century</code></li>
                            <li><code>date_this_decade</code></li>
                            <li><code>date_this_year</code></li>
                            <li><code>date_this_month</code></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

My thinking is you can have a small base and build convenience methods on top of that:

<table>
    <tr>
        <th rowspan="2"></th>
        <th colspan="3">datetime</th>
        <th colspan="3">date</th>
        <th colspan="3">time</th>
    </tr>
    <tr>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
        <th>obj</th>
        <th>str</th>
        <th>ISO</th>
    </tr>
    <tr>
        <td>AD</td>
        <td><code>datetime</code></td>
        <td><code>datetime_str</code></td>
        <td><code>iso_datetime</code></td>
        <td><code>date</code></td>
        <td><code>date_str</code></td>
        <td><code>iso_date</code></td>
        <td><code>time</code></td>
        <td><code>time_str</code></td>
        <td><code>iso_time</code></td>
    </tr>
    <tr>
        <td>Unix</td>
        <td><code>unix_datetime</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>unix_date</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
    <tr>
        <td>Past</td>
        <td><code>past_datetime</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>past_date</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>past_time</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
    <tr>
        <td>Future</td>
        <td><code>future_datetime</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>future_date</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
        <td><code>future_time</code></td>
        <td><code>...</code></td>
        <td><code>...</code></td>
    </tr>
</table>

The API area may seem large, but I expect the implementation can be kept small:

<ul>
    <li>
        <i><code>custom1</code></i>
        <ul>
            <li>
                <code>datetime</code>
                <ul>
                    <li>
                        <code>unix_datetime</code>
                        <ul>
                            <li>
                                <code>unix_timestamp</code>
                            </li>
                        </ul>
                    </li>
                    <li><code>past_datetime</code></li>
                    <li><code>future_datetime</code></li>
                    <li><code>datetime_str</code></li>
                    <li><code>iso_datetime</code></li>
                    <li><code>datetime_this_century</code></li>
                    <li><code>datetime_this_decade</code></li>
                    <li><code>datetime_this_year</code></li>
                    <li><code>datetime_this_month</code></li>
                    <li>
                        <code>date</code>
                        <ul>
                            <li><code>unix_date</code></li>
                            <li><code>past_date</code></li>
                            <li><code>future_date</code></li>
                            <li><code>date_str</code></li>
                            <li><code>iso_date</code></li>
                            <li><code>date_of_birth</code></li>
                            <li><code>date_this_century</code></li>
                            <li><code>date_this_decade</code></li>
                            <li><code>date_this_year</code></li>
                            <li><code>date_this_month</code></li>
                        </ul>
                    </li>
                    <li>
                        <code>time</code>
                        <ul>
                            <li><code>time_str</code></li>
                            <li><code>iso_time</code></li>
                            <li><code>past_time</code></li>
                            <li><code>future_time</code></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

The small base translates to minimum maintenance costs, while still allowing the full fledged API that the users need.

Note the names and relationships might be a little different depending on the decision about "AD vs Unix epoch" above, but I think the idea is the same.


## The "strings vs objects" issue

I understand the `date` and `time` methods become a little bit problematic: currently they're set to return strings, while I'm proposing to refactoring them to return objects. I'm thinking the plan you sketched could accomodate that, don't you think?

<dl>
    <dt>T0: minor release</dt>
    <dd>implement <code>[date|time]_str</code></dd>
    <dd><code>[date|time]</code> start warning users to change to <code>[date|time]_str</code></dd>
    <dd>docs advise to use <code>[date|time]_str</code> instead of <code>[date|time]</code>, and mention <code>[date|time]</code> will start returning objects in the future</dd>
    <dt>T1: major release</dt>
    <dd>update <code>[date|time]</code> to return objects</dd>
    <dd>drop warnings</dd>
    <dd>docs mention that <code>[date|time]</code> return objects since version X while previous versions returned strings</dd>
<dl>
