### ISSUE TITLE
Incorrect language set on Provider during locale fallback

### ISSUE THREAD

**Issue by interDist** [joke2k/faker#1595]
* Faker version: 11.3.0

When faker is initialised with a locale not implemented by some of the built-in providers, it falls back to the DEFAULT_LOCALE for these providers. However, the language set on the provider’s instance in `__lang__` is still the requested locale and not the locale in effect.

This is due to `Factory._find_provider_class` not returning the locale it chose, in: https://github.com/joke2k/faker/blob/001ddee39c33b6b82196fe6a5ecc131bca3b964c/faker/factory.py#L102-L104 to `Factory._get_provider_class` which then proceeds to return the locale value as it was passed in at the first place. Thus, `provider.__lang__` does not contain the found locale (as the variable name `lang_found` would suggest): https://github.com/joke2k/faker/blob/001ddee39c33b6b82196fe6a5ecc131bca3b964c/faker/factory.py#L61

### Expected behavior

`provider.__lang__` should be set to the actual language / locale being used by the provider.

### Actual behavior

`provider.__lang__` is set to the locale that was requested but is not offered by this provider.

**Comment by fcurella** [comment]
Thank you for the report @interDist ! Do you have time to prepare a Pul Request ?

**Comment by interDist** [comment]
> Do you have time to prepare a Pul Request ?

I will try, this will probably happen in beginning of February.

**Comment by interDist** [comment]
@fcurella I started working on the PR, but I am confused by line 74 (and later) in `factory.py`
https://github.com/joke2k/faker/blob/001ddee39c33b6b82196fe6a5ecc131bca3b964c/faker/factory.py#L74-L78
I cannot see an execution path that would reach this line. The test coverage also seems to confirm this (lines 74 until 86 are not covered by tests). Maybe there is some legacy to `_get_provider_class` and `_find_provider_class` and some history I am not aware of?

**Comment by fcurella** [comment]
@interDist I've looked into this and there's definitely a bug.

I can see we already handle the fallback in `_find_provider_class`:

https://github.com/joke2k/faker/blob/001ddee39c33b6b82196fe6a5ecc131bca3b964c/faker/factory.py#L102-L112

 and we return the correct provider:

https://github.com/joke2k/faker/blob/001ddee39c33b6b82196fe6a5ecc131bca3b964c/faker/factory.py#L133-L136

So yeah, I think that's legacy code that should be removed 👍🏼
