### ISSUE TITLE
es_ES postalcode is not generating valid codes

### ISSUE THREAD

**Issue by Pijuli** [joke2k/faker#1596]
* Faker version: 11.3
* OS: Any

When using postcode for es_ES and using it with a field that requires a valid Postal Code, it fails sometimes.
I will assume that there is no logic with postal code generation for Spain.

### Steps to reproduce

Generate postal codes

### Expected behavior

Get a valid Spain postal code

### Actual behavior

Unexpected. Many are wrong

----

I'll dig now into the code. Let's see if I can get some more information and fix it :thinking: Do not expect much from me

**Comment by fcurella** [comment]
yeah, the definition of [postal codes for `es_ES`](https://github.com/joke2k/faker/blob/master/faker/providers/address/es_ES/__init__.py#L27) is currently simply "5 random digits", so there's no real actual logic behind it.

**Comment by FrancYescO** [comment]
if you want you can do the same i've done for IT...
https://github.com/joke2k/faker/pull/1593
