### ISSUE TITLE
Empty string in Korean jobs

### ISSUE THREAD

**Issue by georgidimitrov-hs** [joke2k/faker#1602]
* Faker version: 11.4
* OS: Any

The problem is that the Korean job provider provides empty string once a 400 times, because there is empty element in the jobs list.

### Expected behavior

Korean job should be a string with length > 0.

### Actual behavior

Once per 400 times the string is empty.

**Comment by fcurella** [comment]
Thank you for the report @georgidimitrov-hs ! Do you have time to submit a Pul Request with the fix?

**Comment by fcurella** [comment]
Closed by #1603
