### ISSUE TITLE
no keyword with name 'FakerLibrary.Word' found issue

### ISSUE THREAD

**Issue by chenrui333** [joke2k/faker#1617]
* Faker version: 12.3.3
* OS: macOS

I am using faker along with robotframework-faker (5.0.0) to run selenium e2e tests, but run into some keyword not found issue (like `no keyword with name 'FakerLibrary.Word' found` (or `Fakerlibrary.User Name`))

### Steps to reproduce

TBD

### Expected behavior

keyword should still work with robotframework-faker 5.0.0

### Actual behavior

X is ...

----

After reverting to faker 11.1.0 (just tried an old version), it works for us now.

**Comment by fcurella** [comment]
I don't really know what `robotframework-faker` is and how it works. Have you tried opening an issue on that project?
