### ISSUE TITLE
US Addresses with Apostrophe's

### ISSUE THREAD

**Issue by bfeister** [joke2k/faker#1622]
* Faker version: 4.1.0
* OS: Mac OS Big Sur

Brief summary of the issue goes here.

### Steps to reproduce

1. faker.address()

### Expected behavior

In the US, no apostrophe's

### Actual behavior

US addresses via `faker.address()` yield apostrophe's

### Discussion

So, I'm finding conflicting information - it seems that the US Postal Service forbids special characters, however, Google says

> Five US place names are permitted to use an apostrophe: Martha's Vineyard in the state of Massachusetts, Ike's Point in New Jersey, John E's Pond in Rhode Island, Carlos Elmer's Joshua View in Arizona, and Clark's Mountain in Oregon (the last of the five to be approved, in 2002).May 2, 2013
https://www.google.com/search?q=are+there+any+us+cities+with+an+apostrophe+in+the+name&rlz=1C5GCEM_enUS971US971&oq=are+there+any+us+cities+with+an+apostrophe+in+the+name&aqs=chrome..69i57j33i160l2j33i299l2.8673j1j7&sourceid=chrome&ie=UTF-8

So, the question is, what is considered valid and should `faker.address()` obey the US Postal Service validation rules? If yes, then apostrophe's should be stripped. This came up with my company via intermittent e2e automation failures using `faker.address`

**Comment by fcurella** [comment]
I would say let's go with the rule rather than the exception, and remove apostrophes
