### ISSUE TITLE
Invalid configuration for faker locale `az_AZ`

### ISSUE THREAD

**Issue by alexei** [joke2k/faker#1627]
* Faker version: 9.9.0
* Python version: 3.9
* OS: OSX

Unable to load the `az_AZ` provider.

### Steps to reproduce

```python
>>> from faker import Faker
>>> f = Faker(["az_AZ"])
```

### Expected behavior

It should load the provider e.g.

```python
>>> f = Faker(["el-CY"])
>>> f.locales
['el_CY']
```

### Actual behavior

It raises an exception:

```python
>>> f = Faker(["az_AZ"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[...]/faker/proxy.py", line 67, in __init__
    self._factory_map[locale] = Factory.create(
  File "/[...]/faker/factory.py", line 43, in create
    raise AttributeError(msg)
AttributeError: Invalid configuration for faker locale `az_AZ`
```

**Comment by alexei** [comment]
Oh, yeah, I can confirm it works in 13.3.0. I'm using faker through factory-boy and I assumed it was the latest version, but I see now they have very different release schedules. My bad, sorry! I'll pin faker in my requirements file so it gets tracked independently.

**Comment by fcurella** [comment]
No worries!
