### ISSUE TITLE
`en_IN` locale returns latin sentences

### ISSUE THREAD

**Issue by sizhky** [joke2k/faker#1647]
* Faker version: 13.6.0
* OS: Linux

Brief summary of the issue goes here.
How to generate normal english sentence when local is 'en_IN'

### Steps to reproduce

```python
import faker

fake = faker.Faker("en_IN")
fake.sentence()
```

### Expected behavior

Output should be a normal english sentence

### Actual behavior
`'Nobis quos sint alias atque voluptatibus est.'`
Seeing a latin sentence. No one speaks latin in India

**Comment by zerogonal** [comment]
Try using the `en_US` locale instead.

**Comment by sizhky** [comment]
I need to use Indian names.. should i create two faker instances? Isn't there a better way?

**Comment by zerogonal** [comment]
You can submit a pull request to add the lorem provider to the `en_IN` locale.
For now, I think you should create two faker instances.
