### ISSUE TITLE
Better biology provider

### ISSUE THREAD

**Issue by zerogonal** [joke2k/faker#1652]
There should be a better biology provider. The `faker_biology` community provider has a lot that could be added, like specific methods for genuses, families, orders, etc.

Also, can the biology provider be incorporated into the main Faker package, so that people only need to install one package?

**Comment by zerogonal** [comment]
also, why don't we incorporate *all* of the functionality of the community providers into the main package. Wouldn't that be better?

**Comment by fcurella** [comment]
@zerogonal There are many reason why we don't want to include everything into the main package:

* It's more work for the maintainers (ie: me): I'll have to review more Pull Requests
* It makes the package bigger, which impacts:
  * infrastructure costs (in network transfers) for PyPI
  * Docker images size for anyone using the package

I'm actually evaluating moving some providers out of Faker. The `automotive` and `bank` providers would be good candidates.

**Comment by zerogonal** [comment]
@fcurella can I make my own biology community provider?

**Comment by fcurella** [comment]
@zerogonal I'd recommend you improve the existing one, but there's nothing preventing you from making your own.

**Comment by zerogonal** [comment]
> @zerogonal I'd recommend you improve the existing one, but there's nothing preventing you from making your own.

What about adding it to the official list of community providers?

**Comment by fcurella** [comment]
> What about adding it to the official list of community providers?

As long as it satisfies the requirements listed on the page, I have no problem adding it. But I think it would be kinder if you'd try to improve the existing repo first, rather than create a competitor.
