### ISSUE TITLE
[New Provider] Add new Sport provider.

### ISSUE THREAD

**Issue by e-panourgia** [joke2k/faker#1653]
I was thinking of implementing a new sports provider (similar to [Ruby Faker](https://github.com/faker-ruby/faker)). It would generate fake data regarding basketball teams and players. Would you be interested in a PR?

**Comment by fcurella** [comment]
Thank you for your interest @e-panourgia !

Unfortunately, I don't think sports is a case common enough to be included in the main `Faker` distribution. If you want to implement it as an [External Provider](https://github.com/joke2k/faker#how-to-create-a-provider), I'll be happy to list it on our [community providers page](https://faker.readthedocs.io/en/master/communityproviders.html).

**Comment by edchelstephens** [comment]
Would love to contribute on Sports provider as well @e-panourgia @fcurella 

with providers for 

Sport Name
Team Name
Player Name
and others...
