### ISSUE TITLE
locale 'es_CO' not being detected by Faker() or local bundled packages usage not clear in readme

### ISSUE THREAD

**Issue by Teett** [joke2k/faker#1679]
* Faker version: Faker-13.15.0
* OS: Windows 10

Hello! I've been trying to use the [bundled locale 'es_CO'](https://faker.readthedocs.io/en/master/locales/es_CO.html) without success and getting an error, I've tried many things, but it keeps on failing. An example on the readme on how to use bundled locations would be appreciated. I'll leave my example below.

### Steps to reproduce
Run the following code
``` python
import pandas as pd
from faker import Faker
#from faker.providers import address, person # tried this withoout success
#from faker.providers.person import es_CO # tried this as well

fake = Faker('es_CO')
# fake.add_provider(person) doesn't help
# fake.add_provider(address) doesn't help

def generate_name():
    fake_name = fake.name()
    return fake_name
    
def generate_address():
    fake_address = fake.street_address()
    return fake_address

# Usage example
df = pd.DataFrame({'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
df["name"] = df.apply(lambda x: generate_name(), axis=1)
df["address"] = df.apply(lambda x: generate_address(), axis=1)
print(df)
```

### Expected behavior

This dataframe but with Colombian_Spanish addresses/names:
![image](https://user-images.githubusercontent.com/46414320/177885203-8ffe81a6-904a-4b5c-9ff3-ea58e7718ab5.png)

The es_MX works well, check this:

``` python
import pandas as pd
from faker import Faker
#from faker.providers import address, person # tried this withoout success
#from faker.providers.person import es_CO # tried this as well

fake = Faker('es_MX')
# fake.add_provider(person) doesn't help
# fake.add_provider(address) doesn't help

def generate_name():
    fake_name = fake.name()
    return fake_name

def generate_address():
    fake_address = fake.street_address()
    return fake_address
# Usage example

df = pd.DataFrame({'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
df["name"] = df.apply(lambda x: generate_name(), axis=1)
df["address"] = df.apply(lambda x: generate_address(), axis=1)
df
```
![image](https://user-images.githubusercontent.com/46414320/177885362-4c4a804d-873e-4357-a207-cbe900567e3f.png)

### Actual behavior

```
`Invalid configuration for faker locale `es_CO`
```

**Comment by fcurella** [comment]
Hi, I've just tested with faker 13.15.0 and it works. Could you check the version again with `import faker; print(faker.VERSION)`?

![Screen Shot 2022-07-12 at 10 07 27 AM](https://user-images.githubusercontent.com/89607/178523014-2e6e1038-d8ae-47ae-bd07-6f46c6b31f93.png)

**Comment by Teett** [comment]
I just tested this on a different PC and it worked perfectly, can't reproduce the bug, I guess this issue can be disregarded as some local installation issue. Thanks for the effort trying this @fcurella 
![image](https://user-images.githubusercontent.com/46414320/179429713-2a2a06c3-4689-43e3-8ced-9f106a564ace.png)
