### ISSUE TITLE
What's the annotation to get completions?

### ISSUE THREAD

**Issue by tony** [joke2k/faker#1684]
* Faker version: 13.15.0
* OS: POSIX

### Steps to reproduce

What I see often is using `faker.Faker` ([GitHub Search](https://cs.github.com/?scopeName=All+repos&scope=&q=lang%3Apython+pytest+%22faker%3A%22)):

```python
from faker import Faker

def test_faker(faker: Faker):
    assert isinstance(faker.name(), str)
```

This example above is based on [Pytest Fixture's](https://faker.readthedocs.io/en/master/pytest-fixtures.html) examples

### Expected behavior

Showing the instance methods, e.g. `faker.name()`

### Actual behavior

However that generates this:

![image](https://user-images.githubusercontent.com/26336/179545179-9aef650a-1dc2-4ebc-a466-249612adf4ca.png)

### Next steps?

Not sure if this a "wontfix", "bug", or potential place where we can have a documentation improvement or workaround. Or maybe it's related / but not quite a duplicate.

**Comment by fcurella** [comment]
Duplicate of #1604

**Comment by tony** [comment]
@fcurella I will close this per #1604
