### ISSUE TITLE
I want to add bn_BD locale support to the repository

### ISSUE THREAD

**Issue by saanpritom** [joke2k/faker#1685]
* Faker version: Latest
* OS: Independent

I want to add Bengali (Bangladesh) language provider for the repository. The provider data will be both in the Bengali language and also in the equivalent English language.

**Comment by fcurella** [comment]
Sounds good! Feel free to submit a Pull Request!

**Comment by saanpritom** [comment]
Hi @fcurella I am working on the bn_BD providers. But I need a clarification. To convert randomly generated digits from the English language to the Bengali language I have used a custom method (Given Below). This method has a dict by which it converts the English Digit to Bengali Digit. But the problem is I have to reuse this method on my other modules such as Automotive or Bank etc. What is the most suitable place to put this function so it can be used from all other providers.

```python
english_to_bengali_digits_map = {
        '0': '০',
        '1': '১',
        '2': '২',
        '3': '৩',
        '4': '৪',
        '5': '৫',
        '6': '৬',
        '7': '৭',
        '8': '৮',
        '9': '৯'
    }

def convert_to_bengali_digits(self, en_digit: str = '0') -> str:
        """
        :example: '9786' to '৯৭৮৬'
        """
        bn_digit = ''
        for char in en_digit:
            bn_digit = bn_digit + self.english_to_bengali_digits_map.get(char, '')
        return bn_digit
```

**Comment by saanpritom** [comment]
The task is done and a pull request has been created (Feature/provider/locale/bn bd/1685) @fcurella

**Comment by fcurella** [comment]
Merged in https://github.com/joke2k/faker/commit/598b31a1941595c5c1d4a783c4a34fa5e3cfb1c2

Thank you!
