### ISSUE TITLE
[Suggestion] Add a 'faker.internet.emoji' function

### ISSUE THREAD

**Issue by teacherSsamko** [joke2k/faker#1686]
I'm writing a test code with some emojis included. but there is no function for generating 'emoji' yet.

So, I suggest adding a generator for it.

FYI - one faker-js user also suggested this method, and it was added. https://github.com/faker-js/faker/issues/497

**Comment by fcurella** [comment]
I agree, this sounds pretty useful. Do you have time to work on a pull request?

**Comment by teacherSsamko** [comment]
Sure. I'll take it

**Comment by Artmorse** [comment]
Hi,
I've opened a PR (#1706 ) for this issue.
