### ISSUE TITLE
Faker allows date_time_this_year with unreasonable values

### ISSUE THREAD

**Issue by mlissner** [joke2k/faker#1697]
* Faker version: "13.3.1"
* OS: Linux

I just set up a faker like this (using factory boy):

```
key_expires = Faker("date_time_this_year", before_now=False)
```

Because `after_now` defaults to `False`, this sets both `after_now` and `before_now` to `False.  

As a result, `date_time_this_year` winds up just picking the time right now, because that's the closest thing that makes sense.

Would it be better to just have an assertion to prevent people from having both set to `False`? 

I could probably do a PR to land this. 

The only big consideration I can think of is that it might break some people that have it in the bad config, so we might need some good release notes.

**Comment by fcurella** [comment]
Thank you @mlissner .

> Would it be better to just have an assertion to prevent people from having both set to False?

Would a warning be acceptable? That would allow backward-compatibility and break fewer people's code

**Comment by mlissner** [comment]
Sure, I can probably figure that out. Perhaps I'm too in favor of breaking things...

**Comment by mlissner** [comment]
This issue has a PR that just needs to be merged. I suggest that we do that, and that'll please the Github bot?
