### ISSUE TITLE
fake 'en_US' locale cities have identical structure to 'en_GB' despite much more varied nomenclature

### ISSUE THREAD

**Issue by SJT1988** [joke2k/faker#1699]
* Faker version: 13.15.1
* OS: Windows 10

cities generated with 'en_US' locale sound very, very, VERY British.

my code:

```python
def fakeItToMakeIt():
        n=1000
        id = 0
        with open('customer_info2.csv', 'w', encoding='utf-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Id','Name', 'City', 'Country'])

            #US
            faker = Faker('en_US')
            for i in range(n):
                id+=1
                writer.writerow([id,faker.first_name() + ' ' + faker.last_name(), faker.city(), 'United States'])
            del(faker)

            #Britain
            faker = Faker(['en_GB'])
            for i in range(n):
                id+=1
                writer.writerow([id,faker.first_name() + ' ' + faker.last_name(), faker.city(), 'Great Britain'])
            del(faker)

            (...)
```

### Expected behavior

cities generated with 'en_US' locale do not almost entirely sound like "--shire", "--bury", "--port", "burgh, etc.
The most commonly repeated names for locations in the United States, according to Wikipedia, are

2.1	Washington (91)
2.2	Franklin (45)
2.3	Clinton (39)
2.4	Arlington (38)
2.5	Centerville (38)
2.6   Lebanon (35)
2.7	Georgetown (35)
2.8	Springfield (34)
2.9	Chester (32)
2.10	Fairview (32)
2.11	Greenville (31)
2.12	Bristol (29)
2.13	Dayton (28)
2.14	Dover (28)
2.15	Madison (29)
2.16	Salem (27)
2.17	Winchester (27)
2.18	Oakland (27)
2.19	Milton (25)
2.20	Newport (25)
2.21	Ashland (24)
2.22	Bloomington (24)
2.23	Riverside (25)
2.24	Manchester (23)
2.25	Oxford (23)
2.26	Burlington (22)
2.27	Jackson (23)
2.28	Milford (21)
2.29	Clayton (20)
2.30	Kingston (20)
2.31	Auburn (19)
2.32	Lexington (19)
2.33	Mount Vernon (19)
2.34	Cleveland (18)
2.35	Hudson (19)

Cities in the northeast sound more New England-y,
and cities in the southwest sound more Latin (San Antonio, Los Alamitos, etc.)

So I would expect a lot more variation in (even fake) US city names than just white-sounding names pretending "shire", "port", "burgh", "ville", "mouth", etc.

### Actual behavior

Here are some of the en_US locale  and en_BR locale cities generated in my project: (note that the numbers and 'United States' were programmed separately, without using Faker:

1 North Williamview,United States
2 New Michaelburgh,United States
3 Millerchester,United States
4 Deborahburgh,United States
5 Lisamouth,United States
6 Jonathanchester,United States
7 West Joshuastad,United States
8 East Josephville,United States
9 West Tomview,United States
10 Benjaminfurt,United States
11 Lake Robert,United States
12 Maloneland,United States
13 Lake Susanborough,United States
14 Greenebury,United States
15 Thomasstad,United States
16 West Ryanburgh,United States
17 New Jeffmouth,United States
18 New Colleentown,United States
19 Carolinetown,United States
20 Dawsonburgh,United States

1001 Janiceburgh,Great Brittain
1002 North Ericfurt,Great Brittain
1003 East Valerie,Great Brittain
1004 New Irene,Great Brittain
1005 Waltonside,Great Brittain
1006 Naomi Davies,North Duncanhaven,Great Brittain
100 Lake Adrian,Great Brittain
1008 Geraldstad,Great Brittain
1009 North Lesley,Great Brittain
1010 North Alison,Great Brittain
1011 Scottborough,Great Brittain
1012 West Hugh,Great Brittain
1013 Tracyport,Great Brittain
1014 New Jeffrey,Great Brittain
1015 South Lawrenceville,Great Brittain
1016 Port Gareth,Great Brittain
1017 West Jeanport,Great Brittain
1018 North Anthonychester,Great Brittain
1019 Hallland,Great Brittain
1020 Peterstad,Great Brittain

It has occurred to me (just now) that maybe the "Britishness" I am noticing has a lot to do with european person-names being used in the city name?

#-------------------------------

It would be nice if future updates sampled actual cities from the country they are intended to represent, or if that feature were introduced, as it would better fit real-world models

**Comment by fcurella** [comment]
City suffixes for `en_US` are defined [here](https://github.com/joke2k/faker/blob/master/faker/providers/address/en_US/__init__.py#L10-L30).

If you have time, feel free to submit a PR with a more American list :)

**Comment by SJT1988** [comment]
Lol, I know, right? 😂
