### ISSUE TITLE
Duplicate formats in formats tuple for en_US provider

### ISSUE THREAD

**Issue by anthonyyim** [joke2k/faker#170]
Hi,

There are duplicate formats in https://github.com/joke2k/faker/blob/master/faker/providers/en_US/phone_number.py

E.g. `'+##(#)##########'` appears twice, as does `'0##########'`.

Will be happy to submit a PR for a fix myself. Wanted to confirm the duplicate is a bug.

Best,
Anthony

**Comment by stephenross** [comment]
I have taken a look at the [North American Numbering Plan](https://en.wikipedia.org/wiki/North_American_Numbering_Plan) information and found that both of the first 2 formats (the +##(#)########## and 0########## formats) are not valid formats for the en_US locale. I have removed both and sorted the rest with comments temporarily based on the information in that page for a future enhancement to the phone_number provider to use a few arguments to choose a subset of formats. I have another branch where I have added an argument that will allow manually specifying a phone number format (even though the default numerify provider will have the same result) for portability. Pull requests to come shortly.

**Comment by thehesiod** [comment]
@stephenross I think that last change was still incorrect, 001 does not seem to be a valid us format prefix per  https://en.wikipedia.org/wiki/List_of_international_call_prefixes.  I think what you want is 011-1-###-####
@kestein for finding this.  Is this list supposed to have formats for calling from us to us, or from outside us to us?  as they're different ;). probably need to differentiate between the two
