### ISSUE TITLE
Lower bound for typing_extensions?

### ISSUE THREAD

**Issue by stefan6419846** [joke2k/faker#1708]
* Faker version: 14.1.0
* OS: OpenSUSE Leap 15.3

For old Python versions (before Python 3.8), *faker* requires the *typing_extensions* with at least version 3.10.0.2. Due to some other dependencies inside my project, I am required to use version 3.7.4.3.

### Steps to reproduce

1. `pip install faker`

### Expected behavior

*faker* works with `typing_extensions==3.7.4.3` as well, to allow better integration with larger systems which are stuck at such older versions for some reasons.

### Actual behavior

*faker* declares `typing_extensions>=3.10.0.2` (#1557), although I could see no issue when using it with `typing_extensions==3.7.4.3`.

**Comment by fcurella** [comment]
Thank you for the report @stefan6419846 ! Would you mind submitting a Pull Request?

**Comment by stefan6419846** [comment]
Yes, no problem. Should be should use `typing_extensions>=3.7.4.3` there, or should we try to determine when the `Literal` type has been introduced and use this version?
