### ISSUE TITLE
add parameter: platform

### ISSUE THREAD

**Issue by hjkl01** [joke2k/faker#1716]
* Faker version: latest
* OS: MacOS

Brief summary of the issue goes here.

### Steps to reproduce

1. [code](https://github.com/joke2k/faker/blob/c470c957c6215a39019860e0ea8519fb87118c66/faker/providers/user_agent/__init__.py#L137)
2. cloud you add parameter that I can choose platform

**Comment by fcurella** [comment]
I don't really have much time nowadays to work on new features. If you can submit a Pull Request, I'll be happy to review it!
