### ISSUE TITLE
Feature request: allow calls to Faker instance from module

### ISSUE THREAD

**Issue by duarte-pompeu** [joke2k/faker#1722]
* Faker version: 14.2.0
* OS: Windows / WSL

I wonder if we could simplify the usage of Faker to something like this:

 ```python
import faker
faker.seed(123)
faker.name()
```

This would allow the following behaviors:
- common users: import the module and use the methods directly
- advanced users: import the classes and instantiate them as desired

This is possible via [The Prebound Method Pattern](https://python-patterns.guide/python/prebound-methods/), which is used in standard libraries such as [random](https://github.com/python/cpython/blob/main/Lib/random.py#L876:L908) and 3rd party libraries such as [loguru](https://github.com/Delgan/loguru/blob/master/loguru/__init__.py#L1:L33).

If there's interest, I can put some work on this, although I have limited knowledge about faker.

**Comment by duarte-pompeu** [comment]
Small demo: #1723

**Comment by fcurella** [comment]
What locale would `faker` use? Should it have a method to change locales, eg something like `faker.add_locales()`?

**Comment by duarte-pompeu** [comment]
I hadn't thought about that, as I just used it for some internal tests which weren't concerned about locale.

In this demo, it's using `en_US`, which appears to be the default when `locale` is not specified when initializing `Faker`. I think that's a reasonable default.

But it could be interesting to have a `add_locales()` or `set_locales()`.Mmaybe the instance could have this new method? Then the module could also provide it with:

```python
set_locales = _faker.set_locales
```
