### ISSUE TITLE
random_element fails for dictionaries with string values

### ISSUE THREAD

**Issue by stefan6419846** [joke2k/faker#1728]
* Faker version: 14.2.0
* OS: OpenSUSE Leap 15.3

The `random_element` provider fails if a dictionary with non-numeric values is provided for the elements.

### Steps to reproduce

```python3
from collections import OrderedDict

from faker import Faker


faker = Faker()

print(faker.random_element(OrderedDict(key1=1, key2=2)))
print(faker.random_element(OrderedDict(key1='1', key2='2')))
```

### Expected behavior

No error will be thrown.

### Actual behavior

The second random choice will fail:

```python3
key1
Traceback (most recent call last):
  File "/home/me/path/to/testing.py", line 9, in <module>
    print(faker.random_element(OrderedDict(key1='1', key2='2')))
  File "/home/me/lib/python3.6/site-packages/faker/providers/__init__.py", line 594, in random_element
    max_element_length=max_element_length,
  File "/home/me/lib/python3.6/site-packages/faker/providers/__init__.py", line 506, in random_elements
    length=length,
  File "/home/me/lib/python3.6/site-packages/faker/utils/distribution.py", line 73, in choices_distribution
    return random.choices(a, weights=p, k=length)
  File "/home/me/lib64/python3.6/random.py", line 365, in choices
    for i in range(k)]
  File "/home/me/lib64/python3.6/random.py", line 365, in <listcomp>
    for i in range(k)]
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by fcurella** [comment]
The problem is not with the string values, but with `OrderedDict`. When using an `OrderedDict`, Faker assumes you're providing weighted values.

**Comment by stefan6419846** [comment]
Thanks for the hint - it actually seems to be documented, although I have not been aware of that. I assume that there is not much which could be changed about this, unless we add an explicit parameter to not handle the values as weights?

**Comment by fcurella** [comment]
An alternative would be to define a "WeightedDataset" class and update all providers to use that.

**Comment by stefan6419846** [comment]
I am not sure what the best approach would be in this case. Yes, it is some documented behavior, but the error message is quite cryptic and does not really indicate what is going wrong here.

While at least for recent CPython versions, regular dictionaries are guaranteed to maintain their order, explicitly using *OrderedDict* if order matters is still something which is considered good practice.

Yes, using our own `class WeightedDataset(OrderedDict): pass` would work (and make everything much more explicit), but impose a larger breaking change for anyone actually using the weighted datasets.
