### ISSUE TITLE
Sentence improvements

### ISSUE THREAD

**Issue by gotofritz** [joke2k/faker#1738]
* Faker version: 15
* OS: any

I would like to suggest some small improvements to sentence. Happy to submit a PR myself, just checking it would be well received

- default `sentence_punctuation` should include `.`, `!`, `?`, `...`
- `sentence_punctuation` should also be an argument to the function
  - if an array of strings, the strings will replace the default `sentence_punctuation`
  - if False, the sentence should have no punctuation at the end
- introduce a new paramenter, `inner_punctuation` which includes by default `,`, `;`, `-`, `...` `()`
- `inner_punctuation` should also be an argument to the function
  - if an array of strings, the strings will replace the default `inner_punctuation`
  - if False, the sentence should have no punctuation between words

How does that sound?

**Comment by fcurella** [comment]
To be honest.. that sounds a little complicated, and potentially a rabbit-hole. For example:

* How would we handle the cases  like, eg: Spanish, with sentences like `¿Tienes hambre?` ?
* Should quotes be considered "punctuation"? Consider curly quotes, but also some languages have quotes that [look like this `« … »`](https://en.wikipedia.org/wiki/Guillemet#Uses). Or like this `„ … “`.

**Comment by gotofritz** [comment]
Well, the good news is that currently lorem has no Spanish package so I don't have to worry about that 😄 
But I guess ¿ can simply be prepended to sentences which end in ?

I would avoid quotes in this iteration. Lorem has no concept of punctuation currently. Adding only the punctuation I listed above wouldn't make things _worse, it would still be an improvement. My aim is to be a bit more realistic, without trying to create a fully fledged sentence text synthesiser

**Comment by gotofritz** [comment]
Never mind
