### ISSUE TITLE
How about a release?

### ISSUE THREAD

**Issue by svenstaro** [joke2k/faker#174]
Last release was in March. Perhaps a new release would be in order to make people using pypi get it as well? Would be appreciated! Keeps the ecosystem going and all that.

**Comment by loic** [comment]
Any updates? Just wasted a bunch of time on https://github.com/joke2k/faker/issues/171 when a fix has already been merged 3 months ago.

**Comment by fcurella** [comment]
@joke2k you don't need to wait for my changes to be merged in. You can release anytime you want.

**Comment by fcurella** [comment]
v0.5 was just released today.
