### ISSUE TITLE
Update repo link to correct docs domain

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#1740]
The repo homepage https://github.com/joke2k/faker has a url link to [`faker.rtfd.org`](http://faker.rtfd.org/).

That should point to `faker.readthedocs.io` instead, ideally with the underlying URL hyperlinked to the httpS version: `https://faker.readthedocs.io/`

**Comment by fcurella** [comment]
Thank for noticing @jeffwidman .

This a change only @joke2k can do, as I have no permissions on the repo's settings

**Comment by jeffwidman** [comment]
This is not stale.

**Comment by joke2k** [comment]
Hi @jeffwidman you're right, I'll fix it asap

**Comment by joke2k** [comment]
@jeffwidman why do you prefer the long version of the URL? 
I added the secure protocol now but I think is better to leave the shortened version

**Comment by jeffwidman** [comment]
Two reasons:
1. It skips the `301` to the longer URL... since it redirects there anyway, might as well point to the longer one.
2. RTFD is an abbreviation that is succinct, but a bit rude for what it stands for... thought it was a little more polite to skip the F in RTFD.

**Comment by joke2k** [comment]
@jeffwidman thank you for explaining.

> It skips the 301 to the longer URL... since it redirects there anyway, might as well point to the longer one.
The short link is definitely prettier in the side column of the project, but...

> RTFD is an abbreviation that is succinct, but a bit rude for what it stands for... thought it was a little more polite to skip the F in RTFD.
.. you're right.
