### ISSUE TITLE
Missing return in faker-master\faker\providers\address\en_US\__init__.py

### ISSUE THREAD

**Issue by AssenD** [joke2k/faker#1742]
* Faker version: current
* OS: Windows 10 x64

Brief summary of the issue goes here.
Missing return on row 496 (def state_abbr(self, include_territories: bool = True) -> str:)

### Steps to reproduce

1. invoke state_abbr()
2. check the output 

### Expected behavior
Should return an element from states_and_territories_abbr list

### Actual behavior
Returns an element from states_abbr list only

**Comment by fcurella** [comment]
thank you for the report! Would you mind submitting a Pull Request?
