### ISSUE TITLE
faker spamming the logs with logger set to ERROR

### ISSUE THREAD

**Issue by edmundsj** [joke2k/faker#1752]
* Faker version: 15.3.2
* OS: Ubuntu 22.04

Faker continues to spam the logs even when I set the logging mode to 'ERROR' with things that are definitely not errors and do not raise exceptions.

### Steps to reproduce

1. Set logging appropriately
```
import logging

logging.getLogger('faker').setLevel(logging.ERROR)
```

2. Attempt to run a factory with `create` that has a `SubFactory` or `PostGenerationMethodCall`
3. Receive unwanted messages in the logs:
```
SubFactory: Instantiating users.factories.UserFactory(), create=<BuildStep for <StepBuilder(<DjangoOptions for ProductFactory>, strategy='create')>>
PostGenerationMethodCall: Calling <User: alexandriawilliams@example.com>.set_password('aoeu]+5236753REOu')
```

### Expected behavior

No logs should be generated with calls to `SubFactory` or `PostGenerationMethodCall` when logging is set to `ERROR`. These are not errors and it is not useful for me to know that they were run.

### Actual behavior

Logs are generated unnecessarily.

**Comment by stefan6419846** [comment]
*faker* neither defines the *SubFactory* nor the *PostGenerationMethodCall* class. You are probably mixing this up with *factory_boy*, which actually defines them, but just uses *faker* as a dependency. For this reason, it seems like your issue report is at the wrong repository.
