### ISSUE TITLE
Acceptable to duplicate a locale

### ISSUE THREAD

**Issue by davebulaval** [joke2k/faker#1764]
Since there is no`"fr_CA"` in the `date_time` provider, would it be acceptable to duplicate the `"fr_FR"` one?

My problem is that I need to create two fakers, one with "fr_CA" and the other with "fr_FR" to generate the proper information that I need. Not that is it too much, but if it is acceptable to duplicate (or add a reference to "fr_FR" maybe). It would be easier to handle on the client side.

**Comment by stefan6419846** [comment]
I see no issue in this, as it already seems to have been done for some providers.

**Comment by davebulaval** [comment]
> yes we can add one that just subclasses `fr_FR` with no overrides. FYI I’m on vacations and won’t be able to merge it until January

No worries. enjoy your vacation. I have a work around for now.

**Comment by davebulaval** [comment]
PRs have been merged.
