### ISSUE TITLE
Duplicate data while running in concurrent.future

### ISSUE THREAD

**Issue by XiaoxiaYao** [joke2k/faker#1765]
* Faker version:
* OS:

Brief summary of the issue goes here.

### Expected behavior

It should generate different data.

### Actual behavior

![image](https://user-images.githubusercontent.com/22899096/207526633-fd680f5b-cb6b-4cd8-8080-3bcaba44e0cf.png)

**Comment by geeklogbook** [comment]
Hello @XiaoxiaYao, 
could you share the code so I try to reproduce the error on my machine?
Thanks!

**Comment by XiaoxiaYao** [comment]
Sorry. I fixed later. I did not use different seed. Sorry I am new to `random`
