### ISSUE TITLE
name_female generates mixed names

### ISSUE THREAD

**Issue by constancepopovic** [joke2k/faker#1770]
* Faker version: Lastest
* OS: NA

Using `name_female` actually ends up generating mixed names, the same is true for `name_male`.

### Steps to reproduce
```python
from faker import Faker

fake = Faker("en-GB")

for i in range(1, 100):
    print(fake["en-GB"].name_female())
```
Example output:
```
...
Mr. Russell Morgan
Mr. Vincent Frost
Ruth Perry
Jacob Harris-Fitzgerald
Frances Robinson
Guy Hayward
Pamela Sanders-Davis
Frederick Doyle
Diana Hayes
Diane Hudson
Mr. Leonard Simpson
Mrs. Natalie Wilson
...
```
### Expected behavior

Generates only female names.

### Actual behavior

Generates mixed names.

This appears to be because `formats_female` is not defined, which then causes the function to fall back to a general format.

https://github.com/joke2k/faker/blob/7e78eef2565c5ce78b879bf271f520e817f55d4f/faker/providers/person/__init__.py#L230-L236

**Comment by stefan6419846** [comment]
Feel free to submit a corresponding PR together with a verifying test to this this.

**Comment by nathanael-e** [comment]
I can work on this unless @constancepopovic is already assigned to it.
