### ISSUE TITLE
Suggestion: generate valid data for barcode structures

### ISSUE THREAD

**Issue by myicq** [joke2k/faker#1774]
* Faker version: 15.3.4
* OS: Windows

Suggestion: faker already includes functions to generate simple 1d barcodes (ean8 and ean13) plus a few more. In the barcode world there are many other data structures which would be useful to fake.

I work professionally with barcodes from a customer pov. and often come across some of these:

- GS1 structure
- German Post (premium post)
- UK Royal Mail datamatrix
- Swiss QR code
- vcard structure
- UPU parcel code

In principle these are just appearing as "random strings", but the data format has to be in a very specific way. It would be very useful to generate such structures and feed to a barcode generator.

**Comment by stefan6419846** [comment]
As long as the corresponding formats are documented somewhere, this should usually not be a big deal. Nevertheless, I am not sure whether this should be part of the core module or an external one, as this appears to be rather specific.
