### ISSUE TITLE
Add French equivalents of Dutch `Address`, `Phone_number`, `Ssn` providers for Belgium

### ISSUE THREAD

**Issue by Dutcho** [joke2k/faker#1782]
* Faker version: 15.3.4
* OS: Windows 11

While Faker `Address`, `Phone_number`, and `Ssn` providers exist for Dutch-speaking Belgium (`'nl_BE'`), these are missing for French-speaking Belgium (`'fr_BE'`). I suggest adding these equivalents to Faker, for which I plan drafting a PR.

### Steps to reproduce

```python3
from faker import Faker
fake = Faker('fr_BE') 
```

### Expected behavior

`Phone_number` and `Ssn` providers are only country specific (not language specific), so these should return the same for `'fr_BE'` as for `'nl_BE'`.
`Address` should provide French names like 'rue', 'Anvers' instead of Dutch ones like 'straat', 'Antwerpen'.

### Actual behavior

`Faker('fr_BE')` fails with `AttributeError`.

**Comment by fcurella** [comment]
Thank you @Dutcho! Feel free to submit PRs for those providers!
