### ISSUE TITLE
Question:  sampling n random numbers from a normal distribution with specific min, max values

### ISSUE THREAD

**Issue by idhamari** [joke2k/faker#1790]
This is not an issue, but rather a question (it would be nice to enable[github discussion features](https://docs.github.com/en/discussions) to allow asking such questions).

Is there a function similar to [buildNum(n, min, max, dispersion, outliers)](https://cran.r-project.org/web/packages/conjurer/conjurer.pdf) to allow sampling **n** random numbers from a normal distribution with known **min**, **max**, **dispersion**, **outliers**  values? 

- n: A number. This specifies the number of values to be generated.
- min: A number. This defines the starting value of the number of data points.
- max : A number. This defines the ending value of the number of data points.
- dispersion: A number between −(pi/2) and (pi/2). This defines the dispersion of the distribution.
- outliers: A number. This signifies the presence of outliers. If set to value 1, then outliers are generated randomly. If set to value 0, then no outliers are generated. The presence of outliers is a very common occurrence and hence setting the outliers to 1 is recommended. However, there are instances where outliers are not needed. For example, if the objective of data generation is solely for visualization purposes then outliers may not be needed. The default value is 1.

**Comment by stefan6419846** [comment]
You can find our distribution implementations in https://github.com/joke2k/faker/blob/master/faker/utils/distribution.py, which relies on https://docs.python.org/3/library/random.html itself.

As far as I am aware, your feature would have to be implemented manually, maybe based on https://github.com/SidharthMacherla/conjurer/blob/master/R/buildNum.R. Nevertheless, I am not sure whether this specific type of data might fit better inside an external *faker* plugin.
