### ISSUE TITLE
Latvian ssn generator is not correct

### ISSUE THREAD

**Issue by OskarsPakers** [joke2k/faker#1799]
* Faker version: 17.0.0
* OS: Windows

Latvian ssn generator generates ssn in format 'ddd-dd-dddd', which is not correct. 

### Steps to reproduce

```
from faker import Faker
fake = Faker('lv_LV')
fake.ssn()

```

### Expected behavior

It should be 12 characters long DDMMYY-CZZZQ e.g. 170334-19862

### Actual behavior

fake.ssn() for latvian locale outputs ssn in format  'ddd-dd-dddd'
'604-87-6475'
'824-21-9489'
'411-57-8156'
'938-77-8408'

**Comment by stefan6419846** [comment]
`fake.ssn()` is not implemented/customized for the `lv_LV` locale at the moment (https://github.com/joke2k/faker/blob/master/faker/providers/ssn/lv_LV/__init__.py), thus falling back to the default implementation in https://github.com/joke2k/faker/blob/master/faker/providers/ssn/__init__.py

Feel free to submit a PR with an accompanying test which defines the correct `ssn_formats` list inside the provider or overwrite the corresponding `ssn()` method to return correctly formatted values.
