### ISSUE TITLE
states_postcode fails with territories

### ISSUE THREAD

**Issue by johnekent** [joke2k/faker#1812]
* Faker version: since 15.1.2
* OS:  All

Brief summary of the issue goes here.
en_US state fix in 15.1.2 added territories, which are not in states_postcode

Looking up postcode by state fails with territories enabled, but didn't fail prior to 15.1.2.

The fix made here:
  https://github.com/joke2k/faker/blob/master/faker/providers/address/en_US/__init__.py#L496
Combined with the default to include territories here:
  https://github.com/joke2k/faker/blob/master/faker/providers/address/en_US/__init__.py#L488
Causes this to fail whereas it did not prior to the correction made in 15.1.2.
  https://github.com/joke2k/faker/blob/master/faker/providers/address/en_US/__init__.py#L505

### Steps to reproduce

1. fake.add_provider(providers.address.en_US.Provider)
2. state = fake.state_abbr()  # include_territories=True is default.  user can fix by setting to False?
3. repeatedly call fake.zipcode_in_state(state)  # or alternatively pass in GU or other territory

### Expected behavior
Ideally this would not give an error when combining these functions.
It looks like territories to have zip codes, so best solution may be to update the state/postalcode mapping.

--> from internet:  "Within the U.S. Territories, American Samoa (postal abbreviation AS) uses zip code 96799, and Guam (postal abbreviation GU) uses zip codes in the range 96910–96932."

### Actual behavior
Fails on Step 3 noted above.

**Comment by stefan6419846** [comment]
Related PR is https://github.com/joke2k/faker/pull/1743. Would you mind submitting a PR with a fix and ideally a corresponding test which ensures that this issue will indeed not occur?

**Comment by johnekent** [comment]
Thanks for reviewing.  I will work on PR with tests after reading the contributing guidelines.
