### ISSUE TITLE
random_element weighting isn't honored after adding a provider

### ISSUE THREAD

**Issue by myles2007** [joke2k/faker#1815]
* Faker version: 17.3.0
* OS: macOS 13.1 (22C65)

### Steps to reproduce
The following code reproduces the issue reliably in my environment:
 
```python
from collections import namedtuple, OrderedDict, Counter

from faker import Faker
from faker.providers import BaseProvider
    
class StateProvider(BaseProvider):
    def weighted_state(self):
        StateChoice = namedtuple("StateChoice", ["state", "probability"])
        state_choices = [
            StateChoice(state="TX", probability=0.99),
            StateChoice(state="CA", probability=0.01),
        ]
        return self.random_element(OrderedDict(state_choices))

        # Using `random_elements` directly and providing `use_weighting=True` solves the problem
        #return self.random_elements(elements=OrderedDict(state_choices), length=1, use_weighting=True)[0]
        
Faker.seed(1234)
fake = Faker()

# Define a few possible choices with very different weights
StateChoice = namedtuple("StateChoice", ["state", "probability"])
state_choices = [
    StateChoice(state="TX", probability=0.99),
    StateChoice(state="CA", probability=0.01),
]

# Generate 1000 samples and count the occurrences
# Everything works as expected this time
states = []
for x in range(1000):
    states.append(fake.random_element(OrderedDict(state_choices)))
    
print(Counter(states))

# Add the custom provider, generate 1000 samples and count the occurrences
# The distribution should be roughly the same, but the weights are ignored this time.
fake.add_provider(StateProvider)  # Adding a provider (any provider, it seems) causes a change to behavior.
states = []
for x in range(1000):
    states.append(fake.random_element(OrderedDict(state_choices)))
	# Using `random_elements` directly and providing `use_weighting=True` solves the problem
    #states.append(fake.random_elements(elements=OrderedDict(state_choices), length=1, use_weighting=True)[0])
    
print(Counter(states))

# The same as above, but using the custom provider. Weights are again ignored.
states = []
for x in range(1000):
    states.append(fake.weighted_state())
    
print(Counter(states))
```

Outputs:
```
Counter({'TX': 992, 'CA': 8})     <-- Expected
Counter({'CA': 511, 'TX': 489})
Counter({'TX': 503, 'CA': 497})
```

### Expected behavior

When I provide weighted elements, I expect that the choice should yield elements according to those weights consistently.

### Actual behavior
Before any additional providers are added, this works as expected. Following the addition of—in my experience—any additional provider changes the behavior and weights are ignored.

Using `random_elements([...], length=1, use_weighting=True)[0]` solves the issue, but I'd prefer to stick with the more concise statement if possible.

Please let me know if any additional information would be helpful. If this is confirmed to be a bug and not just something I'm misunderstanding, I'd be happy to try to help resolve it.

Thanks!

**Comment by fcurella** [comment]
Maybe this is not documented properly, but this is by design: if you're using weighted elements, you are supposed to pass `use_weighting=True`.

If you know that your custom provider only uses weighted elements, you can set the `CustomProvider.__use_weighting__` class attribute to `True`, and `use_weighting` will default to `True`.

The reason why we had to add the `use_weighting` parameter is that it's hard to tell when the dataset is a `dict` of weighted elements, or just any dict whose values happen to be tuples.

We considered introducing a custom `WeightedDict` class to type-check against, but that's going to require updating all the providers, and nobody has submitted a PR for that, yet.

**Comment by myles2007** [comment]
Thanks for the reply, @fcurella!

I think some documentation here would help. I did see `__use_weighting__` in the source code, but I don't think I came across it anywhere in the documentation.

That said, I think my example may have slightly mislead because it's not so much about the custom provider as it is about the global behavior change when _any_ provider is added.

```python
fake = Faker()
fake.random_element(weighted_choices) # <-- Uses weighting
fake.add_provider(any_provider_at_all)
fake.random_element(weighted_choices) # <-- No longer uses weighting in any context
```

This behavior was definitely very unexpected to me. I suspect it has something to do with how the proxy object works, but haven't had a chance to really dig into that. Behavior local to a custom provider would have been less surprising (though still surprising), but it's the global change that really caught me off guard. 

Passing `use_weighting=True` wouldn't be a big deal, but `random_element` doesn't accept that argument:
https://github.com/joke2k/faker/blob/5de6bf3fb811272b7e13b6da6623ee1fdfa3efe3/faker/providers/__init__.py#L528-L545

I did also try explicitly creating `fake = Faker(use_weighting=True)`, but it has no effect—unsurprising since it's the default.

Doe this change anything?

**Comment by fcurella** [comment]
Thank you for clarifying!

This does sound familiar, so I dug through past issues and found [#1500](https://github.com/joke2k/faker/issues/1500). So yes, this is a known bug, and a PR is definitely are welcome :)

**Comment by myles2007** [comment]
Thanks for confirming!

I'll review #1500 and see where that takes me. If you have any advice on where to start that's not already written down there, it would be appreciated.

On a related note, what are your thoughts on adding `use_weighting` as an argument to `random_element` so that it can be passed along to the internal call to `random_elements`?

**Comment by fcurella** [comment]
I think `use_weighting` ought to be on `random_element` as well. I have no idea why it's not there.

**Comment by myles2007** [comment]
Great! That one I know I can do. :)
