### ISSUE TITLE
Replace part of locales with Babel's Locale Data

### ISSUE THREAD

**Issue by PerchunPak** [joke2k/faker#1816]
[Babel](https://babel.pocoo.org/en/latest/index.html) provides [useful API](https://babel.pocoo.org/en/latest/locale.html), to get localised data without any translation. This will allow to avoid handly maintain a big amount of localised data and such mistakes as #1809, https://github.com/joke2k/faker/pull/1809#discussion_r1124678363. Those will be handled automatically, with Babel version bump.

**Comment by fcurella** [comment]
I love the idea, I think it would drastically reduce the amount of maintenance work on my part :)

We need to evaluate the impact of adding `babel` as dependency. Babel has a lot of stuff that our users are not necessarily interested in (eg: the `pybabel` script). It would be nice if there was a package with *just* the CLDR data.

**Comment by PerchunPak** [comment]
While there are a few [other libraries](https://github.com/night-crawler/cldr-language-helpers) to access CLDR data (although, they are dead), I do not really think that they should be used. Babel is well-tested, often-used and often updated solution.

Some other parts, like CLI script, are not so big to not use them. There are only a few features, that we do not need. Like CLI, `.po` parsing and maybe some other [rarely useful features](https://babel.pocoo.org/en/latest/api/support.html). Those are not so big part as CLDR is.

**Comment by fcurella** [comment]
Feel free to prepare a Pull Request for discussion 👍🏼

**Comment by PerchunPak** [comment]
Well, I do not have time for this now. This is just suggestion.

**Comment by PerchunPak** [comment]
Bump
