### ISSUE TITLE
Suggestion: Address provider should generate state (where appropriate)

### ISSUE THREAD

**Issue by jenstroeger** [joke2k/faker#1845]
* Faker version: 18.4.0
* OS: macOS 13.2.1

Brief summary of the issue goes here.

The standard [address.Provider](https://faker.readthedocs.io/en/master/providers/faker.providers.address.html) doesn’t have a `state()` or `state_code()` method which would be useful (for countries which support that).

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

**Comment by jens-getpassport** [comment]
The related PR https://github.com/joke2k/faker/pull/1864 is still open, and unfortunately I can’t reopen this issue. Having a PR certainly keeps the issue active…

**Comment by jenstroeger** [comment]
🤷🏻‍♂️

**Comment by stefan6419846** [comment]
Do you want to continue the work from the corresponding PR to resolve this issue?

**Comment by jenstroeger** [comment]
@stefan6419846 You mean reopening #1864 and finishing what @Sbhat92 left unfinished?

**Comment by stefan6419846** [comment]
Re-opening probably does not work, but yes, continuing the work on your own fork to fix the remaining issues seems like seem more suitable approach than fighting against the stale mechanism of the issue itself, given that most(?) of the work already has been done.

**Comment by jenstroeger** [comment]
Thanks @stefan6419846. I’m not too familiar with the inner workings of Faker at this point, but reviewing the work on PR #1864 it looks like I should follow that pattern? For my use case I’m mostly interested in es_CO…

**Comment by stefan6419846** [comment]
At least I would propose so, as @fcurella as the current maintainer just pointed out the style issues and the odd `isinstance` check inside the tests.
