### ISSUE TITLE
Suggestion: Fake Passport, Driving License and County

### ISSUE THREAD

**Issue by psmukherjee009** [joke2k/faker#1853]
* Faker version:
* OS:

Currently I needed Fake Passport, Driving License and County and didn't find it in Faker. Can we have these?

### Steps to reproduce

1. step 1
1. step 2
1. step 3

### Expected behavior

X should be ...

### Actual behavior

X is ...

**Comment by stefan6419846** [comment]
You can probably try to implement this yourself and create a PR, but there is no existing implementation yet.
