### ISSUE TITLE
add an API to genearte a fake dataclass 

### ISSUE THREAD

**Issue by Agent-Hellboy** [joke2k/faker#1854]
Hi 
Today I got a requirement to fake data class for a unit test 
I have written a lib for the same but I think Faker should provide an API to do so.

example code 
```py
from dataclasses import dataclass

@dataclass()
class Heartbeat:
    serialNumber: str
    cbsdId: str
    grantId: str
    grantState: str
    carrier: int
    maxEirp: int

fake = Faker()
fake_data = fake.fake_dataclass(Heartbeat)
print(fake_data)

Heartbeat(serialNumber='economic', cbsdId='pull', grantId='save', grantState='same', carrier=729, maxEirp=1792)
```

I will try to raise a PR if you approve

**Comment by stefan6419846** [comment]
You want to fill an existing dataclass with faked values, not generate a faked dataclass container itself? The former should be doable (although we should probably find a way to deal with non-standard types), while the latter probably would need an external provider to correctly deal with generating multiple field types.

Nevertheless, I am not sure whether filling a dataclass with values actually makes sense for core *faker*. For me this seems like something which might go into another package, like *factory_boy* which works with Django models for example (although dataclasses are part of the stdlib compared to Django).

**Comment by Agent-Hellboy** [comment]
>Nevertheless, I am not sure whether filling a dataclass with values actually makes sense for core faker. For me this seems like something which might go into another package, like factory_boy which works with Django models for example (although dataclasses are part of the stdlib compared to Django)

sure, I can understand

>The former should be doable (although we should probably find a way to deal with non-standard types)

yes
