### ISSUE TITLE
Feature: XML provider

### ISSUE THREAD

**Issue by alona-sotnikova** [joke2k/faker#1855]
Summary:
Add a XML generator function to the Faker library in order to provide the randomly generated XML string.

Example of the output:
`faker.xml()`

`<?xml version="1.0" encoding="utf-8"?>
<picture><son>-9787526.29318886</son><voice>1979-06-24 16:00:13</voice><kitchen>878829203004.256</kitchen><amount>2017-12-27 03:37:52</amount><event>https://www.jones.net/home/</event><much>7113</much><mention>3350</mention><interview>2002-06-18 03:24:51</interview><why>-8016097.351393328711587148418583989471965934232094</why><step>22018684833.96947751591795330413525601230989101399161510903217300869141314562087091634579230225841</step></picture>`

**Comment by fcurella** [comment]
Thank you @alona-sotnikova ! I think this is a good idea. Do you have time to prepare a Pull Request?

**Comment by alona-sotnikova** [comment]
Sure, will create one soon 👍

**Comment by Elihayb** [comment]
Hey @fcurella, 
@alona-sotnikova and I finished creating the xml provider and I pushed a pull request.
https://github.com/joke2k/faker/pull/1862
