### ISSUE TITLE
`include_territories=False` not respected for `state_abbr`

### ISSUE THREAD

**Issue by ryancausey** [joke2k/faker#1856]
* Faker version: 18.6.0
* OS: Ubuntu 22.04.2 LTS

When using the `state_abbr` faker to produce states within the United States of America, passing the `include_territories=False` should prevent returning territories. It seems that the faker will still return US territories even when explicitly asked not to.

```repr
>>> import pycountry
>>> from faker import Faker
>>> fake = Faker()
>>> fake.locales
['en_US']
>>> code = f"US-{fake.state_abbr(include_territories=False)}"
>>> code
'US-NM'
>>> while pycountry.subdivisions.get(code=code) is not None:
...     code = f"US-{fake.state_abbr(include_territories=False)}"
...
>>> code
'US-FM'
>>>
```

### Steps to reproduce

1. install `faker=18.6.0` and `pycountry=22.3.5`
1. run the reproduction snippet above in a repl

### Expected behavior

The loop should never exit because all 2 letter state codes returned are not US territories.

### Actual behavior

The loop will exit because eventually a 2 letter state code for a US territory is returned instead.

**Comment by ryancausey** [comment]
After digging through the code some more, it looks like the issue is because a new parameter `include_freely_associated_states` was added in 18.3.0 that is by default `True`. 

This broke my tests in random and inconsistent ways which made this hard to track down. Should this have been released as a breaking change?

**Comment by fcurella** [comment]
The truth is that every change could be a breaking change for somebody ([XKCD #1172](https://xkcd.com/1172/)), so I just guess every time, and hope I get it right :P

That's the main reason why [we recommend in the README](https://github.com/joke2k/faker/blame/master/README.rst#L409-L411) to pin Faker down to the patch number :)

**Comment by ryancausey** [comment]
> I apologize for all the trouble this has caused to you.
> 
> The truth is that every change could be a breaking change for somebody ([XKCD #1172](https://xkcd.com/1172/)), so I just have to guess every time, and hope I get it right :P
> 
> That's the main reason why [we recommend in the README](https://github.com/joke2k/faker/blame/master/README.rst#L409-L411) to pin Faker down to the patch number :)

Fair enough. I do pin all my deps, but I think this slipped through my CI/CD through random chance. It didn't hit this case and used a US state that worked so all the tests passed.

Did you want me to close this issue?
