### ISSUE TITLE
Missing 18.7.0 tag?

### ISSUE THREAD

**Issue by rsalmaso** [joke2k/faker#1863]
* Faker version: 18.7.0

Current release (18.7.0) has no tag, and checking the [release url](https://github.com/joke2k/faker/releases/tag/v18.7.0) the linked Changelog show the `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` warning

![immagine](https://user-images.githubusercontent.com/171008/237027146-55814326-340a-45aa-b37b-e3c8e273b544.png)

**Comment by rsalmaso** [comment]
Ok,
fetching into my fork doesn't update tags, but if I clone the repository the 18.7.0 tag is there.
But for some reason master branch is not updated.

```shell
13344ed6 (tag: v18.7.0) Bump version: 18.6.2 → 18.7.0
ab83654b :pencil: Update CHANGELOG.md
9a68dfda (HEAD -> master, origin/master, origin/HEAD) Add zh_CN automotive license_plate rules and test functions (#1858)
294768d0 Add `license_plate` for `zh_TW` (#1857)
47a38066 (tag: v18.6.2) Bump version: 18.6.1 → 18.6.2
1b0628a3 :pencil: Update CHANGELOG.md
b379d24c Improve accuracy of departments in `fr_FR` provider `postcode` (#1852)
```

**Comment by fcurella** [comment]
thank you for the report, @rsalmaso !

I did push the tag, but I forgot to push the commit 🤦🏼 Should be ok now

**Comment by rsalmaso** [comment]
Now it's ok!
