### ISSUE TITLE
Add support es_VE

### ISSUE THREAD

**Issue by macagua** [joke2k/faker#1885]
* Faker version: v18.11.2
* OS: Any

I want to add Spanish for Venezuela language provider for the repository. The provider data will be Spanish Venezuelan language.

- [ ] Add `es_VE` address provider.
- [ ] Add `es_VE` person provider.
- [ ] Add `es_VE` internet provider.
- [ ] Add `es_VE` company provider.
- [ ] Add `es_VE` currency provider.

**Comment by fcurella** [comment]
Go for it! :)
