### ISSUE TITLE
Question rather than bug

### ISSUE THREAD

**Issue by karl0ss** [joke2k/faker#1895]
I have a question, and can't find a community anywhere to ask..

Is there a way to force faker to return everything as a string? for example-

`fake.date_of_birth()`
returns a `datetime.date` object, 
is there anyway for this to be returned as `str` based on the object?

Also the same applies for anything else like that, could a returned `list` be a string representation of the `list`?

Thanks

**Comment by fcurella** [comment]
Not currently. We can't possibly predict all the ways users want the output to be, so we leave it up to just regular Python.
