### ISSUE TITLE
Is buil-in serial incrementing number? 

### ISSUE THREAD

**Issue by mihalt** [joke2k/faker#1898]
I want to do something like 
`fake.csv(header=('Sentence','Word','Phone'), data_columns=('Sentence #', '{{name}}', '{{phone_number}}'), num_rows=5)`

And expect on the output something like
`'"Sentence","Word","Phone"\r\n"Sentence 1","Stacy Casey","+1-341-710-9070x397"\r\n"Sentence 2","David Cervantes","(397)692-8057"\r\n"Sentence 3","Lisa Davidson","(713)284-0862x46331"\r\n"Sentence 4","Tamara Carter","+1-296-813-9278x89612"\r\n"Sentence 5","Michael Burns","+1-833-355-3427x80664"\r\n'`

Are any built-in possibilities?

**Comment by fdemmer** [comment]
`#` is "numerified" using a random value; there is no sequence/serial.

https://faker.readthedocs.io/en/master/providers/baseprovider.html#faker.providers.BaseProvider.numerify

**Comment by fcurella** [comment]
I can see usefulness in a method like `.csv`. Feel free to submit a Pull Request!
