### ISSUE TITLE
Unformatted PyPI page

### ISSUE THREAD

**Issue by mgedmin** [joke2k/faker#190]
This is what a user sees on https://pypi.python.org/pypi/fake-factory:
![ekrano nuotrauka is 2015-01-13 16 44 15](https://cloud.githubusercontent.com/assets/159967/5722264/6fe5c138-9b43-11e4-8cd5-6f145c66827e.png)

This is caused by PyPI not understanding Markdown.

You can use [pandoc](http://johnmacfarlane.net/pandoc/) to convert Markdown to ReStructuredText that PyPI understands.

**Comment by joke2k** [comment]
fixed with new version 0.5 
https://pypi.python.org/pypi/fake-factory
