### ISSUE TITLE
Generate uri without http

### ISSUE THREAD

**Issue by mihalt** [joke2k/faker#1900]
Not undarstand, can I do it from box?

**Comment by stefan6419846** [comment]
Please provide some more context.

If you want to omit HTTP and only get HTTPS, then no for now, as the *schemes* parameter cannot be passed through: https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L627-L629 https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L149-L155
https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L318-L331

**Comment by mihalt** [comment]
> Please provide some more context.
> 
> If you want to omit HTTP and only get HTTPS, then no for now, as the _schemes_ parameter cannot be passed through:
> 
> https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L627-L629
> 
> https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L149-L155
> 
> https://github.com/joke2k/faker/blob/83b9dae86555ea35338ea10cc5f46de56f605d28/faker/providers/internet/__init__.py#L318-L331

yes, sorry for uncertainty. I meant without http and https both.

**Comment by fcurella** [comment]
According to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3), an URI must have a scheme:

> The scheme and path components are required, though the path may be
> empty (no characters).

I see there is some inconsistency between the `uri` and the `url` method, in that only `url` accepts the `schemes` arguments. I think that should be fixed so that they behave in the same way.

Once that is done, you could do something like:

```python
my_urn = fake.url(schemes=[]).replace("://", "")
```

**Comment by fcurella** [comment]
@mihalt Does 33e36b1b6cc9c6f039fe387988853771bab60624 address your issue?

**Comment by fcurella** [comment]
Closing as done, feel free to reopen
