### ISSUE TITLE
Aiming to add faker for book genres and titles 

### ISSUE THREAD

**Issue by dmitry-goryachev** [joke2k/faker#1901]
* Faker version: v 19.3.1
* OS: Windows

I have opened this ticket because while I was using the faker in my project for creating books on a website, I found there is no community made faker for books. I would like to contribute to faker by letting it generate:
* titles
* genres
* isbn
* imprints (for book copies)
* number of pages 

### Steps to reproduce

1. Fork the repository
2. Using the already existing music faker, reproduce the same kind of faker for the books, altering the concept if item creation from music-related to book-related.
3. Write some tests for the addon of mine.
4. Use pylint to check my code style and read guides to code style the faker repo provides
5. Correct the code style and optimize performance
6. Submit a pull request to the repository

### Expected behavior

the faker can fake book meta info (contentless).

### Actual behavior

the faker still cannot fake the books

**Comment by dmitry-goryachev** [comment]
I mentioned above I expect the book to generate isbn. This faker feature exists already, I remembered. So everything else remains, isbn will not be developed

**Comment by fcurella** [comment]
Hi @dmitry-goryachev !

Feel free to create an external [community provider](https://faker.readthedocs.io/en/master/communityproviders.html) like the music one. Once it's done, I'll be happy to add it to the list!
