### ISSUE TITLE
RGB/HSV/HSL color tuples from `color` provider

### ISSUE THREAD

**Issue by fdemmer** [joke2k/faker#1903]
* Faker version: 19.3.1
* OS: any

With #104/#1055 the `color` provider learned how to generate colors with certain characteristics like "dark" or from a given hue. 

As noted by @malefice in the previous PR, the faked values are only available as strings. Often a numeric format is more suitable as input for other data-generation or computation. I am personally looking for this functionality to generate placeholder-images with similar colors and [pycairo](https://pycairo.readthedocs.io/en/latest/reference/patterns.html#class-solidpattern-pattern) works with RGB as float. 

With a little refactoring it should be easy to reuse the logic already implemented in `RandomColor` to provide int/float tuples for pseudo-random colors.

### Expected behavior

Instead of adding another `color_format` argument and `color()` having non-string return values, additional fakes could provide the color tuples using the same `hue` and `luminosity` kwargs as `color()`.

```
>>> from faker import Faker
>>> fake = Faker()
>>> fake.color(hue='red')
'#931929'
>>> fake.color_rgb(hue='red')
(247, 127, 118)
>>> fake.color_rgb_float(hue='red')
(0.98, 0.68355, 0.6566)
>>> fake.color_hsv(hue='red')
(334, 91, 78)
>>> fake.color_hsl(hue='red')
(340, 57, 60)
```

### Feature overlap and further changes...

The current color provider only generates strings.

There is however some overlap with `color()` and `rgb_css_color()`, that probably should be refactored/deprecated in a separate step, i.e.:

```
>>> fake.color(hue='blue', color_format='rgb')
'rgb(25, 211, 232)'
>>> fake.rgb_css_color()
'rgb(117,96,199)'
```

**Comment by rag310** [comment]
To the developer
My issue is  about my mobile
Please fix my leg problem
