### ISSUE TITLE
Parameter for disallowed characters?

### ISSUE THREAD

**Issue by sloria** [joke2k/faker#191]
It would be useful to have a parameter that would disallow a set of characters from a provider's output.

``` python
# Don't use outputs that have /, %, or &
fake.bs(disallowed_characters=['/', '%', '&'])
```

The use case I ran into was that we needed fake strings that could safely be put into URIs and therefore cannot contain `/`.

Thoughts on this?

**Comment by cabello** [comment]
My suggestion would be: create your own provider which can call other providers:
```
fake.safe(fake.bs, strip=['/', '%', '&'])
```
