### ISSUE TITLE
Add provider to all Faker instances

### ISSUE THREAD

**Issue by g0di** [joke2k/faker#1910]
* Faker version: 19.6.1
* OS: Windows 10 Enterprise

I want to add a custom provider to all `Faker` instances in a way that any new instance created so far will have that provider added automatically.

Something like

```python
from faker import Faker
from faker.providers import BaseProvider

class MyProvider(BaseProvider):
    def foo(self) -> str:
        return 'bar'
  
Faker.add_provider(MyProvider)

fake = Faker()
fake2 = Fake()

fake.foo()
fake2.foo()
```

According to the documentation we're supposed to add custom provider per instance. I'm wondering if there is a way to do it at Faker class level or any other mechanism to achieve the same goal.

Cheers

**Comment by ernstki** [comment]
Hi @g0di, hope you found a workaround.

I know I'm a bit late discovering this, but a possible answer to your question would've been to use a derived class. This is fortunately a pretty straightforward thing to do in Python:

```python
from faker import Faker
from faker.providers import BaseProvider

class MyProvider(BaseProvider):
    def foo(self) -> str:
        return 'bar'

class MyFaker(Faker):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_provider(MyProvider)  # use the custom provider

# each new instance of the derived class will have a 'foo'
fake = MyFaker()
fake2 = MyFaker()
print(fake.foo())   # result: bar
print(fake2.foo())  # result: bar
```

**Comment by g0di** [comment]
Thank you for your reply! Indeed, seems an easy win. 3 years later, I'm wondering why I did not think about doing this ... Well, ... thanks 😃
