### ISSUE TITLE
`pyfloat` doesn't respect bounds with `right_digits`

### ISSUE THREAD

**Issue by ykrist** [joke2k/faker#1912]
* Faker version: 19.6.2
* OS: Linux

### Steps to reproduce
```
import faker
x = faker.Faker()
x.pyfloat(min_value=0.1, max_value=2, right_digits=2)
```
### Expected behavior

Result should be between 0.1 and 2.

### Actual behavior

Result is either 0.0 or 0.1, the former is out of the supplied bounds.

### Notes

It appears to work fine without the `right_digits` argument.

**Comment by gotofritz** [comment]
Actually no, it doesn't work fine without right_digits either.

It only works fine if max_value is an int (whether defined as float or int), but it's gets weird if it's a float

```python
import faker
x = faker.Faker()

for _ in range(10):
    print(x.pyfloat(min_value=1.0, max_value=2)) # same if max_value is 2.0

# 1.5705916129
# 1.3781490512069
# 1.406
# 1.73333476890438
# 1.6
# 1.9
# 1.4
# 1.62
# 1.4271432
# 1.10036465233726



for _ in range(10):
    print(x.pyfloat(min_value=1.0, max_value=1.4)) 
# 1.14954
# 1.413406488181    <-- out of range
# 1.3815427269856
# 1.94542113024808  <-- out of range
# 1.53              <-- out of range
# 1.609             <-- out of range
# 1.11000401266307
# 1.88785683004263  <-- out of range
# 1.259823466
# 1.456973414797    <-- out of range
```

**Comment by sbv-csis** [comment]
I'm also getting for example `0.2380771`  on `faker.pyfloat(min_value=0.55, max_value=1)`  :thinking: 

```
>>> import faker
>>> x = faker.Faker()
>>> x.pyfloat(min_value=0.9, max_value=1)
0.565299

>>> x.pyfloat(min_value=0.9, max_value=1)
0.6926114

>>> x.pyfloat(min_value=0.9, max_value=1)
0.13921535633853

>>> faker.VERSION
'19.6.2'
```

**Comment by stefan6419846** [comment]
Did it work before #1908?

**Comment by sbv-csis** [comment]
I verified it with 19.6.1 at least - no bug there so #1908 is for sure suspect

**Comment by stefan6419846** [comment]
In the past, we had https://github.com/joke2k/faker/pull/1908/files#diff-415de404be4f9d8d85c668258bc4da2dcd81756b92d86ad4f1a7100cf21baeeeL223-L233 to fix the value if out of range.

@HugoJP1 As you authored the PR: Can you say anything about the changes and what might cause this issues?
