### ISSUE TITLE
Adding gender 

### ISSUE THREAD

**Issue by simcax** [joke2k/faker#1913]
* Faker version:  19.6.2
* OS: Linux

I would like to add gender/sex to the person provider. As this could be localized as well. Right now I am using profile()["sex"], but that is english, and I need it in Danish. 

So wondering if this is best put in the person provider? 

And whether to use "sex " or "gender"? I.e. fake.sex() or fake.gender()?

**Comment by fcurella** [comment]
I think it would be best to be in `profile`. That way, the `.profile()` method can reuse it.

As for the name, it's `sex`, just like for the `profile` method.
