### ISSUE TITLE
Updating to 19.6.2 changes result of pyfloat function while Faker.seed() is set

### ISSUE THREAD

**Issue by dutyrok** [joke2k/faker#1915]
* Tested versions
  * 19.6.1
  * 19.6.2
* OS: ALT Linux Sisyphus

### Summary

Result of Faker.pyfloat is changed by updating faker version (from 19.6.1 -> 19.6.2), when Faker.seed() is installed.
There is the same problem in [pydantic test](https://github.com/pydantic/pydantic/blob/v2.4.2/tests/benchmarks/test_north_star.py).

### Steps to reproduce
1. Create file with code:
```python
from faker import Faker

f = Faker()
Faker.seed(0)
  
print(f.pyfloat(min_value=0, max_value=5))
```
2. Run program with Faker 19.6.1, then with 19.6.2

### Expected behavior

Results have to be the same.

### Actual behavior

```
Result (if 19.6.1): 3.5696932975701
Result (if 19.6.2): 3.15696932975701
```

**Comment by stefan6419846** [comment]
This seems to be another side effect of #1908.

@HugoJP1 Do you have an idea about this behavioral change as well?
