### ISSUE TITLE
where to find how to install providers 

### ISSUE THREAD

**Issue by Sandy4321** [joke2k/faker#1930]
where to find how to install providers 
as mentioned in
https://faker.readthedocs.io/en/master/communityproviders.html
for example
from faker_vehicle import VehicleProvider
fake.add_provider(VehicleProvider)
fake.vehicle_make()

so how to find all packages like faker_vehicle

**Comment by stefan6419846** [comment]
I do not really get what you actually want. For each community provider, you have a link to the corresponding package, which should document on how to use it. What is missing for you?

**Comment by Sandy4321** [comment]
sorry can not find clickable links on this page 
![image](https://github.com/joke2k/faker/assets/11426119/7b91d08e-782e-4091-a36f-cbe0ed81baf3)
