### ISSUE TITLE
Subsecond precision support for fake time

### ISSUE THREAD

**Issue by cknv** [joke2k/faker#1945]
* Faker version: 19.10.0
* OS: Arch Linux

Randomized datetimes produced by a faker instance only ever have second precision. This is rarely a problem but when combined with systems that send datetimes as unix timestamps (because it is easy to deal with in json), it can become a problem that `when.timestamp() == int(when.timestamp())`. This is caused by pythons somewhat loose equality check on numbers where floats and integers can compared and would actually be equal each other, when the fractional part of a float is zero.

I have skimmed the code generating datetime objects and it seems that in most (if not all) cases the randomness comes from a simpler random generation in the form of a second interval generated by `random.randint`, which as the name implies only ever returns integers and not floats as my needs would require.

If this has any interest then I could probably give it a go replacing the innermost calls to `random.randint` in the datetime provider, with something like `random.uniform`. But since am not very familiar with this code, there might be more suitable solution that I am just unaware of.

### Steps to reproduce

```python
from datetime import datetime, timezone, timedelta
from faker import Faker

faker = Faker()
point_in_time = datetime.now(timezone.utc)

randomized_datetime = faker.date_time_between(
	point_in_time,
	point_in_time + timedelta(days=5),
)

# technically this could be able to pass,
# but I have never been so lucky:
assert randomized_datetime.microsecond != 0

# or alternatively from the description above:
unix_ts = randomized_datetime.timestamp()
assert unix_ts != int(unix_ts)
```

### Expected behavior

When producing randomized datetime objects the microsecond value should be non-zero, for sub-second precision.

### Actual behavior

Randomized datetime objects only ever have second precision.

**Comment by fcurella** [comment]
If I remember correctly, we intentionally keep the second-precision to avoid issues with Windows, and we should have regression tests for it.

Feel free to try, and if all tests still pass we can get it merged.

**Comment by cknv** [comment]
Alright, then that would mean different behavior on windows compared to the rest of the platforms, which makes it a bit more complex. It should be reasonably easy to write the code itself, but I need to figure out how to make conditional tests so the different behaviour actually gets tested.
