### ISSUE TITLE
Unable to view changelog.md

### ISSUE THREAD

**Issue by ajatkj** [joke2k/faker#1948]
Whenever a version is released, the link to changelog is broken. I am not sure if its just me or happening to others as well. 

![image](https://github.com/joke2k/faker/assets/8344288/f2413bb3-236a-4eef-97e2-331604e9fe7b)

**Comment by ajatkj** [comment]
Btw this is only on Github phone app.

**Comment by viraj-s15** [comment]
It seems to be working fine for me at the moment. The changelog is auto generated via actions so probably just some delay there. 

![image](https://github.com/joke2k/faker/assets/79002760/8c820d3f-10de-4d0f-b76b-f10d7f01b5d0)
