### ISSUE TITLE
Request: add `extras_require` to `setup.py` for community providers

### ISSUE THREAD

**Issue by jamesbraza** [joke2k/faker#1951]
* Faker version: 20.0.3
* OS: macOS Ventura 13.5.2

It would be convenient if Faker defined [extras](https://stackoverflow.com/questions/52474931/what-is-extra-in-pypi-dependency) for community providers in `setup.py`.

Something like: `pip install Faker[Biology]` to match Biology from https://faker.readthedocs.io/en/master/communityproviders.html

```python
setup(
    extras_require={
        "Biology": ["faker-biology"],
    },
)
```

**Comment by stefan6419846** [comment]
Which advantage does this have over using pinned community providers manually on your side?

**Comment by jamesbraza** [comment]
For me, it keeps all requirements centralized.  For example, other places in my requirements have:

```none
SQLAlchemy[postgresql_psycopgbinary]
langchain[openai]
```

So with a extra I could have: `Faker[Biology]`
