### ISSUE TITLE
[Feature request] Support windows path for `file_path` provider

### ISSUE THREAD

**Issue by michaelCTS** [joke2k/faker#1961]
https://github.com/joke2k/faker/blob/efc91d554f30766c672fd1a9c860e0d47f804c03/faker/providers/file/__init__.py#L256-L281

At the moment, only linux (POSIX?) paths are generated by the provider. It would be great if it supported windows paths e.g

 - absolute path: `C:\Program Files\Internet Explorer\explorer.exe`
 - relative path: `Internet Explorer\explorer.exe`

**Comment by stefan6419846** [comment]
Feel free to submit a corresponding pull request.

**Comment by parsariyahi** [comment]
it's done and merge on #1963, I think we can close this issue @fcurella
