### ISSUE TITLE
Feature request: file_path extension=False to generate a path without extension

### ISSUE THREAD

**Issue by gotofritz** [joke2k/faker#1964]
```
faker.file_path(extension=None)
```
 will generate something like `/event/amount.js`

### Actual behavior

There is no way to generate a path without an extension. 

### Expected behavior

This is counter-intuitive - `exrtension? None` should mean that there is no extension. 
And it would be useful to have a way to generate a path without an extension, regardless of how it is done.

### Suggestion

In order not to break backward compatibility, can I suggest changing extension to be either None, bool or a string, with the following behaviour

* True -> same as None
* False ->  no extension
* None ->  as it is now 
* a string -> the string

Thanks

**Comment by gotofritz** [comment]
Happy to submit a patch if you like the idea

**Comment by joke2k** [comment]
Hi @gotofritz thank you for your proposal.

I was wondering if it wouldn't be more congenial to pass a list of extensions from which the generator can draw an extension, overriding the current behaviour (which extracts from a static list). 
So, we would eventually have, 
None -> current behavior (default)
list -> a new list to draw extensions from, which in your case could potentially be empty.

**Comment by gotofritz** [comment]
Yeah that would also work.

**Comment by parsariyahi** [comment]
> Hi @gotofritz thank you for your proposal.
> 
> I was wondering if it wouldn't be more congenial to pass a list of extensions from which the generator can draw an extension, overriding the current behaviour (which extracts from a static list). So, we would eventually have, None -> current behavior (default) list -> a new list to draw extensions from, which in your case could potentially be empty.

Can we use some sort of a property to implement an dynamic extention generator?
If we do this we need to pass the list of extention we want each time we need to, but having a property like ``extentions``,
and changing it base on instances isn't a better idea?
In this way we just set our extentions in our class, and if we didn't the class uses the current behavior, in other word we use a defualt value for ``extentions`` and if we change the property we use that instead.

**Comment by gotofritz** [comment]
@parsariyahi I am not entirely sure what you are proposing, but it seems to go well beyond my simple request for 'ability to generate a path without extensions'. I suggest you make a separate proposal
