### ISSUE TITLE
two cases failed on Debian buildd

### ISSUE THREAD

**Issue by yuzibo** [joke2k/faker#1969]
* Faker version: 22.0.0
* OS: Debian sid

Brief summary of the issue goes here.

### Steps to reproduce

This is local build from my packaging. I will/should update here once the issue was opened. Because I need the issue id to debian/patch

### Expected behavior

These tests pass

### Actual behavior

======================================================================
FAIL: test_iso8601_fractional_seconds_win (tests.providers.test_date_time.TestDateTime.test_iso8601_fractional_seconds_win)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/providers/test_date_time.py", line 198, in test_iso8601_fractional_seconds_win
    assert len(self.fake.iso8601()) == 19
AssertionError

======================================================================
FAIL: test_unix_time_win (tests.providers.test_date_time.TestDateTime.test_unix_time_win)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/providers/test_date_time.py", line 552, in test_unix_time_win
    assert unix_time % 1 == 0.0
AssertionError

----------------------------------------------------------------------

**Comment by yuzibo** [comment]
I wonder why not these test cases skip on linux.

**Comment by stefan6419846** [comment]
> I wonder why not these test cases skip on linux.

Could you please check what `sys.platform` yields in your case? The conditions appear to be correct at first glance: https://github.com/joke2k/faker/blob/0d9fd7aa3a5177a8dfa30cb0c66cd921608f0cc2/tests/providers/test_date_time.py#L196C25-L202

**Comment by yuzibo** [comment]
Thanks for feedback.

```python
(sid-amd64-sbuild)root@dev:/home/vimer/build/rfs/pyhton-package# python3 platform.py
linux
(sid-amd64-sbuild)root@dev:/home/vimer/build/rfs/pyhton-package# cat platform.py
#!/usr/bin/python3
import sys

print(sys.platform)
```
So could I assume these test case should be skipped on linux platfrom?
```
def test_unix_time_win(self):
        unix_time = self.fake.unix_time()
        assert isinstance(unix_time, float)
        assert unix_time % 1 == 0.0
def test_iso8601_fractional_seconds_win(self):
        assert len(self.fake.iso8601()) == 19
```

**Comment by stefan6419846** [comment]
Yes, they are expected to by skipped there according to the corresponding pytest markers. I am not sure why they are executed in your case unless you are passing non-standard parameters to your *pytest* call.

**Comment by yuzibo** [comment]
Thanks. This hints me here.

I think there is a not right way to call pytest for[ debian/rules](https://salsa.debian.org/python-team/packages/faker/-/blob/master/debian/rules?ref_type=heads#L22):

```python
override_dh_auto_test:
ifeq (,$(findstring nocheck, $(DEB_BUILD_OPTIONS)))
	set -ex ; for i in $(PYTHON3S) ; do \
		python$$i -W default -m unittest --verbose ; \
	done
endif

```

**Comment by stefan6419846** [comment]
AFAIK *pytest* markers as used here will not work correctly with the plain stdlib *unittest* runner as used in this case due to the markers being evaluated as part of *pytest* hooks by *pytest* itself. Therefore, at first glance it seems like the Debian version just does not follow the recommended testing approach for *Faker* here, which states that *tox* should be used, internally using *pytest* as mentioned before: https://github.com/joke2k/faker/blob/0d9fd7aa3a5177a8dfa30cb0c66cd921608f0cc2/tox.ini#L15-L18

**Comment by yuzibo** [comment]
It works but this is a workaround to run pytest when building, see:
https://salsa.debian.org/python-team/packages/faker/-/blame/master/debian/rules#L22

It works to run pytest on Debian autopkgtest:
https://salsa.debian.org/python-team/packages/faker/-/blob/master/debian/tests/pytest?ref_type=heads

CI results: https://salsa.debian.org/python-team/packages/faker/-/pipelines/620086

Thanks again~
