### ISSUE TITLE
Fake names based on ethnicity

### ISSUE THREAD

**Issue by avishwa23** [joke2k/faker#1974]
* Faker version:
* OS: Ubuntu 22.04 LTS

Brief summary of the issue goes here.

I am performing bias evaluation tests for my LLM (language models). While I was able to perform gender bias tests by generating fake male/female data using Faker, I couldnt find a way to generate names based on ethnicity (asian, white, black, etc) to perform ethnicity-based bias tests. Is there a way in Faker to do this?

**Comment by fcurella** [comment]
There currently is any way to do this, and TBH I don't think we should add such a feature. But you're free to implement [your own provider](https://github.com/joke2k/faker?tab=readme-ov-file#how-to-create-a-provider) from your own data.

**Comment by antik-x** [comment]
so?

`
def test_random_elements():
    from collections import OrderedDict
    faker = Faker(["zh-CN"])
    items = OrderedDict([("亚洲人", 0.25), ("非洲人", 0.25), ("欧洲人", 0.25), ("美洲人", 0.25)])
    print(faker.random_elements(items)[0])
`

**Comment by thijstriemstra** [comment]
Interesting question and answer. Looks like you made a typo and meant "There currently isn't any way to do this" @fcurella

**Comment by fcurella** [comment]
Beside the fact that it would be considered borderline racist in some
cultures, where would you even get the data?

I think this would be better served by implementing your own provider.
