### ISSUE TITLE
Idea: Add Http status codes

### ISSUE THREAD

**Issue by dancergraham** [joke2k/faker#1977]
* Faker version: 22.2.0
* OS: all

Feature suggestion : add http status code to `providers.internet` as a random integer between 100 and 599

source: https://www.rfc-editor.org/rfc/rfc9110#name-status-codes

**Comment by fcurella** [comment]
> as a random integer between 100 and 599

we can already generate a "random integer between 100 and 599" with `.pyint(100, 599)`.

But I think what you mean is returning a random choice from a set of specific codes, eg:: something from [this list](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

Feel free to submit a Pull Request, I'll be happy to review it :)

**Comment by dancergraham** [comment]
Hello, thanks for looking at this! 
I think many users of this library would not be certain that a status code can be any integer specifically from 100 to 599 (I had to look it up) so this functionality could be useful. I think limiting it to a specific list would exclude legitimate values.

This text from the rfc says that client code MUST handle the class of non-standard codes in that range - I could specify in the docstring that it includes non-standard codes: 
_HTTP status codes are extensible. A client is not required to understand the meaning of all registered status codes, though such understanding is obviously desirable. However, a client MUST understand the class of any status code, as indicated by the first digit, and treat an unrecognized status code as being equivalent to the x00 status code of that class._

**Comment by dancergraham** [comment]
The official register lists codes as "unassigned" but not "invalid" https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by fcurella** [comment]
Are you thinking of basically aliasing `.pyint(100, 599)`? something like this?

```python
def http_status_code(self):
    return self.pyint(100, 599)
```

or we could let user choose, something like:

```python
def http_status_code(self, unassigned=True):
    if unassigned is True:
        return self.pyint(100, 599)
    else:
        return self.random_choice(some_list)
```

**Comment by dancergraham** [comment]
Yes I was thinking of the former but the latter, optionally limiting it to a list of assigned codes is nice.
