### ISSUE TITLE
Faker data isn't random when called from a function

### ISSUE THREAD

**Issue by jwr0** [joke2k/faker#1984]
* Faker version: 22.4.0
* OS: Ubuntu Linux

This is probably user error, but Faker is returning non-random data when called from a function. I want it to generate random data on each function call. If this is indeed user error, what am I doing wrong?

### Steps to reproduce

```
#!/usr/bin/env python3

from faker import Faker

fake = Faker()
Faker.seed(0)

def generate_person(name=fake.name(), address=fake.address()):
    return name, address


def generate_people():
    print(generate_person(name='John Doe', address='123 Main St'))
    print(generate_person(name='Jane Doe'))
    for n in range(3):
        print(generate_person())


if __name__ == "__main__":
    generate_people()
```

### Expected behavior

I expect this to generate five people. One of whom should have a hardcoded name and a hardcoded address. One of whom should have a hardcoded name and a random address. And three of whom should have a random name and a random address. Each of the random values should be unique and not repeated.

### Actual behavior

The random values are repeated for each function call / each person. Eg:

```
('John Doe', '123 Main St')
('Jane Doe', '4759 William Haven Apt. 194\nWest Corey, CA 90152')
('Norma Fisher', '4759 William Haven Apt. 194\nWest Corey, CA 90152')
('Norma Fisher', '4759 William Haven Apt. 194\nWest Corey, CA 90152')
('Norma Fisher', '4759 William Haven Apt. 194\nWest Corey, CA 90152')
```

**Comment by stefan6419846** [comment]
This is just wrong Python usage and something which `flake8-bugbear` would complain about: You should never call methods inside parameters as this will evaluate the value only once. Nothing which is specific to *faker*.

**Comment by jwr0** [comment]
@stefan6419846 thanks for your reply. You were right, and if I move the faker calls out of the function parameters, it now works as expected.

```
#!/usr/bin/env python3

from faker import Faker

fake = Faker()
Faker.seed(0)

def generate_person(name="", address=""):
    if not name:
        name = fake.name()
    if not address:
        address = fake.address()
    return name, address


def generate_people():
    print(generate_person(name='John Doe', address='123 Main St'))
    print(generate_person(name='Jane Doe'))
    for n in range(3):
        print(generate_person())


if __name__ == "__main__":
    generate_people()
```

Output:
```
('John Doe', '123 Main St')
('Jane Doe', '48764 Howard Forge Apt. 421\nVanessaside, VT 79393')
('Emily Blair', 'PSC 5781, Box 5659\nAPO AP 27302')
('Karen Grimes', '60975 Jessica Squares\nEast Sallybury, IA 19178')
('Jo Miller', '48418 Olsen Plains Apt. 989\nSeanfurt, MD 75952')
```
