### ISSUE TITLE
Questions Documentation

### ISSUE THREAD

**Issue by lozik4** [joke2k/faker#1987]
* Faker version: v22.7.0
* OS: MacOS 14.3
* Python 3.11

How often update documentation on https://faker.readthedocs.io/
Because when use `make html`
`from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' 
`

**Comment by lozik4** [comment]
@stefan6419846 Thanks for the information

**Comment by fcurella** [comment]
Thank you for the report and for looking into this! It's fixed in https://github.com/joke2k/faker/commit/d4401f4dc31e208072750b04c0d00322601d01df
