### ISSUE TITLE
`pydecimal(left_digits=14)` produced value with 13 left digits

### ISSUE THREAD

**Issue by alexei** [joke2k/faker#1992]
* Faker version: 22.6.0
* OS: macOS, Linux

I've encountered a situation where `pydecimal` appears to not respect `left_digits`:

```python
from faker import Faker

fake = Faker()
Faker.seed(0)

fake.pydecimal(left_digits=14, right_digits=2)  # Decimal("5550397399547.96")
```

"5550397399547.96" has 13 left digits. How is this possible?

Note I found this while running a suite of a couple of thousands of tests. One of the tests failed because the value produced did not have the expectated number of digits. If I run the failing test in isolation, it passes i.e. that specific value doesn't get generated. I'm only getting this when I run the whole suite.

**Comment by alexei** [comment]
I have found another case where

```python
fake.pydecimal(left_digits=8, right_digits=3)
```

produced the value:

```python
Decimal("-3337220.745")
```

What can I do to debug this?

**Comment by stefan6419846** [comment]
You should probably try to find a seed which generates a broken value each time. With this, debugging `pydecimal` itself should be possible.

**Comment by alexei** [comment]
Thanks for the suggestion. I found 15:

```python
from faker import Faker
fake = Faker()
fake.seed_instance(15)
fake.pydecimal(left_digits=8, right_digits=3)  # Decimal('8023002.531')
```

**Comment by alexei** [comment]
Upon further inspection, I found it's because it generates "08023002" for `left_number`. I'll see about a fix.

**Comment by alexei** [comment]
I opened a MR at https://github.com/joke2k/faker/pull/1994
