### ISSUE TITLE
Add ability to define type for columns in csv

### ISSUE THREAD

**Issue by gotofritz** [joke2k/faker#2000]
* Faker version:
* OS:

Currently the signature for the csv provider allows to define the name of columns, but not their content

``` python
def csv(
        self,
        header: Optional[Sequence[str]] = None,
        data_columns: Tuple[str, str] = ("{{name}}", "{{address}}"),
        num_rows: int = 10,
        include_row_ids: bool = False,
    ) -> str:
```

Can I suggest adding another argument, `value_types`, which would allow to define types for columns?

``` python
def csv(
        self,
        header: Optional[Sequence[str]] = None,
        data_columns: Tuple[str, str] = ("{{name}}", "{{address}}"),
        num_rows: int = 10,
        include_row_ids: bool = False,
        value_types: Optional[TypesSpec] = None,
    ) -> str:
```

* If len(value_types) > len(data_columns), extra value_types are discared
* If len(value_types) < len(data_columns), the missing value types at end are assumed to be whatever is used now as default

Happy to submit a PR if you like the idea.

**Comment by stefan6419846** [comment]
How do you plan on passing the data types? By using strings referencing the corresponding generator method of *faker*?

**Comment by gotofritz** [comment]
Actually I had misunderstood the documentation, that's what `data_columns` does. It's just a bit unintuitive but I guess it's because of historical reasons. Closing.
