### ISSUE TITLE
Updating land_coords used in local_latlng() to cover every supported country code

### ISSUE THREAD

**Issue by Beblu** [joke2k/faker#2001]
* Faker version: 23.3.0
* OS: macOS Ventura 13.6.4

When using faker.local_latlng method I thought that it has exported locations from geonames.org for every possible country code (which can be generated by faker itself), but it turned out that we have a list of possible locations in 
`faker/faker/providers/geo/__init__.py::Provider:land_coords` 

Hard-coded values are not the problem though, but the lack of locations for some countries (like mentioned below Grenada (GD)). 

Is it possible to update land_coords with additional locations?

### Steps to reproduce

x= faker.local_latlng(country_code="GD")

### Expected behavior

Something similar to:
X is ('12.722', '-61.3729', 'Grenville', 'GD', 'Grenada')

### Actual behavior

X is None

**Comment by lozik4** [comment]
I added ("12.12278", "-61.62498", "Grenville", "GD", "America/Grenada"),
Info from https://www.geonames.org/3580236/grenville.html
