### ISSUE TITLE
Wrong digit separator in ru_RU locale.

### ISSUE THREAD

**Issue by wchistow** [joke2k/faker#2006]
Faker version: 24.2.0

In Russia (and, maybe, in some other countries), a space is used as a separator of digits, not a dot. But in the Faker library (for example, in the `pricetag()` method) it's a dot ever in `ru_RU` location:

```py
>>> from faker import Faker
>>> fake = Faker('ru_RU')
>>> print(fake.pricetag())
47.116,67 р.
# ^
```

The result is `47.116,67 р.`, but it should be `47 116,67 р.`

**Comment by fcurella** [comment]
Thanks for the report! Could you submit a Pull Request?

**Comment by wchistow** [comment]
@fcurella, I think, we need to change this [line](https://github.com/joke2k/faker/blob/master/faker/providers/currency/ru_RU/__init__.py#L174) from
```py
price_formats = ["#,##", "%#,##", "%##,##", "%.###,##", "%#.###,##"]
```
to
```py
price_formats = ["#,##", "%#,##", "%##,##", "% ###,##", "%# ###,##"]
```

but I don't know, how to write tests for this feature.
