### ISSUE TITLE
`.prefix`/`.suffix` returns a tuple instead of a single value

### ISSUE THREAD

**Issue by akx** [joke2k/faker#202]
`.prefix` (and `.suffix`) can occasionally return a tuple of values instead of a single value when `prefixes_male` and `prefixes_female` (or `suffixes_*`) are present in the provider.

[See here for the code responsible.](https://github.com/joke2k/faker/blob/2af330e09d84306d10921fed00ad2e5cc8e3d36f/faker/providers/person/__init__.py#L93-L94)

I wasn't sure if this was intentional (it's documented to do so -- then again, the documentation is autogenerated, isn't it?), so I didn't make a PR yet, but it's certainly counterintuitive.

**Comment by fcurella** [comment]
Hi @akx, thanks for your report.

I believe it is a bug, but I'd like @joke2k to confirm that returning a tuple is not intended behavior

**Comment by laruellef** [comment]
Definitely a bug, in version 0.4.x it was returning a strong and now in version 0.5.x it is returning a tuple, this is breaking our scripts... can u fix pls?

**Comment by fcurella** [comment]
@akx can you submit a PR?

**Comment by foxx** [comment]
Just hit this problem, any idea when it's going to be released?
