### ISSUE TITLE
date_time_this_year provides non existent date

### ISSUE THREAD

**Issue by jon-parise** [joke2k/faker#2027]
* Faker version: 24.4.0
* OS: Mac, Linux (Ubuntu)

Usage of `date_time_this_year` can sometimes choose a date that does not exist. It throws an exception `pytz.exceptions.NonExistentTimeError: 2024-03-10 02:11:40.454602`

This is because this is the time when clocks changed for daylight savings. Clocks rolled back at 2AM, so no times in that hour exist.

### Steps to reproduce

1. Use `date_time_this_year` repeatedly, eventually it will pick a bad date.

### Expected behavior

The library should not provide datetimes that do not exist.

### Actual behavior

The library provided a datetime that does not exist

**Comment by esass10** [comment]
Hi, I am interested in taking this issue on. Can this be assigned to me?
