### ISSUE TITLE
Slovak jobs in 24.14.0

### ISSUE THREAD

**Issue by mtelka** [joke2k/faker#2034]
* Faker version: 24.14.0
* OS: N/A

I looked at the list of Slovak jobs in `faker/providers/job/sk_SK/__init__.py` and here are my observations (I'm native Slovak speaker):

I suggest to remove "Urobiť" (it is not a job), or maybe change it to "Robotník" (Worker)?

These should be changed:
- "Vedec dát" to "Dátový vedec",
- "Diagnostický rádiograf" to "Diagnostický rádiológ" (or maybe simply "Rádiológ"),
- "Optometristu" to "Optometrista",
- "Vybavovač poistných udalostí" to "Likvidátor poistných udalostí".

These sounds strange (no idea what all of them are supposed to be):
- "Učiaci sa mentor",
- "Učiteľ, prvé roky / pred",
- "Výdajný optik",
- "Vizuálny obchodník",
- "Angličtina ako lektorka cudzieho jazyka",
- "Angličtina ako učiteľka druhého jazyka",
- "Dospelý poradenský pracovník",
- "Dôstojník obchodného námorníctva",
- "Vedúci reklamného účtu",
- "Priemyselný kupujúci",
- "Záznamník bahna".

I believe "Docent" and "Dodávateľ" are not jobs.

These are not in Slovak language:
- "Professor Emeritus",
- "Programme researcher, broadcasting/film/video",
- "Programmer, applications",
- "Programmer, multimedia",
- "Programmer, systems",
- "Proofreader",
- "Production assistant, radio",
- "Production assistant, television",
- "Production designer, theatre/television/film",
- "Production engineer",
- "Production manager",
- "Psychiatric nurse",
- "Psychiatrist",
- "Psychologist, clinical",
- "Psychologist, counselling",
- "Psychologist, educational",
- "Psychologist, forensic",
- "Psychologist, occupational",
- "Psychologist, prison and probation services",
- "Psychologist, sport and exercise",
- "Police officer".

**Comment by fcurella** [comment]
Feel free to submit a Pull Request :)
