### ISSUE TITLE
Not getting type hint sugesstion in vs code 🙏🙏🙏

### ISSUE THREAD

**Issue by RanaRana10** [joke2k/faker#2035]
* Faker version: latest Faker               24.14.0

Here my question is after i defines, 

fake = Faker() 

and then i try to use fake.name, fake.address etc, i though when i write the dot(.) i should get some type hint sugestion of list parameter or fun or so on which i thought we should see it, 

![image](https://github.com/joke2k/faker/assets/167146554/c3770f13-466c-46bf-83e3-a0af9164dae9)

![image](https://github.com/joke2k/faker/assets/167146554/fe21c493-64a7-4960-ba18-5fa3e97cd367)

see i am not getting any sugesstion but when i use other library or suppose i am using, the random 

![image](https://github.com/joke2k/faker/assets/167146554/5d632fc1-cdd7-4ed5-a50b-ecea8c1e568f)
see like this case i am getting sugesstion , like this, how i can get type hint when using this faker libarry in my vs code, as for otehr libaryr i use i always see the type hint

**Comment by stefan6419846** [comment]
With #1939, *faker* started providing a `proxy.pyi` stub file which should be picked up by your IDE in theory.

**Comment by stefan6419846** [comment]
Could you please try to update to the latest version and try again?

**Comment by stefan6419846** [comment]
Version 24.14.1 has been released already including the corresponding fix: https://github.com/joke2k/faker/blob/refs/tags/v25.0.0/CHANGELOG.md#v24141---2024-04-28

**Comment by mishamsk** [comment]
I didn’t test 24.14.1, but 25.0.0 doesn’t package pyi file

**Comment by stefan6419846** [comment]
I do not know how the release bundles are built, but running the usual `python -m build .` locally with the latest code generates a wheel file which indeed includes the `faker/proxy.pyi` file. Thus we probably have to wait for @fcurella to clarify this.

**Comment by mishamsk** [comment]
yeah, this works too `pip install git+https://github.com/joke2k/faker.git` which is more or less the same. However, downloading the latest version from pipit clearly shows that sdist includes the stub, but wheel doesn't:
![CleanShot 2024-05-01 at 15 11 49@2x](https://github.com/joke2k/faker/assets/5206955/df8a4024-226c-42a4-a938-6e9739781b4d)

tbh I've never used vanilla python build backend, so not sure why this is happening. My best guess is that it should also be included here: https://github.com/joke2k/faker/blob/7f5dc148afdcf06dee08381a4f85e082da2346b4/setup.py#L66

**Comment by RanaRana10** [comment]
i still not understand how i can allow the type sugesstion in vs code like i want to see the sugession when write 

fake.name() fake.addre it should show a sugesstion fake.address like autocomplite, but i dont get any , i want to say this problem, can you say more
![image](https://github.com/joke2k/faker/assets/167146554/20948b8b-9789-4500-b62d-218abf00daf1)
i wish here should show a sugession like .address

**Comment by RanaRana10** [comment]
see what i say why the type hint need, see this example,

![image](https://github.com/joke2k/faker/assets/167146554/84797786-de02-41df-8068-9757e5b9c3f1)

when i move my mouse cursor to this i expect this will show "int" return , but it always shows any, this maybe need to solve, as actual returns need to show here

**Comment by stefan6419846** [comment]
I just had a look at the wheel and the file seems to be part of it now:

```
Archive:  Faker-25.0.1-py3-none-any.whl
  inflating: faker/__init__.py       
  inflating: faker/__main__.py       
  inflating: faker/cli.py            
  inflating: faker/config.py         
  inflating: faker/documentor.py     
  inflating: faker/exceptions.py     
  inflating: faker/factory.py        
  inflating: faker/generator.py      
  inflating: faker/proxy.py          
  inflating: faker/proxy.pyi         
  inflating: faker/py.typed          
  inflating: faker/typing.py         
  inflating: faker/contrib/__init__.py  
[...]
```

**Comment by RanaRana10** [comment]
i am not good enough in python, i dont understand the things you have said, 
i ask you , do you understand what things i means to say here, 





like this i want to say in the docs of faker it says a lot of things available, like in the official docs it shows alot of list but when i do this

from faker import Faker
fake = Faker()

and then use fake, is this here any issue, or providers what it say, i mostly want for type hint, as one example is, 

a fun which returns string, and after write the fun when i write (fun()). then here shows a lot of string related type hint, when a fun returns a int, it shows int related type hint, like this, so this will mroe helpful, that why i am saying about the type hint in this faker


![image](https://github.com/joke2k/faker/assets/167146554/68c5a5fb-377a-4c84-b414-b21db612bd06)
![image](https://github.com/joke2k/faker/assets/167146554/95a60f18-1b9f-4e5b-88df-d637aa2e48e1)


so that if vs code give sugesstion and we can know what a fun will return what kind of obj, then we can perform the operation on this obj easily



![image](https://github.com/joke2k/faker/assets/167146554/9d734ace-bb15-4237-849f-cc243ff60dd1)


like this case i want to get the lower letter, so for this, as when i press . i dont get any type hint , so i mistakes sometime wehre to give the lower()
as 2nd and 3rd line username gives same expected reasult which is to use

**Comment by stefan6419846** [comment]
Please upgrade to the latest version and try again. In theory, it should work now as the required file is being shipped now.

**Comment by fcurella** [comment]
@RanaRana10  you can Faker's version with `Faker.VERSION`:

```python
>>> import faker
>>> faker.VERSION
'25.0.1'
```

**Comment by RanaUniverse** [comment]
Owo boss, Thanks you all ❤❤❤

it really works as we expected, 
![image](https://github.com/joke2k/faker/assets/142967497/4e228a6e-9e13-4ed9-bfa5-36f1dbbd4dd9)

![image](https://github.com/joke2k/faker/assets/142967497/fea44fc6-3d95-4915-86c9-033ba23284bf)

it really make our code experience so much speed 😘😘😘
it works so much easy now, i never thought in so little time you have fixed this issue in just a week, it is really a so easy to use library now☑☑☑


and like this type hint, is really so so so much helpful, i cannot express my enjoyment with this, 

![image](https://github.com/joke2k/faker/assets/142967497/f55adaa7-ca01-4dd3-8950-de55ce703944)

![image](https://github.com/joke2k/faker/assets/142967497/80ecc021-4439-42f9-81ec-acf02656be93)

this type of hint direct in the code editor is really so much easy ❤❤❤
