### ISSUE TITLE
Type annotations on `md5`, `sha1`, and `sha256` should be overloaded

### ISSUE THREAD

**Issue by samueljsb** [joke2k/faker#2046]
* Faker version: 25.0.1
* OS: all

The docstrings for these functions state:

> If raw_output is False (default), a hexadecimal string representation of the MD5 hash
> will be returned. If True, a bytes object representation will be returned instead.

But the type annotations do not reflect this:

```console
$ cat t.py
import faker

fake = faker.Faker()

x = fake.md5(raw_output=False)
reveal_type(x)

y = fake.md5(raw_output=True)
reveal_type(y)

$ mypy t.py
$ mypy t.py
t.py:6: note: Revealed type is "Union[builtins.bytes, builtins.str]"
t.py:9: note: Revealed type is "Union[builtins.bytes, builtins.str]"
Success: no issues found in 1 source file
```

The revealed types ought to be `builtins.str` and `builtins.bytes` respectively.

I believe this can be achieved by overloading the type annotations on those methods (using `typing.overload`.

I would be happy to open a PR to make those changes, if that would be welcome?

**Comment by fcurella** [comment]
Thank you so much, that would be wonderful!

**Comment by samueljsb** [comment]
I've tried to do this but I'm having trouble with the stub files. They don't seem to match the type annotations I put in the actual Python modules (even after running the stub generation script) and manually editing them gets undone when I run the linters.

**Comment by steve-mavens** [comment]
If I'm still in time to catch this train - the same applies to uuid4(), which has a return type of `str | bytes | UUID`, and the return type is similarly controlled by a parameter.

**Comment by fcurella** [comment]
the `generate_stubs.py` script will need to be updated to detect overloads, but [`typing.get_overloads()`](https://docs.python.org/3/library/typing.html#typing.get_overloads) is only available in Python 3.11, and we need to support at least 3.8.

**Comment by steve-mavens** [comment]
It's in [typing_extensions](https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.get_overloads) if that's any help for pre-3.11. The trouble is it that pre-3.11 it only detects overloads defined using `typing_extensions.overload`, not `typing.overload`.

**Comment by fcurella** [comment]
I dont see any issues with falling back to `typing_extension` on <3.11. Do you want to try to update `generate_stubs.py` to use `get_overloads()`?
