### ISSUE TITLE
passport_owner() generates different gender names in wrong order

### ISSUE THREAD

**Issue by Bikbai** [joke2k/faker#2061]
* Faker version: "25.8.0"
* OS: windows 11

Trying to generate female names in cyrilic. First component should be family, last name according to ICAO DOC 9303

### Steps to reproduce

`from faker import Faker
fake = Faker('ru-RU')
print(fake.passport_owner(gender='F'))`

### Expected behavior

('Белоусова', 'Лариса')

### Actual behavior

('Лариса', 'Белоусов')

**Comment by stefan6419846** [comment]
The corresponding provider is only implemented for the US: https://github.com/joke2k/faker/tree/master/faker/providers/passport Feel free to submit a localized version for Russia.
