### ISSUE TITLE
fake.time_delta is always datetime.timedelta(0)

### ISSUE THREAD

**Issue by amingilani** [joke2k/faker#2077]
* Faker version: all
* OS: all

I'm not sure I understand why this is the case. But the expected behvaior as described in the [documentation](https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.time_delta) is that `fake.time_delta()` always returns `timedelta(0)`. I would expect this to be randomized like all the other fake values we generate. If this is intentional, please let me know. I couldn't discussions around this behavior.

### Actual behavior

```python
from faker import Faker
Faker.seed(0)
fake = Faker()
for _ in range(5):
  fake.time_delta()
 
datetime.timedelta(0)
datetime.timedelta(0)
datetime.timedelta(0)
datetime.timedelta(0)
datetime.timedelta(0)
```

### Expected behavior

The result should be

```python
datetime.timedelta(days=8041, seconds=60445, microseconds=593254)
datetime.timedelta(days=-9448, seconds=15856, microseconds=620945)
datetime.timedelta(days=7332, seconds=68815, microseconds=994962)
datetime.timedelta(days=-1456, seconds=6174, microseconds=787389)
datetime.timedelta(days=-1833, seconds=11987, microseconds=179397)
```

### Workaround

```
from faker import Faker
Faker.seed(0)
fake = Faker()
for _ in range(5):
  fake.date_time() - fake.date_time()

datetime.timedelta(days=8041, seconds=60445, microseconds=593254)
datetime.timedelta(days=-9448, seconds=15856, microseconds=620945)
datetime.timedelta(days=7332, seconds=68815, microseconds=994962)
datetime.timedelta(days=-1456, seconds=6174, microseconds=787389)
datetime.timedelta(days=-1833, seconds=11987, microseconds=179397)
```

I am more than happy to submit a patch if this needs to be fixed.

**Comment by amingilani** [comment]
> This has been changed in #907 and only occurs when running this without `end_datetime` as it seems to choose a seconds value in the range `[0, datetime.now() - datetime.now()]` in this case, which will basically always map to `[0, 0]` and thus always generate `0`:

Thanks for the reply and the additional context @stefan6419846!

While #907 does improve the behavior with `end_datetime`. I still don't think the behavior when trying to generate a random `time_delta` should result in non-random values. If an `end_datetime` is required to output random timedeltas, then it should be a required parameter. But I don't it should be required parameter to get random timedeltas.

As an example, this wouldn't be considered acceptable:

```python
>>> for _ in range(5):
>>>     print(fake.pyint())
0
0
0
0
0
```

**Comment by fcurella** [comment]
I think we need to change the signature of `timedelta` to make `end_datetime` mandatory.

**Comment by amingilani** [comment]
I can submit a patch for that.
