### ISSUE TITLE
'Generator' object has no attribute 'random_good_service_adjective_chain'

### ISSUE THREAD

**Issue by Arbureva** [joke2k/faker#2087]
* Faker version: Latest
* OS: MacOS

'Generator' object has no attribute 'random_good_service_adjective_chain'

### Steps to reproduce
use fake.random_good_service_adjective_chain() function

### Expected behavior

random_good_service_adjective_chain should be success

### Actual behavior

X is not work

**Comment by stefan6419846** [comment]
Could you please clarify by some code? Judging from the search results at https://github.com/search?q=repo%3Ajoke2k%2Ffaker%20random_good_service_adjective_chain&type=code, this should only work if you use the `fil_PH` locale and maybe should even be internal to avoid confusion.

**Comment by Arbureva** [comment]
thank you
