### ISSUE TITLE
slug() - returns an empty string in some locales

### ISSUE THREAD

**Issue by kymckay** [joke2k/faker#2103]
* Faker version: 28.4.1
* OS: Mac

When using certain locales (e.g. `jp_JP`), the `slug` fake returns an empty string. I had a quick look and this is probably because the `slugify` decorator disallows unicode characters (which makes sense) and the fake is using the `text` fake under the hood - not anticipating that it is going to return unicode characters.

### Steps to reproduce

1. `fake = Faker("jp_JP")`
2. `fake.slug()`

### Expected behavior

The `slug` fake should never return an empty string

### Actual behavior

The `slug` fake returns an empty string in some locales.

**Comment by Pandede** [comment]
What is the expected behaviour of `slug()` in locale `ja_JP`, while the slug can only be composed by English characters?

**Comment by kymckay** [comment]
I think the best effort behaviour here would be to return a slug with English characters, so it'd return an ascii slug even though it doesn't contain Japanese characters. This mimics the fallback behaviour of locale providers in general.

This fake is particularly problematic when in multi locale mode - where you only sometimes get an empty string because of certain locales. You may want to generate multi-locale text, but to still generate valid slugs without instantiating a separate generator only set to English for that purpose.

**Comment by Pandede** [comment]
> I think the best effort behaviour here would be to return a slug with English characters, so it'd return an ascii slug even though it doesn't contain Japanese characters. This mimics the fallback behaviour of locale providers in general.
> 
> This fake is particularly problematic when in multi locale mode - where you only sometimes get an empty string because of certain locales. You may want to generate multi-locale text, but to still generate valid slugs without instantiating a separate generator only set to English for that purpose.

This is a fair point, maybe make `slug()` always generate texts in locale `en_US` regardless of the assigned locale?
