### ISSUE TITLE
Wrong pattern for Greek SSNs

### ISSUE THREAD

**Issue by nepiskopos** [joke2k/faker#2121]
https://github.com/joke2k/faker/blob/8cee450e10463c0360e50e2b56da4ecfea1dd513/faker/providers/ssn/el_GR/__init__.py#L70

* Faker version: v30.3.0
* OS: Linux

### Expected behavior

Proper format / pattern should be "%d%m%y#####".

### Actual behavior

Current format / pattern is "%d%m%y####".

**Comment by Abdujabbar** [comment]
It looks like that, and these documents can prove this:

https://learn.microsoft.com/en-us/purview/sit-defn-greece-social-security-number#pattern

https://docs.trellix.com/bundle/data-loss-prevention-11.10.x-classification-definitions-reference-guide/page/GUID-113631C2-C1E5-41FF-8794-B22A90EE2E61.html

**Comment by nepiskopos** [comment]
> It looks like that, and these documents can prove this:
> 
> https://learn.microsoft.com/en-us/purview/sit-defn-greece-social-security-number#pattern
> 
> https://docs.trellix.com/bundle/data-loss-prevention-11.10.x-classification-definitions-reference-guide/page/GUID-113631C2-C1E5-41FF-8794-B22A90EE2E61.html

Exactly, one of the cited sources states that a Greek SSN consists of

- Six digits as date of birth YYMMDD
- Four digits
- a check digit

So, proper format / pattern in faker should be "%d%m%y#####", having 5 digits after date of birth instead of 4 (which is the current behavior).

**Comment by stefan6419846** [comment]
You probably want to update/fix the existing links inside the current code in this case as well.

**Comment by nepiskopos** [comment]
I apologize, but the issue is invalid. I misunderstood the way Luhn algorithm creates the check digit. The current behavior is correct.

**Comment by nepiskopos** [comment]
I apologize, but the issue is invalid. I misunderstood the way Luhn algorithm creates the check digit. The current behavior is correct.
