### ISSUE TITLE
faker.providers: is this really needful to keep in this package

### ISSUE THREAD

**Issue by RanaUniverse** [joke2k/faker#2125]
* Faker version: faker             30.8.0
* OS: Ubuntu 24.04

Brief summary of the issue goes here.

![image](https://github.com/user-attachments/assets/5124dfca-450e-4cb3-9104-6a82ce032935)
I was trying to learn how to use faker library in python, so first went to the pypi page and trying checking copy paste the code example given there, so when i come to this example and then i copy paste this in my vs code and i find no problem, but see the below image, when i exactly copy paste the code from the website into my main.py then when i run it shows a random ip address, which i understand as the docs says it will generate the fake ip address.

![image](https://github.com/user-attachments/assets/c31cfecc-c91f-4a8a-b64e-ef5ab814e24e)

And after i see the code i didn't understand why the **from faker.providers import internet**

and i didnot understand what is the use case of this line, and why i need to add it liek thsi, **fake.add_provider(internet)**

so i just comment this two line form the example code and then copy paste this in a new main2.py file and when i run , i found the same type result, i am also getting the fake ip address from this library as seen in the below image:

![image](https://github.com/user-attachments/assets/7ee554a4-c5ec-4d95-82a0-85ccacba8358)

😢😢😢😢😢😢😢😢😢😢😢😢
😢😢😢😢😢😢😢😢😢😢😢😢
😢😢😢😢😢😢😢😢😢😢😢😢

Please friends say me why i need to use this 

*** 
from faker.providers import internet
fake.add_provider(internet)
***

Please say me when i will use this and when i will not use this, i am just confused in the beginning of this library use.
Please say if you can explain in little words,

**Comment by stefan6419846** [comment]
I do not understand the title, but as you saw, the README seems to be a bit outdated and the providers usually are registered automatically.

Feel free to submit a corresponding PR.

**Comment by stefan6419846** [comment]
You should not have to use the `add_provider` calls unless you are using external providers - the bundled providers are already available out of the box.

The rendered representation on PyPI usually is the README of the package and not the actual documentation, although it might include some basic information. You should usually have a look at the linked documentation at https://faker.readthedocs.io/en/stable/index.html (although this uses the same README/text on the index page).

I have been talking about submitting a pull request here on GitHub. Nevertheless, the README seems just a big misleading here and I am not sure whether it is worth it to make this more explicit.

**Comment by RanaUniverse** [comment]
Now i understand what you say, but i am a beginner, i dont know much about pull requests and so on, so i think not to do any chagnes here, as i fear to do wrong things here, 

But thanks for the docs link you send...

**Comment by laziest-coder** [comment]
@stefan6419846 I've created [PR](https://github.com/joke2k/faker/pull/2127) for this issue, could you please review it?

**Comment by RanaUniverse** [comment]
i don't understand what to review 😁😁😁
i am not a programmer i have zero idea of what u say, what do u change and what it will impact 🤔

**Comment by fcurella** [comment]
That specific example is meant to show how you can add your own custom providers. You wouldn't need to call `.add_provider` for providers already included with faker.

I do agree the example should be rewritten with an hypotetical custom provider. Something like:

```python
    from faker import Faker
    from mymodule import MyProvider

    fake = Faker()
    fake.add_provider(MyProvider)
    print(fake.my_method())
```
