### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'mobile_number'

### ISSUE THREAD

**Issue by r3x5ur** [joke2k/faker#2145]
* Faker version: 33.1.0
* OS: win10

AttributeError: 'Generator' object has no attribute 'mobile_number'

### Steps to reproduce
- **Running this demo will get an error AttributeError**

```python
from faker import Faker
# from faker.providers import phone_number

fake = Faker('zh_CN')
# fake.add_provider(phone_number)

print(fake.mobile_number())
```

### Expected behavior

**Print fake mobile phone number**

### Actual behavior

AttributeError

**Comment by r3x5ur** [comment]
**Release the following two lines of comments and the result will be the same.**
```python
# from faker.providers import phone_number
# fake.add_provider(phone_number)
```

**Comment by r3x5ur** [comment]
**Stack info**
```bash
Traceback (most recent call last):
  File "E:\Workspace\tests\tmp.py", line 7, in <module>
    print(fake.mobile_number())
  File "E:\Workspace\venv\lib\site-packages\faker\proxy.py", line 130, in __getattr__
    return getattr(self._factories[0], attr)
AttributeError: 'Generator' object has no attribute 'mobile_number'
```

**Comment by r3x5ur** [comment]
Find a usable example:
```python
from faker import Factory, Faker

fake: Faker = Factory.create('zh_CN')

print(fake.phone_number())
```

**Comment by stefan6419846** [comment]
The generator is apparently only implemented for the `en_PH` locale at the moment: https://github.com/search?q=repo%3Ajoke2k%2Ffaker%20mobile_number&type=code If you need support for it within the `zh_CN` locale, feel free to submit a corresponding PR.

**Comment by r3x5ur** [comment]
I just discovered that I can use phone_number instead of mobile_number
