### ISSUE TITLE
.text() returns incorrect language for ('uk_UA') local

### ISSUE THREAD

**Issue by bestblast** [joke2k/faker#2146]
* Faker version: Faker 14.2.1
* OS: linux

If try to get text in uk_UA localization, text was not in ukraininan language. 

### Steps to reproduce
$ python3
Python 3.6.8 (default, Apr 24 2024, 21:36:10)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from faker import Faker
>>> fake = Faker('uk_UA')
>>> fake.text()
'Vel harum qui dolorem asperiores incidunt aliquam minima. Quis quae id voluptates aliquam. Ad suscipit voluptatum soluta.\nCum consequuntur quia nostrum quis. Cumque eveniet illo id sed earum.'

### Expected behavior

The text should be in ukrainian language.

### Actual behavior

But text is not ukrainian

**Comment by stefan6419846** [comment]
Python 3.6 is EOL for over three years now and Faker 14.2.1 (released in September 2022) is highly outdated. Please update to the latest versions. Faker provides the corresponding localization since version 23.1.0 (https://github.com/joke2k/faker/commit/0708af7e4d0332b65496ba34e20bf8d17c07f84a).

**Comment by bestblast** [comment]
Thanks! 

I`ve already sorted out that I have too old py version. I`ve tested installing the packet on the 3.12.5 and got an actual version of Faker.

This issue can be closed.
