### ISSUE TITLE
Cannot subclass due to bad metaclass magic

### ISSUE THREAD

**Issue by foxx** [joke2k/faker#230]
It's impossible to inherit from the Faker class due to bad metaclass magic;

``` py
class Faker2(Faker):
    pass

  File "/vagrant/server/app/api/tests.py", line 44, in <module>
    class Faker2(Faker):
TypeError: Error when calling the metaclass bases
    first argument must be callable
```

**Comment by fcurella** [comment]
`faker.Faker` is not a class, but a class method. `faker.Faker` is just another name for `faker.factory.Factory.create` (I agree this is confusing and a little mind-bending).

I think the solution to your issue is to subclass from `faker.factory.Factory`:

```python
from faker import Factory

class Faker2(Factory):
    pass
```

Let me know if this solution works for you.

**Comment by foxx** [comment]
There are some more problems, again due to the way this library has been constructed.

The following is an instruction from the README, which fails to work;

```
>>> from faker.providers import BaseProvider
ImportError: No module named providers
```

There is *far* too much import abuse and magic going on, this project is a good idea but the implementation is very broken. Are there any plans to re-structure this in a pythonic way?

**Comment by fcurella** [comment]
Hi @foxx 

What version of faker is giving you `ImportError: No module named providers`? I've just tried on master and it seems to work for me (I've tried Python 2.7 and Python 3.4)

**Comment by fcurella** [comment]
Re: refactoring, I don't like all the magic either, and I'd like refactoring it as well, but I haven't made any plans on how to accomplish that, yet.
