### ISSUE TITLE
Should date_time_between() accept an optional timezone parameter

### ISSUE THREAD

**Issue by simonv3** [joke2k/faker#232]
If you're working with timezones, it'd be nice is these randomly generated dates had an optional parameter for adding a timezone to these dates.

Would that be a new method or just adding a new **kwargs parameter to the existing method?

**Comment by j0hnsmith** [comment]
Implemented in https://github.com/joke2k/faker/commit/3da7fd3109e317025e033fb95260c0032668ae0e

@fcurella close?

**Comment by fcurella** [comment]
yes, thank you for pointing it out :)

closed in 3da7fd3
