### ISSUE TITLE
Faker should provide company VAT numbers

### ISSUE THREAD

**Issue by kivipe** [joke2k/faker#239]
It would be nice if faker could provide company VAT numbers. More information about VAT codes is in Wikipedia: https://en.wikipedia.org/wiki/VAT_identification_number

**Comment by fcurella** [comment]
VATs are very locale specific. We are going to rely on contributors to add locale-specific VAT providers.

Maybe you could submit a PR be the first one :)

**Comment by kivipe** [comment]
Hi,

Here is a commit I made for generating Finnish VAT Identification Numbers. I am not sure if function names are good. Could you have a look before I make a PR?

https://github.com/kivipe/faker/commit/31af7ad0279cb08fb76d9a3d10991a1ce4ea20da

**Comment by fcurella** [comment]
Hi @kivipe 

looks good, the only thing i'd change is renaming the `company_vatin` method to just `company_vat`
