### ISSUE TITLE
Provider module resolution error of the faker module resolved working with the egg file

### ISSUE THREAD

**Issue by d3prof3t** [joke2k/faker#240]
I was not able to get my fake-factoy0.5.0 working in my project  and it was throwing errors.

Installation:->
============
[saurabh@d3prof3t ~] $ sudo easy_install fake_factory
[sudo] password for saurabh: 
Searching for fake-factory
Reading https://pypi.python.org/simple/fake_factory/
Best match: fake-factory 0.5.0
Downloading https://pypi.python.org/packages/source/f/fake-factory/fake-factory-0.5.0.tar.gz#md5=d62fb4ebe5606c49247e658cc8f6d178
Processing fake-factory-0.5.0.tar.gz
Writing /tmp/easy_install-ooVVRt/fake-factory-0.5.0/setup.cfg
Running fake-factory-0.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ooVVRt/fake-factory-0.5.0/egg-dist-tmp-nB3JAC
warning: no files found matching '*.md'
Adding fake-factory 0.5.0 to easy-install.pth file
Installing faker script to /usr/bin

Installed /usr/lib/python2.7/site-packages/fake_factory-0.5.0-py2.7.egg
Processing dependencies for fake-factory
Finished processing dependencies for fake-factory

Error Log:->
=========
>>> from faker import Factory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/faker/__init__.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/faker/factory.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/faker/config.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/faker/utils/loading.py", line 24, in find_available_locales
  File "build/bdist.linux-x86_64/egg/faker/utils/loading.py", line 7, in list_module
OSError: [Errno 20] Not a directory: '/usr/lib/python2.7/site-packages/fake_factory-0.5.0-py2.7.egg/faker/providers/address'
>>> 

So, while working in a virtualenv I followed the following steps to make this work.
Step 1=>  setup an virtualenv
I had included the fake_factory package installation. And it happened succesfully.

Step 2=>  easy_install or pip install --egg 
Then I made the python egg file of the package from setup.py

Step 3=>  To verify I imported the the Factory module from faker. It worked.

** for generating egg=> python setup.py bdist_egg
After these steps I got it working in my virtenv :)
Do have a look at this, hope it solves it.:)
Cheers:)

**Comment by fcurella** [comment]
hi @d3prof3t 

does this still happen with the new release, v0.5.1?

**Comment by d3prof3t** [comment]
hi @fcurella 

No, its working perfectly fine. Thanks :+1:  :

**Comment by fcurella** [comment]
Awesome! Closing as this is fixed.
