### ISSUE TITLE
en_US SSN provider generates invalid SSNs

### ISSUE THREAD

**Issue by jschaf** [joke2k/faker#260]
There's a few limitations on United States' SSNs that prevent it from being completely random.

* No group can be all 0s
* The SSN cannot start with 666
* The SSN cannot start with a number >= 900

See http://www.ssa.gov/employer/randomization.html

Could you modify the SSN generator to avoid these issues?

**Comment by fcurella** [comment]
Hi Joe,

sorry I couldn't get to you sooner, I've been swamped at work.

I'll look soon into how fix this. If you can send a pull request in the meantime, it will help a ton.

**Comment by jschaf** [comment]
Sure, I have a function that I'm using that should do the trick.  I'll send
it up as a PR.
