### ISSUE TITLE
Releases are not tagged

### ISSUE THREAD

**Issue by Ichimonji10** [joke2k/faker#261]
Releases 0.5.2 and 0.5.3 are not included in the git history:

    [ichimonji10@beech:faker]$ git tag --list
    v0.3.2
    v0.4
    v0.4.1
    v0.4.2
    v0.5
    v0.5.1

Please add tags for these releases:

    git tag v0.5.2 383b8f73bd1d3dd69e3e5dfb2d789576f90a7ef4
    git tag v0.5.3 dabf922af72783ebd9d163611ab0f4f307156443
    git push --tags origin master

**Comment by fcurella** [comment]
I've pushed the missing tags, and fixed `.bumpversion.cfg` so that will be automatically created in future.

Thank you very much for the report :)

**Comment by Ichimonji10** [comment]
Thank you for the prompt and elegant fix, @fcurella.
