### ISSUE TITLE
use environment markers and reactivate universal wheels + distribute wheels

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [joke2k/faker#263]
right now pip install  is broken due to the released package claiming to be universal wheel but not using environment markers

so pip makes a wheel for all pythons with the first python its run on, then its used on all other pythons,
so a pip install on python2.6 would create a broken wheel with the extra dependency which is then subsequently tried in other pythons, and will utterly break them

**Comment by fcurella** [comment]
Hi @RonnyPfannschmidt ,

I'm going to look into this, but I'm not very well versed in wheels and packaging. Will you be available to review and test my PR?

**Comment by RonnyPfannschmidt** [comment]
yes

**Comment by RonnyPfannschmidt** [comment]
the simple solution would be not claiming to be a universal wheel,
the more complete solution would be to set up environment markers for the affected python versions

**Comment by fcurella** [comment]
Thank you very much, I appreciate it.

I'm going to try using env markers, and if I can't get it to work, I'll give up on wheels for the moment.
