### ISSUE TITLE
"Edit on Github" link broken in ReadTheDocs

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#264]
http://fake-factory.readthedocs.org/en/latest/locales.html

Clicking "Edit on Github" results in a 404 error.

EDIT: 
http://fake-factory.readthedocs.org/en/latest/ has a github link to `https://github.com/joke2k/faker/blob/docs/docs/index.rst` when the correct link is
`https://github.com/joke2k/faker/blob/master/docs/index.rst`
(Note the doubled up `docs/docs` instead of `master/docs`)

**Comment by fcurella** [comment]
The link results on 404 because the .rst document is autmatically generated on RTD on build. I'll look if there's a way to disable the button.
