### ISSUE TITLE
ReadTheDocs spacing is off for providers

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#265]
http://fake-factory.readthedocs.org/en/latest/providers/internet.html

The spacing makes this pretty unreadable without constantly scrolling back and forth, which is annoying. 

Since these are the official extended docs linked to in the project ReadMe, it'd certainly be aesthetically nicer if they used native RTD formatting, for example see the formatting for the reference page of the factory boy project: http://factoryboy.readthedocs.org/en/latest/reference.html

I dug around a little trying to make a pull request to fix this, but it looks like Faker's docs are auto-generated somehow and I didn't have time to figure it all out. If you point me in the right direction, I'd be happy to submit a PR.

**Comment by fcurella** [comment]
Hi @jeffwidman ,

Thank you very much for offering your help, I really appreciate it.

You want to look into https://github.com/joke2k/faker/blob/master/faker/build_docs.py#L25-L57 . That's the method that writes the rst lines for a single provider.
