### ISSUE TITLE
Python Provider does not support Python 3

### ISSUE THREAD

**Issue by derekjamescurtis** [joke2k/faker#267]
The python provider uses the python 2.x basestring builtin, which is gone in 3.x.

https://docs.python.org/3/whatsnew/3.0.html

https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L63

Something like the following will trigger it on python 3

``` python

from faker import Factory
f = Factory.create()
f.pylist() # works!
f.pylist(10, True, int) # does not!

```

**Comment by fcurella** [comment]
Closed in #268
