### ISSUE TITLE
ImportError: cannot import name rand

### ISSUE THREAD

**Issue by Miserlou** [joke2k/faker#284]
>>> from faker import Faker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/api/env/lib/python2.7/site-packages/faker/__init__.py", line 12, in <module>
    import patterns
  File "/srv/api/env/lib/python2.7/site-packages/faker/patterns.py", line 4, in <module>
    from utils import rand
ImportError: cannot import name rand

Latest fake-factory from pip, CentOS.

**Comment by prasanthj** [comment]
This issue still happens with Python 2.6.6 in CentOS 6.6. Any solutions for it?

**Comment by joke2k** [comment]
@Miserlou @prasanthj are you sure you install `fake-factory`?
In this package there is not `init.py` or `patterns.py`.
Post you `pip freeze` please

**Comment by prasanthj** [comment]
Weird. Uninstalling and reinstalling worked for me. Will report back if I am able to repro again. Thanks!

**Comment by okamuuu** [comment]
I found similar problem. This is my case on MacOSX.

```
>>> import faker
>>> print faker
<module 'faker' from '/usr/local/lib/python2.7/site-packages/python_faker-0.2.4-py2.7.egg/faker/__init__.pyc'> 
```

So, unintall python_faker

```
>>> import faker
>>> print faker
<module 'faker' from '/Users/ma_okamura/.virtualenvs/userdive/lib/python2.7/site-packages/faker/__init__.pyc'>
```

Maybe I mistakenly implemnted pip install not in virtualenv once...

**Comment by omidraha** [comment]
There is another package on `pypi` with name [faker](https://pypi.python.org/pypi/Faker).
To solve this problem do these:
```
pip uninstall faker
pip install fake-factory
```

**Comment by okamuuu** [comment]
I see. Thank you for your helpful reply:)

**Comment by Luckymethod** [comment]
I'm finding the same problem with Python 3.5

`import faker
print(faker)
<module 'faker' from '/Users/luca/anaconda/lib/python3.5/site-packages/faker/__init__.py'>
`

if I try

`from faker import Generator`

like the documentation suggests I get 

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-21-e1b9d1057174> in <module>()
----> 1 from faker import Factory

ImportError: cannot import name 'Factory'`

Can anyone shed some light on what I'm doing wrong?

**Comment by Miserlou** [comment]
Related to https://github.com/joke2k/faker/issues/331
