### ISSUE TITLE
zh_CN email not returning valid email addresses

### ISSUE THREAD

**Issue by zdelagrange** [joke2k/faker#302]
When creating a fake Factory with the zh_CN or zh_TW it is not returning valid email addresses.

>>> f = Factory.create(locale='zh_CN')
>>> f.email()
u'.@yahoo.com'
>>> f.email()
u'.@gmail.com'
>>> f.email()
u'76@gmail.com'
>>> f.email()
u'.@.com'
>>> f.email()
u'.@.net'
>>> f.email()
u'.@.com'
>>> f.email()
u'.@yahoo.com'
>>> f = Factory.create(locale='zh_TW')
>>> f.email()
u'u@.com'
>>> f.email()
u'm@.com'
>>> f.email()
u'x@.org'
>>> f.email()
u'89@.net'
>>> f.email()
u'25@.com'
>>> f.email()
u'e@.info'
>>> f.email()
u'.@.com'

**Comment by zdelagrange** [comment]
There isn't a locale for zh_* for this provider. Maybe there should be a catch if there isn't a locale for a given provider when you call the function?

**Comment by zdelagrange** [comment]
Upon further investigation into this, the bg_BG locale for internet contains a _to_ascii function which replaces unicode characters with ascii characters. This might not be the best approach given the internationalization efforts underway, specifically for email addresses: https://en.wikipedia.org/wiki/Email_address#Internationalization

**Comment by fcurella** [comment]
Hi @zdelagrange , thank you for the report.

The issue is in https://github.com/joke2k/faker/blob/master/faker/providers/internet/__init__.py#L95.

```python
from faker import Factory

f = Factory.create(locale='zh_CN')

f.email()
> /Users/flavio/working_copies/faker/faker/providers/internet/__init__.py(96)domain_word()
     95         import ipdb; ipdb.set_trace()
---> 96         return re.sub(r'\W', '', company).lower()
     97

ipdb> company
u'\u65f6\u7a7a\u76d2\u6570\u5b57\u4f20\u5a92\u6709\u9650\u516c\u53f8'
ipdb> print(company)
时空盒数字传媒有限公司
```

We should probably add some list of 'ascii company names' to use in these situations, and fall back to en_US if we don't have any.

**Comment by zdelagrange** [comment]
@fcurella That does not address the possibility for unicode domain names, for example, http://☃.net/ is a valid domain.

**Comment by fcurella** [comment]
@zdelagrange can we move the discussion over to #303 ?
