### ISSUE TITLE
date_time_this_month logic error

### ISSUE THREAD

**Issue by mark-love** [joke2k/faker#304]
The logic blows up when the current month (now.month) is December (12) as I have found out. 

faker/providers/date_time/__init__.py
`next_month_start = datetime(now.year, now.month + 1 % 12, 1, tzinfo=tzinfo)`
should be 
`next_month_start = datetime(now.year, (now.month + 1) % 12, 1, tzinfo=tzinfo)`

**Comment by PaulLiang1** [comment]
Had the same issue just right now...

**Comment by fcurella** [comment]
Hi @mark-love , thanks for the report.

Do you mind submit a Pull Request? Really appreciate it :)

**Comment by mark-love** [comment]
No problem, I can work on one right now.

**Comment by fcurella** [comment]
@mark-love `now().month` is zero-based, so it needs to be compensated by doing something like:

```python
(now.month + 2) % 12
```

**Comment by mark-love** [comment]
@fcurella is it? From what I can tell in the documentation and experimenting is that it is between 1 and 12. https://docs.python.org/2/library/datetime.html#datetime.datetime.month

**Comment by fcurella** [comment]
@mark-love , no you're right.

The issue is that on Nov 30th, 'next month' means December, and `12 % 12` returns `0`, when we actually need it to be `12`

**Comment by fcurella** [comment]
I'll have to wait for tomorrow morning to dig deeper into this

**Comment by mark-love** [comment]
@fcurella ah yes that would be it `now.month % 12 + 1` should fix it.
Do we also want/need the year to increment or is that unnecessary?

**Comment by rshk** [comment]
I guess the year needs to be incremented as well, "next month" in Dec '15 is Jan '16, not Jan '15..

so better be explicit, something like:

```
if now.month == 12:
    next_year = now.year + 1
    next_month = 1
else:
    next_year = now.year
    next_month = now.month + 1
```

**Comment by rshk** [comment]
Btw, the current code is failing because of operator precedence (`%` has higher precedence than `+` so ``now.month + 1 % 12`` is actually ``now.month + (1 % 12)``), but anyways, ``(now.month + 1) % 12`` is broken as well, as month is one-based.

**Comment by kot-behemoth** [comment]
Is there any reason to not use `relativedelta` from the `dateutil` package (https://pypi.python.org/pypi/python-dateutil)? It provides a very robust way to get "next month" and is a well-known module:

```python
import datetime
import dateutil

next_month = datetime.date.today() + dateutil.relativedelta.relativedelta(months=1)

# In [1]: datetime.date.today()
# Out[1]: datetime.date(2015, 12, 1)

# In [2]: next_month
# Out[2]: datetime.date(2016, 1, 1)
```
