### ISSUE TITLE
date_time_this_month() tries to create a datetime on month 13, due to precendence problems in the implementation

### ISSUE THREAD

**Issue by luisincrespo** [joke2k/faker#309]
Hey there. I'm getting the following error

`ValueError: month must be in 1..12`

When trying to do

`faker.date_time_this_month()`

Being December the current month. It is trying to create something like:

`datetime(<year>, 13, <day>)`

Because the implementation does this:

**Line 439 /faker/providers/date_time/__init__.py**
`next_month_start = datetime(now.year, now.month + 1 % 12, 1)`

Due to precedence rules, `now.month + 1 % 12` is the same as `now.month + (1 % 12)`, which gives `now.month + 1`, which is (December) `12 + 1`, giving 13 as a result.

**Comment by fcurella** [comment]
hi @luisincrespo 

this should be fixed with https://github.com/joke2k/faker/pull/307/files. Are you running `faker` from `master`?

**Comment by fcurella** [comment]
/ping @joke2k It's probably a good time for a new release on PyPI

**Comment by luisincrespo** [comment]
Yeap I've just figured out you had this fixed on master. I'm using the latest version on PyPI, which is 0.5.3

**Comment by thecardcheat** [comment]
@fcurella @joke2k Any plan to release this fix on PyPi soon?
