### ISSUE TITLE
Better 'Unknown formatter' message for specific locale

### ISSUE THREAD

**Issue by matheuscas** [joke2k/faker#310]
I've just tried the "bs" formatter defining my locale as 'pt_BR' and I received the following error message: **Unknown formatter "bs"**

It's not clear that "bs" formatter is unknown using a specific locale. I just discovered because I looked into source code. I think that something like **Unknown formatter "bs" for "pt_BR"**, for instance, would be more clear. Of course that the original message would remain when no locale is set.

**Comment by malefice** [comment]
@fcurella according to this [git blame](https://github.com/joke2k/faker/blame/master/faker/generator.py#L87), you already fixed this in #567 so this should be safe to close.
