### ISSUE TITLE
Param switches on faker.password() don't guarantee valid password

### ISSUE THREAD

**Issue by craig552uk** [joke2k/faker#313]
The format switches on `faker.password()` (`special_chars, digits, upper_case, lower_case`) don't always return passwords matching those rules.

This is problematic as when using generated passwords in unit tests, where passwords must conform to validity rules (e.g. "must contain numbers"), tests can randomly fail.

I expected that these switches would guarantee the function returns a conforming password. e.g. `faker.password(digits=True)` always returns a password containing digits, but this is not the case.

**Comment by fcurella** [comment]
Thanks fro the report @craig552uk :)

I've create PR #314 to track the work on a bugfix.
