### ISSUE TITLE
Access to the Generator.random

### ISSUE THREAD

**Issue by gsingers** [joke2k/faker#317]
It would be nice if one could gain access to the Generator.random variable so that one could save/set the state.  I realize I can pass in the seed, but one currently has no way of gathering what the seed/state is if using the automatically generated seed.  I don't want to use a fixed seed, but I do want to log/print the seed used _if_ the tests fail.

That is, I'd like to be able to do something like:  `faker.generator.getstate()` (which gets the random state w/o exposing random) or `faker.generator.random.getstate()` (which gives access to the random variable)

For now, the workaround appears to be to create a Faker object with your own Generator.

**Comment by fcurella** [comment]
we could expose the `random` instance on the generator. Something like:

```python
>>> from faker import Faker
>>> fake = Faker()
>>> fake.random
<random.Random at 0x7f992ca24e20>
>>> fake.random.getstate()
3,
 (2147483648L,
  3782733512L,
  2477412110L,
[...]
```
