### ISSUE TITLE
Find a way to share providers within the community

### ISSUE THREAD

**Issue by fcurella** [joke2k/faker#319]
The final goal is put to a good use the time spent by who created a provider for this project.

Non-exhaustive list of possible options (not necessarily mutually exclusive):

* Page in the docs listing packages (easy-peasy #320 )
* Packages will contain a `faker-provider` in their `setup.py`'s `keywords` attribute, so they can easily found on PyPI. The docs will point to the search results page
* Bonus points with :sparkles: : cli option that parses a page or queries PyPI for providers to download and install.

Options I'd rather avoid:

* `faker` umbrella github org, and have everyone bring their code on GitHub (which not everybody may be OK with) and under the org. Also brings issues of governance.
* just accepting every single provider that gets proposed. We simply don't have the necessary time and resources to guarantee speedy reviews and quality control.

**Comment by danhuss** [comment]
So would the idea be to deploy those as packages on PyPI? I've never done that before, so is there anything I should be aware of while i'm hunting down a how-to tutorial for submitting those packages?

Thanks,
Daniel

**Comment by fcurella** [comment]
@danhuss I'm thinking the upload on PyPI should be optional. On the page we'd list URL (could be a repo, could be your package's page on GH). On the same page, we can also have a link to the PyPI search results. If you decide not to publish your package on PyPI, your provider will simply be listed only once.

**Comment by fcurella** [comment]
Addresses in #320
