### ISSUE TITLE
Add a faker[hypothesis] extra

### ISSUE THREAD

**Issue by Daenyth** [joke2k/faker#326]
It would be useful to be able to use Faker with [Hypothesis](http://hypothesis.readthedocs.org) for testing. It can be declared as an [optional dependency in setup.py](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)

I can put in a PR at some point adding this if you'll accept it

**Comment by fcurella** [comment]
Hi @Daenyth 

I personally think it would be really useful, I'm just not sure if it should be an extra of `fake-factory`, or its own separate package.

IMHO it comes down to how much maintenance cost will it add to the project. We are already stretched pretty thin.

We'll definitely need @joke2k opinion.

**Comment by Daenyth** [comment]
I *think* it should be fairly simple. I don't think it'll be hard to write one generic method that connects hypothesis's `random` to a given provider and then dynamically generates strategies for all providers. That said, I haven't dug into it yet. The benefit of it being in-repo vs as an extra package is of course that api changes would be caught by tests right away.

**Comment by DRMacIver** [comment]
FWIW, there is [already support for this in Hypothesis](https://hypothesis.readthedocs.org/en/latest/extras.html#hypothesis-fakefactory).

**Comment by fcurella** [comment]
Thanks for pointing that out @DRMacIver 

@Daenyth since `faker` is already supported in Hypothesis, I don't see any reason to implement the same thing twice. Would `hypothesis[fakefactory]` work for you?

**Comment by Daenyth** [comment]
Yeah, seems reasonable.
