### ISSUE TITLE
point http://www.joke2k.net/faker/ at RTD 

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#333]
Having docs at both http://www.joke2k.net/faker/ and http://fake-factory.readthedocs.org/en/stable/providers.html is confusing. 

At first I didn't realize the RTD docs existed, then once I realized that, I assumed the joke2k.net link is a copy of the Readme. But then I realized it's different, and now I'm simply confused. 

Any of the following would be better than the current state of affairs:

- joke2k.net faker docs don't exist or merely redirect to extended docs at RTD
- RTD doesn't exist, and joke2k.net has the actual extended docs
- joke2k.net just mirrors the README off the repo and clearly links to the extended docs on RTD (worst option IMHO, better to just have a README on the repo, and one set of offsite extended docs)

As part of this, I'd suggest changing the URL at the top of the repo to point to the extended docs, whether that ends up being on RTD or on joke2k.net

**Comment by fcurella** [comment]
I think I'd rather have the docs on RTD and have everything point to that.

@joke2k what would you rather do?

**Comment by jeffwidman** [comment]
Bump @joke2k

**Comment by joke2k** [comment]
Hi guys, in my opinion the best option is RTD.

I'll move all the references from joke2k.net/faker to fake-factory.readthedocs.org.

**Comment by jeffwidman** [comment]
Given https://github.com/joke2k/faker/issues/331 and the overall standardization on 'faker' as the namespace, probably better to point joke2k.net/faker to http://faker.readthedocs.org/ rather than http://fake-factory.readthedocs.org/

**Comment by jeffwidman** [comment]
Redirect is now in place, so this issue has been fixed.
