### ISSUE TITLE
Dates in Changelog are wrong for 2016 releases

### ISSUE THREAD

**Issue by Chronial** [joke2k/faker#334]
See https://github.com/joke2k/faker/blob/c4cabf759d17aeccdcc730064c381a45115732c2/CHANGELOG.rst :)

**Comment by fcurella** [comment]
Nice catch!

Fixed in master, and I've updated the changelog on PyPI as well.

Thank you very much! :sparkles:

**Comment by Chronial** [comment]
That was a quick fix :) :+1:
