### ISSUE TITLE
Dependency on python-dateutil >= 2.4 excludes python 2.x

### ISSUE THREAD

**Issue by jjmurre** [joke2k/faker#335]
The last version of python-dateutil that supports python 2.x is version 1.5
Because faker now depends on version >= 2.4 of python-dateutil, faker can only be used for python 3.x

**Comment by fcurella** [comment]
Hi @jjmurre , Thanks for your report.

According to https://pypi.python.org/pypi/python-dateutil/2.5.0, `python-dateutil` v2.5.0 supports Python 2.6 and 2.7.

Moreover, the builds for Python 2.x are all installing `python-dateutil-2.5.0` and passin (eg https://travis-ci.org/joke2k/faker/jobs/113448867).

Do you have a stacktrace I could look at?

**Comment by jjmurre** [comment]
@fcurella You are totally right! In the past I had to pin python-dateutil to 1.5, because 2.0 was python3 only and the story was that python2 users should keep using 1.5. This version pin was conflicting with the faker requirement of >=2.4. However, it seems that python-dateutil changed its policy, luckily. Sorry to have bothered you about this! I'll close the issue.
