### ISSUE TITLE
Is there a reason why the pypi package was renamed 0.5.6-proper?

### ISSUE THREAD

**Issue by josegonzalez** [joke2k/faker#339]
This appears to break builds for us because pypi can't find it. Just curious as to why it was pulled, and why the name had `-proper` attached.

**Comment by fcurella** [comment]
While uploading to PyPI, the server returned a 500 so I had to re-upload manually with a different name. I'm afk ATM. @joke2k can you either remove the .tar.gz or upload a new release?

**Comment by fcurella** [comment]
Hi @josegonzalez 

sorry about the issue. I've just released 0.5.7 on PyPI. It doesn't contain any changes except for the version bump.

**Comment by josegonzalez** [comment]
<3
