### ISSUE TITLE
the email is invalid when use locale='zh_CN'

### ISSUE THREAD

**Issue by fengdy** [joke2k/faker#340]
fake = Factory.create(locale='zh_CN')
print fake.company_email()
print fake.email()

Then output:
秀兰87@维旺明信息有限公司.org
x越@gmail.com
it's a invalid email, and the other (free_email etc) email function in the same,

**Comment by fcurella** [comment]
to expand a little, the issue here is that email addresses can only contain Latin letters.

**Comment by fengdy** [comment]
also in the condition, fake = Factory.create(locale='zh_CN'), the  website also have the same problem, u'http://www.\u65f6\u7a7a\u76d2\u6570\u5b57\u79d1\u6280\u6709\u9650\u516c\u53f8.biz/' -----http://www.时空盒数字科技有限公司.biz/

**Comment by fcurella** [comment]
Hi @fengdy ,

we'll need to compile a list of romanized common names to use. I've been looking at https://en.wikipedia.org/wiki/List_of_common_Chinese_surnames and https://en.wikipedia.org/wiki/Chinese_given_name#Common_Chinese_names and it looks like 'Pinyin' would be the de-facto 'standard' romanization. The only issue is that those names still contain accented letters, which are outside of the ascii range. Would it be appropriate to use that romanization and simply strip the accents?

**Comment by sikko** [comment]
Hi,
Same issue when the locale contains characters with accents (éèàô etc...)

**Comment by markalexander** [comment]
@fcurella 

> [...] it looks like 'Pinyin' would be the de-facto 'standard' romanization. The only issue is that those names still contain accented letters, which are outside of the ascii range. Would it be appropriate to use that romanization and simply strip the accents?

I would say yes. This is pretty much what Chinese people will do when confronted with an ascii-only form.  Technically you can write the tones (i.e. the accents) by appending numbers (e.g. mā  má  mǎ  -> ma1 ma2 ma3).

Also there is also the use of ü, which isn't actually a tonal mark, but indicates a change in vowel sound.  Stripping the umlaut in this case is approximately the same as stripping them from the German ü.
