### ISSUE TITLE
Add method to generate fake text with a minimum number of characters

### ISSUE THREAD

**Issue by coffeesippa** [joke2k/faker#346]
Faker has methods to afford text strings with a maximum number of character, such as, `fake.text(max_nb_chars=200)`. Would like the ability to specify a minimum number of characters for a set of text or a specific length. This would allow users to easily input data into fields with minimum character input requirements. There is currently only two methods, `fake.password()` and `fake.ean()`, that allow the user to specify a length.

**Comment by crf1028** [comment]
Hi @tamarbuata 
I tried to solve the problem and is almost there except for testing part.
So I am wondering is there an enxisting function for testing `fake.text()`.
I searched the file and was unable to find one.

**Comment by fcurella** [comment]
Isn't this solved by https://github.com/joke2k/faker/pull/347 ?

**Comment by fcurella** [comment]
Oh I see, this is the same as #347, but for the `text` provider.

@crf1028 Take a look at the diff #347 for an example of how to test it
