### ISSUE TITLE
The "community providers" link on PyPI is broken

### ISSUE THREAD

**Issue by devinbarry** [joke2k/faker#360]
The link pointing to community providers on the PyPI page (https://pypi.python.org/pypi/fake-factory) gives the following error:

>Permission Denied
>
>You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.

This is the current address of the link
http://fake-factory.readthedocs.org/en/latest/communityproviders.html

**Comment by fcurella** [comment]
The build on read the docs is trying to build a single html file even tho I've selected 'Sphinx Html' and not 'Sphinx Sigle Page HTML', and that step is running out of memory, causing the build to fail.

I'll have to check with rfd people to see how to disable that step.

**Comment by fcurella** [comment]
ok, i think I've figured it out. Fixed in https://github.com/joke2k/faker/commit/43bc86b94ee6038ee345b9a50d821d29abcf39a4
