### ISSUE TITLE
Would a faker.format() method make sense?

### ISSUE THREAD

**Issue by cclauss** [joke2k/faker#362]
It could enable the syntax:
`print(faker.format('{name} considers a {catch_phrase} in {country}'))`

A sample implementation show how simple it would be:

``` python
def fake_fmt(fmt="{first_name}'s favorite number: {random_int}", fake=None):
    fake = fake or Faker()
    fields = [fld.split('}')[0].split(':')[0] for fld in fmt.split('{')[1:]]
    return fmt.format(**{field: getattr(fake, field)() for field in fields})
```

More test cases at: https://github.com/cclauss/Ten-lines-or-less/blob/master/fake_format.py

**Comment by gamesbook** [comment]
Any definite plans to include this?

**Comment by fcurella** [comment]
Hi @gamesbook ,

I'm still waiting on someone to submit a PR. Feel free to take this on :)
