### ISSUE TITLE
Company Name reversed in providers/company/zh_TW

### ISSUE THREAD

**Issue by JIElite** [joke2k/faker#364]
There are a lot of company names are reversed, like: "台灣印無品良" should be "台灣無印良品" ,
"AYHOO!摩奇" should be "YAHOO!奇摩". It likes "Glegoo" should be "Google" in English.
Almost every company name in company_prefixes need to be fixed.

Is it necessary to change them? I think change their name will make it more intuitively clear for Taiwanese user.

[check this](https://github.com/joke2k/faker/blob/master/faker/providers/company/zh_TW/__init__.py)

**Comment by kevin-brown** [comment]
Based on the note in https://github.com/joke2k/faker/pull/99 about "reversed character order", I think this may have been intentional.

**Comment by fcurella** [comment]
I'm not sure why the character order was reversed. @keitheis could you shed some light?

**Comment by keitheis** [comment]
I intentionally don't want to use real existed company here and I am not sure that I have the right to use them here directly. If it's a necessary case for @JIElite and you're sure about the right of using them, a pull-request should be welcome.

**Comment by fcurella** [comment]
I would rather remove them to avoid misunderstandings in the first place.

The `en_US` provider avoids this by using a `{last_name}, {company_suffix}` pattern. Would a similar behaviour be appropriate for the `zh_TW` locale?

**Comment by JIElite** [comment]
@keitheis Thank you for explanation, just remain the same.
@fcurella  I think use the current format is OK.   

The only question for me is there are a lot of company names in `{company_prefixes} `which are much similar to the exactly existed company name in Taiwan (just with little reversed word). I just want to know why the character is reversed in its company name.  Instead, it use the real company in `zh_CN`. 

Even though there are some characters reversed in the company name, according to its `{company_suffix}` we also can know it is a company. So, the current format is OK, it can generate the fake company.

Thank you for explanation
If it needs changing, I am glad to commit the pull-request
