### ISSUE TITLE
TypeError: pystruct() got multiple values for keyword argument 'count' ,  what is the correct value_types?  

### ISSUE THREAD

**Issue by eromoe** [joke2k/faker#366]
example doesn't show the value_types
http://faker.readthedocs.io/en/master/providers/faker.providers.python.html

I want generate a ramdon json with all key and value is string.
But only `fake.pystruct(count=10)` work 

I look into the provider.python and find:

```
if not value_types:
    value_types = ['str', 'str', 'str', 'str', 'float', 'int', 'int', 'decimal', 'date_time', 'uri', 'email']
```

But still error

```
>>>value_types = ['str', 'str', 'str', 'str', 'float', 'int', 'int', 'decimal', 'date_time', 'uri', 'email']
>>>fake.pystruct(count=10, *value_types)
TypeError: pystruct() got multiple values for keyword argument 'count'
```

This `fake.pystruct(10, 'str')` work,  you should change the doc with a correct

**Comment by ThibaultLemaire** [comment]
:+1: for documenting this. The valid values for `value_types` are nowhere documented.

My own testing yielded that you can pass built-in types (`int`, `str`, `float`, etc. without `""`) or names of providers (e.g. `'email'`)
