### ISSUE TITLE
Kill http://fake-factory.readthedocs.io/ since http://faker.readthedocs.io/en/master/ exists

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#372]
Kill http://fake-factory.readthedocs.io/ since http://faker.readthedocs.io/en/master/ exists and we're standardizing on `faker` as the project name.

It minimizes confusion that way.

**Comment by jeffwidman** [comment]
#373 needs to be merged first...

**Comment by fcurella** [comment]
It's done, thanks for pointing it out :)
