### ISSUE TITLE
0.7.3 on PyPI + missing Changelog

### ISSUE THREAD

**Issue by michael-k** [joke2k/faker#388]
1. https://pypi.python.org/pypi/fake-factory does not link to https://pypi.python.org/pypi/Faker.  The only hint that the name changed is `pip install Faker`.

2. There is no changelog after `0.6.1 - TBD`.

**Comment by fcurella** [comment]
Fixed in https://github.com/joke2k/faker/commit/367cf6170f44478bb59c16745a48f12572854773 and https://github.com/joke2k/faker/commit/afa51017f9fdf29e1ae4f3c208aee193aeca1561
