### ISSUE TITLE
differentiate between male and female first names

### ISSUE THREAD

**Issue by jabbalaci** [joke2k/faker#39]
As I can see, `fake.first_name()` can return either a male or female first name. Do you plan to make a difference between them? Like `fake.first_name(gender='male')`, where the default value could be `'any'`.

I ask it because I want to add support for Hungarian names. I have an up-to-date list with all the Hungarian names, put in two files: males and females. I could put them in two sets, or I could add them in one set.

**Comment by fcurella** [comment]
I think this issue is resolved. @joke2k can you confirm?

**Comment by kdeldycke** [comment]
This ticket can be closed. Gender was implemented in commit 4bb388fbc901b0eccd7555c403d8e4bba26ebcb7 .

**Comment by fcurella** [comment]
thanks @kdeldycke , appreciate your help! :sparkles:
