### ISSUE TITLE
[pl-PL] Django model factory don't provide all methods

### ISSUE THREAD

**Issue by dszmaj** [joke2k/faker#427]
I can't use all methods for pl locale for ex.
```python
fake.region()
```
it throws that object doesn't have that, and dir() shows that it's true, but i see that provider has this implemented so there is a problem with proxying that

**Comment by stephane** [comment]
Yes (and it's not related to Django,) I think the documentation must warn about this limitation, when a translation doesn't provide a faker there is not fallback to the English one.
