### ISSUE TITLE
Remove duplicate PyPI registration

### ISSUE THREAD

**Issue by chrisspen** [joke2k/faker#429]
I noticed this package appears to be registered twice on PyPI, under different names.

https://pypi.python.org/pypi/fake-factory
https://pypi.python.org/pypi/Faker

Is this on purpose? One appears to be slightly out-of-date, but otherwise, they refer to the identical github. I was using fake-factory at first, and when I found a bug, I stumbled across Faker, where the bug had already been fixed, but not in fake-factory.

To avoid confusion, I'd highly recommend deleting one of them.

**Comment by fcurella** [comment]
We are in the process of transitioning from `fake-factory` to `Faker`, and we plan to remove `fake-factory` later this month. See #331 

The repos are supposed to be in sync, except for the version number. What bug are you referring to?

**Comment by chrisspen** [comment]
A datetime provider was generating an invalid month for November, but I see that's since been fixed.
