### ISSUE TITLE
Published packages include docs/ as a module

### ISSUE THREAD

**Issue by wyattanderson** [joke2k/faker#434]
The published wheel and sdist on PyPI for at least version 0.7.5 include `docs/__init__.py` as a top-level module in addition to `faker`. This conflicts with some other packages we use (PyICU) and seems like bad package hygiene, especially since the `docs` dir in this repository is definitely not a module. My guess is that a `__init__.py` made it in there on the maintainer's machine before running `setup.py` and it was erroneously discovered as a module.

We're going to republish the package to our own internal repository, but I think it would help the community to `git clean` as necessary and re-publish a new version, and consider adding necessary exclusions to the `setup.py` or `MANIFEST.in`.

**Comment by fcurella** [comment]
Thank you @wyattanderson .

I've created #435 to fix setup.py. Once the CI passes, I'll get it merged in and make a new release

**Comment by michaelgmiller** [comment]
Woohoo! Seems to have passed CR. Thanks for looking at this so quickly!

**Comment by fcurella** [comment]
Faker 0.7.6 relased on PyPI: https://pypi.python.org/pypi/Faker/0.7.6
