### ISSUE TITLE
random_number(digits=10)) generates number lesser than 10 digits sometimes

### ISSUE THREAD

**Issue by maran0206** [joke2k/faker#444]
I used random_number(digits=10)) to generate 1000 random numbers and saved them in an excel. But I could able to see some numbers have only 7-9 digits in them. 
My code:
`import faker
import xlwt

data = faker.Faker()

wk = xlwt.Workbook()
ws = wk.add_sheet("sheet1")

for i in range(0,1000):
    ws.write(i,0,data.first_name())
    ws.write(i,1,data.last_name())
    ws.write(i,2,data.email())
    ws.write(i,3,data.random_number(digits=10))
    ws.write(i,4,data.random_int(min=0, max=9999))

wk.save("D:\\results.xlsx")`
[results.xlsx](https://github.com/joke2k/faker/files/674437/results.xlsx)

**Comment by fcurella** [comment]
Hi @maran0206 

that's expected. The `digits` parameter of `random_number` controls the maximum amount of digits. See the docstring for the method: https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py#L77

**Comment by maran0206** [comment]
I have an use case where i have to provide exact 10 digits to an input box. Is there any way to do so? Is it possible to use phone number with 10 digit format?

**Comment by maran0206** [comment]
Hi #fcurella

I found a way to overcome this, PFB the code which works like charm. 

from random import randint

def random_with_N_digits(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return randint(range_start, range_end)

for i in range(0,100):
    print random_with_N_digits(10)

**Comment by stephane** [comment]
@fcurella could be closed...

**Comment by fcurella** [comment]
fixed in a58490a7228b2ad4deb2f68f9dc60754e4eba64a
