### ISSUE TITLE
Add Indian English Locale

### ISSUE THREAD

**Issue by riturajtiwari** [joke2k/faker#448]
A fair amount of electronic activity in India is done in English, but with Indian names, etc. This issue is to add and Indian English locale.

**Comment by stephane** [comment]
@riturajtiwari If you don't provide the Indian English locale I don't see why this issue is useful?

**Comment by riturajtiwari** [comment]
Hi Stephane:
I created this issue so I could contribute some things from that locale.

Thanks.
-Raj
