### ISSUE TITLE
Refactor Profile to be used with locale: how

### ISSUE THREAD

**Issue by chobeat** [joke2k/faker#45]
I got this idea but i'm not sure it would be the simplest: the actual profile.py becomes something like "internal_profile.py", its methods are renamed "internal_simple_profile()" and "internal_profile()", and is removed from the list of standard providers. Then we will have a standard profile.py that simply calls self.generator.internal_profile(). For each locale instead, we will be able to add more logic, for example to customize field names and eventually values. 

Do you think there would be a simpler way to do it?

**Comment by alltheoptions** [comment]
+1
