### ISSUE TITLE
Documentation about Factory Boy

### ISSUE THREAD

**Issue by stephane** [joke2k/faker#450]
The Factory Boy and Faker documentations don't provide the same way to use Faker in Factory Boy.

http://factoryboy.readthedocs.io/en/latest/reference.html#faker

vs

https://faker.readthedocs.io/en/master/#how-to-use-with-factory-boy

A link to Factory Boy will be great too.

**Comment by fcurella** [comment]
@stephane I've updated the docs and added a link, let me know if there's anything else I can do :)

**Comment by stephane** [comment]
That was quick (see related #451).
