### ISSUE TITLE
Two entry points: Factory vs Faker

### ISSUE THREAD

**Issue by stephane** [joke2k/faker#453]
I think it will be clearer to have a single way to create a `fake` instance.

```
from faker import Factory
fake = Factory.create()
```

VS

```
from faker import Faker
fake = Faker()
```

I propose to deprecate the `Factory` class to remove it in future releases.

PS: why Faker isn't a proper class (Generator)?

**Comment by fcurella** [comment]
@stephane I'm not the original author, so I don't really have an answer.

@joke2k can you shed some light?

**Comment by joke2k** [comment]
At the begining Faker class doesn't exists.
I had only Factory and Generators. Then I introduce the Faker shortcut for Factory.create.
Nothing special.

I'm agree to deprecate the Factory class in favor of new Faker class.
 
@stephane care about Faker, it isn't a Generator class but a shortcut for static method `Factory.create`

**Comment by fcurella** [comment]
I'm a little worried about breaking backward compatibility with 3rd party libraries.

If we deprecate `Factory`, it should be done gradually. First we raise a warning, then we deprecate later on a major release.
