### ISSUE TITLE
EAN-13 starting with 0

### ISSUE THREAD

**Issue by olegpidsadnyi** [joke2k/faker#456]
ean13 function generates codes starting with zeroes.

According to http://www.barcodeisland.com/ean13.phtml ean13 has to duplicate the leading zero.
So basically UPC-A code "075678164125" in ean13 form should be "0075678164125".

**Comment by grantbachman** [comment]
From reading the text, it says EAN-13 is a superset of UPC-A, and that EAN-13 codes with a leading 0 are also valid UPC-A codes. Are you saying `ean13()` shouldn't be generating codes that are also valid UPC-A?

**Comment by olegpidsadnyi** [comment]
I'm not sure. Why I was confused is that the ean-13 that starts with 0 and rendered with the js barcode library is not being read entirely with the zxing scanning library. Somehow it strips the last (or the first,  don't remember exactly) character.
This is how I found out there are UPC-A codes.
Currently I'm working around this in my factories and trying to avoid codes that begin with 0 at all.

Please also read: NOTE: In reality, an UPC-A symbol is an EAN-13 symbol with the first number system digit set to 0. For example, take the UPC-A code "075678164125".

I guess the mobile scanning apps are thinking this way as well. So my solution would be generating UPC-A (with 00 in front) if it happens that the first one is 0.

**Comment by grantbachman** [comment]
That site says that the first two digits of EAN-13s can be anything from 00-13. I also checked a few against a [validator](https://www.getnewidentity.com/validate-ean.php) I found online. Doesn't look like there's anything wrong with leading 0's in an EAN-13. It sounds like an issue with the js library you're using.

**Comment by olegpidsadnyi** [comment]
Here: http://www.barcodeisland.com/ean13.phtml
Number System: The number system consists of two digits (sometimes three digits) which identify the country (or economic region) numbering authority which assigned the manufacturer code. Any number system which starts with the digit 0 is a UPC-A bar code.

I tried few online generators and android barcode scanners. They all expect 00 when the code is starting from 0. 00-13 seems like USA/Canada only EAN13. ZXing and others think this is UPC-A.

**Comment by kungfu71186** [comment]
https://github.com/Redth/ZXing.Net.Mobile/issues/70

Seems to be an issue with the library. But this is also an issue in the implementation of ean13 in real world. Some scanners don't support leading 0s and mark it as UPC code.

Maybe add a flag to not generate any codes that start with 0, but default allow it
