### ISSUE TITLE
Create fake product name.

### ISSUE THREAD

**Issue by alexanderwhatley** [joke2k/faker#457]
Does Faker have the ability to create fake product names right now? If not, this definitely seems like something you should include.

**Comment by chrisvoncsefalvay** [comment]
I have an algorithm for realistic sounding fake product names for four genres:

- apps (Prototronix, Futurex, Prokit)
- medications (Volvinex, Subarctone, Temexpera, Serocate)
- FMCG (Sudex, Prelox, Masic)
- 'traditional' (Uncle Ray's, Old Billie Walt's, Crab Creek)

Interested?

**Comment by alexanderwhatley** [comment]
That would be awesome.

**Comment by chrisvoncsefalvay** [comment]
@alexanderwhatley OK, I'll get onto it this week. 📦

**Comment by matheussilva97** [comment]
this issue still need to include?

**Comment by djordjen** [comment]
Hi, not sure if this has been implemented so far?

**Comment by fcurella** [comment]
Since this would be pretty hard to localize, I'd it would be better implemented as a [Community Provider](https://faker.readthedocs.io/en/stable/communityproviders.html)
