### ISSUE TITLE
Windows 10 fake.date OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by akotulu** [joke2k/faker#460]
I'm generating 30000+ date entries on Windows and get a crash with traceback
```
Traceback (most recent call last):
  File ".\builder.py", line 196, in <module>
    builder.gen(count=count)
  File ".\builder.py", line 97, in gen
    ctime = fake.date(pattern='%Y%m%d%H%M%S')
  File "C:\Users\Ako\AppData\Local\Programs\Python\Python36\lib\site-packages\faker\providers\date_time\__init__.py", line 288, in date
    return cls.date_time().strftime(pattern)
  File "C:\Users\Ako\AppData\Local\Programs\Python\Python36\lib\site-packages\faker\providers\date_time\__init__.py", line 256, in date_time
    return datetime.fromtimestamp(cls.unix_time(), tzinfo)
OSError: [Errno 22] Invalid argument
```
Python 3.6 64bit, Windows 10 64bit
```
fake = Faker()
ctime = fake.date(pattern='%Y%m%d%H%M%S')
```

Found on Stackoverflow

> If the timestamp is out of the range of values supported by the platform C localtime() or gmtime() functions, datetime.fromtimestamp() may raise an exception like you're seeing. On Windows platform, this range can sometimes be restricted to years in 1970 through 2038. I have never seen this problem on a Linux system.

**Comment by kungfu71186** [comment]
Python bug: https://bugs.python.org/issue29097

I suggest using timedelta instead. 

where seconds is generated randomly
(datetime(1970, 1, 1) + timedelta(seconds=timestamp)).strftime('%Y%m%d%H%M%S')

**Comment by fcurella** [comment]
Closed by #534

**Comment by KeynesYouDigIt** [comment]
IM not sure I understand the solution proposed, I am getting the same error using `date_between(start_date='-99y', end_date='-1y'`

**Comment by kungfu71186** [comment]
@KeynesYouDigIt can you open a new issue with the stack trace?
