### ISSUE TITLE
Test installed to /usr/lib/python3.6/site-packages/tests/

### ISSUE THREAD

**Issue by jorti** [joke2k/faker#468]
Why are the tests now installed to /usr/lib/python3.6/site-packages/tests/ ? are they a new package called "tests"? it looks wrong to me.

**Comment by fcurella** [comment]
I've moved them to a separate package, but I've also excluded it from 'find_packages', so I don't know exactly what's going on

**Comment by fcurella** [comment]
Thanks @jorti , should be fixed on 0.7.9
