### ISSUE TITLE
Add ISBN support

### ISSUE THREAD

**Issue by barseghyanartur** [joke2k/faker#469]
Please, add [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number) support.

**Comment by fcurella** [comment]
Hi @barseghyanartur ,

I think that would be a useful addition. Feel free to submit a Pull Request! :)

**Comment by grantbachman** [comment]
Is it okay if I work on this one? Never done OSS work before but I've been looking for a project to which I can contribute, and faker looks like a great way to get started!

**Comment by fcurella** [comment]
@grantbachman Absolutely! Thank you so much for volunteering :)

If you have any question, don't hesitate to ask :)

**Comment by grantbachman** [comment]
Hey @fcurella I have basic ISBN-10/ISBN-13 number support working, meaning I can generate basic 10/13 digit numbers that meet the ISBN-10/13 check digit requirements. However things start to get complicated when we talk about hyphenating these numbers (e.g. turning `9783161484100` into `978-3-16-148410-0`). Doing this requires referencing the [ISBN rules](https://www.isbn-international.org/range_file_generation) to identify which language/region the number falls under, then looking up the hyphenation rules for that region. These rules appear to change over time.

My question becomes, how real do we want these numbers to look? I could simply code in the rules for english ISBNs and call it a day, or we could attempt to follow the rules of all of the regions by either storing them somewhere in faker or letting a separate python package (like [python-stdnum](https://github.com/arthurdejong/python-stdnum)) handle that for us. Thoughts?

**Comment by fcurella** [comment]
@grantbachman Thank you! I think we can start with just `en_US`. We can always add more countries later, if any requests come in.

**Comment by grantbachman** [comment]
What's the policy on closing issues? Should this be closed right away because it was merged or do we wait a period before doing so?

**Comment by fcurella** [comment]
This should be closed upon merge. Thanks @grantbachman for reminding me
