### ISSUE TITLE
Change project name to avoid confusion

### ISSUE THREAD

**Issue by chobeat** [joke2k/faker#47]
I just received this feedback talking about the original Faker in PHP:

"I would recommend some sort of distinguishing name then. They both have the same name, that is going to be really confusing. Even something like FakerPy or something."

I think it makes sense and FakerPy is a good option.

**Comment by joke2k** [comment]
probably the repository will change its name to `fake-factory` to match with pypi package name.

**Comment by fcurella** [comment]
the package name is officially `Faker`
