### ISSUE TITLE
Community providers page is blank

### ISSUE THREAD

**Issue by thiagofigueiro** [joke2k/faker#470]
https://faker.readthedocs.io/en/latest/communityproviders.html

Is it intentionally blank?

If so, what is the process to add a provider to this page?  I'd be happy to update the documentation and submit a PR.

**Comment by fcurella** [comment]
hi @thiagofigueiro 

it's blank because nobody has added their provider yet :)

The process is simple: just open a PR that adds your project to that table.

**Comment by thiagofigueiro** [comment]
That is a great reason :-)

Does it need to be my project?  I've tested these guys and they work as advertised:

https://pypi.python.org/pypi/faker_extras
https://pypi.python.org/pypi/faker_cinema

I'm happy to include them otherwise feel free to close this.

**Comment by fcurella** [comment]
> Does it need to be my project?

Preferably. I wouldn't necessarily assume the authors want to be included.

I would either ask them to submit a PR, or ask them permission for you to open it on their behalf.
