### ISSUE TITLE
Break up tests by provider instead of by language

### ISSUE THREAD

**Issue by grantbachman** [joke2k/faker#476]
Looking through the tests directory, I see that the tests are mainly broken up by language. To me, this isn't very discoverable in that I have no idea what's actually under test in each of those directories. Would it make more sense to break them up by their individual functions?

For instance, something like this:
```
tests/
    providers/
        isbn.py
        ssn.py
        postcode.py
   generator.py
   documentor.py
```

**Comment by fcurella** [comment]
yes, it would make more sense to break them down. I meant to do that, but haven't had the chance yet.

**Comment by grantbachman** [comment]
I can handle it. I quite enjoy mucking with tests :) I can get started tonight.
