### ISSUE TITLE
isbn10 and isbn13 do not work when downloaded from pypi.python.org

### ISSUE THREAD

**Issue by sblondon** [joke2k/faker#478]
Hello,

the methods isbn10() and isbn13() raise an AttributeError when called from a virtualenv. It's because the faker/providers/isbn/ directory is not embedded in the library. When the code is executed from a cloned repository, it works because the directory exists.
I guess that setuptools.find_packages() does not find it so it's not included when the library is built.

Examples:
When the code is executed from a cloned repository, it works properly:
$ ./venv/bin/python
Python 3.4.3rc1 (default, Mar 17 2015, 16:22:37) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Factory
fake = Factory.create()
>>> fake.isbn10()
'1-4325-7338-1'
>>> fake.isbn13()
'978-0-424-29655-5'

However it does not work when the library is installed in a virtualenv from pypi.python.org:
$ ./venv/bin/python
Python 3.4.3rc1 (default, Mar 17 2015, 16:22:37) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Factory
>>> fake = Factory.create()
>>> fake.isbn10()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'isbn10'
>>> fake.isbn13()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'isbn13'

**Comment by fcurella** [comment]
The last published version on PyPI is v0.7.9, which did not include the ISBN provider yet.

I'll release a new version be EOD

**Comment by sblondon** [comment]
It works perfectly. Thanks!
