### ISSUE TITLE
country_code found in address and misc provider

### ISSUE THREAD

**Issue by J535D165** [joke2k/faker#487]
``Faker.country_code`` is found twice in the providers (misc and address).

https://github.com/joke2k/faker/blob/master/faker/providers/misc/__init__.py#L137
https://github.com/joke2k/faker/blob/master/faker/providers/address/__init__.py#L85

Only one of them is used now (which one?). One should be removed. 

This issue causes problems in making a unit test for #484.

**Comment by fcurella** [comment]
let's keep the one in `address`
