### ISSUE TITLE
Improve accuracy of hu_HU generators

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [joke2k/faker#490]
The Hungarian 🇭🇺 generator (`hu_HU`) exhibits some anomalies:

- Domains and e-mail addresses, which derive their content from the first and last name generators, contain accents. In general, it is uncommon for Hungarian domains to contain accents, and in most cases, these are simply outright skipped.
- Fake month names are capitalised. In Hungarian, month names are non-capitalised.
- Name in credit card generator has 'Western' naming order
- `fake.street_address()`, `fake.address()` and `fake.street_address_with_county()` return a capitalised result
- `fake.street_address_with_county()` is in a wrong format
- `fake.color_name()` returns English result
- `fake.company_suffix()`, `fake.bs()` and `fake.catch_phrase()` return English results
- `fake.currency_code()` should return `HUF`
- `fake.isbn()` should be Hungarian, not 978 (the fictitious `Bookland`)
- `fake.job()` is still in English
- `faker.providers.lorem` are still in English
- `faker.providers.profile` should generate coherent name-mail-sex-username combos!
-  telephone numbers should use the standard `(20) 123-4567`, `(1) 234-5678` or `(21) 234-567` formats only

**Comment by Newman101** [comment]
Hi. Thanks for the feedback! I'm running some tests today and we'll see what can be improved. =)

**Comment by Newman101** [comment]
```fake.company_suffix()``` returns now Hungarian results.

**Comment by fcurella** [comment]
Closed By #504

**Comment by fcurella** [comment]
reopening, all other Hungarian providers still have the mentioned issues

**Comment by Newman101** [comment]
Accents have been removed from domains and e-mail addresses.

**Comment by Newman101** [comment]
Months + days of the week implemented.

**Comment by Newman101** [comment]
Task list: 

- [x] E-mail addresses and domains
- [x] Month names
- [ ] Credit card generator
- [ ] Capitalize street addresses
- [ ] Capitalize addresses with a country
- [ ] Localize colors
- [x] Localize fake.company_suffix()
- [ ] Localize fake.bs() and fake.catch_phrase()
- [ ] Localize fake.street_address_with_county()
- [ ] Localize fake.currency_code()
- [ ] Localize fake.isbn()
- [ ] Localize fake.job()
- [ ] Localize faker.providers.profile
- [ ] Localize telephone numbers

**Comment by Newman101** [comment]
@chrisvoncsefalvay: I am not native Hungarian speaker so I need some assistance. Can you point me to a decent source of colours in Hungarian language please? 

Thank you.

**Comment by n1ngu** [comment]
I'd add: the color provider does not work at all! Try this out
```
$ python -m faker -l hu_HU safe_color_name
$ python -m faker -l hu_HU color
$ python -m faker -l hu_HU hex_color
$ python -m faker -l hu_HU rgb_color
```
etc
