### ISSUE TITLE
pt_BR email not returning valid email addresses

### ISSUE THREAD

**Issue by ghost** [joke2k/faker#491]
When creating a fake Factory with the pt_BR it is not returning valid email addresses.
Example:
```
melocauã@bol.com.br
joão-gabrielferreira@ig.com.br
lavíniarodrigues@sales.org
vitória78@example.br
```

**Comment by J535D165** [comment]
Same kind of issue as #455. It's not a country/language specific issue.

**Comment by paternal** [comment]
Although it is generally not advised to have "weird" characters in email address, they are not forbidden by the specification (see for instance [this](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/) or [that](https://en.wikipedia.org/wiki/Email_address#Local-part)).

However, this is so rare and unsupported by a lot of platforms that faker should probably generate only ascii email addresses…

**Comment by fcurella** [comment]
I would accept a PR, if anybody is willing to work on it

**Comment by clarmso** [comment]
@fcurella I am tempted to work on a PR addressing this issue.  Would slugify from faker/utils/text.py be the proper place to tackle?

**Comment by fcurella** [comment]
@clarmso thank you for volunteering! What's needed is a 'replacements' attribute on the provider, such as in https://github.com/joke2k/faker/blob/master/faker/providers/internet/fr_FR/__init__.py#L12

Could you also add the same to pt_PT? I would assume they would need the same replacements

**Comment by dvdmgl** [comment]
@clarmso @fcurella also can make a PR

Found this bug in my tests, last place that i checked was Faker, a lot of time wasted...
my 2 cents, escape all latin1 https://unicodelookup.com/#latin
```python
replacements = (
    ('À', 'a'), ('Á', 'a'), ('Â', 'a'), ('Ã', 'a'), ('Ä', 'a'), ('Å', 'a'),
    ('à', 'a'), ('á', 'a'), ('â', 'a'), ('ã', 'a'), ('ä', 'a'), ('å', 'a'),
    ('Ç', 'c'), ('ç', 'c'),
    ('Ñ', 'n'),
    ('È', 'e'), ('É', 'e'), ('Ê', 'e'), ('Ë', 'e'),
    ('è', 'e'), ('é', 'e'), ('ê', 'e'), ('ë', 'e'),
    ('Ì', 'i'), ('Í', 'i'), ('Î', 'i'), ('Ï', 'i'),
    ('ì', 'i'), ('í', 'i'), ('î', 'i'), ('ï', 'i'),
    ('Ò', 'o'), ('Ó', 'o'), ('Ô', 'o'), ('Õ', 'o'), ('Ö', 'o'), ('Ø', 'o'),
    ('Ù', 'u'), ('Ú', 'u'), ('Û', 'u'), ('Ü', 'u'),
    ('Ý', 'y'),
    ('Æ', 'ae'),
    ('Ð', 'eth'),
    ('Þ', 'thorn'),
    ('ß', 'sharp'),
    ('æ', 'ae'),
    ('ð', 'eth'),
)
```
