### ISSUE TITLE
Allow subdomains in domain_name()

### ISSUE THREAD

**Issue by thiagofigueiro** [joke2k/faker#505]
Sometimes it's useful to test domain names that contain subdomains.  Currently, domain_name() can only return domain names composed of domain_word + . + domain_tld.

I propose to modify domain name to accept an optional parameter to specify the domain depth.  Example:
```python
        >>> domain_name()
        nichols-phillips.com
        >>> domain_name(2)
        williamson-hopkins.jackson.com
```

**Comment by joke2k** [comment]
Implemented in #506
