### ISSUE TITLE
Using É, é (e-acute)  in emails.

### ISSUE THREAD

**Issue by Bergil32** [joke2k/faker#511]
It looks that É, é (e-acute) symbols are not appropriate for valid email. I used https://pypi.python.org/pypi/robotframework-faker/ which uses this library and the following email was returned: 
andré38@mentzel.net

But email verification was failed for this email. 
Could you remove É, é and other such letters if they are present from valid email generation?

**Comment by fcurella** [comment]
Thanks for the report @Bergil32 .

What version of faker are you using and what locale is having this problem?

**Comment by Bergil32** [comment]
robotframework-faker 4.0.0 that uses Faler 0.7.11
It was detected for de_DE locale.

**Comment by fcurella** [comment]
The `É` and the `é` are missing from https://github.com/joke2k/faker/blob/master/faker/providers/internet/de_DE/__init__.py#L14

@Bergil32 Can you submit a PR with the appropriate replacements?

**Comment by Bergil32** [comment]
@fcurella thanks
