### ISSUE TITLE
Adding locale in python script

### ISSUE THREAD

**Issue by BLCKPSTV** [joke2k/faker#516]
Where or how do I add the -l flag with the locale in a python script!? In the terminal command I get how it works but the same doesn't work for the python script way.

Anybody care to explain how this is done or how approach this?

**Comment by fcurella** [comment]
Hi @BLCKPSTV ,

To explicitly set the local on the provider, you create an instance of factory with the locale string that you want:

```
from faker import Factory
fake = Factory.create('it_IT')
fake.name()
```
see: https://faker.readthedocs.io/en/latest/#localization

**Comment by BLCKPSTV** [comment]
Thanks!

I have following questions and not sure where else to ask them, because these are not issue's but more guidance question. I'll ask them any way and maybe they can be used as supplement example on the pypi page. 

1. When fake.profile(fields=None, sex=None) => where does fields stand for? And second If I change sex in to Female or Male it gives me an error `NameError: name 'Female' is not defined
` the define part is between brackets of the `fake.profile()` or is it one step higher, at the `Factory.create()? `

2. Second in the example of the the `fake.profile()` the output is aligned under each other for each new rule. How do I achieve this? In the examples it's done with `-s=";"` but this is again in the terminal output and not as a python script. I tried adding in to `Factory.create()` and `fake.profile() `but did not work. 
3. In the example it starts with adress and ends the website, I would like to start with a name and end with the website. (Now it starts with website and ends with email, as there is no straight order)

4. Lastly a really non related issue, and just a not knowing on my behalve part, how can I use the outcome as a new set for a another lib that I use in the script.
e.g.= I use the Japanese local and sometimes I want the kana translated in to roman. 

Thanks!
```
fake.profile(fields=None, sex=None)
# {   'address': '561 James Rest Apt. 960\nThomastown, NC 00410-0087',
#     'birthdate': '1997-11-09',
#     'blood_group': 'A+',
#     'company': 'Aguirre-Larsen',
#     'current_location': (Decimal('7.055488'), Decimal('148.641730')),
#     'job': 'Agricultural consultant',
#     'mail': 'msmith@yahoo.com',
#     'name': 'Robert Byrd',
#     'residence': '0765 Zachary Course\nEast Eric, MT 95660-5148',
#     'sex': 'M',
#     'ssn': '104-27-9627',
#     'username': 'qcasey',
#     'website': [   'http://www.williams.net/',
#                    'http://johnson-williams.com/',
#                    'http://www.bauer.com/',
#                    'https://chapman.biz/']}
```
1.

**Comment by fcurella** [comment]
1. the `fields` argument can be a list of strings of the fields you want. Valid values are any of the keys you see in the docs for the returned object (eg `['address', 'birthday', 'blood_group']`. The only valid values for `sex` are `'M'` or `'F'`

2. I'm not sure what you mean by 'aligned'. What you get back is a `dict`, not some string.

3. `dict`s are unsorted in python. To create a `dict` that can be sorted, you could use `collection.SortedDict`, and add the keys in the order that you want.

4. You'll have to provide your romanization logic. Alternatively, if you only need first name and last name, you can use the `. romanized_name` method from the `jp_JP` `person` provider. Or you can create a localize `profile` provider for `jp_JP` (we only have `en_US` at the moment)

**Comment by BLCKPSTV** [comment]
awesome!! thanks! 

Last following question, I don't get (after reading documention twice) where the romanized name method should go. Is this in the factory create? And this only works for jp_Jp or also for Persian?

**Comment by BLCKPSTV** [comment]
Nevermind! Found it! :)
