### ISSUE TITLE
python providers should use value_types as a keyword argument

### ISSUE THREAD

**Issue by mhubig** [joke2k/faker#525]
Some of the python providers use a slightly unusual function call signature like this:

```
fake.pydict(nb_elements=10, variable_nb_elements=True, *value_types)
fake.pylist(nb_elements=10, variable_nb_elements=True, *value_types)

```
This leads to some usage problems with factory_boy (https://github.com/FactoryBoy/factory_boy/issues/387).

IMHO it would be much more convenient to be able to call the python providers with `value_types` as a keyword argument like so:

```
fake.pydict(nb_elements=10, variable_nb_elements=True, value_types=['str'])
fake.pylist(nb_elements=10, variable_nb_elements=True, value_types=['str'])

```

I know this would introduce a braking change to the python provider api, but if this is acceptable I can try to provide a PR.

**Comment by kungfu71186** [comment]
Looks like it's already implemented. Unless I'm misunderstanding

**Comment by joke2k** [comment]
Hi @mhubig, it seems reasonable.
To handle the backcompatibility we could use some signature like that:
```
fake.pydict(nb_elements=10, variable_nb_elements=True, value_types=None, *allowed_types)
fake.pylist(nb_elements=10, variable_nb_elements=True, value_types=None, *allowed_types)
```
Combining `values_types` and `allowed_types` carefully.

**Comment by fodra** [comment]
I agree this confused me a little bit.

At first I was doing this
```
>>> fake.pydict(nb_elements=5, variable_nb_elements=False, ['str', 'str', 'str', 'str', 'str'])
  File "<input>", line 1
SyntaxError: positional argument follows keyword argument
```

Figured out you should not use the keywords if you want to specify value_types
```
>>> fake.pydict(5, False, 'str')
{'kind': 'NNxcLDYxjKXcCypxOanT', 'social': 'RfNzeHzBFhcHdEbUMiGL', 'article': 'HrTMTBGFOAcsUAibdVRo', 'per': 'gwZMuksrnrvMyVPXAkJB', '
imagine': 'RkvSHFrUMESRLIQDgkxL'}
```

I hope this helps someone going through the same issue.

**Comment by fcurella** [comment]
the `value_types` argument in `pydict` is a variable-lenght number, ie it's specified as `*value_types`.

The correct way to call it would be something like:
```
>>> fake.pydict(nb_elements=5, variable_nb_elements=False, 'str', 'str', 'str', 'str', 'str')
```

**Comment by marcosschroh** [comment]
Hi all,

Is someone working on this? @mhubig

**Comment by andorend** [comment]
I know it is not a good thing to do to modify a library directly but there is tested workaround (I have also tried it) of the factory_boy but it is not pulled/released yet: 

[FactoryBoy/factory_boy#456](https://github.com/FactoryBoy/factory_boy/pull/456
)

Hopefully it will be in the released version soon.

**Comment by ThibaultLemaire** [comment]
**This is not only true for FactoryBoy compat.**

I agree with @fodra: `value_types` passed as variable arguments not only forces you out of named argument passing -- which really is a shame for boolean arguments -- but also makes the syntax weird enough to be confusing (and python's syntax errors don't help you there, cf. #366).

**Comment by fcurella** [comment]
I think it would be ok to break compatibility, as long as we release a new major version.

**Comment by DanLipsitt** [comment]
As a first step, it would be great to add @fodra's workaround [above](#issuecomment-377084985) added to the documentation. What would be the right place to do that?
