### ISSUE TITLE
Factory doesn't import

### ISSUE THREAD

**Issue by nipponaihito** [joke2k/faker#562]
`from faker import Factory` doesn't work. It says 'Cannot import Factory'. Looking at __init.py__ in the package I see `from faker.factory import Factory` to import the class. So I try that and I get `Cannot import Generator`. Changing `factory.py` to have `from faker.generator import Generator` allows the import to go through. The documentation doesn't appear to state this is neccessary.

**Comment by fcurella** [comment]
Hi @nipponaihito 

Is `from faker import Faker()` working for you? And what version of `Faker` are you using?

**Comment by cvetkoff** [comment]
same problem. `from faker import Faker()` doesn't work too. Faker version 0.7.18

**Comment by fcurella** [comment]
@cvetkoff could you check if it still happens on `v0.8.0`?

If so, I need more info about your environment, because I can't get to reproduce the error. In particular, I need to know OS and locale.

**Comment by cvetkoff** [comment]
Yes, first environment on my iOS app Pythonista, the same problem (v.0.8.0) and on my Mac OS Sierra Python 3.6 both locale RU, UTF8
