### ISSUE TITLE
Include faker-e164 in community providers

### ISSUE THREAD

**Issue by aljp** [joke2k/faker#564]
[I've written a provider specifically for generating E164 formatted phone numbers](https://github.com/crowdcomms/faker-e164) called faker-e164.

I intend on building out more faker providers for different phone number formats, and potentially consolidate those providers down the line).

Two questions:
 - Would you like to include this in your community providers?
 - Do you have any changes you'd recommend for this provider?

**Comment by fcurella** [comment]
Something I'd change is making it a localized provider for all locales in the region that you support, which means resolving the `region_code` argument based on the local and removing it from the provider's API.
