### ISSUE TITLE
Cannot seed datetime generator

### ISSUE THREAD

**Issue by ndbradley730** [joke2k/faker#566]
The faker lib allows you to seed Python's `random` instance, and the expected result is that all faker calls will have deterministic results every time the code is run. But the datetime generator relies on the `unix_time()` method, which drifts based on the current time:
```
@classmethod
def unix_time(cls):
    """
    Get a timestamp between January 1, 1970 and now
    :example 1061306726
    """
    return random.randint(0, int(time()))
```
The usage of time() as the end date means that datetime results change over time, even if random has been seeded.

I suggest making these methods accept an optional `end_datetime` (maybe `start_datetime` as well) parameter that would let the caller set the range of acceptable datetimes. That would allow users seeding random to get deterministic results.

**Comment by kungfu71186** [comment]
@fcurella Was this fixed? I went to go test this right now, when seeding I seem to get the same expected value. 

`import unittest

class SeedTimeTestCase(unittest.TestCase):
    def test_seed_time(self):
        from time import time
        import random
        
        for _ in range(100):
            seedint = random.randint(0,123456789)
            random.seed(seedint)
            prev = random.randint(0, int(time()))
            for j in range(100):
                random.seed(seedint)
                curr = random.randint(0, int(time()))
                self.assertEqual(curr, prev)
                prev = curr
                
                #No seed, should be different now
                curr = random.randint(0, int(time()))
                self.assertNotEqual(curr, prev)

if __name__ == '__main__':
    unittest.main()
`

**Comment by fcurella** [comment]
@kungfu71186 i dont think it's fixed. I'm still waiting on a PR to add the requested feature

**Comment by fcurella** [comment]
@kungfu71186 I think the issue is that the range of `randint` increments by 1 every second. Try putting a `time.sleep(1)` somewhere in the loop

**Comment by kungfu71186** [comment]
I see now. It's has to be way more than a second. for instance

```
random.seed(1)
random.randint(0,11999999999)
random.seed(1)
random.randint(0,10000000000)
```

will be the same output. 

Ok, i can do a PR for this
