### ISSUE TITLE
Add more command line example please?

### ISSUE THREAD

**Issue by jiming** [joke2k/faker#579]
1. I wanted to generate a csv content but not work
`faker -r 30 -s ',' name,address`

2. Can I use random_element like this?
`faker -r 30 -s ',' random_element('a','b','c')`

3. Add command options like this:
`faker --list-providers`

Have a nice day!

Jiming

**Comment by greggles** [comment]
I used `faker -h` to get help text. From that help text I figured out the syntax of the first example needs to use the `profile` argument:

> faker -r 30 -s ',' profile name,address

I think the second and third ideas are just not possible so they would be feature requests and not a documentation request.

**Comment by greggles** [comment]
Cool to see the bot cleaning up the queue, but this feels like a worthwhile issue that should be pretty easy to achieve.
