### ISSUE TITLE
Are images outside of the scope of this project?

### ISSUE THREAD

**Issue by wengole** [joke2k/faker#58]
Hi,

We're using this currently in our tests to generate test data. However we'd also like to use it to generate sample HTML pages (blog posts - for example). For this it would be great if faker could have an image provider (or maybe a file provider as a lower level).

Would you be averse to this idea? If not I'm more than happy to work on the provider and submit a pull request.

Cheers,
Ben

**Comment by malefice** [comment]
@fcurella this looks like it can be closed as there is already an `image_url` provider method.

**Comment by fcurella** [comment]
Thank . you @malefice !
