### ISSUE TITLE
Method randomize_nb_elements can generate 0

### ISSUE THREAD

**Issue by blokfyuh** [joke2k/faker#581]
Hi everyone,

Just to let you know that the method **_randomize_nb_elements_** of the BaseProvider is implemented in a way that it can returns 0 (e.g. if the randint is below 100), but this method is called from the **_sentence_** method of the LoremProvider which will break if the randomized number of elements is 0. Because it will try to generate a sentence of 0 word and access the first element.

Where it is used:

    if variable_nb_words:
        nb_words = self.randomize_nb_elements(nb_words)

Where it breaks:

    words = self.words(nb=nb_words, ext_word_list=ext_word_list)
    words[0] = words[0].title()

PS: Faker version => 0.8.0

**Comment by haakenlid** [comment]
This bug broke my automated tests. A workaround is to call `sentence` with the parameter `variable_nb_words = False`.

**Comment by fcurella** [comment]
@haakenlid `v0.8.1` is supposed to revert the offending change. Is it not working for you?

**Comment by blokfyuh** [comment]
@haakenlid Thanks for the tips but I didn't want to change the client code. 
@fcurella Yes, the rollback is working for me.
