### ISSUE TITLE
Reproducibility of results broken between Faker-0.7.18 and (Faker-0.8.0, 0.8.7)

### ISSUE THREAD

**Issue by sp-1234** [joke2k/faker#586]
Faker-0.8.0 and Faker-0.7.18 generate different values when given the same `random` source.

Is the deterministic generation a goal of the project or not? I assumed that it is before… because the README specifically says that it's useful for unit testing, which is how I use it.

**Comment by sp-1234** [comment]
Hmm, it's probably because `random` was renamed to `__random` in the generator…

**Comment by sp-1234** [comment]
Seems like the `text()` generator is the offender.

I tested this code under Python 3.6.2:
```
from faker import Faker

def create_deterministic_faker(seed):
    fake = Faker()
    fake.seed(seed)
    fake.binary = lambda length: fake.random.getrandbits(8 * length).to_bytes(length, byteorder='big', signed=False)
    return fake

def main():
    f = create_deterministic_faker(1)
    print(f.name())
    print(f.domain_name(levels=1))
    print(f.text())
    print(f.binary(4))
    print(f.random.randrange(0, 42))
    pass

if __name__ == '__main__':
    main()
```

Output with Faker 0.7.18:
```
Ryan Gallagher
wilson-hodges.info
Consequatur placeat aliquam molestias non sequi. Voluptatem occaecati fugiat eum. Corporis ipsum aliquam adipisci alias totam quis accusamus modi. Nisi aliquam quia est nulla possimus.
b'\xd8\xa0d\xdf'
32
```

Output with Faker 0.8.0:
```
Ryan Gallagher
wilson-hodges.info
Consequatur placeat aliquam molestias non. A voluptatem occaecati fugiat eum rerum corporis ipsum. Adipisci alias totam.
b'\xf3\xc6J\xf7'
18
```

Note that everything starts to diverge after number of words in first sentence got different.

Can you please roll back the formula used for default text generation? Or at least promise to not change it again in the future?

**Comment by sp-1234** [comment]
Found the culprit, it's in this commit https://github.com/joke2k/faker/commit/04f697a90df185ef8d7b2730c8e0fcab4096aeb3
Can you please roll back this change? Or it's somehow necessary to do this breaking change?

**Comment by fcurella** [comment]
Hi @sp-1234 

I've published `v0.8.1` as an emergency release with rolls back 04f697a.

That commit fixes an incorrect behaviour, so it will need to go in eventually. I'm investigating the best way to do it.

**Comment by blokfyuh** [comment]
Hi @sp-1234,
It's funny because somehow the culprit commit you've posted is related to my issue posted few days ago #581 . Removing the "+ 1" broke things for me as well...

**Comment by fcurella** [comment]
@sp-1234 @blokfyuh Could check if my solution at https://github.com/joke2k/faker/pull/587 works for your case?

**Comment by blokfyuh** [comment]
Thanks @fcurella for the fix. Does your master branch is deployed to pip automatically or do I have to pip install from git ?

**Comment by fcurella** [comment]
@blokfyuh it's already on pip

**Comment by sp-1234** [comment]
pip sees latest version Faker-0.8.1. Does it mean that 
https://github.com/joke2k/faker/pull/587 is not available yet?

**Comment by fcurella** [comment]
@sp-1234 I havent published #587 yet, since I don't have confirmation that it works, yet.

You'll have to call `pip install "git+https://github.com/joke2k/faker.git@nb-elements"`

**Comment by adamchainz** [comment]
Just came on to say I also noticed the reproducibility break whilst upgrading my pytest plugin for reproducible random unit test runs, in adamchainz/pytest-randomly#72 . I don't think it's too much of a problem if you break reproducibility, but it should probably be considered semver major.

**Comment by reverbc** [comment]
Sorry for causing this reproducibility issue, but IMHO, I believe faker user should not hard-coded the generated random value in their code.

The random value after seeding should be consistent within the same version, i.e. when user uses faker v0.7.18, every time he/she invokes the same code it should provide the same result, and v0.8.0 does provide this consistency.

It's possible for contributors to alter the test data set (probably correct the format or adding more details to generate more real-life like data), so even if we have this fix on #587, those user uses hard-coded value will encounter issue at that time anyway.

I use faker for generating unit test fake data set as well, and my usual pattern might look like the following example:

```
import pytest

@pytest.fixture(scope='function')
def faker():
    import faker as Faker
    faker_instance = Faker.Faker()
    faker_instance.seed(9527)
    return faker_instance

def foo(input_data):
    return input_data

@pytest.mark.parametrize('input_amount', [0, 1, 2, 10])
def test_foo_method(faker, input_amount):
    input_data = [faker.uuid4() for _ in range(input_amount)]

    foo(input_data)

    for data in input_data:
        assert data in input_data
```

In this way we don't need to have any magic number/string in our test code, and the code should be able to survive throughout different faker version.

However, if having fixed data set across different faker version does has it's use case and can't be replaced, we should have a new set of unit test to verify this feature otherwise it will very likely to break again in the future.

**Comment by fcurella** [comment]
I think #587 fixes the issue retaining backwards compatibility. Can any of you @sp-1234 @blokfyuh @haakenlid or @adamchainz try it out?

**Comment by blokfyuh** [comment]
@fcurella In your fixes #587, you forgot to add the keyword argument min=1 when calling randomize_nb_elements in then sentence method:

        if variable_nb_words:
            nb_words = self.randomize_nb_elements(nb_words, **_min=1_**)

        words = self.words(nb=nb_words, ext_word_list=ext_word_list)
        words[0] = words[0].title()

**Comment by adamchainz** [comment]
Actually @reverbc, you're right, consistency within the same version of faker is the most important. The tests for my plugin for tests just get this problem because they're on the meta level, I guess I should expect that.

**Comment by fcurella** [comment]
@blokfyuh nice catch! but let's keep the code review on #587

**Comment by fcurella** [comment]
if the only problem with #587 is consistency, I think it should be ok to merge it and issue a new major version.

**Comment by blokfyuh** [comment]
Yep, you're right, sorry for that. I don't have a lot of experience regarding Github processes.

**Comment by adamchainz** [comment]
What I thought here was just a reproducibility change was actually a bug in the API of how to re-seed faker, as per #591 . So no worries about reproducibility per se from me.

**Comment by sp-1234** [comment]
0.8.3 seems to be fine, maybe it's time to close this

**Comment by sp-1234** [comment]
Again, 0.8.7 produces different results than 0.8.3

**Comment by sp-1234** [comment]
Can you please officially state what version is correct and stick to it in the future?

**Comment by fcurella** [comment]
@sp-1234 Since we keep updating data in the providers pretty much at every release, we'll keep breaking the reproducibility at every release.

Maybe we should just stop using semver entirely and switch to date-based versioning.

**Comment by adamchainz** [comment]
I think it's fine to use semver, just add a notice that the data inside the providers is subject to change between versions, and that the only guarantee of reproducibility is when using the same faker version.
