### ISSUE TITLE
Reseed code broke in 0.8 unnecessarily

### ISSUE THREAD

**Issue by adamchainz** [joke2k/faker#591]
Commit ea4f189bbff1925d7a7e2d7cbc6e91e2e8a9a3f3 changed the name of the `random.Random()` object in `faker.generator` from `random` to `mod_random`, re-exposing the `random` module as the name `faker.generator.random`. This broke code like:

```py
from faker.generator import random
random.seed(1)
``` 

which is basically what my `pytest-randomly` plugin does. At first I thought this was #586 but then I saw that every run was broken. The failure is silent because `random` is still a name in `faker.generator`, it just now points at the global `random` module 😱

I suggest just doing some renaming in the module to fix this so old code continues to work.

**Comment by fcurella** [comment]
@adamchainz I don't think we ever documented such way to seed Faker.

That said, if we can fix it the issue and keep the functionality, we should do the rename. More importantly, if Faker.generator.random is to be relied on, it should be documented somewhere

**Comment by guykisel** [comment]
I actually used similar behavior that seems to have broken in 0.8.0 at https://github.com/guykisel/robotframework-faker/blob/master/robotframework-faker/FakerLibrary/keywords.py#L55-L56

For now I've just pinned to <0.8.0 but I was planning to poke around and see how to fix compatibility between my wrapper and 0.8.0.

**Comment by fcurella** [comment]
@adamchainz @guykisel FYI I've released `v0.8.3`, which includes #592

**Comment by guykisel** [comment]
@fcurella thank you <3

**Comment by adamchainz** [comment]
🎉 thanks🚀
