### ISSUE TITLE
dutch safe_email contains non-email characters

### ISSUE THREAD

**Issue by robkorv** [joke2k/faker#612]
I get `daniël34@example.com` as value, which doesn't validate as an email address.

A solution like https://github.com/joke2k/faker/pull/509 would be cool.

**Comment by fcurella** [comment]
Thanks @robkorv ! Feel free to submit a PR for the `nl_NL` internet provider. You can just follow what it's in #509

**Comment by fcurella** [comment]
should be fixed by #609.
