### ISSUE TITLE
Uk mobile number

### ISSUE THREAD

**Issue by Ehmed-kino** [joke2k/faker#622]
It seems like the uk mobile number is not in the right format 
it's completely not valid
some examples of them: 
+44(0)9128 405119
(01414) 35336
01231052134

**Comment by fcurella** [comment]
Hi @Ehmed-kino , thank you for reporting this.

Could you submit a PR with the correct formats?

**Comment by jacobbudin** [comment]
On second thought, #626 may not "fix" this issue since `cellphone_number` was previously unimplemented for `en_GB`. I may have misunderstood by assuming `cellphone_number` "defaults" to `phone_number` in some interfaces.
