### ISSUE TITLE
Locales for cs_CZ fake.name_male() shows a female name

### ISSUE THREAD

**Issue by quapka** [joke2k/faker#625]
Looking at the very last example [here](https://faker.readthedocs.io/en/latest/locales/cs_CZ.html#faker-providers-misc). The name is actually a female name.

```
fake.name_male()
# 'Ing. Sára Mašková CSc.'
```

**Comment by fcurella** [comment]
Thank you for the report @quapka ! could you submit a PR to fix the issue?

**Comment by quapka** [comment]
Yes I can, I did no have time at the moment of writing this issue.

**Comment by quapka** [comment]
Hmm, I've forked the code and search for the problem, but could not find it. I glimpsed over `/faker/providers/person/cs_CZ/__init__.py` and it looks alright.

It can be only a mistake in the docs maybe? I'm unsure how the
```
fake.name_male()
# 'Ing. Sára Mašková CSc.'
actually ends up there though.

**Comment by clarmso** [comment]
I do not speak Czech, but I can tell the following output is a female name:

fake_cs_cZ.name_male()
'Emilie Poláková'
