### ISSUE TITLE
Unidecode dependency GPL license

### ISSUE THREAD

**Issue by richardowen** [joke2k/faker#628]
In commit adc1b1b a dependency on the Unidecode python package was introduced.

Unidecode is released under the GPL license while Faker is using MIT. I'm concerned that this might not be permitted by the GPL license and that users of the Faker library might not realise they are introducing GPL code into their dependencies. It could be argued that any code using the Faker library now has to be licensed under the GPL too.

See here for some opinions on using GPL libraries:

https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l
https://softwareengineering.stackexchange.com/questions/87446/using-a-gplv3-python-module-will-my-entire-project-have-to-be-gplv3-licensed
https://opensource.stackexchange.com/questions/2139/can-i-license-python-project-under-3-clause-bsd-while-it-has-gpl-based-dependenc
https://opensource.stackexchange.com/questions/6062/using-gpl-library-with-mit-licensed-code

I'm not an expert in this area at all, just a concerned user!

**Comment by fcurella** [comment]
Thanks for the report @richardowen .

I've switched to `text-unidecode` (which is licensed under the Artistic License), and release a new version of `Faker`
