### ISSUE TITLE
Base provider methods are documented with the address provider.

### ISSUE THREAD

**Issue by 153957** [joke2k/faker#642]
In the docs the [BaseProvider methods](https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py) are grouped with the [address provider](https://github.com/joke2k/faker/blob/master/faker/providers/address/__init__.py). Here is the documentation: http://faker.readthedocs.io/en/master/providers/faker.providers.address.html

I would expect those to be in their own category, and they have nothing to do with addresses.

**Comment by malefice** [comment]
Duplicate of #832
