### ISSUE TITLE
Maintain Consistency

### ISSUE THREAD

**Issue by vyshaliN** [joke2k/faker#653]
Need to use Faker and create anonymized values such that it is consistent across multiple faker instances.
For example,
When the faker instance is created and generates fake values for the name "vyshali" as "George Harris".I need the same fake value to be generated when I create a faker instance.
Please help me with required methods or documentation

**Comment by fcurella** [comment]
Hi @vyshaliN ,

What you need to do is seeding the generator with a constant number. Take a look at http://faker.readthedocs.io/en/master/index.html#seeding-the-generator for some example

**Comment by vyshaliN** [comment]
hi,

Thanks for the reply.I had a look at this documentation before.If we use the constant number,the same output is obtained even when the input is changed.I don't want that to happen.

for example,if I use
faker.seed_instance(1234) and obtain output for "Vyshali" as "George Harris".
I'm getting the same output "George Harris" if I change the input as "Divya"

**Comment by kungfu71186** [comment]
This is exactly what seed is for. If you convert vyshali to an int and use that as input, you get the same output no matter what. You need to randomize the seed while keeping it constant based on input. At this point it's up to your interpretation on how to do that as no one knows what your data does or how it works. Faker has implementations to allow you to do this.

**Comment by vyshaliN** [comment]
My requirement is to create some mapping between the original and the fake data i.e. only "George Harris" should be generated for the input "vyshali".I don't want to randomize the seed based on the input.How can we achieve this kind of semantic relationship using Faker across multiple instances ?

**Comment by kungfu71186** [comment]
Thats up to you on how you want to implement the mapping. But the means is there. Use the seed to set a specific seed to get expected output.

You have an input that changes. Use that for the seed.

**Comment by vyshaliN** [comment]
The means is there but this is not working for dataset taken as batches and given as input for anonymization. Because I would have same output (having seed constant) for different values.So,there is no consistency maintained throughout.

**Comment by kungfu71186** [comment]
I literally gave you a way to do it. `If you convert vyshali to an int and use that as input, you get the same output no matter what.` I'll quote it again. You are taking an input, converting it to some int for the seed. I don't really know what else to say.

I have the same issue that I had to solve. I took different parameters and created a seed from that. I get expected output, while getting random data.

Otherwise, just create your own data set and map it.

**Comment by fcurella** [comment]
@vyshaliN suppose you have the following code:

```
names = ['vyshali', 'Real Name1', 'Real Name2', 'vyshali', 'Real Name2']
```
and you want to convert it to something like:

```
anonymized_list = ['George Harris', 'John Smith', 'Alice Ross', 'George Harris', 'Alice Ross']
```

Your mapping code would look something like (assuming python3):

```
from faker import Faker


fake = Faker()
anonymized_list = []
for name in names:
    fake.seed_instance(name)
    anonymized_list.append(fake.name())
```

**Comment by vyshaliN** [comment]
Awesome..thank you so much!! @fcurella and @kungfu71186

**Comment by kungfu71186** [comment]
@vyshaliN 

Another solution would be something like

 sum([ord(x) for x in 'vyshaliN']) which will give you a seed number. 

Or you can do something like

import hashlib
int(hashlib.md5(b'vyshaliN').hexdigest(), 16)

again, this would give you a seed you can then use.
