### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by vyshaliN** [joke2k/faker#654]
I have written the code for anonymization  and executing the code in Nifi using executescript processor and also running as normal python script.I'm getting different results of anonymization for both the flows even though the input is same.I have made the results of anonymization to be consistent by using seed() function.So really confused and surprised on why I'm getting different results for both the flows.

**Comment by kungfu71186** [comment]
When you opened an issue. There should be a template. It should be something like steps to reproduce. What the expected outcome is and the actual outcome. Do you mind adding all that info in the issue? Thanks!

**Comment by vyshaliN** [comment]
Cool..I have taken a dataset with three values -> name,email,ssn

Sample dataset :
Sharmila,sharmismithy@redmail.com,999-12-0000
narasimha srinivasan,narasimma_srinivasan@gmail.com,222-26-789
avyukt,vysh234@redmail.com,456-89-5678

I have used seed functionality for maintaining consistency in the results of anonymization. So,I should get same results for multiple faker instances.I'm using the anonymizing code as normal python script and also executing in Nifi using executescript processor.

When I run as **python script**,I'm getting the following output,
Scott Bryan,bbeck@yahoo.com,712-48-4862
James Miranda,bradykaitlyn@hotmail.com,446-57-4047
James Jordan,fgarcia@hotmail.com,887-47-4663

When I execute the script in **Nifi** using executescript processor,I'm getting the following output:
Andrew Simon,dncanrobert@hawkins.com,621-02-7781
Gregory Grant,michelle50@yahoo.com,709-80-9027
Holly Nelson,bchang@yahoo.com,867-56-9800

I'm not sure why the same input is giving different results due to different cirucumstances where it is put into same kind of action.

**Comment by fcurella** [comment]
@vasilcovsky I've never used Nifi, but from a quick search looks like executescript runs in Jython, while your python script is probably CPython or PyPy.

I think you may be getting different results because of the different implementation of the `random` module in CPython vs Jython.

**Comment by vyshaliN** [comment]
I just checked the random module in Jython and Python.It is more or less the same implementation.Will there be any other reasons for different results ?

**Comment by kungfu71186** [comment]
Could be something similar to this issue

https://stackoverflow.com/questions/8003460/jython-random-module-produces-different-results-to-cpython

The implementation might be similar, but you may get different results even with the same seed.

**Comment by kungfu71186** [comment]
So. After reading over the python docs. Random is not guaranteed between different versions of python. Only guarantee is that a seed with produce the same results. Now with that said, it might be possible to gaurantee a result no matter the os or version. If we write a random function ourselves, it would be the same everywhere. I would suggest if going down that route, it would simply be a way to override the builtin random function in extreme cases like this. One way to do this is to generate a hash and convert that to a float. This should be good enough even with collisions here and there. 

As far as how to implement that, basically setting the random generator function to something else, I'm not entirely sure of how to do that.

**Comment by vyshaliN** [comment]
@kungfu71186 Thanks for your suggetion
