### ISSUE TITLE
Can not sub class Faker

### ISSUE THREAD

**Issue by manoadamro** [joke2k/faker#657]
Was hoping to extend the Faker class with some extra fields

### Steps to reproduce

```python
from faker import Faker

class MyFaker(Faker):

    def something(self):
        return 'i work!'

f = MyFaker()

print(f.name())
print(f.something())
```

### Expected behavior

Should either give an error saying Faker is final or allow me to sub class it

### Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Path/To/Python/File.py", line 5, in <module>
    class MyFaker(faker.Faker):
TypeError: method expected 2 arguments, got 3
```

**Using Factory does not work either:**

### Steps to reproduce

```python
from faker import Factory

class MyFaker(Factory):

    def something(self):
        return 'i work!'

f = MyFaker()

print(f.name())
print(f.something())
```

### Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aromano/Documents/GitHub/mock-kong/faker_test.py", line 11, in <module>
    print(f.name())
AttributeError: 'MyFaker' object has no attribute 'name'
```

**Comment by kevin-brown** [comment]
This is because `Faker` is not actually a class, instead [it's a method](https://github.com/joke2k/faker/blob/0d036eed9a3c0dc2cad5329802abc00aab702fe8/faker/__init__.py#L6). So you can't use it like a class and subclass based on it.

**Comment by fcurella** [comment]
@manoadamro as @kevin-brown points out, `Faker` is an alias to the `create` classmethod. You'll have to use your subclass' `create` as well. Try this:

```
from faker import Factory

class MyFactory(Factory):

    def something(self):
        return 'i work!'

MyFaker = MyFactory.create

f = MyFaker()

print(f.name())
print(f.something())
```
