### ISSUE TITLE
Option for emitting safe phone numbers only

### ISSUE THREAD

**Issue by maxnordlund** [joke2k/faker#660]
Hi, thanks for this lovely library. The current phone number generator emits invalid ones, as pointed out by [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers). This is a bummer, but there's hope.

[Fake Number](https://fakenumber.org/) has a list of safe phone numbers for use as example data. It's essentially a list of numbers the telephone providers have agreed to leave alone, at least for the foreseeable future.

It would be pretty sweet if faker could take advantage of this and produce valid, safe phone numbers.

**Comment by clintonb** [comment]
The `e164` provider generates valid phone numbers. See https://github.com/crowdcomms/faker-e164 for more information.

**Comment by maxnordlund** [comment]
Lovely, but that's not part of this package. It would be nice if either this ships with faker-e164, or the phone_number generator is deprecated with a pointer to faker-e164.

Basically, if you are using libphonenumber for validation, python-fakers phone_number generator breaks your code, most of the time (unless it happens to generate a valid phone number).

**Comment by clintonb** [comment]
I see your point, but one of the benefits of making providers plug-and-play is that others can expand the offerings, as has been done. I've used faker for years, and this is the first time I have needed phone number generation. Packaging the two libraries—three when you include `phonenumbers`—seems unnecessary without data showing a majority of folks need valid phone numbers.

I like the approach of https://github.com/joke2k/faker/issues/564. Add the package to the list of community providers. Additionally, add a link to the existing phone number provider docs page noting the fact that the numbers are not always valid.

**Comment by maxnordlund** [comment]
Hence the deprecation option. I rather have one way to do things, and make that the correct way, then leaving a foot gun lying around.

Having a community providers list would certainly help, and link it in the docs. But I think you also need to deprecate the existing faker since it generates invalid numbers.

I needed it at a previous job where we were sending texts, an you really want to make sure that you call the sending provider with valid numbers. Kinda like spam score when trying to send emails to non-existing email addresses.

I'm guessing that not many need phone numbers, but those that do need valid ones.

**Comment by fcurella** [comment]
I would love to replace the current phone provider with `faker-e164`, but the original author hasn't replied to the issue in more than 2 years.

The license allows us to include it, and I think we can read #564 as the author's permission to do so. We just need someone to put the work, preferably @aljp
