### ISSUE TITLE
past_datetime() crashes when start_date is within one second of now

### ISSUE THREAD

**Issue by acdha** [joke2k/faker#667]
I ran into a problem while generating a bunch of fake dates where I was calling `fake.past_datetime()` with the start date using the result of a previous `fake.past_datetime()` call (simulating a bunch of files being created as part of a collection). The first call could randomly return a value which is within one second of the current time, causing the second call to trigger an exception from `random.randint()` because the `a` and `b` values were the same.

This was pretty easy to solve simply by using `fake.date_time_between(start_date=previous_created_date)` but it might be useful if `past_datetime()` was safe to call like this.

**Comment by fcurella** [comment]
@acdha Could you provide a unit test reproducing the exception?

**Comment by acdha** [comment]
It'd be slow since it's a race condition but the logic was basically this:

```python
import random
import faker

fake = faker.Faker()

for i in range(0, random.randint(1, 1000)):
    collection_start = fake.past_datetime()

    for j in range(0, random.randint(1, 100000)):
        # This was used as a fake file creation time:
        fake.past_datetime(start_date=collection_start)
```

Looking at this a bit more, my comment above wasn't quite right – `random.randint` handles the case where it's called with the same value – but the error is the same as what I get calling `fake.past_datetime(start_date='now')` so it must have been a timing race where the first call returned within a second of the current time and then when `past_datetime` did the `-1s` call it was effectively calling `randint(1, 0)` and getting that error. That'd fit with it happening very infrequently out of millions of calls. I'm not sure whether it'd be worth handling it inclusively and just returning the start_date when the end date is less than or equal to the value or simply documenting that you need to use `date_time_between` if you can't guarantee that `start_date` is at least a couple seconds in the past.

**Comment by fcurella** [comment]
@acdha take a look at https://github.com/joke2k/faker/pull/671. The test should be close enough to the scenario you're seeing.
