### ISSUE TITLE
Output to .JSON format

### ISSUE THREAD

**Issue by quintendewilde** [joke2k/faker#672]
Is there a way to output the commandline -o to a .JSON format styled document?

**Comment by fcurella** [comment]
Hi @BLCKPSTV ,

There currently isn't a way to export to JSON.

If we had to write an exporter, how do you think the format should look like? Would just an `Array` of the values work?

**Comment by BLCKPSTV** [comment]
Yeah i'm pretty new at this but maybe an array per local? would that be possible? Sorry for the late answer.
