### ISSUE TITLE
Generate fake hostnames

### ISSUE THREAD

**Issue by thedrow** [joke2k/faker#674]
Occasionally I find the need to generate fake hostnames for testing.
I'd like faker to be able to generate valid hostname stings.

**Comment by fcurella** [comment]
Would `.domain_name()` or `domain_work()` work for your case?

**Comment by thedrow** [comment]
They might, but they are not the only valid hostnames available.
I'd expect `.hostname()` to generate strings like `db01.<domain_name>` or `worker01-mycluster`.
These kind of strings are what you'd expect from hostnames.

**Comment by ediblesushi** [comment]
Created a pull request to add a function that generates hostnames with or without a domain from predefined names. Let me know if this would work to fix this issue.

**Comment by SuperBlueEyeBall** [comment]
wowzers
