### ISSUE TITLE
prune the default word list a little to prevent really wrong sentences

### ISSUE THREAD

**Issue by Pomax** [joke2k/faker#683]
Some words from the [default "lorem" word set](https://github.com/joke2k/faker/blob/d9c4e87cbba9e345285eb24815199d0c9b56d156/faker/providers/lorem/en_US/__init__.py) can lead to really bad combinations have been removed in this PR so that people don't need to worry as they show a staging/test thing to their managers and suddenly being the center of a textual scandal. Before this PR, phrases like "die die die hang", "finger beautiful daughter" or "sexual man boy love" were all too common, and removing the possibility of people getting into genuine trouble for an out-of-the-box word list is probably not worth it.

**Comment by joke2k** [comment]
You're right.

Thank you
