### ISSUE TITLE
new locale ro_RO in 0.8.9 generates <str> names under python2.7

### ISSUE THREAD

**Issue by levkowetz** [joke2k/faker#684]
Under python2.7, first_name() produces `<unicode>` results under all locales I've tested
under 0.7.*, 0.8.*, up to 0.8.8.

0.8.9 introduced the locale ro_RO, which returns `<str>` results.  In a test setup which
generates persons with names from random locales, this can create problems with
functions that expect unicode parameters.

### Steps to reproduce

test_faker_first_name_type.py:

    #!/usr/bin/env python2
    import faker
    locales = list(faker.config.AVAILABLE_LOCALES)
    locales.sort()
    for locale in locales:
        f = faker.Faker(locale)
        name = f.first_name()
        print("%-5s %s" % (locale, type(name)))

### Expected behavior

    $ python test_faker_first_name_type.py
    #...
    pt_PT <type 'unicode'>
    ro_RO <type 'unicode'>
    ru_RU <type 'unicode'>
    #...

### Actual behavior

    $ python test_faker_first_name_type.py
    #...
    pt_PT <type 'unicode'>
    ro_RO <type 'str'>
    ru_RU <type 'unicode'>
    #...

[test_faker_first_name_type.txt](https://github.com/joke2k/faker/files/1640305/test_faker_first_name_type.txt)

**Comment by levkowetz** [comment]
The cause of this seems to be that `ro_RO/__init__.py` doesn't have `first_names` defined, so things fall back to `first_names` in `providers/person/__init__.py`, where it's defined as a regular string, no `u` prefix, and no import of `unicode_literals`.

**Comment by fcurella** [comment]
Thank you for figuring this out. Fixed in 5c9fb8d295167e37f0d118bedb6ea71b0981b70f

**Comment by levkowetz** [comment]
On 2018-02-16 16:26, Flavio Curella wrote:
> Thank you for figuring this out. Fixed in 5c9fb8d295167e37f0d118bedb6ea71b0981b70f

Thank you!

	Henrik
