### ISSUE TITLE
possible acquisition of performant faker backed by Rust

### ISSUE THREAD

**Issue by Dowwie** [joke2k/faker#685]
Your project is great.  I've used it.  It can be faster, though.  I'd like to offer work that I recently did to optimize many of the common fakes.  I released the project to pypi today:  pyfakers.

I'd gladly help you integrate the work with faker.  It's got a very straightforward api.  

The reason for this offer is to improve the most common library used for fake data generation (faker) rather than develop another further.

Thoughts?

project:  https://github.com/Dowwie/pyfakers

**Comment by fcurella** [comment]
Hi @Dowwie 

Thanks for reaching out.

I'm interested in helping improving Faker's performance, but I'm not sure we can leverage the `fake-rs` project.

Could we somehow use it but provide our own data sets? `fake-rs` dataset look very limited in its locales

**Comment by Dowwie** [comment]
That sounds like a straightforward pull request to enhance fake-rs, which
is the rust library I bind to in pyfakers.
