### ISSUE TITLE
zh_CN (and possible other providers) return invalid results for domain_name

### ISSUE THREAD

**Issue by zdelagrange** [joke2k/faker#687]
Brief summary of the issue goes here.

### Steps to reproduce

f = Faker('zh_CN')
f.domain_name()
>he.cn

### Expected behavior

it should return valid domain names

### Actual behavior

he.cn is not a valid domain. he is in the list of second-level domains (https://en.wikipedia.org/wiki/.cn#Second-level_domains_of_provinces) and will cause failures in places where domains are being validated.

it's unclear where this change should/could be made after briefly reviewing the source code.

**Comment by clarmso** [comment]
I may be able to open a PR to add second level domains.  The file in question is in faker/provider/internet/zh_CN/__init__.py :)
