### ISSUE TITLE
New To GitHub / Want To Contribute 

### ISSUE THREAD

**Issue by A-Edusei** [joke2k/faker#689]
Hi I am new to contributing and GitHub in general. I came across this repo and thought it will be a great way to get some experience and help with contributing I have a few ideas of other “fake providers” that can be included in this repo. I’m not sure who or how to contact the author of this repo or where to begin. I would like to communicate with someone before forking and starting on this repo. I hope I can get some assistance on where to begin. 

Kind Regards
Andrew

**Comment by fcurella** [comment]
Hi Andrew,

Welcome to GitHub!

We only accept new providers if they cover a need that's common enough. We don't really have a formal definition of what 'common enough' means, other than "yeah, that seems like it could be useful to > 100 people"

You can start by looking at any of already existing providers. Pick one, make a copy, and make your changes :)

**Comment by A-Edusei** [comment]
Hi Fcurella,

Firstly thank you, for the kind welcome.

Furthermore I will take your advice on looking at the existing providers and take it from there :) To be honest my Python skills are at a beginner level however I am looking to learn and improve it in order to contribute on this project. Also I would like to add, I am more than happy to consider ways that you think I can help contribute to this project. Finally is it okay with you if we use this issue as a form of communication?

Kind Regards,
Andrew

**Comment by cartertemm** [comment]
If I were you, I'd start out with a look at the [open-source guide](https://opensource.guide/)

Issues are usually used as a means of discussing specific, issues, with a project as well as suggesting features and gauging community interest.
