### ISSUE TITLE
Faker produces prefixes and suffixes in English names - how to remove?

### ISSUE THREAD

**Issue by tensigh** [joke2k/faker#690]
When generating multiple names in Fake Factory in English, there are randomly names that include a prefix (Mr., Dr., Miss, etc), suffixes (DDS, Jr., M.D., etc) or BOTH. Is there a way to turn this off and only get first and last name output?

**Comment by turbowizard** [comment]
`from faker import Faker`
`fake = Faker()`
`print fake.first_name(), fake.last_name()`

**Comment by tensigh** [comment]
Okay, thanks.

**Comment by timkeeler** [comment]
That's a helpful workaround, however it poses a challenge when generating unique full names - using `fake.unique.name()`. I think the default behavior should be to omit prefix/suffix from the names.
