### ISSUE TITLE
feature request: concat locale providers

### ISSUE THREAD

**Issue by zdelagrange** [joke2k/faker#691]
I would like to include a way to include multiple locales into a faker instance. For example, it would be nice to instantiate Faker with a list of locales and then faker will provide data from both locales.

### Expected behavior

from faker import Faker
fake = Faker(['en_US', 'zh_CN'])
fake.name()
u'Andrea Barnes'
fake.name()
u'\u6797\u79c0\u73cd'

### Actual behavior

Faker only allows one locale(?)

**Comment by kungfu71186** [comment]
I was thinking about this issue as well. I've had instances where I wanted multiple locales.

It would probably be nice to have an include all type of thing, maybe an exclude as well. 

Example:
`fake = Faker(exclude=['en_US', 'zh_CN'])`

Where if exclude is not None, then it will include all providers.

With the way it's setup now, it makes it a little difficult to do. For instance, if you had location and you wanted to generate a random country. Do you combine all the countries together first or select a random locale first and then get a country. 

Programmatically, I'm not really sure the best approach to do this. Thoughts?

**Comment by zdelagrange** [comment]
to add some more info, one of our main use cases for using faker is to make our application unicode compatible. Currently, some of the providers have very thin coverage which cause foreign key issues since we are saving objects to our database. We're basically trying to increase the pool of provider data to choose from to get unicode support and avoid foreign key constraints.

@kungfu71186 i really like the idea of having an "all" configuration. I also like the idea of exclude as well.

**Comment by kungfu71186** [comment]
@zdelagrange Not sure how you are using faker as of right now, but it could be possible to kinda get around it for right now. I don't see a way to set the locale after creating a Faker instance. This could be one possibility.

Another possibility is to create a list of faker objects with different locales. Then randomly select one and then generate what you want.

For example,

```
from faker Import Faker
import random

faker = (Faker('en_US'), Faker('zh_CN'))
random.choice(faker).address()
```

this could be a workaround for you in the meantime.

**Comment by zdelagrange** [comment]
thanks for the suggestion @kungfu71186 , a proxy type object was what i was thinking as well. that's a fairly good plan for a simple implementation.
