### ISSUE TITLE
Faker city in Faker country

### ISSUE THREAD

**Issue by quintendewilde** [joke2k/faker#697]
How do I call a fake_country followed by a fake_city. Where the city belongs in that country? 
I've seen it work in the faker PHP deviation of faker. But I can't figure it out for the python or the JS version of faker. 

All help would be really appreciated.

**Comment by fcurella** [comment]
Since the provider is localized, wouldn't all cities belong to the same country?

For example:
```python
from faker import Faker

en_us_faker = Faker()  # Defaults to `en_US`
it_it_fake = Faker('it_IT')

print('{}, USA'.format(en_us_faker.city())
print('{}, Italy'.format(it_it_fake.city())
```

**Comment by BLCKPSTV** [comment]
I mean more if I have random country I get corresponding cities in that country? 
Would that be possible? Otherwise I can try your example and do it for every country, which would be a lot of work.
@fcurella

**Comment by BLCKPSTV** [comment]
Or is this not possible?

**Comment by fcurella** [comment]
This is currently not possible.

If we had a way to list a provider's available locales, you could have a that creates a different instance of `faker` on runtime.

Something like:

```python
from faker.providers.address import AddressProvider
from faker import Faker
import pycountry  # https://pypi.python.org/pypi/pycountry

for i in range(1000):
    locale = random.choice(AddressProvider.locales)  # this doesn't exist yet
    country = locale.split('_')[1]
    fake = Faker(locale)

    print('{}, {}'.format(fake.city(), pycountry.get(alpha_2=country).name)
```

This begs the question, which language should the country name be in? And how would you specify it?

**Comment by david-shiko** [comment]
> This is currently not possible.
> 
> If we had a way to list a provider's available locales, you could have a that creates a different instance of `faker` on runtime.
> 
> Something like:
> 
> ```python
> from faker.providers.address import AddressProvider
> from faker import Faker
> import pycountry  # https://pypi.python.org/pypi/pycountry
> 
> for i in range(1000):
>     locale = random.choice(AddressProvider.locales)  # this doesn't exist yet
>     country = locale.split('_')[1]
>     fake = Faker(locale)
> 
>     print('{}, {}'.format(fake.city(), pycountry.get(alpha_2=country).name)
> ```
> 
> This begs the question, which language should the country name be in? And how would you specify it?

Better to use `sample` to avoid duplication

**Comment by fasemoreakinyemi** [comment]
This should do it

```python
from faker.config import AVAILABLE_LOCALES
from faker import Faker
import pycountry
import random

for i in range(5):
    locale = random.choice(AVAILABLE_LOCALES)  # this doesn't exist yet
    country = locale.split('_')[1]
    fake = Faker(locale)

    print('{}, {}'.format(fake.city(), pycountry.countries.get(alpha_2=country).name))
```
