### ISSUE TITLE
Fork with new provider not pulling down data directory

### ISSUE THREAD

**Issue by phoebebright** [joke2k/faker#702]
I have created a new provider and in that directory I have a directory called "data" that contains some csv files.  Although I can see the directory in github, when I load from requirements, the data directory goes away.  Is this something to do with the setup of faker or is it my problem?!

### Steps to reproduce

See the fork with the data directory: https://github.com/phoebebright/faker/tree/master/faker/providers/horse

Line in my requirements.txt
git+git://github.com/phoebebright/faker.git

### Expected behavior

data directory exists

### Actual behavior

Fails because csv files are missing because data directory is missing

**Comment by fcurella** [comment]
Hi @phoebebright ,

are you loading data from a file whose extension is not included in the [Manifest](https://github.com/HorseTechInnovation/faker/blob/master/MANIFEST.in)? That would explain the different behaviour
