### ISSUE TITLE
Credit card numbers' validity is not enforced

### ISSUE THREAD

**Issue by jphalip** [joke2k/faker#711]
Credit card numbers generated by `credit_card_number()` are not always valid.

### Steps to reproduce

```python
fake = Faker()
fake.credit_card_number()
```

### Expected behavior

The credit card numbers generated should always be valid ones.

### Actual behavior

Some returned numbers are invalid. For example: "3337083863794024", "3337957986872777", "3088184514627042". You can verify it with http://www.validcreditcardnumber.com/

The problem is that the issuer identification is not always correct. You can check that by performing a RegEx, see as an example https://www.regular-expressions.info/creditcard.html

Could the generator be modified to ensure that credit card numbers are always valid?

**Comment by fcurella** [comment]
I'm not sure where the numbers in https://github.com/joke2k/faker/blob/master/faker/providers/credit_card/__init__.py#L33-L34 comes from, but based on https://www.regular-expressions.info/creditcard.html, they look completely wrong and need to be fixed.
