### ISSUE TITLE
Faker cannot create artificial SSNs for FI_fi

### ISSUE THREAD

**Issue by kivipe** [joke2k/faker#725]
Finnish SSN has identification number that is between 002 and 899. Numbers starting with 9 are reserved for temporary use or cases when SSN is not known. It would be nice to be able to create these artificial numbers. What would be the best way to add this? I am thinking of adding a third named parameter to ssn:

`def ssn(self, min_age=18, max_age=90, artificial=False):`

**Comment by sanga** [comment]
Should be closed now, I suppose.

**Comment by fcurella** [comment]
Closed in https://github.com/joke2k/faker/commit/9d1facead29c3e9488a498de388d09eb570abfaf
