### ISSUE TITLE
ModuleNotFoundError: No module named 'faker'

### ISSUE THREAD

**Issue by aditya98ak** [joke2k/faker#749]
I've installed faker but upon running I am getting "ModuleNotFoundError: No module named 'faker' "
Please find the screenshots attached!
![image](https://user-images.githubusercontent.com/21143936/39409353-33cf785a-4c03-11e8-81d0-b790bcc118c7.png)
My script in which I am importing Faker!
![image](https://user-images.githubusercontent.com/21143936/39409369-6046dbd0-4c03-11e8-8638-1caa1a147cad.png)

### Expected behavior

My Script should run perfectly!

### Actual behavior

I am getting this traceback
![image](https://user-images.githubusercontent.com/21143936/39409374-8f6b80be-4c03-11e8-9478-458b98d620dd.png)
Any help will be highly appreciated!

**Comment by aditya98ak** [comment]
It worked by python -m pip install Faker
Sorry, My bad!

**Comment by CrispyCrafter** [comment]
I am having the same issue with Jupyter Notebooks.

Here is a screenshot of the error, in conjunction with a printout from pip list.

![image](https://user-images.githubusercontent.com/29259177/48707737-0e163f80-ec09-11e8-89fe-89cae51ba94d.png)

![image](https://user-images.githubusercontent.com/29259177/48707615-abbd3f00-ec08-11e8-8028-662cfd7b4a23.png)

With respect to the issue, I have tried the following:

1) Create new virtualenv
2) python -m pip install Faker vs. pip install Faker vs pip3 install Faker

Can confirm ipython (7.1.1) can import faker.

Any advise?

**Comment by CrispyCrafter** [comment]
I beleive the issue is based on a faulty kernel.
My bad. See below
[https://github.com/jupyter/notebook/issues/2563](url)

**Comment by z-zafirov** [comment]
For me (on Linux Mint) the following solution worked:
1. pip uninstall Faker
2. sudo apt install python3-pip
3. pip3 install Faker

**Comment by ULTRAxHURRICANE** [comment]
> It worked by python -m pip install Faker
> Sorry, My bad!

GREAT BRO THANKS

**Comment by fcurella** [comment]
Locking to prevent "thanks!", "me too!", and similar comments.
