### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by sanga** [joke2k/faker#751]
Any chance we could get a new release? We're waiting on a couple of features that have recently been merged to master

**Comment by fcurella** [comment]
I usually release monthly, around the 12th of the month. If you can wait a couple of days, I can release this Friday.

**Comment by sanga** [comment]
Sure, that sounds fine. Thanks for this excellent lib!

**Comment by fcurella** [comment]
I've just released `v0.8.14` to PyPI

**Comment by sanga** [comment]
cheers!
