### ISSUE TITLE
German address postcode + city missing

### ISSUE THREAD

**Issue by TZanke** [joke2k/faker#761]
Missing address with postalcode in german languages

### Steps to reproduce

fake.street_name()
 'Justina-Birnbaum-Allee'
fake.building_number()
 '75'
fake.city()
 'Halberstadt'
fake.postcode()
 '25842'

### Existing combinations: 
fake.address()
 'Justina-Birnbaum-Allee 75\n25842 Halberstadt'

fake.street_address()
 'Justina-Birnbaum-Allee 75'

### Missing:

fake.missing_method_for_city_with_postalcode()
 '25842 Halberstadt'

**Comment by fcurella** [comment]
I don't think we have any address provider with a method for city + postal code, so this would apply to all address providers. Some will return zip + city, while other would return city + zip, depending on the locale. German languages may have different different formats (I'm thinking Germany vs Austria vs Switzerland)

Feel free to submit a PR for the `de_DE` and/or all other locales you know :)
