### ISSUE TITLE
Canada provider: should have NU, not NV, for province abbreviation

### ISSUE THREAD

**Issue by straz** [joke2k/faker#788]
Brief summary of the issue goes here.

### Steps to reproduce

The abbreviation "NV" (presumably for Nunavut) appears in `provinces_abbr` in 
[the provider for Canada](https://github.com/joke2k/faker/blob/master/faker/providers/address/en_CA/__init__.py)

`provinces_abbr = ( .. 'NV' ..)`

### Expected behavior

The correct abbreviation for Nunavut should be `NU`
according to 
[Canada Post](https://www.canadapost.ca/tools/pg/manual/PGaddress-e.asp#1442131) and
[Statistique Canada](https://www12.statcan.gc.ca/census-recensement/2011/ref/dict/table-tableau/table-tableau-8-eng.cfm)

### Actual behavior

Generates inappropriate fake data with NV instead of NU.

**Comment by fcurella** [comment]
thank you for the report! ✨

**Comment by straz** [comment]
that was fast, thank you!
