### ISSUE TITLE
Ensure words() returns a unique list of words without duplicates

### ISSUE THREAD

**Issue by fgs-dbudwin** [joke2k/faker#791]
When calling `words(10)` there is no guarantee that the returned list of elements is unique.   While I could do `set(words(10))`, this may only return 9 items when I am in need of 10.

If creating a list of words with potential duplicates is a useful feature to some, maybe adding an optional parameter called `unique` to the `words` generator could prove useful.

**Comment by fcurella** [comment]
Hi @fgs-dbudwin 

Thanks for the report.

I have a PR up to refactor how we choose elements from list, which include optional uniqueness.

Once that's merged in, this feature will be trivial to implement
