### ISSUE TITLE
Custom providers not working with profile(fields)

### ISSUE THREAD

**Issue by erm3nda** [joke2k/faker#798]
I've created a dead-simple fakemailgenerator provider for Faker.

I't works, i can get both email and fakemail_url for a given email using `fake.fakemail() and fake.fakemail_url(fake.fakemail())`.

My problem is that it didn't accept those custom providers as fields for `fake.profile(fields=)`.
When i tried it with `fake.profile(fields="name, fakemail")` i got "name" and "mail" instead of "fakemail".

I thougt that adding custom provider was about integrate it, but im seeing it seems that just adds the method to the current instance of the class. 

**Is there any way to integrate custom provider in fields?**

**Comment by fcurella** [comment]
Hi @erm3nda ,

that would required modifying the `profile` provider to call methods on itself.

I'm +1 on the idea, but I don't know when I'll have time to work on it. Feel free to submit a PR and I'll be happy to review it :)
