### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'password'

### ISSUE THREAD

**Issue by brotatos** [joke2k/faker#81]
This error occurs when attempting to use the `password` method on a `Factory` object.

``` py
Python 2.7.6 (default, Feb 26 2014, 12:07:17) 
[GCC 4.8.2 20140206 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from faker import Factory
>>> fake = Factory.create()
>>> fake.password()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Generator' object has no attribute 'password'

```

**Comment by Sunno** [comment]
I'm having this issue too, I tested with 0.4 and 0.5 version, I have this installed in two diferent projects and different environments, in one of them (I'm using in django tests) it works, in the other one it doesn't...
