### ISSUE TITLE
pyfloat, pydecimal cannot be negative when left_digits=0

### ISSUE THREAD

**Issue by IamJeffG** [joke2k/faker#813]
I am trying to fake random floats in the range `(-1, 1)`.  Currently, `pyfloat` and `pydecimal` will never be negative as long as `left_digits=0`, even if `positive=False`.

This seems to be because [the `sign` (-1, 1) is multiplied by only the left digits](https://github.com/joke2k/faker/blob/6e32e07/faker/providers/python/__init__.py#L62) (which in this case is 0, canceling out the `sign`), rather than by the entire numeric value.

### Steps to reproduce

```python
>>> import faker
>>> fake = faker.Faker()
>>> any(fake.pyfloat(left_digits=0, positive=False) < 0 for _ in range(10000))
False
```

### Expected behavior

I'd expect approximately half of the floats to be negative, when `positive` is not `True`

**Comment by fcurella** [comment]
Thank you for the report!

I'm not sure when I'll have time to look into it. Feel free to submit a PR!
