### ISSUE TITLE
Add flake8 to the CI

### ISSUE THREAD

**Issue by fcurella** [joke2k/faker#820]
Configuration must have:
* https://pypi.org/project/flake8-commas/ 
* https://pypi.org/project/flake8-comprehensions/

I'd also like to flag visual indentation.

**Comment by andrzej3393** [comment]
Hi, I'm working on this issue. I checked the project with flake8 without any config at all and it found 2080 errors. Most of them are `E501` (line too long) and `W191` (indentation contains tabs). What to do with this? Ignore whole errors, tune settings (like line length) or just fix code to pass flake8 on default settings?

**Comment by fcurella** [comment]
Hi @andrzej3393 , thank you for volunteering!

I would set `max-line-length` to 120 _and_ fix the code. Hopefully `120` would take the number of errors down a bit.

**Comment by fcurella** [comment]
@andrzej3393 don't worry about coverage, it's been flaky and reporting wrong numbers for a while, and in any case, I'm not concerned about a .02% drop.
