### ISSUE TITLE
Documentation of utilities like random_choices

### ISSUE THREAD

**Issue by denizdogan** [joke2k/faker#832]
Is there any online documentation of the utility functions like random_choices? I always end up looking at the source code when I forget what they're named.

**Comment by BrodyUnderwood1** [comment]
http://lmgtfy.com/?q=python+faker

**Comment by BrodyUnderwood1** [comment]
http://lmgtfy.com/?q=python+faker

:rofl:

**Comment by denizdogan** [comment]
@BrodyUnderwood1 That's what I've always been doing, but it's been difficult finding the information about e.g. `random_choices`, `random_int` or `random_letters` when you can't remember the names of them or know whether they even exist in the first place. Turns out, the documentation for them has been incorrectly placed under the `address` provider: https://faker.readthedocs.io/en/master/providers/faker.providers.address.html

It would be nice if they were documented in a more obvious place.

**Comment by BrodyUnderwood1** [comment]
Ah I misunderstood the question my mistake

**Comment by fcurella** [comment]
@malefice Ideally. I'like to have a section with the methods shared by all providers (ie: `random_choices` et al). Then each provider would have a section with the methods that are guaranteed to be on all locales, followed by locale-specific methods.

Go ahead and see what you can come up with. Thank you so much for volunteering! :)
