### ISSUE TITLE
Add "Null" as potential surname, plus Pythonic variants?

### ISSUE THREAD

**Issue by adamchainz** [joke2k/faker#851]
I love this famous Wired article: https://www.wired.com/2015/11/null/ . Basically there's a man called Mr Null who finds computer systems breaking down for him all the time when badly written code interprets his name as literal `null`.

I think the providers should have a chance of generating strings like "Null", "None", "0" etc. so users of faker test their systems a bit more. This could be quite a big change as I imagine it would be valuable in all languages in most providers generating strings.

Thoughts?

**Comment by tytoons** [comment]
I could see "Null" and "None" being very useful to catch some cases!

**Comment by fcurella** [comment]
I'm not against if it gains enough support. My main doubt is: should we add those names to all `person` providers, regardless of locale? For example, I could see people being surprised to find `Null` when they asked for names in arabic

**Comment by tytoons** [comment]
Ah yeah that is a great point. I don't think people would expect that.  Maybe a new person en_dev provider would be a better case?
