### ISSUE TITLE
More granular control of Phone number generation

### ISSUE THREAD

**Issue by stephenross** [joke2k/faker#854]
I would like to write an improvement to the generation of random phone numbers using a few different arguments (default arguments calling a fake phone number would generate substantially the same as today).

Some of these could be ignored by certain providers by specifying empty sets for data used by that argument, or only single values. Specifically, I would like to see options for including international prefixes (`None` is allows them randomly like current functionality, `True` forces it, and `False` prevents it), and including extensions (Same values apply as prefixes).

It may also be useful to provide separator characters and simply list a smaller number of formats with a separator placeholder (for example, American phone numbers can use spaces, dashes, or period characters relatively interchangeably between blocks of digits, though this would likely be skipped as a feature if it causes generation to take longer than simply specifying all permutations and selecting from them).

Lastly, some of these, like extensions or separators, could specify an explicit value to use instead of the randomly selected one. This would obviously involve editing all existing provider regions to ensure the specified data sets are present, such as international dialing codes and localized phone extension formats.

Please let me know if this is something that would be useful to include or if it would not be very useful.

**Comment by fdemmer** [comment]
i needed more strict phone numbers generated recently and threw together this provider, creating only valid at, de phone numbers using the regex-patterns from [phonenumbers](https://pypi.org/project/phonenumbers/). maybe that is of use or an inspiration to someone :)

```python
import factory
from faker.providers import BaseProvider
from phonenumbers.data.region_AT import PHONE_METADATA_AT
from phonenumbers.data.region_DE import PHONE_METADATA_DE

from lynx.common.xeger import Xeger


@factory.Faker.add_provider
class PhoneProvider(BaseProvider):
    x = Xeger()
    mobile_patterns = [
        PHONE_METADATA_AT,
        PHONE_METADATA_DE,
    ]

    def mobile_phone(self):
        meta = self.random_element(self.mobile_patterns)
        national_number = self.x.xeger(meta.mobile.national_number_pattern)
        return f'+{meta.country_code}{national_number}'
```
