### ISSUE TITLE
uuid4 should return UUID instead of str

### ISSUE THREAD

**Issue by ThibaultLemaire** [joke2k/faker#858]
__Context__: I'm using faker in combination with [FactoryBoy](https://github.com/FactoryBoy/factory_boy) to test [Django](https://www.djangoproject.com/) models. I have this test to make sure some data dict generated from model data is JSON-serializable. The test passed, but not the code in production. (`Object of type UUID is not JSON serializable`).

Now, of course the fix to the offending code is simple:

``` diff
- data['uuid'] = model.uuid
+ data['uuid'] = str(model.uuid)
```

but the problem is two-fold:

1. __The fact that `uuid4` returns `str` is confusing__. I didn't pay attention and couldn't test properly.
2. __There is no provider for actual `UUID` objects__. I can understand if some people want strings that are in fact uuid representations, after all that's [how AutoFixture generates strings](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#completely-autogenerated-string) (Autofixture does approximately the same job as faker, but for C#). But there should be a provider for true `UUID`s as well.

### Steps to reproduce

1. Call `fake.uuid4()`

### Expected behavior

`fake.uuid4()` should return an `UUID` object

### Actual behavior

`fake.uuid4()` returns a `str`

**Comment by fcurella** [comment]
we could add an argument to `uuid4()`, like `faker.uuid(coerce=True)`. I'd like to keep the ddefault behavior to a string, for backward compatibility reasons

**Comment by ThibaultLemaire** [comment]
> I'd like to keep the default behavior to a string, for backward compatibility reasons

Yeah, I figured you'd say that.

An argument to `uuid4` is fine by me. I might even implement it myself.

**Comment by ThibaultLemaire** [comment]
I'm on it.

**Comment by ediblesushi** [comment]
Sorry accidentally committed other changes to the previous branch I made a pull request for. Closed out the old pull request and created a new one for a seperate branch with just the uuid4 fix.
