### ISSUE TITLE
How to use custom phone formats

### ISSUE THREAD

**Issue by shmidtelson** [joke2k/faker#873]
f.phone_number()

f.formats ??

**Comment by fcurella** [comment]
Hi @shmidtelson ,

Could you provide more context for your issue? We provide a simple [template](https://github.com/joke2k/faker/blob/master/ISSUE_TEMPLATE.md) that you could follow.

**Comment by thiagofigueiro** [comment]
Hi, @shmidtelson. You might be looking for [numerify]:(https://github.com/joke2k/faker/blob/d6581f58aabf1aa24fd26e9a61f4dd0af56f66c3/faker/providers/__init__.py#L204-L212)

```python
from faker import Faker
f = Faker()
f.numerify('+##.###-###-####')
'+86.634-981-0599'
f.numerify('+!%.###-###-####')
'+4.904-572-6858'
```

**Comment by shmidtelson** [comment]
Thank you!
