### ISSUE TITLE
Wrong class in localization text of README.rst

### ISSUE THREAD

**Issue by jocassid** [joke2k/faker#875]
In README.rst the text under the Localization says faker.Factory, but the code example uses faker.Faker

### Steps to reproduce

1. Read localization section of README.rst

### Expected behavior

should read faker.Faker

### Actual behavior

reads faker.Factory

**Comment by jianbin-allseeing** [comment]
should this issue be closed?  The test failed due to deleted branch. @fcurella

**Comment by fcurella** [comment]
Yes, it can be closed. Thank you @jianbin-allseeing
