### ISSUE TITLE
fake.local_latlng Error

### ISSUE THREAD

**Issue by perezba** [joke2k/faker#889]
### Summary: 
I am new to github and faker. I am trying to use faker.providers.geo to generate lat and longs bounded by specific country / locale. 
Following the examples listed in the documentation: https://faker.readthedocs.io/en/stable/providers/faker.providers.geo.html

### Steps to reproduce

1. I am using Ananconda Jupyter Python 3

2. I tried the following code: 
```
from faker import Faker
fake = Faker()
fake.address()
```
Returning the following successfully: 
```
#'72630 Snow Cove\nTeresaport, WI 67917'
```
3. `fake.local_latlng(country_code="US", coords_only=False)`

### Expected behavior
```
fake.local_latlng(country_code="US", coords_only=False)

('40.57788', '-73.95958', 'Brighton Beach', 'US', 'America/New_York')
```
### Actual behavior

```
fake.local_latlng(country_code="US", coords_only=False)

AttributeError                            Traceback (most recent call last)
<ipython-input-21-b9116cccd1c9> in <module>()
----> 1 fake.local_latlng(country_code="US", coords_only=False)

AttributeError: 'Generator' object has no attribute 'local_latlng'
```

Thank you!

Brian

**Comment by perezba** [comment]
Thanks @fcurella the version that shows is: ['Faker==0.9.1']

**Comment by fcurella** [comment]
Hi @perezba 

`local_latlng` is new in `v1.0.0`, so you'll have to upgrade your version of `Faker` in order to use it.

**Comment by perezba** [comment]
The update worked. I opened an Anaconda Jupyter Terminal and ran "pip install Faker --upgrade" and it worked! 

Thank you @fcurella
