### ISSUE TITLE
'Generator' object has no attribute 'locale' when calling user_agent()

### ISSUE THREAD

**Issue by Mattwmaster58** [joke2k/faker#899]
The user_agent method intermittently will fail with the message `AttributeError: 'Generator' object has no attribute 'locale'`

#### Systems bug has been reproduced on
Python: Python 3.7.0 & 3.7.1
Faker version: git and pypi 1.0.2 both tested.
Platform: Windows 10x64 & Arch Linux 4.20.0-arch1-1-ARCH

```
for _ in range(10):
     Faker(providers=['faker.providers.user_agent', 
                      'faker.providers.date_time']).user_agent()
```
Manually specifed `locale` has no effect. The snippet below is effectively the same in the case of this bug as the one above:
```
for _ in range(10):
     Faker(providers=['faker.providers.user_agent', 
                      'faker.providers.date_time'], locale='en_US').user_agent()
```
### Expected behavior

`user_agent()` should work 100% of the time.

### Actual behavior

A error is raised with the following traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-319-5c64504eb0d2>", line 1, in <module>
    Faker(providers=['faker.providers.user_agent', 'faker.providers.date_time', 'faker.providers.internet']).user_agent()
  File "C:\Program Files\Python37\lib\site-packages\faker\providers\user_agent\__init__.py", line 34, in user_agent
    return getattr(self, name)()
  File "C:\Program Files\Python37\lib\site-packages\faker\providers\user_agent\__init__.py", line 114, in safari/firefox/opera
    locale = self.generator.locale().replace('_', '-')
AttributeError: 'Generator' object has no attribute 'locale'
```

Note: only occurs in `firefox`,`safari`, and `opera`. Am I missing a provider to import?

**Comment by fcurella** [comment]
The issue is that the `user_agent` providers is depending on the `misc` provider, which you are not loading. I'm going to move the required methods to our base provider, but for the time being you should be able to call:
```
Faker(providers=[
    'faker.providers.user_agent', 'faker.providers.date_time', 'faker.providers.misc',
]).user_agent()`
```

**Comment by Mattwmaster58** [comment]
Thank you for the quick response and solution.

Will these changes fix the issue of having to guess which providers depend on who, either partially or in full?
I've had issue like this before, but was always able to infer the providers that needed to imported. What's the recommended procedure for importing providers?

**Comment by fcurella** [comment]
@Mattwmaster58 No, this is a fix just for that Provider.

I'd like to have a more systematic solution to inter-provider dependencies, but I need some time to think about how it would look like and how to implement it.
