### ISSUE TITLE
Date between month implementation

### ISSUE THREAD

**Issue by anneclairebrld** [joke2k/faker#909]
Missing implementation of months for the date_time provider. Additionally, it would be good to add information regarding the acronyms used (5y = 5 years, 5m = 5 minutes (this is very confusing => thought it was months and had to go into source code to understand that months are not actually implemented)). 

### Steps to reproduce
faker.date_between(start_date = "-5M", end_date = "today")

### Expected behaviour

produce fake date between the time given

### Actual behaviour
Error.

It would also be good to add the option to change the pattern of the returned date (e.g. pattern = '%d,%m,%y') to the function.

**Comment by fcurella** [comment]
Hi @anneclairebrld ,

Thank you for reaching out! I think it's a good idea :)

Would you have time to submit an initial PR? I'll be happy to review!

**Comment by anneclairebrld** [comment]
PR?

**Comment by fcurella** [comment]
Sorry, I was overly terse. I meant a Pull Request

**Comment by anneclairebrld** [comment]
@fcurella I'd be happy to but will not have time to get to it till mid next week.

**Comment by fcurella** [comment]
@anneclairebrld That's ok, no rush :)
