### ISSUE TITLE
Tests fail on 32bit platforms

### ISSUE THREAD

**Issue by scarabeusiv** [joke2k/faker#912]
When running tests on 32bit platform the time check actually overflows :)

### Steps to reproduce

Run tests on 32bit platform

### Expected behavior

Tests pass

### Actual behavior

Test fail, see full build log: 
[faker.txt](https://github.com/joke2k/faker/files/2868550/faker.txt)

**Comment by fcurella** [comment]
Thank you for the report @scarabeusiv 

Sadl, we really don't have a way to test on 32bit platforms, so we can't support it. But we will accept a Pull Request if you'd have the time to work on it :)

**Comment by jayvdb** [comment]
Advice at https://github.com/travis-ci/travis-ci/issues/5770 and predecessor is to use 32bit docker images.

**Comment by scarabeusiv** [comment]
Problem in this case is that 32bit clocks give up in 2038+- and the test expects "datetime_end = date(2100, 1, 1)" which overflows the container on 32bit machine.

You can either lower the check on the date, or skip those tests on 32bit.

**Comment by fcurella** [comment]
@jayvdb could you submit a PR to add a 32bit build on travis?

**Comment by fcurella** [comment]
My opinion is that if we can't test on 32bit systems on the CI, we should just be upfront and declare Faker as 64bit-only

**Comment by frispete** [comment]
Well, as @scarabeusiv written before, why not either
 * skip this very test for 32bit
 * or change the date to something before 2038...

**Comment by fcurella** [comment]
I'm working on skipping the test

**Comment by frispete** [comment]
Great @fcurella, LGTM, thanks.

Let's see, how this works out with the next release... ;-)

**Comment by scarabeusiv** [comment]
Apologies for the dupe, I really missed I opened this bug too. Anyway I've added the patch to openSUSE and it works^Wskips well on 32bit :)
