### ISSUE TITLE
Consistency between phones and addresses

### ISSUE THREAD

**Issue by sam-s** [joke2k/faker#915]
I would like to generate fake PII (Name/Address/Phone).
Alas, `Phone` and `Address` should be consistent (area code maps to geolocation well), but there seems to be no way to enforce it:
```python
print(fake.name(), fake.address(), fake.phone_number(), "\n", sep="\n")
Tara Phillips
7919 Holder Creek
Norristown, TX 14338
(451)822-0895x3913
```
but area code 451 is in KS not TX.

Is it possible to enforce this level of consistency?

**Comment by sam-s** [comment]
Furthermore, it appears that the zip code is not necessarily compatible with the state, which reduces plausibility of the address.

**Comment by fcurella** [comment]
Hi @sam-s ,

Currently, there isn't any way to let `fake_phone_number()` know what the previous invocation of `fake_address()` returned.

We do have `faker.profile()`, but it currently doesn't relate the various fields.

If you have the time, feel free to submit a PR. You're not the first one to request this feature :)

**Comment by fcurella** [comment]
Related: #697

**Comment by anneclairebrld** [comment]
has this issue been addressed or can I give it a shot?

**Comment by fcurella** [comment]
@anneclairebrld Feel free to give it a try!
