### ISSUE TITLE
generate a fake object by a schema

### ISSUE THREAD

**Issue by amnonkhen** [joke2k/faker#928]
Is there a need for Generator that generates a whole fake object using a schema such as [jsonschema ](https://json-schema.org) or [marshmallow](https://marshmallow.readthedocs.io/en/stable)?

For example, given an object schema definition, such as:

```python
class TodoSchema(marshmallow.Schema):
    text = marshmallow.fields.Str()
    due_date = marshmallow.fields.DateTime()
```
it would be possible to generate random objects:

```python
fake = faker.Faker()
fake.schema(TodoSchema)
# { 
#   'text' : 'Sint velit eveniet. Rerum atque repellat', 
#   'due_date' : '2008-03-29 19:00:00', 
# }
```

Such functionality would save boilerplate code, since the schema definition holds almost all information needed for creating the good fake object.

I have implemented an initial version of this functionality, and am wondering of this would be valuable to the _faker_ user community.

**Comment by fcurella** [comment]
I think it's too specific to be included by default, but it could we could list it under our [Community Providers page](https://faker.readthedocs.io/en/master/communityproviders.html).

**Comment by amnonkhen** [comment]
No objection for being included as community provider. 
However, I do not understand the reason it is too specific.

**Comment by fcurella** [comment]
@amnonkhen the people using `sqlalchemy`, `marshmallow` or `jsonschema` represnets only a small subset of our user, when compared to how many people need an `int`, or person names, etc.

I'm not saying it's few people, just that it's not _most_ of our users.

Another issue is how should we manage dependencies. If we include a provider returning mashmallow Schemas, should we add `marshmallow` as dependency?

**Comment by amnonkhen** [comment]
Let us go with the Community Provider option for starters.

Regarding the dependencies, I guess that using a provider that uses 3rd party dependency would require that  said dependency be added to the requirements. I would not, however, add all those 3rd party dependencies to _faker_. It should stay lean.

**Comment by amnonkhen** [comment]
I was also consider supporting [Django's DB Models](https://docs.djangoproject.com/en/2.1/topics/db/models/).  I guess this also would help many users.

**Comment by newbery** [comment]
@amnonkhen -- What is the status of this effort?  Pretty soon, I think I'll need a faker generator using jsonschema as input and would be happy to assist to get this over the line.
