### ISSUE TITLE
pl_PL tasks - a lot of things to add

### ISSUE THREAD

**Issue by adwojak** [joke2k/faker#931]
Hi,

I'm using faker quite often, but there is some missing functionalities for pl_PL, like e.g. PESEL generator (Polish id for every person), car plates or some more. 

Can I contribute on my own branch (e.g. pl-PL-features or something), to add missing functionalities?

**Comment by fcurella** [comment]
Hi @adwojak ,

Thank for reaching out!

Feel free to fork the repo, create your branch and submit Pull Requests!

**Comment by adwojak** [comment]
Thanks a lot!
