### ISSUE TITLE
Unable to import Faker

### ISSUE THREAD

**Issue by AnanthReddyGit** [joke2k/faker#942]
Installed Faker Package using pip command in Ubuntu. But I was not able to import Faker and use it in code.

**Comment by fcurella** [comment]
Hi @AnanthReddyGit 

I've just tried installing the newest release and it's working for me. Could you tell me exactly what command did you use with pip?

**Comment by AnanthReddyGit** [comment]
I have tried using <pip install Faker> command to install the Faker. But I am not able to use it in code.

**Comment by fcurella** [comment]
@AnanthReddyGit how are you importing it?

**Comment by AnanthReddyGit** [comment]
_from faker import Faker_. This is how I imported Faker package and while running. This is error is thrown.
_Traceback (most recent call last):
  File "faker.py", line 1, in <module>
    from faker import Faker
  File "/home/ananthreddy/Documents/Cyber Security/faker.py", line 1, in <module>
    from faker import Faker
ImportError: cannot import name 'Faker' from 'faker'_ananthreddy

**Comment by fcurella** [comment]
@AnanthReddyGit Python is getting confused because the filename of your script is `faker.py`, and so it's trying to "import itself", so to speak. Try renaming it to something else than `faker.py`

**Comment by AnanthReddyGit** [comment]
Thank You. That worked
