### ISSUE TITLE
The doc shows no arguments for `pyint()`

### ISSUE THREAD

**Issue by ThibaultLemaire** [joke2k/faker#945]
I want to use faker to generate integers for testing so I can seed it for reproducibility. But when reading the doc, there is no mention of parameters to the `pyint()` generator. At first I took it as gospel truth that `pyint()` takes no arguments, grumbled, then went ahead and used `random.randint()`. But then I went back and thought "that's impossible: there must be at least a `min` and `max` argument to that generator". And looking at the source, indeed there is. So I think the doc should be updated for idiots like me.

### Steps to reproduce

1. [Open the doc](https://faker.readthedocs.io/en/master/providers/faker.providers.python.html)
1. read the `fake.pyint()` example

### Expected behaviour

Should be

``` python
pyint(min=0, max=9999, step=1)
# 7882
```

### Actual behaviour
``` python
pyint()
# 7882
```

**Comment by ThibaultLemaire** [comment]
Oops, that was added super recently it would seem (by #937). Well then this issue only applies to the next release I guess?

**Comment by fcurella** [comment]
Hi @ThibaultLemaire 

Thanks for the report. Looks like for some reason ReadTheDocs hasn't kicked a build in the past 4 months. I manually kicked off one, and now it's up to date.

**Comment by ThibaultLemaire** [comment]
Oh. Just a small hiccup in doc generation then.

Alright, then I'm looking forward to using this feature in the next release
