### ISSUE TITLE
Faker.timezone() produced timezones that can't be handled by Pytz

### ISSUE THREAD

**Issue by blairg23** [joke2k/faker#949]
Brief summary of the issue goes here.

### Steps to reproduce

```
In [1]: import pytz                                                                                  

In [2]: from faker import Faker

In [3]: fake = Faker()

In [4]: timezone = fake.timezone()

In [5]: pytz_timezone = pytz.timezone(timezone)

---------------------------------------------------------------------------
UnknownTimeZoneError                      Traceback (most recent call last)
<ipython-input-2-d744b31c47ff> in <module>
----> 1 pytz.timezone('Asia/Shangri-La')

~/.virtualenvs/tomis/lib/python3.6/site-packages/pytz/__init__.py in timezone(zone)
    179                 fp.close()
    180         else:
--> 181             raise UnknownTimeZoneError(zone)
    182 
    183     return _tzinfo_cache[zone]

UnknownTimeZoneError: 'Asia/Shangri-La'
```

### Expected behavior

Pytz should be able to handle the faked timezone.

### Actual behavior

Pytz was not able to handle the faked timezone because it wasn't a real timezone.

**Comment by fcurella** [comment]
hi @blairg23 , what version of `Faker` are you using? I can't find `Asia/Shangri-La` anywhere in the code on master

**Comment by blairg23** [comment]
Hi, I think this was a mistake on my part. I think I copied part of the doc string code that showed up in output from Django-Faker that was running as part of FactoryBoy in Pytest tests. You can close this ticket.
