### ISSUE TITLE
No function to return an invalid US format SSN.

### ISSUE THREAD

**Issue by darrylwhiting** [joke2k/faker#961]
* Faker version: v0.8.17+
* OS: N/A

When an invalid en_US format SSN is desired, there is no function to return an invalid en_US format SSN.

### Steps to reproduce

1. N/A

### Expected behavior

Along with generating valid United States' EIN, ITIN, and SSNs, there should be a function to generate an invalid US format SSN, which is also not a valid ITIN. An invalid SSN assist teams with negative testing for applications or code which consume en_US format SSNs.

### Actual behavior

No function for returning an invalid en_US format SSN is available.

**Comment by malefice** [comment]
@fcurella it looks like this can be closed.
