### ISSUE TITLE
problem with importlib_metadata

### ISSUE THREAD

**Issue by tomaszrycz** [joke2k/faker#973]
There has been a problem with tests in python3.5's windows environment. Setup.py can't build `importlib_metadata` package for source and because of that all `appveyor` test failed.

### Steps to reproduce

1. Run `appveyor` tests

### Expected behavior

All tests should pass.

### Actual behavior

Tests for python3.5 in windows environment fail.

**Comment by fcurella** [comment]
fixed in #980
