### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by zd-project** [joke2k/faker#976]
* Faker version: 1.0.7

I don't see an API exposed to change locale for a Faker object programatically. I'm wondering if it's possible to do so.

**Comment by 153957** [comment]
Do you mean like this? https://github.com/joke2k/faker#localization

**Comment by zd-project** [comment]
Sorry for not replying promptly. Similar to what you described but seems that a single Faker instance can only use one locale, which is read upon initialization. Is it possible to extend this feature so we can change locale during runtime?

**Comment by 153957** [comment]
Im not certain if this is currently possible. A workaround would be initializing multiple Faker instances, one for each locale. Which you could keep in a dict for easy access.

```python
fakers = {locale: Faker(locale) for locale in ['ja_JP', 'tr_TR', 'hi_IN', …]}
…
fakers[current_locale].name()
```
