### ISSUE TITLE
Food Faker

### ISSUE THREAD

**Issue by GarridoM** [joke2k/faker#977]
Hi! 

It is not an issue, it is just a question. Is any way of doing fake data related with food? (like this page: https://hexdocs.pm/faker/Faker.Food.html)

Thanks in advance!!

**Comment by josephwon0310** [comment]
Looks like you can add a custom module under `faker/faker/providers` by inheriting the `BaseProvider` class.

**Comment by josephwon0310** [comment]
Adding on to this thread since I don't want to create another issue; Is there a guideline for submitting PRs regarding adding additional datasets such as food data?

**Comment by fcurella** [comment]
To propose a new provider, simply open an issue.

In this specific case, I don't think food is generic nor common enough to be included by default, but you could implement it as a [separate package](https://github.com/joke2k/faker#how-to-create-a-provider) and send a PRs to have included in our [community providers](https://github.com/joke2k/faker/blob/master/docs/communityproviders.rst) page.
