### ISSUE TITLE
ImportError: cannot import name get_random_word

### ISSUE THREAD

**Issue by swaroop-m** [joke2k/faker#982]
I'm new to Python. I'm trying in import random words from words. I'm facing this issue. Help me out anyone.

>  from words import get_random_word
ImportError: cannot import name get_random_word

**Comment by fcurella** [comment]
Hi @swaroop-m,

There is no `get_random_word` function anywhere in the [code base](https://github.com/joke2k/faker/search?q=get_random_word&unscoped_q=get_random_word).

Please check the [Basic Usage](https://github.com/joke2k/faker#basic-usage) section of the Readme. In a nutshell, if you just want a random word:

```python
from faker import Faker
fake = Faker()

fake.word()
```

**Comment by swaroop-m** [comment]
thank you @fcurella ,
I checked the function faker but i got a similar import error 
`from faker import Faker`
`ImportError: No module named faker`

I tried installing faker using pip,

> pip install faker
> Requirement already satisfied: faker in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (2.0.0)
> Requirement already satisfied: six>=1.10 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (1.12.0)
> Requirement already satisfied: python-dateutil>=2.4 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (2.8.0)
> Requirement already satisfied: text-unidecode==1.2 in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from faker) (1.2)

faker is already installed, but still i get the same error.(tried uninstalling fake-factory but fake-factory was not installed either)

**Comment by fcurella** [comment]
@swaroop-m 

Is it possible that you have some circular import in your code?

Another common mistake I usually make is calling the file with the same name of a module I'm importing. Is your file called `faker.py` by any chance?

**Comment by swaroop-m** [comment]
@fcurella 
No, i just created a new file named demo to check out this module.
