### ISSUE TITLE
suggestion: pytimezone

### ISSUE THREAD

**Issue by OJFord** [joke2k/faker#988]
In addition to the currently available [timezone](), it would be very useful* to have a similar python object faker, something like:
```python
import pytz

class TheExistingPythonProvider:

    def pytimezone(self, **kwargs):
        return pytz.timezone(self.generator.timezone(**kwargs))
```

For an example use-case, see:

\* FactoryBoy/factory_boy#643

**Comment by fcurella** [comment]
I'm +1 on add a timezone provider. I just wonder if it should go into the `date_time` provider than the `python` one.

Either way, feel free to submit a PR and I'll review it :)

**Comment by OJFord** [comment]
Oh, true, since date_time provider does already have  python `datetime` objects. 👍 

Will do.
