### ISSUE TITLE
Suggestion: Enhance faker.providers.date_time to generate dates of a particular day_of_week

### ISSUE THREAD

**Issue by vijayshinva** [joke2k/faker#999]
To test systems that react differently based on day_of_week it would be really helpful if Faker can generate dates of a particular day_of_week

Something like 

```
fake.date_between(start_date="-30y", end_date="today", day_of_week="Sunday")
fake.date_object(day_of_week="Sunday")
fake.date_this_year(day_of_week="Sunday")

```
would generate dates that are Sundays.

**Comment by fcurella** [comment]
I'm not sure this is common enough to be worth the complexity of the change. Feel free to submit a PR. If it's simple enough, I'll get it merged :)
